### ISSUE TITLE
文档页面bug：Textarea文档页面存在栈溢出情况

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#100]
此页面存在栈溢出情况，导致无法继续浏览。
https://arco.design/vue/component/textarea

![image](https://user-images.githubusercontent.com/21995186/140603451-572ab7b5-38f3-4012-bf87-b583ea62bbf4.png)

**Comment by Flsion** [comment]
@fangjc1986 收到，我来处理一下
