### ISSUE TITLE
权限控制功能需要优化

### ISSUE THREAD

**Issue by DotnetManGoYu** [arco-design/arco-design-vue#1002]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
业务逻辑中一个用户会对应多个角色，['admin','user']  是Arry类型，arco-design-vue中role是string类型，无法满足需求。对应文档：https://arco.design/vue/docs/pro/permission

**Comment by ljnchn** [comment]
> @ad666666 你好
> 
> 现在的角色就是 array 数据，支持多个数据的判断，若从后端拿到的是 string roles，可以处理为数组，再使用

现在代码里写的就是单用户权限，路由守卫里也是按照单用户检查的，一个用户只对应一个权限吧？
![image](https://user-images.githubusercontent.com/6970776/172131674-68cc8d19-8b9c-41a5-a88a-8bdc76c70f25.png)
![image](https://user-images.githubusercontent.com/6970776/172131798-2f53eb8a-1921-499e-b6e8-7afb94e4ad42.png)

**Comment by mitoop** [comment]
@flsion 请问 这个标记完成 是怎么处理的

**Comment by Loongphy** [comment]
> @flsion 请问 这个标记完成 是怎么处理的

see https://github.com/arco-design/arco-design-vue/issues/2900#issuecomment-1890922964
