### ISSUE TITLE
Menu组件 问题

### ISSUE THREAD

**Issue by QQOQ** [arco-design/arco-design-vue#1003]
`mode="horizontal"` 当父级div设置 ` justify-content: space-between` 时菜单不能显示完整，会自动隐藏部分，目前不知道怎么解决，结构类似下边代码
```
<div style="display:flex;justify-content: space-between;">
    <div class="navbar-left">
        <a class="logo" href="">LOGO</a>
    </div>
    <div class="navbar-right">
        <a-menu mode="horizontal">
            ...
        </a-menu>
    </div>
</div>
```

**Comment by hehehai** [comment]
@QQOQ 你好 

这应该是样式的问题，尝试设置下 `navbar-right` 的 `width` 或者 `flex-grow: 1`

参考：https://codesandbox.io/s/cranky-bash-g14won?file=/src/App.vue

**Comment by QQOQ** [comment]
@hehehai 你这个一样会出现那个问题，`flex-grow: 1`菜单还是靠左对齐的，我是想让菜单靠右对齐的，所以不能用`flex-grow: 1`

**Comment by kirazxyun** [comment]
你好
问题1: 菜单自动隐藏是横向菜单的默认功能，当宽度不足以放下所有菜单项的时候，会将多余的菜单收起
问题2: 右对齐可以加一个 text-align: right
![image](https://user-images.githubusercontent.com/10192144/164677008-4bfaedc4-e94b-4376-bd08-3bd2a7c25685.png)

**Comment by QQOQ** [comment]
@kirazxyun 谢谢，这样可以

**Comment by atom-git** [comment]
自定义如下组件，在可显示全部的空间范围，显示的菜单数量异常，会默认隐藏大部分，只留一个菜单
如下图，直接引入示例中的不存在这个问题，怎么设置都不对：
![image](https://github.com/arco-design/arco-design-vue/assets/76482041/4fa06db2-31b4-4748-9866-3909de800c37)


组件引用：
 <a-layout-header>
    
    <Logo></Logo>
    
    <div class="atom-menu">
      <Menu mode="horizontal" :theme="theme" :menus="menus"
            :fieldNames="{ title: 'name', key: 'routePath' }"></Menu>
    </div>
    

  </a-layout-header>
  <a-layout-content>

  </a-layout-content>

样式如：
<style lang="less" scoped>
.atom-layout.top {
  .arco-layout-header {
    padding: 0 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    .atom-menu {
      flex-grow: 1;
    }
  }
}
</style>

<style lang="less">
.arco-menu-horizontal {
  height: 48px;
  .arco-menu-inner {
    padding: 9px 12px 8px 12px;
    overflow: hidden;
    .arco-menu-selected-label {
      bottom: -6px;
    }
  }
}
</style>

组件如下：
Menu.vue
<a-menu :theme="theme"
          :mode="mode"
          :breakpoint="breakpoint"
          :accordion="accordion"
          v-model:openKeys="openKeys"
          :selectedKeys="selectedKeys">
    <template v-for="(menu, index) in menus">
      
      <template v-if="!menu[fieldNames.hidden]">
        
        <SubMenu v-if="menu[fieldNames.children]?.length > singleHide ? 1 : 0"
                 :key="index"
                 :subMenu="menu"
                 :fieldNames="fieldNames"
                 :singleHide="singleHide"
                 @click="handleClick"></SubMenu>
        
        <a-menu-item v-else
                     :key="menu[fieldNames.key]"
                     @click="handleClick(menu)">
          <template #icon><IconFont :type="menu[fieldNames.icon]"/></template>
          {{ menu[fieldNames['title']] }}
        </a-menu-item>
      </template>
    </template>
  </a-menu>
SubMenu.vue 
<a-sub-menu :key="subMenu[fieldNames['key']]" :title="subMenu[fieldNames['title']]" :popup="false">
    <template #icon><IconFont :type="subMenu[fieldNames['icon']]"/></template>
    
    <template v-for="(menu, index) in subMenu[fieldNames['children']]">
      
      <template v-if="!menu.hidden">
        
        <SubMenu v-if="menu[fieldNames['children']]?.length > singleHide ? 1 : 0"
                 :key="index"
                 :subMenu="menu"
                 :fieldNames="fieldNames"
                 :singleHide="singleHide"
                 @click="handleClick"></SubMenu>
        
        <a-menu-item v-else
                     :key="menu[fieldNames['key']]"
                     @click="handleClick(menu)">
          <template #icon><IconFont :type="menu[fieldNames['icon']]"/></template>
          {{ menu[fieldNames['title']] }}
        </a-menu-item>
      </template>
    </template>
  </a-sub-menu>
