### ISSUE TITLE
table 增加表头吸顶功能

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-vue#1006]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://arco.design/react/components/table#%E8%A1%A8%E5%A4%B4%E5%90%B8%E9%A1%B6

## 预期解决问题
表头无法吸顶

**Comment by pleiades-embers** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/44309088/168525318-b5cbec8e-649e-45da-a7df-de00c31a43af.png">

**Comment by suKarXiao** [comment]
@flsion 现版本表头吸顶无效，麻烦安排修复一下

**Comment by zhangzhenfei** [comment]
@flsion 现版本表头吸顶无效，麻烦安排修复一下
