### ISSUE TITLE
文档中 的版本号是咋回事  为啥和发布版本号对不上

### ISSUE THREAD

**Issue by qingtiantongxie** [arco-design/arco-design-vue#1008]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.24.1
- **Browser:** chrome100.0.4896.88
- **Reproduction Link:** https://arco.design/vue/component/modal#async

## What is expected?
请解答下 

## Steps to reproduce

https://arco.design/vue/component/modal#async 

在modal 异步关闭的文档中  onBeforeOk  的版本信息是2.7.0   这个2.7.0 是什么意思？将要在2.7.0添加此功能？我看发布的版本最高才2.4.1

**Comment by qingtiantongxie** [comment]
是的，所以
```
Modal.confirm({
    title: `提示`,
    content: ``,
    simple: true,
    onBeforeOk: (done: (closed: boolean) => void) => {
      setTimeout(()=>{done(true)}, 1000)
    },
  });
```
这种异步关闭方式  暂时还不支持是吗

**Comment by hehehai** [comment]
@qingtiantongxie 支持的

例子：https://codesandbox.io/s/quiet-voice-7e2i66?file=/src/App.vue

**Comment by hehehai** [comment]
@qingtiantongxie 支持的

例子：https://codesandbox.io/s/quiet-voice-7e2i66?file=/src/App.vue

**Comment by qingtiantongxie** [comment]
好的   看来是我的 ts 有问题  谢谢！这个开源写的很好  多谢你们的努力付出
