### ISSUE TITLE
建议image组件的全屏可以切换

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#1009]
目前的效果是第一次点击全屏是正常全屏效果，第N次点击依然是全屏效果

理想效果，单数全屏，双数恢复原样，这样比较符合大众体验效果

只是建议，感谢🙏

**Comment by kirazxyun** [comment]
你好，目前的交互已经成型，修改对已经使用的用户不友好，如果需要实现这样的功能，可以自定义操作按钮来实现的。
