### ISSUE TITLE
Image控件会被图片撑开

### ISSUE THREAD

**Issue by wyqhl** [arco-design/arco-design-vue#101]
希望能够更新一个属性 保证图片在控件设置的大小中平铺展示，不要撑开组件

**Comment by kirazxyun** [comment]
@wyqhl 目前图片的宽度是适配 width 属性的，为了保证图片显示正常所以没有限制高度（这个我这边改一下）。被撑开这个问题没有太明白，能否给个 demo 看一下呢？

**Comment by wyqhl** [comment]
就是高度无法固定 做多行的图片展示时候 其他的图片可能被上方的图片盖住 希望可以增加一个属性就是可以固定高度来展示 这个时候图片平铺显示在固定的高宽内

**Comment by kirazxyun** [comment]
> 就是高度无法固定 做多行的图片展示时候 其他的图片可能被上方的图片盖住 希望可以增加一个属性就是可以固定高度来展示 这个时候图片平铺显示在固定的高宽内

好的，我这边加一下高度的限制
