### ISSUE TITLE
tabs组件暗黑模式颜色不正确

### ISSUE THREAD

**Issue by lainbo** [arco-design/arco-design-vue#1010]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.24.1
- **System:** Windows11
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://codesandbox.io/s/nervous-shockley-t0t3o4?file=/src/App.vue

## Extra info
和tabs组件在同一vue文件下的button组件变动正常，但是tabs组件的背景颜色依旧是白色

## What is expected?
期望tabs的背景颜色也正确变动

## Steps to reproduce
1、使用tabs组件
2、按照文档写切换主题的函数
3、调用函数

**Comment by hehehai** [comment]
@lainbo 你好

tabs 默认是没有设置背景色的，所看到的白色，是底部元素的颜色。可以为 tabs 加一层容器，背景色设置为 背景色变量。
参考：https://codesandbox.io/s/crazy-rosalind-ud7o0e?file=/src/App.vue

**Comment by lainbo** [comment]
> @lainbo 你好
> 
> tabs 默认是没有设置背景色的，所看到的白色，是底部元素的颜色。可以为 tabs 加一层容器，背景色设置为 背景色变量。 参考：https://codesandbox.io/s/crazy-rosalind-ud7o0e?file=/src/App.vue

解决方案了解了，是否还有类似的透明背景组件呢，希望在“暗黑模式”那一页单独列出需要这种特殊处理的组件
