### ISSUE TITLE
Tree组件 checkNode方法设置某节点选中， onCheck回调参数event 是undefined

### ISSUE THREAD

**Issue by yanglaowu** [arco-design/arco-design-vue#1013]

**Comment by kirazxyun** [comment]
你好，关于这个问题，手动操作目标元素可以单个或者是多个，所以没有添加 checked 和 node 这两个回调参数。
目前我们会进行以下处理：
1. 指定单个节点，会在回调参数上增加 checked 和 node
2. 参数为数组，会被认定为操作多个节点，checked 和 node 维持 undefined

**Comment by yanglaowu** [comment]
不是事件，是设置check-strictly=true,然后指定单个节点选中，回调参数checked 和 node也是undefined
