### ISSUE TITLE
a-table  如何让单元格 span标签  arco-table-cell 的高度撑开到 100%

### ISSUE THREAD

**Issue by li077** [arco-design/arco-design-vue#1014]
![image](https://user-images.githubusercontent.com/103936594/164619189-c003664e-56f8-4cc0-944e-3533fee39e28.png)
试了很多方法,不能把 arco-table-cell 的高度撑开到100%和 td 标签下的 arco-table-td 高度一样占满整个单元格

**Comment by hehehai** [comment]
@li077 你好

可以使用样式覆盖下，参考：https://codesandbox.io/s/sweet-black-cr1bj7?file=/src/App.vue

**Comment by li077** [comment]
> @li077你好
> 
> 可以使用样式覆盖下，参考：https://codesandbox.io/s/sweet-black-cr1bj7?file=/src/App.vue

你好,但是这样也不能让  <span class="arco-table-cell"> 的高度撑开撑开为和 td标签 的高度一样 100% 吧

**Comment by hehehai** [comment]
@li077 

这里td容器填充已经为0了，可以看到背景颜色已经填充满了
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/12692552/164675725-fe1a7bec-bcd4-4016-831b-a0aa32d1f655.png">

你可以试着修改下这个案例

**Comment by li077** [comment]
> @li077
> 
> 这里td容器填充已经为0了，可以看到背景颜色已经填充满了 <img alt="image" width="1357" src="https://user-images.githubusercontent.com/12692552/164675725-fe1a7bec-bcd4-4016-831b-a0aa32d1f655.png">
> 
> 你可以试着修改下这个案例

你好,我这边的需求是根据单元格的数值来填充不同的背景颜色, 但是 a-table 的 的插槽 #td 和没有可接收参数来判断去return css类名 ,且cell-style也不能接收返回的值为css类名, 故我想通过 #cell 插槽根据值动态返回 css类名, 所以出现了撑不开高度问题 ,您发的案例 只有 td能撑开,但是下面的 span class='arco-table-cell'  高度不能撑开,因此为它添加背景颜色没有填充满, arco-design 目前有其他的方式来解决此问题吗,谢谢.
![image](https://user-images.githubusercontent.com/103936594/164684761-28f9374e-cb0e-4856-9156-a958b6b901ca.png)

**Comment by hehehai** [comment]
@li077 是这个意思吗？
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/12692552/164687273-6ca72931-7751-4a16-86d1-b754dd32d345.png">

**Comment by li077** [comment]
> @li077 是这个意思吗？ <img alt="image" width="1360" src="https://user-images.githubusercontent.com/12692552/164687273-6ca72931-7751-4a16-86d1-b754dd32d345.png">

![image](https://user-images.githubusercontent.com/103936594/164699762-18eeb440-1f51-43e0-8fc0-a165984e1fd2.png)

是的, 这种情况添不添加固定高度就会出现以上情况: 窗口或者表格伸缩 就无法填充满的情况. 希望能拥有常用的 整个单元格(td) css接收返回类名事件.

**Comment by hehehai** [comment]
@li077  嗯，试了一下，这是 table html 标签的问题 

https://limebrains.com/blog/2021-03-02T13:00-heigh-100-inside-table-td/

可以先按这个解决：https://codesandbox.io/s/sweet-black-cr1bj7?file=/src/App.vue

@Flsion

**Comment by li077** [comment]
好的, 谢谢, 希望 a-table 的 cell-style 以后可以支持接收返回 css类名

**Comment by Flsion** [comment]
@li077 @hehehai 如果是想修改表格整体的背景色的话，可以定制下 td 元素。 https://codesandbox.io/s/unruffled-meadow-mcb4xp
columns 属性上有个 cellStyle 的属性，可以定制单列单元格的 `table-cell` 的样式。

**Comment by li077** [comment]
> @li077 @hehehai 如果是想修改表格整体的背景色的话，可以定制下 td 元素。 https://codesandbox.io/s/unruffled-meadow-mcb4xp 另外如果需要的话，columns 属性上有个 cellStyle 的属性，可以定制单列单元格的 `table-cell` 的样式。

谢谢, 确实可以考虑这种方式, 但业务上逻辑更复杂了, 还是希望 a-table 以后能考虑有 单元格接收 css 类名 的方法, 根据用其他UI框架的经验上看, 感觉处理上会更方便~

**Comment by Tosn** [comment]
同样遇到这个问题，最后还是自定义td来实现的，
