### ISSUE TITLE
table组件开启多选框以及使用了分页组件后，无法跨分页获取选择的数据,或者说无法在数据更新之后保留之前选中的数据

### ISSUE THREAD

**Issue by lcllhh** [arco-design/arco-design-vue#1016]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
element-ui 2.15.7版本 
Table-column Attributes中reserve-selection：类型为 Boolean，为 true 则会在数据更新之后保留之前选中的数据（需指定 row-key）

## What problem does this feature solve?
分页获取数据并选择数据进行操作或保存

**Comment by hehehai** [comment]
@lcllhh 你好

element ui 的问题请到 element ui 社区处理😊

**Comment by lcllhh** [comment]
> @lcllhh 你好
> 
> element ui 的问题请到 element ui 社区处理😊

我只是举了一个elementui的类似案例，希望能有和elementui这个功能相类似的功能
