### ISSUE TITLE
table组件开启多选框以及使用了分页组件后，无法跨分页获取选择的数据,或者说无法在数据更新之后保留之前选中的数据

### ISSUE THREAD

**Issue by lcllhh** [arco-design/arco-design-vue#1019]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
目前需求是在table中选择数据去进行操作，但当table翻页进行数据更新之后，之前选中的数据获取不到了，希望能获取到数据更新之前选中的数据

## What problem does this feature solve?
分页获取数据并选择数据进行操作或保存

**Comment by hehehai** [comment]
@lcllhh 你好，这个是支持的

可以参考这个：https://stackblitz.com/edit/vue-sbttgq?file=src/App.vue

**Comment by hehehai** [comment]
若是想获取当前选择数据的完整数据，需要自己将选中的数据保存到单独的数据中使用，因为分页跳转后，之前也没的数据已经不在了，arco-design selection row keys 中仅保存 key

**Comment by lcllhh** [comment]
> 若是想获取当前选择数据的完整数据，需要自己将选中的数据保存到单独的数据中使用，因为分页跳转后，之前也没的数据已经不在了，arco-design selection row keys 中仅保存 key

可是如果我在第一页选中了数据，并且获取下一页数据的时候把第一页选中的数据保存起来，当我再回到第一页做一些更改的时候，没办法知道我做了哪些更改

**Comment by hehehai** [comment]
@lcllhh 这应该不是 table 组件要做的事情了，其他的更改自行编写即可。

如果有其他的一些使用问题的话请提供一些案例代码，这样方便参考，或者可以来飞书群讨论
![飞书20220422-172038](https://user-images.githubusercontent.com/12692552/164677010-e16d85f8-cacd-45f7-bdd2-3b3300ecf122.png)
