### ISSUE TITLE
a-upload 为何上传图片之后，无法检测到v-model或者file-list绑定的数据的变化？

### ISSUE THREAD

**Issue by jerryhu88** [arco-design/arco-design-vue#103]
![image](https://user-images.githubusercontent.com/40226377/140606525-3d4e648b-3777-46e5-a176-869697bc71d6.png)
![image](https://user-images.githubusercontent.com/40226377/140606508-e6772aa0-e6f2-43e3-8f69-b615b79917d2.png)

**Comment by kirazxyun** [comment]
需要使用 v-model:fileList 绑定

**Comment by jerryhu88** [comment]
谢谢
