### ISSUE TITLE
a-card-grid组件设置高度失效

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#1031]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.25.0
- **Browser:** chrome100.0.4896.88
- **Reproduction Link:** https://codesandbox.io/embed/fervent-dust-h7i4v7?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
设置高度百分比

## Steps to reproduce
假如代码中有二行, 但是我想让这二行高度普忙整个屏幕, 但是height设置是无效的, 我要怎么做

**Comment by Flsion** [comment]
用 row 和 col 可以实现，整体是个flex，第二行的 row 高度开启 flex-grow:1
