### ISSUE TITLE
upload 组件  多文件上传

### ISSUE THREAD

**Issue by qingtiantongxie** [arco-design/arco-design-vue#1032]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.25.0
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://codesandbox.io/s/tztpms?file=/src/App.vue

## What is expected?
希望能增加针对多文件的上传，调用一次接口上传所有文件的逻辑  

PS： 如果这个issue 是由于我使用不深或者文档读的不详细导致的问题  还请您在评论里告诉我  万分感谢  ：）

## Steps to reproduce
多文件上传  是调用了多次单文件上传接口  每次上传一个文件 
比如我选择了三个文件  那么upload 默认调用了3次上传   
这个功能体验非常不好  而且十分鸡肋

首先从功能上说，上传成功一般都有提示用户 上传成功的message  然后还有更新列表的操作
多次上传导致了message 连续出现几条   列表也是连续更新几次  这个体验很差   
而项目中一般都有对接口重复的判断  在同一时间调用多次接口  会默认取消重复调用 这点我在控制台会打印axios isCancel 为 true 的console会执行。

之所以我认为这个功能比较鸡肋  因为在elementui ant-design 中  都有这样的糟糕设计  我看了几个开源的前端项目  多文件上传基本都没有用到这个功能  

自定义的custom-request我也试过了 没有解决问题

当然这并不是一个bug  而是优化体验   但依然希望你们能看到   🙏

**Comment by qingtiantongxie** [comment]
我看了ant 的upload  在before-upload 中有两个参数  分别是file 以及 fileList   通过axios 提交 fileList 并且在before-upload 函数中返回false  可以让用户使用自己的上传函数 从而避免调用多次的问题

arco 中before-upload 则只有一个参数  因为这个函数在每一个文件上传之前执行，返回false 的话，fileList也是空的  所以不能采用ant 的方式   还有其他的实现方式吗

**Comment by Flsion** [comment]
upload 这里为了显示和控制上传进度，所以每个 item 的上传请求都是独立的。使用同一个请求可以当做新功能支持一下，目前想到的是会影响到进度的展示和错误显示。

**Comment by qingtiantongxie** [comment]
好的  能够理解你的意思   
抛开这些  我想知道咱们这个acro 怎么写能够支持多文件一次提交   我试了before-upload  也试了 custom-request   好像都不行

**Comment by Flsion** [comment]
> 好的 能够理解你的意思 抛开这些 我想知道咱们这个acro 怎么写能够支持多文件一次提交 我试了before-upload 也试了 custom-request 好像都不行

目前是不行的，组件里面把上传的文件都拆开到单独的了，这个需要开发支持一下

**Comment by seepine** [comment]
> 好的 能够理解你的意思 抛开这些 我想知道咱们这个acro 怎么写能够支持多文件一次提交 我试了before-upload 也试了 custom-request 好像都不行

把自动上传关闭，fileList是双向的，点击提交的时候获取fileList手动上传后端

**Comment by qingtiantongxie** [comment]
好的 理解了
