### ISSUE TITLE
a-form-item能加个属性控制标签宽度么

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#1033]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
element UI有个label-widht属性

## What problem does this feature solve?
有时想单独控制一部分表单的标签长度

**Comment by hehehai** [comment]
@pylist 你好，这个有的

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/12692552/164965220-d76f84a7-bebe-4189-8ad2-851a47fa59cc.png">

**Comment by Flsion** [comment]
上面的几个属性都可以，如果想简单的设置 label 宽度，也可以用 label-col-flex
