### ISSUE TITLE
选择器 Select当a-option为false时不会正确的响应

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#1035]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.25.0
- **Browser:** chrome100.0.4896.88
- **Reproduction Link:** https://codesandbox.io/embed/cranky-wood-eigcw9?fontsize=14&hidenavigation=1&theme=dark

## What is expected?
选择不了  否

**Comment by hehehai** [comment]
@pylist 你好，select 是不支持 Boolean 值得，仅支持 String 或 Number

**Comment by pylist** [comment]
@hehehai 这样很不方便吧! 后面会打算支持么, 我看element ui框架是支持的

**Comment by Flsion** [comment]
@pylist 后面会优化一下，增加 boolean 和 空值 的支持

**Comment by thislyc** [comment]
> @pylist 后面会优化一下，增加 boolean 和 空值 的支持

同求支持

**Comment by SunYuanOnly** [comment]
同上

**Comment by JsweetA** [comment]
Invalid prop: type check failed for prop "value". Expected String | Number | Object, got Boolean with value true.  同理，但是官网文档里写了支持Boolean。请问一下为什么

**Comment by LIjiAngChen8** [comment]
> Invalid prop: type check failed for prop "value". Expected String | Number | Object, got Boolean with value true. 同理，但是官网文档里写了支持Boolean。请问一下为什么

@JsweetA  你好需要确保组件库版本 >=2.51.0，如还未解决可提供可复现链接。
