### ISSUE TITLE
给抽屉(Drawer)增加点击穿透功能

### ISSUE THREAD

**Issue by Xy2002** [arco-design/arco-design-vue#1036]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://codepen.io/Marshall_W/pen/qBpGRKW

## 预期解决问题
若利用Drawer制作一个聊天框，没有点击穿透会导致Drawer打开时，即使不显示Mask，也无法点击Drawer外的HTMLElement

**Comment by hehehai** [comment]
重复问题，后续转到 https://github.com/arco-design/arco-design-vue/issues/1363
