### ISSUE TITLE
icon图标如何动态使用

### ISSUE THREAD

**Issue by changzhengithub** [arco-design/arco-design-vue#104]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
<icon :type="item.icon"></icon>

## What problem does this feature solve?
让icon图标可以动态使用

**Comment by Flsion** [comment]
@changzhengithub 你好，是使用动态组件的意思吗

**Comment by jerryhu88** [comment]
<component is='icon-user'/>

**Comment by jerryhu88** [comment]
<component is='icon-user' />

**Comment by jerryhu88** [comment]
![image](https://user-images.githubusercontent.com/40226377/140724033-ca087444-b6be-48b6-8dcc-16191ec610e7.png)

**Comment by kirazxyun** [comment]
要切换的图标必须先注册，才能切换～

**Comment by herozzm** [comment]
问题没解决 为什么closed了 tsx中如何动态使用？
