### ISSUE TITLE
加载中 Spin

### ISSUE THREAD

**Issue by lnool** [arco-design/arco-design-vue#1042]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
希望增加颜色功能，和和通过API调用

## What problem does this feature solve?
希望增加颜色功能，和通过API调用

**Comment by Flsion** [comment]
@lnool 目前已经有计划添加一个指令

**Comment by andantei** [comment]
希望支持全局自定义Spin

**Comment by hehehai** [comment]
后续将在 #443 追踪
