### ISSUE TITLE
table 中渲染checkbox ，操作checkbox 不能修改table 数据？

### ISSUE THREAD

**Issue by qingtiantongxie** [arco-design/arco-design-vue#1044]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/24731632/165241775-a9af1c20-2cc2-438a-b69f-43e8658cf941.png">
 table 中渲染的checkbox

问题1: checkbox 不能通过 `v-model:value="record.value"` 形式用于双向数据绑定吗？
问题2: table 中的初始勾选要用`:default-checked`属性来绑定？为什么不是v-model直接绑定初始值呢？

问题描述的可能不够清楚，我创建了一个demo ：
[https://codesandbox.io/s/falling-currying-lidki9?file=/src/App.vue](https://codesandbox.io/s/falling-currying-lidki9?file=/src/App.vue)

**Comment by Flsion** [comment]
@qingtiantongxie 
1：最新的 2.25.0 版本开始支持直接修改 record 的，之前的版本需要通过 rowIndex 来修改原始数据。看了下 DEMO ，checkbox 组件上没有 v-model:check 这个，用 v-model 就行。
2：:default-checked 用来设置初始值的。比如只需要设置初始状态，后续不再需要收集值时会用到此项。
