### ISSUE TITLE
数字输入框 input 没有同步值，导致 form 校验出现问题

### ISSUE THREAD

**Issue by DingRui12138** [arco-design/arco-design-vue#1062]
![image](https://user-images.githubusercontent.com/24449677/165879453-141956df-702d-4e5f-a454-1162d37e4653.png)

已提交相关 [pr](https://github.com/arco-design/arco-design-vue/pull/991)

**Comment by Flsion** [comment]
@DingRui12138 input-number 目前在失焦时才会更新值，设置了min/max 时 input中更新值会出现把超出返回的值传出去，产生问题
