### ISSUE TITLE
当通过行点击事件去选中某一行的复选框时，不能选中，我是直接将行点击获取的key赋值到了RowSelection的defaultSelectedRowKeys属性或者selectedRowKeys里面了，但是表格的复选框却没有选中，值已经变了。

### ISSUE THREAD

**Issue by xindiyang** [arco-design/arco-design-vue#1067]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
elementUI 里面可以通过行点击直接给表格的toggleRowSelection直接赋值就可以选中表格的复选框了

## What problem does this feature solve?
表格行点击选中

**Comment by Flsion** [comment]
@xindiyang https://codesandbox.io/s/pedantic-firefly-r53knv?file=/src/App.vue 可以用 selectedRowKeys 控制下
