### ISSUE TITLE
descriptions组件，当value值为boolean类型时不显示

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#107]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.1.0
- **System:** macos
- **Browser:** google chrome
- **Reproduction Link:** https://arco.design/vue/component/descriptions

## What is expected?
可以显示boolean类型的值为true或false

## Steps to reproduce
```vue
<template>
  <a-descriptions
    :data="data"
  />
</template>
<script setup>
const data = [{
  label:'是否锁定',
  value:true
}]
</script>
```

**Comment by kirazxyun** [comment]
收到，我们改一下

**Comment by seepine** [comment]
> 你好，我们这个格式是 string 哦，在 template 中 true 是不显示的呢，我们这边传值的时候注意转一下格式哦～

因为一个项目下来基本多个场景都会出现boolean的字段，只是觉得直接支持boolean可以更省事不需要让开发者再手动转，毕竟对于descriptions组件，只需要内部转换一下就可以，不然的话开发者要嘛得再二次封装，要嘛就每个使用到的地方都得自己处理数据

**Comment by kirazxyun** [comment]
> > 你好，我们这个格式是 string 哦，在 template 中 true 是不显示的呢，我们这边传值的时候注意转一下格式哦～
> 
> 因为一个项目下来基本多个场景都会出现boolean的字段，只是觉得直接支持boolean可以更省事不需要让开发者再手动转，毕竟对于descriptions组件，只需要内部转换一下就可以，不然的话开发者要嘛得再二次封装，要嘛就每个使用到的地方都得自己处理数据

嗯嗯，明白的，只是 template 的默认是这样处理的，如果我们在这个组件里处理了，那其他的组件必然也要跟着一起处理，那这个范围就十分的广了，而且还不一定能覆盖的全，所以以全局和后续维护成本的角度出发，我们比较希望能够和 vue 语法保持一致。
