### ISSUE TITLE
switch组件在首次被创建时触发change事件

### ISSUE THREAD

**Issue by Little-Ki** [arco-design/arco-design-vue#1074]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Browser:** chrome101.0.4951.41
- **Reproduction Link:** https://codesandbox.io/s/confident-phoebe-10is1r?file=/src/App.vue

## What is expected?
它不应该在首次被创建时触发change事件

**Comment by Flsion** [comment]
@Little-Ki 这个写法不对，事件的绑定要用@change。DEMO中的方式相当于执行了foo函数并添加了一个change属性

![image](https://user-images.githubusercontent.com/29793175/166861871-46a44a4f-75c9-420d-90f1-480f129be7a3.png)

**Comment by Little-Ki** [comment]
> @Little-Ki 这个写法不对，事件的绑定要用@change。DEMO中的方式相当于执行了foo函数并添加了一个change属性
> 
> ![image](https://user-images.githubusercontent.com/29793175/166861871-46a44a4f-75c9-420d-90f1-480f129be7a3.png)

第一次用这种东西 谢谢指正
