### ISSUE TITLE
table开启scroll传入y后表头错位

### ISSUE THREAD

**Issue by sunkebkn8** [arco-design/arco-design-vue#1080]
版本2.26.0

![image](https://user-images.githubusercontent.com/66460612/167088001-d48e31fa-9ce3-48a3-af06-f2c309841ab5.png)

传入y
![image](https://user-images.githubusercontent.com/66460612/167088119-7bbf0f44-a82a-4370-8e4f-2bc6b78abce3.png)
![image](https://user-images.githubusercontent.com/66460612/167088175-480dd2a4-8656-4e81-a839-fb8399b1acbb.png)
取消y后正常但是不能自动判断父元素高度

还有就是2.26.0版本 表格空数据不居中

**Comment by Flsion** [comment]
@sunkebkn8 可以提供一个复现的地址吗
