### ISSUE TITLE
table 带有选中框时，并且有Expand的情况下，能否加一个在选中父节点的同时，也选中子节点的配置？

### ISSUE THREAD

**Issue by xindiyang** [arco-design/arco-design-vue#1084]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
table 带有选中框时，并且有Expand的情况下，能否加一个在选中父节点的同时，也选中子节点的配置？

## 预期解决问题
table 带有选中框时，并且有Expand的情况下，能否加一个在选中父节点的同时，也选中子节点的配置？

**Comment by flsion** [comment]
@xindiyang 2.29.0版本会支持下
