### ISSUE TITLE
tree 组件增加一个selectedLimit的属性，控制选中数量限制

### ISSUE THREAD

**Issue by zhangzhenfei** [arco-design/arco-design-vue#1085]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
tree 组件增加一个selectedLimit的属性，控制选中数量限制

## What problem does this feature solve?
tree 组件增加一个selectedLimit的属性，控制选中数量限制

**Comment by kirazxyun** [comment]
你好，这个可以通过 model-value 和 onCheck 来配置完成，在 onCheck 中拿到最新的值，如果个数超过了限制就不要更新到 model-value 绑定的变量上。

**Comment by kirazxyun** [comment]
你好，因为 issue 不再活跃，这边先关掉，如有问题可再重开

**Comment by Loongphy** [comment]
`select` 在 `update:selectedKeys` 之前，导致 `v-model:selected-keys` 设置的值一直被后更新，无法限制被选中的数量
![image](https://user-images.githubusercontent.com/42089082/208623472-07b54e00-75db-4a2f-8d36-3936dd960ad3.png)
