### ISSUE TITLE
a-select组件添加allow-search后 在火狐浏览器上的问题

### ISSUE THREAD

**Issue by wpp19146456770** [arco-design/arco-design-vue#1086]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
a-select 加上 allow-search 后 选择一个选项后  再次聚焦 火狐浏览没有展示下拉框  需要再次点击才会展示

## 预期解决问题
a-select 加上 allow-search 后 选择一个选项后  再次聚焦   希望可以和谷歌浏览器实现一样的效果

**Comment by wpp19146456770** [comment]
这周会处理嘛

**Comment by liu-xinhui** [comment]
现在依然存在这个bug，`select` `treeSelect` `cascader`都存在这个问题
