### ISSUE TITLE
a-dropdown 的 a-dsubmenu 不支持icon插槽和class

### ISSUE THREAD

**Issue by xiaosongmao123** [arco-design/arco-design-vue#1093]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://arco.design/issue-helper?repo=arco-design-vue

## Extra info
extra

## What is expected?
当使用自定义icon的下拉菜单时，doption 和 dsubmenu 表现一致
1. 同样支持icon插槽
2. 同样支持自定义class

## Steps to reproduce
当使用自定义icon的下拉菜单时，doption如下，设置了自定义icon，设置了自定义class
```js
 <a-doption class="danger">
            <template #icon> <i class="icondelete" /> </template>
            <template #default>放回收站</template>
</a-doption>
```
当需要使用二级菜单时，dsubmenu如下，是不支持设置自定义icon的，导致相邻的菜单一个有icon一个没有icon，很丑陋
```js
 <a-dsubmenu class="danger">
            <template #default >彻底删除</template>
            <template #content>
              <a-doption title="Ctrl+Shift+Delete" @click.stop="() => handleTrashSelectFile(false, true)" class="danger">
                <template #default>删除后无法恢复</template>
              </a-doption>
            </template>
</a-dsubmenu>
```

并且，因为需要使用自定义的样式class="danger"，而dsubmenu竟然不支持设置class。导致相邻的菜单，一个有样式(红色背景)，一个没有(白色背景)，很丑陋

所以，希望当使用自定义icon的下拉菜单时，doption 和 dsubmenu 表现一致
给dsubmenu 增加icon插槽，并且支持class样式

注意：
doption 实际渲染的dom
```html
<li class="arco-dropdown-option danger" >
    <span class="arco-dropdown-option-icon"><i class="iconfont icondelete"></i></span>
    <span class="arco-dropdown-option-content">放回收站</span>
</li>
```
dsubmenu 实际渲染的dom
```html
<li class="arco-dropdown-option arco-dropdown-option-has-suffix">
<span class="arco-dropdown-option-content">彻底删除 </span>
<span class="arco-dropdown-option-suffix"><svg ...></svg></span>
</li>
```
是完全一致的，所以不知道是为什么，一开始不给dsubmenu设置icon插槽

**Comment by flsion** [comment]
2.29.0 版本增加支持
