### ISSUE TITLE
希望能为几个输入组件提供与输入框一致的slot

### ISSUE THREAD

**Issue by arect** [arco-design/arco-design-vue#1097]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://arco.design/vue/component/input#API

## 预期解决问题
目前已有的几个输入组件，例如日期选择器、数字输入框、选择器等，比起输入框缺少append、prepend等slot，在一些场合难以做到视觉效果统一。希望能添加相关slot。

**Comment by lin-97** [comment]
没必要好吗，直接用input-group

**Comment by flsion** [comment]
目前仅 input 和 input-number 存在前后置插槽，其他类似组件可以通过 input-group 实现类似效果
