### ISSUE TITLE
textarea文档页面出错，控制台报错，且无法预览代码

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#110]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.1.0
- **System:** macOS
- **Browser:** GoogleChrome
- **Reproduction Link:** https://arco.design/vue/component/textarea

## Extra info
文档报错，且红框中按钮无法正常点击
![image](https://user-images.githubusercontent.com/93666053/140697149-c621075f-cad0-4d5c-a72f-3ca0f21f5242.png)

**Comment by kirazxyun** [comment]
你好，这个问题在另一个 issue 中处理，请关注 #100
