### ISSUE TITLE
 Typography的edit-end事件，使用回车健完成编辑edit-end会触发两次

### ISSUE THREAD

**Issue by wou101771** [arco-design/arco-design-vue#1103]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

**Comment by hehehai** [comment]
@wou101771 你好，谢谢，这是一个bug，近期会修复

@Flsion Bugs

复现案例：https://vue-nuj8hq.stackblitz.io

❗️keyboard enter 事件后，还会触发一个 blur 事件，出现了两次 end

https://github.com/arco-design/arco-design-vue/blob/dba580d40fa8d0c7c644209e1a920e3355a3930f/packages/web-vue/components/typography/edit-content.vue#L41-L62

**Comment by Flsion** [comment]
@wou101771 @hehehai 收到，我们会修复下
