### ISSUE TITLE
Popover组件包裹的元素会拦截鼠标右击

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#1109]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Browser:** chrome100.0.4896.127

## What is expected?
不拦截鼠标右击事件

## Steps to reproduce
右击不弹出菜单

**Comment by flsion** [comment]
@pylist 是指包裹的元素不能触发右键事件吗，这个在 2.27.x 版本有处理

**Comment by pylist** [comment]
> @pylist 是指包裹的元素不能触发右键事件吗，这个在 2.27.x 版本有处理

确定处理好了么, 我已经升级到了2.27.1版本, 但是包裹的元素还是不能触发右键时间, 官网文档里面的示例也是一样

**Comment by flsion** [comment]
> > @pylist 是指包裹的元素不能触发右键事件吗，这个在 2.27.x 版本有处理
> 
> 确定处理好了么, 我已经升级到了2.27.1版本, 但是包裹的元素还是不能触发右键时间, 官网文档里面的示例也是一样

https://codesandbox.io/s/blue-mountain-vmzky1?file=/src/App.vue  测试可以触发

**Comment by pylist** [comment]
> > > @pylist 是指包裹的元素不能触发右键事件吗，这个在 2.27.x 版本有处理
> > 
> > 
> > 确定处理好了么, 我已经升级到了2.27.1版本, 但是包裹的元素还是不能触发右键时间, 官网文档里面的示例也是一样
> 
> https://codesandbox.io/s/blue-mountain-vmzky1?file=/src/App.vue 测试可以触发

chrome浏览器里面触发不了, emenent plus的是不会拦截
![image](https://user-images.githubusercontent.com/52667561/169496229-4718eeb8-dc05-4f42-992b-9e7e0448a0ca.png)

**Comment by flsion** [comment]
> > > > @pylist 是指包裹的元素不能触发右键事件吗，这个在 2.27.x 版本有处理
> > > 
> > > 
> > > 确定处理好了么, 我已经升级到了2.27.1版本, 但是包裹的元素还是不能触发右键时间, 官网文档里面的示例也是一样
> > 
> > 
> > https://codesandbox.io/s/blue-mountain-vmzky1?file=/src/App.vue 测试可以触发
> 
> chrome浏览器里面触发不了, emenent plus的是不会拦截 ![image](https://user-images.githubusercontent.com/52667561/169496229-4718eeb8-dc05-4f42-992b-9e7e0448a0ca.png)

这个是右键的默认行为，目前组件库的弹出层触发器有屏蔽默认行为，这里可以处理下，没有绑定trigger的话就不再屏蔽了
