### ISSUE TITLE
Typography的edit-end事件没有返回值

### ISSUE THREAD

**Issue by Syritian** [arco-design/arco-design-vue#1110]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://codesandbox.io/s/staging-glade-8032hd?file=/src/App.vue

**Comment by hehehai** [comment]
@Syritian 你好，谢谢，这是一个bug，近期会修复。

@Flsion Bugs

https://github.com/arco-design/arco-design-vue/blob/dba580d40fa8d0c7c644209e1a920e3355a3930f/packages/web-vue/components/typography/base.tsx#L317-L326

文档也有点问题

https://github.com/arco-design/arco-design-vue/blob/dba580d40fa8d0c7c644209e1a920e3355a3930f/packages/web-vue/components/typography/base.tsx#L228-L239

**Comment by kirazxyun** [comment]
你好，这个事件确实不应该有返回值，我们改进一下文档
