### ISSUE TITLE
arco vue的表格,筛选功能,开启多选时,多选的结果需要同时满足,希望多选的结果是其中一个满足

### ISSUE THREAD

**Issue by 18782944209** [arco-design/arco-design-vue#1126]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
no

## What problem does this feature solve?
arco vue的表格,筛选功能,开启多选时,多选的结果需要同时满足,希望多选的结果是其中一个满足

**Comment by hehehai** [comment]
@18782944209 你好

有两种建议
1. 直接使用单选模式（参考：https://arco.design/vue/component/table#radio）
2. 监听 table 的 select 事件，修改 selectedRowKeys 为触发事件的 rowkey
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/12692552/168402075-f0b2bafa-c9ce-4ce8-9b7f-b150a89fa406.png">

**Comment by flsion** [comment]
已解决
