### ISSUE TITLE
日期选择器的快捷选择（shortcuts）按钮误触BUG

### ISSUE THREAD

**Issue by xiaosongmao123** [arco-design/arco-design-vue#1127]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.27.0
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://arco.design/vue/component/date-picker

## What is expected?
应该把快捷选择按钮的触发条件，更改为鼠标点击click，而不是鼠标经过hover

## Steps to reproduce
1.选择一个日期
2.下移鼠标去点击 确定按钮
3.如果鼠标移动轨迹经过快捷选择按钮，则导致选择的日期被清除

--

![inputerr2](https://user-images.githubusercontent.com/41795713/168411992-9ae9d20a-64ad-4194-a6cb-9f93e7844332.gif)

**Comment by kirazxyun** [comment]
你好，这个设计确实不怎么合理，我们改进一下，移出的时候恢复原值

**Comment by xiaosongmao123** [comment]
不能增加一个选项值，让用户自己设置，shortcuts按钮   是click触发还是hover触发吗？

我更希望点击触发，即使以后优化为移出 shortcuts按钮 恢复原值，这对用户来讲，也是不理想的操作

--我就想去点一下 `确定`--结果你给我变来变去变魔术--让人很不爽

--我想点选择一个月后，我自然是有明确的目的性的

我自然的会想到去点击`a month later`这个按钮，
我不会想把鼠标移上去让他自己变（一般人想不到这个操作）
点一下让他变，这才是常规的思路吧

**Comment by kirazxyun** [comment]
@xiaosongmao123 收到，将新增属性 `preview-shortcut` 来自定义是否要预览快捷选项
