### ISSUE TITLE
tabs不能修改当前选中的值 设置v-model无效

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1129]
:v-model="xxxx"
2.27.0

**Comment by hehehai** [comment]
@xiaomilaaz 你好，tabs 的 v-model 请这样写 `<a-tabs v-model:active-key="xxxx">`

**Comment by xiaomilaaz** [comment]
> @xiaomilaaz 你好，tabs 的 v-model 请这样写 `<a-tabs v-model:active-key="xxxx">`

我刚测试了还是一样的无效，我是子组件上面的，直接改这个变量都不行，只有用default-active-key有效果，当关闭子组件在打开回不到原来的tabs了..

**Comment by hehehai** [comment]
@xiaomilaaz 参考一下这个

https://codesandbox.io/s/musing-moon-r210t3?file=/src/App.vue

**Comment by xiaomilaaz** [comment]
> @xiaomilaaz 参考一下这个
> 
> https://codesandbox.io/s/musing-moon-r210t3?file=/src/App.vue

@hehehai 
已解决，也不知道什么地方导致的，感谢。
