### ISSUE TITLE
tree setting disableCheckbox = true, parent &&  child linkage failure

### ISSUE THREAD

**Issue by chenxueling** [arco-design/arco-design-vue#1132]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.23.0
- **Framework version:** vue ^3.2.16
- **Browser:** chrome101.0.4951.54

## What is expected?
checked-strategy=‘child’，.disableCheckbox = true, parent&&child Linkage is effective

**Comment by kirazxyun** [comment]
你好，这个现象是符合预期的，当 disableCheckbox ，disabled 都是禁用当前节点，当节点被禁用之后就认为脱离了管控，所以其状态将不再影响父节点。

**Comment by kirazxyun** [comment]
你好，由于该 issue 长时间没有活跃，这边先关闭，如还有问题可再开启。
