### ISSUE TITLE
Failed to import '@arco-design/web-vue/es/icon' under 'vite build'

### ISSUE THREAD

**Issue by hyp530** [arco-design/arco-design-vue#1134]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.27.0
- **Framework version:** Latest version
- **Browser:** chrome101.0.4951.67
- **Reproduction Link:** https://github.com/hyp530/vp2test/blob/main/docs/.vuepress/components/TestButton.vue

## My code:
It works under vite development mode, but doesn't work under vite build.
![image](https://user-images.githubusercontent.com/4817812/168468959-61bbb9cb-9cf9-44dc-8c66-bfc5dd032a32.png)

## Result:
![image](https://user-images.githubusercontent.com/4817812/168469016-5e5c081d-c06b-46b7-b06e-62db8c69649a.png)

**Comment by flsion** [comment]
这个是在build的时候没有module的支持造成的，如果默认用 esbuild 是有带的。可以看下 vite 配置或者贴上来看下

**Comment by hyp530** [comment]
> 这个是在build的时候没有module的支持造成的，如果默认用 esbuild 是有带的。可以看下 vite 配置或者贴上来看下

没有vite配置可以贴上来，因为我这是Vuepress自带的vite默认配)。是因为vite生产环境默认没有采用esbuild打包吗，是否有解决方案呢？多谢。

![image](https://user-images.githubusercontent.com/4817812/168522298-e8cb9fbe-c45f-4499-9573-bff0a07d3110.png)

**Comment by fire-hydrant** [comment]
同样的问题，麻烦请教下vite如何配置支持module；在package.json中使用type:module还会引入其他问题。
