### ISSUE TITLE
2.27版本typography: 修复按下回车的时候触发两次 editEnd 的问题 (#1122)依然存在

### ISSUE THREAD

**Issue by wou101771** [arco-design/arco-design-vue#1136]
2.27版本typography: 修复按下回车的时候触发两次 editEnd 的问题 (#1122)依然存在

**Comment by hehehai** [comment]
@wou101771 你好，麻烦提供下复现，以及使用的浏览器和版本

**Comment by kirazxyun** [comment]
你好，由于该 issue 长时间没有活跃，这边先关闭，如有问题可再次开启。
