### ISSUE TITLE
今天是2022年5月16日，DatePicker不可选取的时间，官网实例都无法选择今天

### ISSUE THREAD

**Issue by wou101771** [arco-design/arco-design-vue#1137]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
今天是2022年5月16日，DatePicker不可选取的时间，官网实例都无法选择今天
## 现有案例
[12312](https://codesandbox.io/s/k362c6?file=/src/App.vue)

**Comment by kirazxyun** [comment]
你好，面板渲染的时间是早于当前时间的，当天拿到的 current 一定会小于 dayjs()，这边要选择当天的话可以提取一下年月日来对比。

**Comment by kirazxyun** [comment]
你好，该 issue 由于长时间不活跃，这边先关闭，如有问题可再开启。
