### ISSUE TITLE
Select 显示问题: 若多个 option 的 value 相同，当鼠标移上去时它们都处于 active 状态

### ISSUE THREAD

**Issue by xuxucode** [arco-design/arco-design-vue#1143]
### 问题
如下图“选择手机号国家码”所示，当鼠标移动到“美国 +1”时，其它条目也处于选中状态：
<img width="358" alt="Screen Shot 2022-05-16 at 10 17 40 PM" src="https://user-images.githubusercontent.com/8274162/168614729-24a30545-8844-4d1d-9c89-544399bade95.png"><img width="440" alt="Screen Shot 2022-05-16 at 10 27 55 PM" src="https://user-images.githubusercontent.com/8274162/168616344-7e1f46a6-5627-4326-ba52-6b705f9da370.png">

### 期望结果
只选中“美国 +1”

### 复现链接
https://codesandbox.io/s/cold-dawn-f4yme9?file=/src/App.vue

**Comment by xuxucode** [comment]
我可以想办法让 value 不一样：value 为对象并设置 value-key，或者拼接 value+label。但这种场景下 Select 的使用方法似乎就变得复杂了

**Comment by yanbowe** [comment]
> 我可以想办法让 value 不一样：value 为对象并设置 value-key，或者拼接 value+label。但这种场景下 Select 的使用方法似乎就变得复杂了

下拉数据肯定需要一个唯一值去绑定的

**Comment by xuxucode** [comment]
👌，那就设置唯一的值
