### ISSUE TITLE
table组件中，当有右边列为自定义操作时，双击操作按钮旁边的空白区域，会选中下一行第一个元素的文本

### ISSUE THREAD

**Issue by 1243182475** [arco-design/arco-design-vue#1144]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.27.1
- **框架版本:** vue 3.2.31
- **浏览器版本:** chrome101.0.4951.67

## 复现步骤
官网table中自定义渲染那一块，双击右侧view按钮旁边空白区域即可复现

**Comment by vsme** [comment]
这并不是bug，而是浏览器的 `user-select: none` 机制造成的

即 table td 里面的 button 是  `user-select: none`，双击的时候 会自动选择下一项；你可以在 button 外面再包一层盒子，设置为  `user-select: all` 双击就不会选择下一项了。
