### ISSUE TITLE
Table selectedRowKeys的类型问题

### ISSUE THREAD

**Issue by raythunder** [arco-design/arco-design-vue#1145]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
现在的类型是string[]。ts环境下，如果我的key值属性是数字类型。那数据渲染和数据提交时，就要做额外的数据类型转换。这里的类型不能为number[]吗

## What problem does this feature solve?
selectedRowKeys 也可以绑定数字类型的数组

**Comment by flsion** [comment]
@raythunder 这个可以扩展支持下。如果是ts检验警告，可以先加个 as string[] 或者 ignore 处理下
