### ISSUE TITLE
选择器 Selec在允许搜索的情况下怎么禁止输入前后空格

### ISSUE THREAD

**Issue by Likunone** [arco-design/arco-design-vue#1146]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
避免输入空格

**Comment by flsion** [comment]
@Likunone 目前select的inputValue没有做受控处理，这里需要增加下支持

**Comment by flsion** [comment]
新版本已经支持受控处理
