### ISSUE TITLE
<textarea>组件设置固定高度，缩放角标不能正常撑开

### ISSUE THREAD

**Issue by kfcgm666** [arco-design/arco-design-vue#1148]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.27.1
- **Framework version:** "vue": "^3.2.16"
- **Browser:** chrome100.0.4896.127

## What is expected?
给文本域设置固定高度，缩放角标正常撑开。

## Steps to reproduce
`<a-textarea placeholder="请输入" style="height: 300px;"  />`

给文本域设置固定高度，缩放角标不能正常撑开。

![XlXhBtVaRG](https://user-images.githubusercontent.com/21199365/168772094-4e837306-2969-4d7c-8c3f-af7c2a58863a.jpg)

**Comment by vsme** [comment]
目前没有高度配置功能，如果你想自定义高度可以用覆盖默认样式的办法。比如：

```css
.arco-textarea-wrapper textarea {
  height: 300px;
}
```

建议还是要自定义局部class，避免污染。

**Comment by flsion** [comment]
@kfcgm666 2.28.0版本已经处理

**Comment by Fengjing95** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/51731411/172819609-244a202f-ad94-41dc-b55b-e71ebc1a9198.png">
设置高度之后可以撑开，但是角标仍然可以随意拖动

```vue
<a-textarea :style="{ height: '100%' }" />
```

**Comment by Wjinlei** [comment]
> <img alt="image" width="351" src="https://user-images.githubusercontent.com/51731411/172819609-244a202f-ad94-41dc-b55b-e71ebc1a9198.png">
> 
> 设置高度之后可以撑开，但是角标仍然可以随意拖动
> ```
> <a-textarea :style="{ height: '100%' }" />
> ```

很遗憾，这个问题到现在也没修复。
