### ISSUE TITLE
table组件调整列宽后刷新网页就没了

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#1150]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
或者还有其他更好的方案, 让用户只调整一次表格的宽度

## What problem does this feature solve?
能不能加个事件, 调整的时候返回一下数据, 我自己做处理

**Comment by flsion** [comment]
@pylist table这里可以加个回调事件
