### ISSUE TITLE
提问:表格组件如何设置百分比列宽

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1151]
在制作一个两列的表格时，想要实现两列宽度一致，却发现宽度很难调整。虽然组件会适当的分配宽度，并且具有响应式，但即使只有两列，也似乎并不是完全平均分配的。
恳请大佬们支支招。

**Comment by flsion** [comment]
@yymjku18 可以给每列设置一个相同的宽度 https://codesandbox.io/s/elated-aryabhata-bceei5

**Comment by yymjku18** [comment]
@flsion 非常感谢，顺便问下VUE的日历组件什么时候出啊，急用

**Comment by flsion** [comment]
@yymjku18 目前可以看下第三方的日历组件，这个在后面的计划中，但最近几周应该还不会出来

**Comment by yymjku18** [comment]
@flsion 非常感谢

**Comment by suKarXiao** [comment]
@flsion 同问，希望列宽可以设置百分比，固定宽度计算会比较繁琐要计算且不能随宽度变化自动调整，而全自适应会导致表格跳动感明显
