### ISSUE TITLE
a-year-picker使用vite编译后地址错，.库里面没有这个路径  无法正常发布，开发环境正常

### ISSUE THREAD

**Issue by lishuminjames** [arco-design/arco-design-vue#1154]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.25.2
- **Framework version:** vue3.0
- **Browser:** chrome101.0.4951.64
使用  a-date-picker  能正常编译打包
![{3706860B-A1E8-4349-8268-2668A0CC9D5A}](https://user-images.githubusercontent.com/26424075/168986066-afea3f4b-8862-4f11-b56e-035b242ea3d3.png)

**Comment by kirazxyun** [comment]
@lishuminjames 请问是否使用了 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)，可以升级一下版本试试，之前我们漏掉了一些组件，已经补充完整。升级后不用再配置 external

**Comment by lishuminjames** [comment]
@

> 

 "unplugin-vue-components": "^0.17.21",   现住版本是这个，还有更搞的版本吗

**Comment by kirazxyun** [comment]
目前最新版是 0.19.3，可以先升级看看。
如果还是不行，请先检查一下 arco 的 resolver 里是否包含如下配置
![image](https://user-images.githubusercontent.com/10192144/170616673-35ba2772-189c-44ed-869b-ff93a0b43afd.png)
如果有还是报错的话，就不是这个插件的问题，需要你这边提供给我们最小复现场景，我们好帮助排查问题。

**Comment by dddddd1** [comment]
我也遇到了 这个问题怎么解决的呢
