### ISSUE TITLE
修改保存form组件的标签属性，视图没有实时更新，使用vite编译

### ISSUE THREAD

**Issue by xs9888** [arco-design/arco-design-vue#1158]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Framework version:** 3.2.33

## What is expected?
修改保存form组件的标签属性，视图能实时更新

## Steps to reproduce
修改保存a-form-item组件的label等其他属性，视图没有实时更新，得手动刷新页面才能看到变化

![75371c4203880b49c42e528ea43a4e9](https://user-images.githubusercontent.com/52398118/169242511-04301ed6-e9e5-4f07-8a60-2ba82b0a93b9.png)
![e34b4c8ab1f32bb350f65148af58514](https://user-images.githubusercontent.com/52398118/169242575-425a909b-bbee-4ed7-8742-0ccb2e5590fc.png)
![47effc1127e00a31b91c542bb36f76a](https://user-images.githubusercontent.com/52398118/169243603-3d223115-39d9-4b97-8468-4d474fb73a13.png)

## Extra info
`
 "devDependencies": {
    "@vitejs/plugin-vue": "2.3.1",
    "vite": "2.9.5"
 }
`

**Comment by hehehai** [comment]
@xs9888 你好，这应该是 vite 热重载的问题，尝试升级 vite 版本，看是否解决

**Comment by hehehai** [comment]
该问题长期无跟踪暂时关闭，后面有补充再可开启。
