### ISSUE TITLE
Form setFields Api设置数据不合理

### ISSUE THREAD

**Issue by strongyc** [arco-design/arco-design-vue#1162]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.27.1
- **Browser:** chrome101.0.4951.41
在表单初始化设置值时，通常使用{}对象更好初始化，而目前使用Record<string, FieldData>需要转换，特别是对于添加和编辑操作，编辑数据时还得进行转换，增加了难度

**Comment by flsion** [comment]
@strongyc setFields方法更多是为了设置表单状态提供的，如果是修改值，通常是直接修改传入的 model 数据
