### ISSUE TITLE
我很困惑，我把upload二次封装就会提示这个change的问题

### ISSUE THREAD

**Issue by jerryhu88** [arco-design/arco-design-vue#117]
![image](https://user-images.githubusercontent.com/40226377/140719098-e4b09788-5346-44c6-80d1-40d417a2b706.png)

![image](https://user-images.githubusercontent.com/40226377/140719072-9525a376-1a51-4872-88a4-961243b24ae7.png)

**Comment by kirazxyun** [comment]
你好，我们为了兼容 jsx 的提示，给每个 emit 事件加了 props 声明导致了这个问题的产生，下个版本我们会去处理这个问题，去掉这个警告，十分抱歉～

**Comment by jerryhu88** [comment]
明白了，但是还有个问题，我上传一次，会触发四次change事件
![image](https://user-images.githubusercontent.com/40226377/140721109-75640689-c289-41b6-95b6-5722d5ddeaf4.png)

![image](https://user-images.githubusercontent.com/40226377/140721094-e8467a23-b2c4-44e7-98ea-3ab1a36804b9.png)

**Comment by kirazxyun** [comment]
是的，change 是状态变化就会触发，你可以把参数打出来看看哦
