### ISSUE TITLE
是否有计划支持vue2呢

### ISSUE THREAD

**Issue by hesunfly** [arco-design/arco-design-vue#1181]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
如题

## What problem does this feature solve?
如题

**Comment by flsion** [comment]
@hesunfly Arco Design Vue 只会提供 Vue3 版本，没有 Vue2 版本的计划

**Comment by hesunfly** [comment]
@flsion 那真是太遗憾了
