### ISSUE TITLE
「Modal 打开造成窗口滚动条消失，页面抖动」

### ISSUE THREAD

**Issue by abnereel** [arco-design/arco-design-vue#1184]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.28.0
- **框架版本:** 2.27.1
- **浏览器版本:** chrome101.0.4951.64

## 复现步骤
modal组件，高度全屏，宽度指定，大概是600，后来发现宽度全屏也会出现这种情况
mac系统下，开启滚动条一直显示会出现这种情况，关闭滚动条一直显示则不会出现
windows会有这种情况

**Comment by flsion** [comment]
@abnereel 这个是指高度设置了 100% 而没有使用 fullscreen 属性时出现的问题吗？这个是在 modal 打开时会有一个缩放动画造成的，fullscreen属性有对这个做处理。如果使用了 100% 高度，可以额外设置下 modalAnimationName = 'zoom-in' 和 maskAnimationName = 'fade-in-standard'

**Comment by abnereel** [comment]
是的，高度设置了 100% 而没有使用 fullscreen 属性时出现的问题，我试试这两个属性

**Comment by abnereel** [comment]
OK了

**Comment by 981433814** [comment]
> @abnereel 这个是指高度设置了 100% 而没有使用 fullscreen 属性时出现的问题吗？这个是在 modal 打开时会有一个缩放动画造成的，fullscreen属性有对这个做处理。如果使用了 100% 高度，可以额外设置下 modalAnimationName = 'zoom-in' 和 maskAnimationName = 'fade-in-standard'

请问只使用fullscreen 为什么也会出现，滚动条消失的情况

**Comment by kibble5788** [comment]
解决了，我是全局加了：
```
.arco-modal-wrapper {
  overflow: hidden;
}
```
