### ISSUE TITLE
a-tab-pane  是否可以添加title<slot>插槽

### ISSUE THREAD

**Issue by zhoucici** [arco-design/arco-design-vue#1186]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
一些场景当中，title可能含有icon已经徽标。所以建议提供 title插槽

## What problem does this feature solve?
一些场景当中，title可能含有icon已经徽标。所以建议提供 title插槽

**Comment by zhoucici** [comment]
查看源码发现已经有该slot，doc上面没有写而已

**Comment by flsion** [comment]
@zhoucici tab-pane 下有 title 插槽可以使用，我看文档这里缺失了，后面补一下
