### ISSUE TITLE
求问如何为menu组件自定义颜色

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1187]
目前menu只内置了黑白两色，如果想自定义颜色该怎么办。这似乎跟自定义主题之类的有关，奈何本人less掌握的不是很好，文档没怎么读懂--其他相关的Issues也看得云里雾里。有没有什么思路或案例可以参考。求大佬们指点了~

**Comment by kirazxyun** [comment]
方案有 2 个：
1. 修改 less 变量和自定义样式覆盖原有样式，需要了解相关 less 变量，dom 结构，有较好的 css 编写能力。
2. 使用风格配置平台可视化地定制外观，完成后引入该主题包即可。风格配置平台地址：https://arco.design/themes?currentPage=1&onlyPublished=false&pageSize=9&sortBy=starCount&tag=all，风格配置平台使用指南：https://arco.design/docs/designlab/guideline
