### ISSUE TITLE
布局滚动条显示会导致菜单栏宽度变窄

### ISSUE THREAD

**Issue by he675724590** [arco-design/arco-design-vue#119]
![image](https://user-images.githubusercontent.com/15225368/140838420-d1c6c60f-1f68-446f-ae2d-068e36a22504.png)
![image](https://user-images.githubusercontent.com/15225368/140838472-5679e459-f806-44f5-8f36-3f6c8b3b32cb.png)

windows布局显示滚动条时菜单栏会变窄，并且滚动条样式与风格不搭

**Comment by kirazxyun** [comment]
你好，我们没有对滚动条的样式进行处理哦，不同系统显示不一致时符合预期的
