### ISSUE TITLE
[Cascader] 级联选择中不同分组下相同的 value 回填展示不正确

### ISSUE THREAD

**Issue by Otto-J** [arco-design/arco-design-vue#1192]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.28.0
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://stackblitz.com/edit/angular-eq6kfj-8es9ey?file=src/App.vue

## What is expected?
重复值合并展示，实际区分不出来

## Steps to reproduce
1. 北京分组下有两个 same-value 张三，在业务中表示不同分组下的相同成员，多次选中 beijign/xicheng/张三，观察 model-value 的值

**Comment by flsion** [comment]
@Otto-J 如果存在相同值可以使用 `path-mode`，普通模式下需要选项值唯一
