### ISSUE TITLE
input-number 组件步进器 focus 下不显示（input 没有 hover）

### ISSUE THREAD

**Issue by hehehai** [arco-design/arco-design-vue#1194]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.28.0
- **浏览器版本:** chrome101.0.4951.54

## 额外补充
需要步进器按钮整体显示（可以使用：focus-within 样式，或者 foucs 事件添加样式类）

## 预期结果
步进器 foucs 下，应该显示出来（即使 input 没有被 hover）

## 复现步骤
1. input-number focus
2. 鼠标不要悬停再 input 上（此时，步进器隐藏）
3. 使用 tab 切换 index，这里会让 步进器 focus, 但此时步进器没有显示

**Comment by flsion** [comment]
@hehehai 确实要显示，顺便加下input-number的键盘事件
