### ISSUE TITLE
Typography 组件，点击编辑文本后，无法进行输入Typography 组件，点击编辑文本后，无法进行输入

### ISSUE THREAD

**Issue by Liao-js** [arco-design/arco-design-vue#120]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.1.1
- **系统版本:** Window
- **浏览器版本:** chrome
- **复现地址:** https://arco.design/vue/component/typography

## 额外补充
在 /packages/web-vue/components/typography/edit-content.vue 文件， Input 组件的change方法需要失去焦点才会触发，所以无法通过绑定change方法实时获取输入框的值，但是input方法可以

## 预期结果
进入编辑状态后，输入框能够正常输入

## 复现步骤
在官网 typography 组件中的可交互，点击编辑，进入编辑状态后，输入框无法输入

**Comment by kirazxyun** [comment]
收到，下个版本修复。
