### ISSUE TITLE
ts类型报错

### ISSUE THREAD

**Issue by strongyc** [arco-design/arco-design-vue#1210]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.0
- **Browser:** chrome101.0.4951.41

## Extra info
 node_modules/.pnpm/registry.npmmirror.com @arco-design web-vue@2.27.1_vue@3.2.33/node_modules/@arco-design/web-vue/es/table/index.d.ts:45:13
    45             rowSelection?: unknown;

## What is expected?
 node_modules/.pnpm/registry.npmmirror.com @arco-design web-vue@2.27.1_vue@3.2.33/node_modules/@arco-design/web-vue/es/table/index.d.ts:45:13
    45             rowSelection?: unknown;

## Steps to reproduce
 node_modules/.pnpm/registry.npmmirror.com @arco-design web-vue@2.27.1_vue@3.2.33/node_modules/@arco-design/web-vue/es/table/index.d.ts:45:13
    45             rowSelection?: unknown;

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/170826383-d69d9e06-b496-4b76-a7f5-0977b54886ce.png)

**Comment by strongyc** [comment]
![image](https://user-images.githubusercontent.com/51156342/170826397-2637fa5d-982f-4a4b-a1a7-bdc27f553c9c.png)

**Comment by hehehai** [comment]
@strongyc 你好

可以设置下类型（这里的类型应该是 type 没匹配）
```
const rowSelection = reactive<TableRowSelection>({
	type: 'checkbox',
	showCheckedAll: true
})
```

**Comment by strongyc** [comment]
收到，希望可以修复下

**Comment by flsion** [comment]
这个是 ts 默认处理的方式，组件库没有在此处做额外处理。类似对象的值，可以使用组件库提供的ts类型进行声明
