### ISSUE TITLE
a-range-picker 预设shortcuts ts提示错误

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1211]
版本：2.29.0
使用a-range-picker
:shortcuts="[
                  {
                    label: 'next 10 years',
                    value: () => [dayjs(), dayjs().subtract(10, 'year')],
                  },
                ]"

value报错不能将类型“() => dayjs.Dayjs[]”分配给类型“string | number | Date | (string | number | Date)[] | (() => string | number | Date | (string | number | Date)[])”。
  不能将类型“() => dayjs.Dayjs[]”分配给类型“() => string | number | Date | (string | number | Date)[]”。

**Comment by hehehai** [comment]
@xiaomilaaz 你好

这里 dayjs 返回的使用 dayjs 对象，可以转换为 [Date](https://day.js.org/docs/en/display/as-javascript-date#docsNav) 、 [number](https://day.js.org/docs/en/display/unix-timestamp-milliseconds) 或者 [string](https://day.js.org/docs/en/display/as-string)

**Comment by xiaomilaaz** [comment]
> @xiaomilaaz 你好
> 
> 这里 dayjs 返回的使用 dayjs 对象，可以转换为 [Date](https://day.js.org/docs/en/display/as-javascript-date#docsNav) 、 [number](https://day.js.org/docs/en/display/unix-timestamp-milliseconds) 或者 [string](https://day.js.org/docs/en/display/as-string)

好的，解决
