### ISSUE TITLE
a-cascader 子节点点击不显示名称 只显示编号

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1212]
<a-cascader
            v-model="id"
            :options="data"
            check-strictly
            :field-names="{ value: 'id', label: 'name' }"
          />

一级点击正常显示名称，选择二级就变成显示编号了

版本：2.29.0

**Comment by xiaomilaaz** [comment]
<a-cascader
                v-model="id"
                :options="data"
                allow-search
                allow-clear
                check-strictly
                :field-names="{ value: 'id', label: 'name' }"
              />

2.28.0可以正常。2.29.0就不行

**Comment by xiaomilaaz** [comment]
测试value的key是字符串可以，数字就二级选择不显示名称了，希望修复，后台一般都是给的数字不是字符串。

**Comment by xinhaoxx** [comment]
@flsion 哈喽，这个是版本 2.29.0 下的复现地址：https://stackblitz.com/edit/angular-eq6kfj-h6ddyu?file=src/App.vue

**Comment by xiaomilaaz** [comment]
> @flsion 哈喽，这个是版本 2.29.0 下的复现地址：https://stackblitz.com/edit/angular-eq6kfj-h6ddyu?file=src/App.vue

用你这个复现了，一样的，只要是二级就不行
