### ISSUE TITLE
a-tree无法设置默认选中

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1213]
:default-checked-keys="checkedKeys"
        v-model:checked-keys="checkedKeys"

设置都无效 只能固定写[1,2]
后端返回的不能复现。怎么解决

**Comment by xiaomilaaz** [comment]
已找到问题所在，字符串数组不行，需要整数数组！

**Comment by kirazxyun** [comment]
@anLl @xiaomilaaz 你好，这边的 key 和数据的 key 能匹配上才行，能否提供一下具体的 demo 呢。

**Comment by xiaomilaaz** [comment]
> @anLl @xiaomilaaz 你好，这边的 key 和数据的 key 能匹配上才行，能否提供一下具体的 demo 呢。

[1,2]可以
['1','2'] 无效

你试试吧

**Comment by anLl** [comment]
> 

[大概意思的demo](https://codesandbox.io/s/twilight-fog-dlgy0r?file=/src/App.vue)

**Comment by flsion** [comment]
> > 
> 
> [大概意思的demo](https://codesandbox.io/s/twilight-fog-dlgy0r?file=/src/App.vue)

default-* 类属性仅在组件初始化时会生效，用来处理非受控情况的使用。这种后加载数据可以用受控的方式
https://codesandbox.io/s/blissful-sky-gcrp7o

**Comment by anLl** [comment]
> > > 
> > 
> > 
> > [大概意思的demo](https://codesandbox.io/s/twilight-fog-dlgy0r?file=/src/App.vue)
> 
> default-* 类属性仅在组件初始化时会生效，用来处理非受控情况的使用。这种后加载数据可以用受控的方式 https://codesandbox.io/s/blissful-sky-gcrp7o

这样可能不好，例子中我根节点是四川省，直接在data里面默认写001没问题，但项目中现在是不同省份的角色登录进来不一样的，可能是广东省、安徽省。也可能是广东省佛山市，我只能去computed拿根节点的id
