### ISSUE TITLE
date-picker控件的readonly无效

### ISSUE THREAD

**Issue by hao3304** [arco-design/arco-design-vue#1215]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.0
- **Browser:** chrome101.0.0.0

## What is expected?
不可编辑，不可清除。参考input控件效果

## Steps to reproduce
设置readonly以后，还可以编辑，allow-clear也生效。跟没设置一样效果

**Comment by hehehai** [comment]
@hao3304 请升级下最新版本。#1400
