### ISSUE TITLE
按需加载（模板）条件下，mention组件type=textarea时样式丢失

### ISSUE THREAD

**Issue by javed119** [arco-design/arco-design-vue#1222]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.0
- **Framework version:** vue 3.2.25
- **Browser:** chrome101.0.4951.67
- **Reproduction Link:** https://stackblitz.com/edit/angular-dr26r1-jpdlmn

**Comment by flsion** [comment]
@javed119 mention组件少了对textare样式的引用，下版本会修复下
