### ISSUE TITLE
当select option label值为空字符时，样式错误

### ISSUE THREAD

**Issue by OneSeven** [arco-design/arco-design-vue#1236]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.29.1
- **框架版本:** vue3.2.36
- **浏览器版本:** chrome102.0.5005.63
- **复现地址:** https://codesandbox.io/s/polished-cdn-f74y1g?file=/src/App.vue

## 预期结果
显示正常高度

## 复现步骤
```vue
<a-select v-model="0" :style="{width:'320px'}" placeholder="Please select ...">
      <a-option :value="0">{{""}}</a-option>
</a-select>
```

**Comment by flsion** [comment]
@OneSeven 收到了，新版本会处理下
