### ISSUE TITLE
自动补全a-auto-complete的提示文字ts报错

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1240]
如题，虽然placeholder的效果可以实现，但是会出现ts报错，看了一下a-auto-complete组件，好像里面也确实没有placeholder这个props
![image](https://user-images.githubusercontent.com/77368194/172082912-2958bbe2-4619-4eca-977b-611b87187249.png)

**Comment by yymjku18** [comment]
不好意思打扰了，已解决。
是VSCode Vue Language Features (Volar)插件造成的，升级到0.37.0以后会有很多ts报错，
到0.37.1还有更多ts报错
如果觉得这个Issues用不上的话可以关了。

**Comment by flsion** [comment]
> 如题，虽然placeholder的效果可以实现，但是会出现ts报错，看了一下a-auto-complete组件，好像里面也确实没有placeholder这个props ![image](https://user-images.githubusercontent.com/77368194/172082912-2958bbe2-4619-4eca-977b-611b87187249.png)

嗯，这个属性会透传到下面的 input 组件。在 Vue 中继承的属性没有办法被 ts 识别，所以这里会出现不存在的警告。
目前可行的解决方法是把继承的属性全部重新声明一遍，但工作量会很大，优先级比较低
