### ISSUE TITLE
Select组件在选中状态时，鼠标移到其他项再离开，原选中项的选中状态消失

### ISSUE THREAD

**Issue by bytrix** [arco-design/arco-design-vue#1242]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Element-Plus的select：https://element-plus.gitee.io/zh-CN/component/select.html

## What problem does this feature solve?
提示用户当前选中的项在哪一个

**Comment by flsion** [comment]
@bytrix 你好，select 的选中状态是这样设计的，在鼠标移出下拉菜单后会释放选中项

**Comment by bytrix** [comment]
> @bytrix 你好，select 的选中状态是这样设计的，在鼠标移出下拉菜单后会释放选中项

设计能否改进一下呢？个人认为这样不符合用户习惯

**Comment by hehehai** [comment]
@bytrix 你好，目前该组件的交互行为不会做调整。该功能可以根据当前选中项来为 option 添加自定义样式或 className 实现
