### ISSUE TITLE
抽屉 Drawer组件能否增加header入参（参数值为true或false）用于控制是否展示顶部内容

### ISSUE THREAD

**Issue by youhuan** [arco-design/arco-design-vue#1246]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
抽屉 Drawer组件可以通过设置footer入参控制是否展示底部内容

## What problem does this feature solve?
设置抽屉组件是否展示顶部内容

**Comment by flsion** [comment]
@youhuan 好的，后面会添加一个控制的属性。目前不传 title 并且设置 closable="false" 时会隐藏 header，可以先这样使用

**Comment by youhuan** [comment]
收到，多谢
