### ISSUE TITLE
更新最新arco design 版本之后在 "arco-design-pro-vue": "^2.0.2" 中点击菜单列表报错 Cannot destructure property 'type' of 'vnode' as it is undefined.

### ISSUE THREAD

**Issue by HollowWater** [arco-design/arco-design-vue#1247]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Framework version:** Vue
- **Browser:** chrome102.0.0.0

## What is expected?
请问如何解决？

## Steps to reproduce
在 "arco-design-pro-vue": "^2.0.2" 使用"@arco-design/web-vue": "^2.29.1"部分代码在点击菜单的时候报错 
Uncaught (in promise) TypeError: Cannot destructure property 'type' of 'vnode' as it is undefined.
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')

**Comment by flsion** [comment]
@HollowWater 可以定位到处理的问题位置吗，如果menu是用作路由切换，可能是页面卸载的问题

**Comment by HollowWater** [comment]
@flsion  无法定位了，我把代码切迁移到最新的pro后台了 =。=

**Comment by flsion** [comment]
OK
