### ISSUE TITLE
使用Select 分组后打包异常，生产无法正常发布，缺失 “/@arco-design/web-vue/es/optgroup/style/css.js”

### ISSUE THREAD

**Issue by bzw1204** [arco-design/arco-design-vue#1251]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.29.1
- **框架版本:** Vue 2.29.1
- **浏览器版本:** chrome102.0.5005.63

![image](https://user-images.githubusercontent.com/9693637/172521512-23e19af1-36af-4fd3-927c-f3845766fb12.png)

**Comment by flsion** [comment]
@bzw1204 应该是 vite 插件 styleImport.ts 的问题， https://github.com/arco-design/arco-design-pro-vue/blob/main/arco-design-pro-vite/config/plugin/styleImport.ts#L46 ，这里的 'Optgroup' 改成 'optgroup' 试下。

**Comment by lesonky** [comment]
如果使用了 useFormItem 也会有类似的问题，解决方法是在列表里面加上  “use-form-item” 。大概类似 css.js 找不到的问题都是这里的问题

**Comment by fairySusan** [comment]
@lesonky 请问是在什么列表里添加“use-form-item”
