### ISSUE TITLE
当select option value值 为空时，选项label不显示

### ISSUE THREAD

**Issue by raythunder** [arco-design/arco-design-vue#1252]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Browser:** chrome102.0.5005.63

## What is expected?
<a-option value="">全部</a-option> 选项选中时，显示 "全部"

## Steps to reproduce
https://codesandbox.io/s/smoosh-currying-hswts0?file=/src/App.vue

**Comment by flsion** [comment]
@raythunder 目前的 select 是把 ''、null、undefined 当做没有选择的状态，并且 default-value = ''，这个修改会产生的 break change，影响到已经使用的用户，风险比较大，在目前的版本中应该不会再修改了。这里可以使用其他的值替代一下
