### ISSUE TITLE
input-password组件prefix插槽无法被识别

### ISSUE THREAD

**Issue by SouthWan** [arco-design/arco-design-vue#1254]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.29.1
- **框架版本:** Vue
- **浏览器版本:** chrome98.0.4758.81

**Comment by hehehai** [comment]
@SouthWan 你好，目前 `a-input-password` 组件是支持 prefix 的。[demo](https://stackblitz.com/edit/angular-u15txr?file=src/App.vue)

如果是出现无法识别的情况，麻烦提供一下复现，可能是使用的问题

**Comment by flsion** [comment]
> 是的，它是支持的，可是webstrom无法识别到这个slot

嗯，是的，目前 web-types 上智能提示的属性、插槽都是组件自身的，类似继承自 input 的没有添加。
这个可以作为个优化点处理下
