### ISSUE TITLE
select组件在不同size的情况下，options的尺寸都是相同的

### ISSUE THREAD

**Issue by XieYuanCode** [arco-design/arco-design-vue#1255]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Framework version:** Vue
- **Browser:** safari/605.1.15
- **Reproduction Link:** https://codesandbox.io/s/cranky-microservice-ufckqq?file=/src/App.vue

## What is expected?
select的不同尺寸，可以同步映射到options

**Comment by flsion** [comment]
@XieYuanCode 目前的设计上下拉菜单是没有 size 区分的，这里会和设计确定下，是否还需要添加 size 的差别

**Comment by hehehai** [comment]
同类问题 #658
