### ISSUE TITLE
table Columns增加泛型

### ISSUE THREAD

**Issue by strongyc** [arco-design/arco-design-vue#1257]
import type { TableColumnData } from '@arco-design/web-vue/es/table/interface'
 const columns: TableColumnData[] = [
    {
      title: '类型名称',
      dataIndex: 'name'
    },
    {
      title: '唯一编码',
      dataIndex: 'code',
      slotName: 'code'
    }]
建议TableColumnData[] 支持泛型  类似于TableColumnData<type>[]

**Comment by strongyc** [comment]
TableColumnData<type>[]

**Comment by strongyc** [comment]
TableColumnData< Type >[]

**Comment by hehehai** [comment]
@strongyc 你好，这里的具体是 TableColumnData 里的那个值需要泛型支持？目前 TableColumnData 应该没有需要泛型的，若需要自定义字段的话，可以继承下 TableColumnData 做扩展。
