### ISSUE TITLE
Drawer 中使用带插槽的输入框会导致输入框高度异常

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1261]
如题输入框，数字输入框，搜索框均有此问题。
![image](https://user-images.githubusercontent.com/77368194/172771332-42ee9b81-263e-49c4-8c4d-c3e775aefe0e.png)

**Comment by hehehai** [comment]
补充复现：https://stackblitz.com/edit/angular-dlu9of?file=src/App.vue
