### ISSUE TITLE
全局配置ConfigProvider的prefix-cls属性更改默认值后样式丢了

### ISSUE THREAD

**Issue by OPBR** [arco-design/arco-design-vue#1266]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Browser:** chrome102.0.5005.63

**Comment by flsion** [comment]
修改 prefix-cls 后，要使用 less 格式的样式文件，同时修改 @prefix 变量与自定义样式前缀相同。
https://arco.design/vue/docs/theme
