### ISSUE TITLE
按需加载，a-layout-sider组件设置resize-directions=“['right']”闪屏

### ISSUE THREAD

**Issue by robin901118** [arco-design/arco-design-vue#1269]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Browser:** edge 102.0.1245.33

## Steps to reproduce
unplugin-vue-components 插件的按需加载，
a-layout-sider组件设置resize-directions=“['right']”

**Comment by hehehai** [comment]
@robin901118 你好，麻烦提供一个复现吧

**Comment by tufygithub** [comment]
@robin901118 请问一下这个问题是怎么解决的，遇到了同样的问题，而且是开发环境查看时不闪烁，打包融合后端后查看页面闪烁

**Comment by Allenkearn** [comment]
请问下后面怎么解决的？我现在也遇到了这个问题
