### ISSUE TITLE
a-tree 、a-tree-select组件勾选框状态异常

### ISSUE THREAD

**Issue by wpp19146456770** [arco-design/arco-design-vue#1276]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.30.0
- **浏览器版本:** chrome102.0.0.0

## 预期结果
父级半选状态时   点击勾选父级   父级勾选框状态正常

## 复现步骤
1：全选tree  
2：取消勾选一个子级 
3：点击勾选父级
效果：父级为半选状态

**Comment by kirazxyun** [comment]
@wpp19146456770 你好，目前的问题有些模糊，麻烦给一下详细的说明，可以搭配上图来展示比较清楚。目前的理解是：
1. 父节点是全选状态的时候，取消一个子节点（此时父节点应该是半选的状态）
2. 接下来的步骤是点击父节点（结果应该是全选）
这样操作下来应该是父节点全选的状态，这是符合预期的，当父节点为半选状态的时候，再次点击会判断要全选。

**Comment by wpp19146456770** [comment]
你的第二步全选时对的  但是按钮样式还是半选状态
![image](https://user-images.githubusercontent.com/88469702/174288026-787d3c7e-97c7-409a-b9bf-525d1e655fb2.png)

**Comment by wpp19146456770** [comment]
如图  这时候不应该是 √吗

**Comment by wpp19146456770** [comment]
@kirazxyun

**Comment by flsion** [comment]
新版本已修复
