### ISSUE TITLE
range-picker v-model绑定后，选择后总是变为初始值

### ISSUE THREAD

**Issue by ssqf** [arco-design/arco-design-vue#1281]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.26.0
- **Framework version:** arco-design-pro-vue
- **Browser:** chrome102.0.5005.63

stackblitz 中运行也是相同的问题
https://stackblitz.com/edit/angular-wmso9b?file=src/App.vue

**Comment by hehehai** [comment]
@ssqf 你好，使用方式有问题，model 绑定，使用 v-model，若使用 :model-value 的方式，需要使用绑定事件去操作 model 值

https://staging-cn.vuejs.org/api/built-in-directives.html#v-model

```
...
<a-range-picker
    mode="month"
   v-model="timeRange"
    @change="onChange"
    @select="onSelect"
    style="width: 254px; marginBottom: 20px;"
  />
...
setup() {
   const timeRange = ref(['2022-06-13 00:00:00', '2022-06-13 23:59:59'])
}
```

**Comment by kirazxyun** [comment]
@ssqf 你好，v-model 需要绑定一个响应式的对象才可以。
