### ISSUE TITLE
当a-modal里放入a-tree的时候，同时给a-tree的父元素加上max-height: 400px

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#1283]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.30.2
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://codesandbox.io/s/wonderful-pond-5unwfs?file=/src/App.vue

## Extra info
按道理说，在展开树节点的时候，树的整体高度没有达到400px，不应该就显示滚动条，目前初步判断是a-tree的问题

**Comment by hehehai** [comment]
@lin-97 hi, 看了复现，这里不设置 `overflow-y: auto` 后就不会出现滚动条了。

- 不为 tree 包裹元素设置 overflow，当溢出后，modal-content 有设置 overflow, 会出现滚动条
- 或者使用 min-height 或 height 来限制容器高度
