### ISSUE TITLE
datepicker配置时间显示

### ISSUE THREAD

**Issue by afang-z** [arco-design/arco-design-vue#1284]
当配置不添加秒数的时候提示valid date
![image](https://user-images.githubusercontent.com/48020274/173324379-a121c4b6-e1fe-494f-b210-7a257b75592f.png)
![image](https://user-images.githubusercontent.com/48020274/173324151-72160966-07c5-4e89-a7dc-d217f85d5af4.png)

当配置添加上秒数的时候又是正常的
![image](https://user-images.githubusercontent.com/48020274/173324451-dbee1dde-bd79-40ce-b4e6-fa2f387f58eb.png)
![image](https://user-images.githubusercontent.com/48020274/173323912-b41abfb4-4032-439b-8077-4a576d4c0ed8.png)

**Comment by kirazxyun** [comment]
@afang-z 你好，需要同步配置一下 format 为 'HH:mm'

**Comment by afang-z** [comment]
有配置哦，这是我现在配置的效果






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design-vue] datepicker配置时间显示 (Issue #1284)





 
@afang-z 你好，需要同步配置一下 format 为 'HH:mm'

**Comment by hehehai** [comment]
后续追踪转至 #1515
