### ISSUE TITLE
<a-table>表格在展示树形数据并开启超出省略时缩进异常

### ISSUE THREAD

**Issue by skytot** [arco-design/arco-design-vue#1289]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Framework version:** vue3
- **Browser:** chrome102.0.0.0

## Steps to reproduce
表格展示树形数据
设置行属性  :ellipsis="true" :tooltip="true"
孙子节点数据缩进丢失

**Comment by flsion** [comment]
@skytot 这个问题在 2.30.x 版本修复了，可以升级一下。https://github.com/arco-design/arco-design-vue/pull/1248
