### ISSUE TITLE
a-modal组件bug。a-table性能问题

### ISSUE THREAD

**Issue by mark980828** [arco-design/arco-design-vue#1290]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.30.2
- **Framework version:** Vue3.2.36
- **Browser:** chrome102.0.5005.63

## Steps to reproduce
a-modal组件开启draggable时当内容长度超出屏幕高度的时候，去拖动标题，整个弹窗直接就上移了，怎么都弄不回来。
a-table组件开启column-resizable时  数据有100条时而且数据并不复杂，拖动列宽已经有明显卡顿，而且拖动的时候线是不跟着鼠标的，鼠标移动了100px，可能线才移动了七八十px。

**Comment by flsion** [comment]
@mark980828 Hi~ 2.32.0 版本已经处理了modal的问题。table 的性能问题预计会在近期着手优化一下。
