### ISSUE TITLE
[component] 未来会考虑实现滚动条组件吗?

### ISSUE THREAD

**Issue by L1yp** [arco-design/arco-design-vue#1291]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
类似于element-plus的el-scrollbar组件，

## What problem does this feature solve?
如table的滚动条，select下拉的滚动条目前还是windows原生的比较难看

**Comment by L1yp** [comment]
arco-design的table组件深得我心，唯一不匹配的就是滚动条，特别喜欢拖拽排序和radio功能~~~🤭

**Comment by hehehai** [comment]
@L1yp 你好，滚动条组件已在 beta #1098  中，稳定了会正式发布，欢迎尝鲜

ref: [playground](https://arco-vue-playground.netlify.app/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHdpZHRoID0gcmVmKDUwMClcbmNvbnN0IG51bWJlciA9IHJlZigxMClcbmNvbnN0IHRhZ3MgPSBjb21wdXRlZCgoKSA9PlxuICBBcnJheS5mcm9tKHsgbGVuZ3RoOiBudW1iZXIudmFsdWUgfSwgKF8sIGlkeCkgPT4gaWR4ICsgMSlcbilcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBBcmNvIFZ1ZSEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxhLXNjcm9sbGJhciBzdHlsZT1cImhlaWdodDogMjAwcHg7IG92ZXJmbG93OiBhdXRvXCI+XG4gICAgICA8ZGl2XG4gICAgICAgIHN0eWxlPVwiXG4gICAgICAgICAgaGVpZ2h0OiAyMDAwcHg7XG4gICAgICAgICAgd2lkdGg6IDIwMDBweDtcbiAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1wcmltYXJ5LWxpZ2h0LTQpO1xuICAgICAgICBcIlxuICAgICAgPlxuICAgICAgICBDb250ZW50XG4gICAgICA8L2Rpdj5cbiAgICA8L2Etc2Nyb2xsYmFyPlxuICAgIDxhLWRpdmlkZXIgLz5cbiAgICA8YS1mb3JtIGF1dG8tbGFiZWwtd2lkdGg+XG4gICAgICA8YS1mb3JtLWl0ZW0gbGFiZWw9XCJUYWcgTnVtYmVyXCI+XG4gICAgICAgIDxhLWlucHV0LW51bWJlclxuICAgICAgICAgIHYtbW9kZWw9XCJudW1iZXJcIlxuICAgICAgICAgIDptaW49XCIwXCJcbiAgICAgICAgICA6bWF4PVwiMjBcIlxuICAgICAgICAgIHN0eWxlPVwid2lkdGg6IDIwMHB4XCJcbiAgICAgICAgLz5cbiAgICAgIDwvYS1mb3JtLWl0ZW0+XG4gICAgICA8YS1mb3JtLWl0ZW0gbGFiZWw9XCJMaXN0IFdpZHRoXCI+XG4gICAgICAgIDxhLXNsaWRlciB2LW1vZGVsPVwid2lkdGhcIiA6bWluPVwiMFwiIDptYXg9XCI4MDBcIiAvPlxuICAgICAgPC9hLWZvcm0taXRlbT5cbiAgICA8L2EtZm9ybT5cbiAgICA8ZGl2IDpzdHlsZT1cInsgd2lkdGg6IGAke3dpZHRofXB4YCwgbWFyZ2luVG9wOiAnMjBweCcgfVwiPlxuICAgICAgPGEtb3ZlcmZsb3ctbGlzdD5cbiAgICAgICAgPGRpdj5ESVYgRWxlbWVudDwvZGl2PlxuICAgICAgICA8YS10YWcgdi1mb3I9XCJpdGVtIG9mIHRhZ3NcIiA6a2V5PVwiaXRlbVwiPlRhZ3t7IGl0ZW0gfX08L2EtdGFnPlxuICAgICAgPC9hLW92ZXJmbG93LWxpc3Q+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLmNvbnRhaW5lciB7XG4gIHBhZGRpbmc6IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

<img width="324" alt="image" src="https://user-images.githubusercontent.com/12692552/173760525-45d0a0b4-13ec-4ff6-9861-653e70566cfe.png">

**Comment by flsion** [comment]
repeat #23
