### ISSUE TITLE
Select  @change 方法可不可以接受多个形参

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1293]
```
              <a-select v-model="form_Model.clientId" allow-search allow-clear @change="clientChangeFunc">
                <a-option v-for="(item, index) in ClientList" :key="'list' + index" :value="index">{{ item.NameEn }}
                </a-option>
              </a-select>

```

```
const clientChangeFunc = (index: any) => {
  form_Model.invoiceto = ClientList.value[index].CompanyRemark;
  form_Model.clientId=index;
  form_Model.client = ClientList.value[index].NameEn;
}

```

作者您好，在这种情况下， 我没办法把 ClientList.value[index].Id 获取回显，因为 @change 只接受一个参数
能不能在扩展一下，

clientChangeFunc = (index: number,rows:any) => {

}
把rows行也返回出来

这个算一个建议

**Comment by flsion** [comment]
@cgrain1998 Hi~ 目前 change 事件的第一个参数有把已经选择的选项传出，我没有太明白，这里是还需要什么其他数据吗？

**Comment by cgrain1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cgrain1998** [comment]
大佬您好，意思是  @change  这里的方法是否能在返回一个参数，比如当前选中的option的集合下标  
![image](https://user-images.githubusercontent.com/35121432/176425524-7d17e3c1-3dc1-4b6f-b14d-7a7b0dadad5e.png)
您看，我这里选中的是shanghai 她在这个options 集合中的下标是1 
所以我想在  @change   改变是，既获取他的 index, 也行获取到他的 value值

**Comment by hehehai** [comment]
@cgrain1998 你好，这里建议使用 `${index}-${value}` 的方式处理，不使用数据绑定，@change事件的拿到 value 字符串后解析后再更新数据（这里传递 index 的话，会组件接口有变动-如多选情况）

**Comment by cgrain1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cgrain1998** [comment]
> @cgrain1998 你好，这里建议使用 `${index}-${value}` 的方式处理，不使用数据绑定，@change事件的拿到 value 字符串后解析后再更新数据（这里传递 index 的话，会组件接口有变动-如多选情况）

1
