### ISSUE TITLE
select选择项没办法用model-value(v-model)绑定选中值

### ISSUE THREAD

**Issue by chenyongxiong** [arco-design/arco-design-vue#1296]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **浏览器版本:** firefox101.0
- **依赖包名 及 版本:** @arco-design/web-vue@2.30.2

## 复现步骤
当editFormModel.status值为1时应该是选中正常，现在是直接拉插进多一个1的选项。
代码如下
<a-form-item field="status" label="状态" :rules="[{ required: true, message: '请选择' }]" :validate-trigger="['change']">

        <a-select v-model="editFormModel.status" placeholder="请选择" >
          <a-option value="1" >正常</a-option>
          <a-option value="2">禁用</a-option>
        </a-select>

      </a-form-item>

## 预期结果
v-model绑定的时候希望是默认选中正常。

**Comment by flsion** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
> 
> ## 基本信息
> * **浏览器版本:** firefox101.0
> * **依赖包名 及 版本:** @arco-design/web-vue@2.30.2
> 
> ## 复现步骤
> 当editFormModel.status值为1时应该是选中正常，现在是直接拉插进多一个1的选项。 代码如下
> 
> ```
>     <a-select v-model="editFormModel.status" placeholder="请选择" >
>       <a-option value="1" >正常</a-option>
>       <a-option value="2">禁用</a-option>
>     </a-select>
> 
>   </a-form-item>
> ```
> 
> ## 预期结果
> v-model绑定的时候希望是默认选中正常。

value="1" 对应的是字符串的 "1"，如果是想要数字这里改下 :value="1"
