### ISSUE TITLE
tabs样式疑问

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1306]
![QQ截图20220618002836](https://user-images.githubusercontent.com/88036648/174338994-e951dd5a-07ac-4e71-aedb-3c2dfcc93479.png)
这个点击的时候黑框哪里来的，之前没有哦。 刚升级2.31.0

**Comment by yinkaihui** [comment]
没有复现诶

**Comment by xiaomilaaz** [comment]
> 没有复现诶
你复现不吗，我很诧异呢，不知道怎么出现的。 刚升级2.32.0都一样有黑框

**Comment by hehehai** [comment]
@xiaomilaaz 你好，请打开官网的 [tabs网页](https://arco.design/vue/component/tabs) ，看下是否有同样的问题，尝试切换其他浏览，看是否有区别。

🤔 猜测：应该是聚焦时 outline 样式，可能是浏览器或相关插件有样式覆盖

**Comment by xiaomilaaz** [comment]
已经解决。自己的问题
