### ISSUE TITLE
Anchor锚点组件为什么没有随着页面滚动变化？

### ISSUE THREAD

**Issue by william-wei1** [arco-design/arco-design-vue#1308]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.31.0
- **Framework version:** Vue
- **Browser:** chrome95.0.4638.69

## Extra info
设置了line-less=false，change-hash=false

## What is expected?
Anchor锚点组件会随着页面滚动变化

## Steps to reproduce
anchor组件没有随着页面滚动变化是否是因为scroll-container属性没有正确设置？我的页面布局是左侧菜单列表固定，右侧内容滚动。所以scroll-container不能设置为window

**Comment by william-wei1** [comment]
设置为父级元素的class名

**Comment by mengdream** [comment]
我遇到了类似的问题，设置`scroll-container`为父级元素的class名为`content-container`，但是仍旧无效 

Package Name And Version: @arco-design/web-vue@2.35.1
Framework version: Vue
Browser: chrome 104.0.5112.101


`<template>
    <div class="app">
        <div class="layout">
            <a-layout style="background-color: transparent;">
                <a-layout-header>
                    <a-page-header title="EEEE" >
                    </a-page-header>
                </a-layout-header>
                <a-layout>
                    <a-layout-sider>
                        <a-menu
                            :style="{height: '100%',borderTopRightRadius: '16px',borderBottomRightRadius: '16px'}"
                            :default-open-keys="['0']"
                            :default-selected-keys="['0_0']"
                            show-collapse-button
                        >
                            <a-sub-menu key="0">
                                <template #icon>
                                    <icon-apps></icon-apps>
                                </template>
                                <template #title>测试测试</template>
                                <a-menu-item key="0_0">测试测试</a-menu-item>
                            </a-sub-menu>
                        </a-menu>
                    </a-layout-sider>
                    <a-layout-content style="margin: 20px 10px;">
                        <div class="content-container">
                            <a-link name="nrs" />
                            <div class="flex-box">
                                <img :src="yingYangIcon" class="titleImage"/>
                                <div class="content">

                                    <a-typography-title :heading="3">测试测试</a-typography-title>
                                    <a-typography-paragraph>测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试</a-typography-paragraph>
                                </div>
                            </div>
                            <a-divider class="half-divider"/>
                            <a-link name="asa" />
                            <div class="flex-box">
                                <img :src="ASAIcon" class="titleImage"/>
                                <div class="content">

                                     <a-typography-title :heading="3">测试测试</a-typography-title>
                                    <a-typography-paragraph>测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试</a-typography-paragraph>
                                </div>
                            </div>
                            <a-divider class="half-divider"/>
                            <a-link name="kangFu" />
                            <div class="flex-box">
                                <img :src="kangFuIcon" class="titleImage"/>
                                <div class="content">

                                    <a-typography-title :heading="3">测试测试</a-typography-title>
                                    <a-typography-paragraph>测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试</a-typography-paragraph>

                                </div>
                            </div>
                        </div>

                    </a-layout-content>
                    <a-affix>
                        <a-layout-sider>
                            <a-anchor :line-less="false" scroll-container="content-container">
                                <a-anchor-link href="#nrs" title="AAAAA">
                                </a-anchor-link>
                                <a-anchor-link href="#asa" title="BBBBB"></a-anchor-link>
                                <a-anchor-link href="#kangFu" title="术前盆底功能筛查"></a-anchor-link>
                            </a-anchor>
                        </a-layout-sider>
                    </a-affix>
                </a-layout>
                <a-layout-footer>Footer</a-layout-footer>
            </a-layout>
        </div>
    </div>
</template>`

**Comment by lhlyu** [comment]
作为补充
```vue
<a-anchor line-less :change-hash="true" scroll-container=".dom">
       <a-anchor-link :href="`#${k}`" v-for="(v, k) in Category" :key="k"> {{ v }}  </a-anchor-link>
</a-anchor>

<div class="dom">
这里是监听滚动的容器
</div>
```

测试发现只有 `change-hash` 为 `true` 时才生效
