### ISSUE TITLE
Modal 对话框有关闭并销毁吗？

### ISSUE THREAD

**Issue by liaocp666** [arco-design/arco-design-vue#1309]
类似React版本的unmountOnExit

**Comment by hehehai** [comment]
@liaocp666 你好，有的

<img width="996" alt="image" src="https://user-images.githubusercontent.com/12692552/174462853-3ac6844a-8e15-43cc-8c3e-3523cb68b7c6.png">

**Comment by liaocp666** [comment]
@hehehai 谢谢^_^，我感觉我是瞎了，还找了半天。。。。
