### ISSUE TITLE
Popover频繁闪现

### ISSUE THREAD

**Issue by xiaosongmao123** [arco-design/arco-design-vue#1310]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.31.0
- **Browser:** chrome102.0.5005.124
- **Reproduction Link:** https://arco.design/vue/component/popover

## What is expected?
隐藏后不再显示

## Steps to reproduce
官网示例，
1.鼠标移动到hover按钮上，让pop弹出显示
2.鼠标移动到pop弹出框里
3.鼠标移出pop -- pop隐藏
4.鼠标移动回原位--pop重新弹出 -- 隐藏后就不应该弹出

如图
![pop](https://user-images.githubusercontent.com/41795713/174473336-a00f7776-c9a1-4b04-83d4-d80b94412f73.gif)

**Comment by xiaosongmao123** [comment]
另外一个问题，
dropdown组件 支持属性 popup-max-height 用来禁止出现滚动条

`<a-dropdown @select="handleSelect" :popup-max-height="false">`

select组件不支持？希望select同样支持这个属性

**Comment by flsion** [comment]
@xiaosongmao123 很好的问题，我都没有这么操作过。弹出层在移入时会重置显示，这里需要优化下，触发隐藏后不再可以重置显示。

针对下面这个问题，目前只有展示类下拉组件 dropdown 和 menu 有 popup-max-height 属性，输入类的 select 和 cascader 等没有添加，这个可以再新建一个功能的 issue，用来跟踪一下
