### ISSUE TITLE
请问如何全局注入并修改组件的默认属性？

### ISSUE THREAD

**Issue by skytot** [arco-design/arco-design-vue#1311]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.29.1
- **Browser:** chrome102.0.0.0

## Steps to reproduce
比如需要全局设定input的allow-clear为true；
如何通过全局配置注入呢？

**Comment by hehehai** [comment]
@skytot 你好，全局配置可参考这个 https://arco.design/vue/component/config-provider

但目前是不支持全局设置 allow-clear 的
