### ISSUE TITLE
Typography.Paragraph类型缺少ellipsis

### ISSUE THREAD

**Issue by liziwork** [arco-design/arco-design-vue#1312]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.30.2
- **框架版本:** Vue ^3.2.25
- **浏览器版本:** chrome101.0.4951.67

## 额外补充
<Typography.Paragraph
    ellipsis={{ row: 1, showTooltip: false }}
    style={{ marginBottom: 0 }}
  >
  {item.content}
</Typography.Paragraph>

## 复现步骤
(property) ellipsis: {
    row: number;
    showTooltip: boolean;
}
不能将类型“{ ellipsis: { row: number; showTooltip: boolean; }; style: { marginBottom: number; }; }”分配给类型“IntrinsicAttributes & Partial<{ blockquote: boolean; spacing: "default" | "close"; }> & Omit<Readonly<{ blockquote?: unknown; spacing?: unknown; } & { blockquote: boolean; spacing: "default" | "close"; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "blockquote" | "spacing">”。
  类型“IntrinsicAttributes & Partial<{ blockquote: boolean; spacing: "default" | "close"; }> & Omit<Readonly<{ blockquote?: unknown; spacing?: unknown; } & { blockquote: boolean; spacing: "default" | "close"; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "blockquote" | "spacing">”上不存在属性“ellipsis”。ts(2322)

**Comment by hehehai** [comment]
@liziwork 你好，请升级最新版本后再次尝试
