### ISSUE TITLE
能否实现表格数据的跨页行选择

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1315]
表格组件的selected-keys属性只能记录当前页的被选择行，如果在某一页行选择后⇒进行翻页⇒在新的一页再进行行选择，之前页的勾选状态会被清空。

**Comment by hehehai** [comment]
@yymjku18 你好，可以的

https://github.com/arco-design/arco-design-vue/issues/1019#issuecomment-1106178581

**Comment by yymjku18** [comment]
@hehehai 感谢，已解决

**Comment by yymjku18** [comment]
@hehehai 啊，不好意思，果然我也是遇到跟上述issue一样问题，想获取完整的选择数据变得很不方便，画面表示虽然没什么问题，但数据没有被完整记录，只维护着当前页的被选择key

**Comment by hehehai** [comment]
@hehehai 嗯，这个可以在 select 事件发生时，将选中的完整数据更新一下（可以使用一个单独的数据集合）

**Comment by yymjku18** [comment]
@hehehai 非常感谢，可以实现。
不过这么做虽然多写不了多少业务逻辑，但着实感觉这些逻辑加的有点被动(UI组件库依存症--)
今后有考虑添加props来维护完整数据么。

**Comment by hehehai** [comment]
@yymjku18 谢谢🥰，目前这块应该不会改动了。之后文档部分有计划补充些说明和解决方案。

**Comment by yymjku18** [comment]
@hehehai 不好意思，还是有麻烦，之前的问题一件一件的勾是没有问题的。
但我想实现全选第一页，单选第二页几条，然后拿到所有key，这似乎很难实现
问题点:
    1.只有@select的时候是无法完成全选的。需要提供 @selection-change完成全选逻辑
    2.选取一件时触发select的同时也会触发selection-change会造成一系列的逻辑冲突，导致全选的keys被重新赋值
    3.@select-all似乎可以使用但只能接受一个checked参数，无法维护key数据。

**Comment by hehehai** [comment]
@yymjku18 嗯，明白了。

看了下，新的版本库，select 事件有些行为变动（之前的demo版本不是最新的），我这边先再测试下看

**Comment by flsion** [comment]
@yymjku18 可以用个map存一下，我弄了个DEMO https://codesandbox.io/s/headless-glitter-n89y9p?file=/src/App.vue 

写下来感觉是很麻烦，目前考虑可以优化下几种选择事件，让这种情况更好处理下

**Comment by yanbowe** [comment]
> @yymjku18 可以用个map存一下，我弄了个DEMO https://codesandbox.io/s/headless-glitter-n89y9p?file=/src/App.vue
> 
> 写下来感觉是很麻烦，目前考虑可以优化下几种选择事件，让这种情况更好处理下

hi,这个demo实现方式似乎有些问题，当我第一页点击全选，第二页点击全选，第三页点击全选后，在回到第一页或第二页发现无法去掉勾选状态了

**Comment by yymjku18** [comment]
> 
大佬幸苦了，这个demo确实有如上问题，我也是研究了一阵子，也没找到原因
如果进行如下操作:全选任意两页⇒进行一次任意的翻页操作
结果 :被选中的勾就再也取不掉了（数据也乱了）

**Comment by yymjku18** [comment]
> @yymjku18 可以用个map存一下，我弄了个DEMO https://codesandbox.io/s/headless-glitter-n89y9p?file=/src/App.vue
> 
> 写下来感觉是很麻烦，目前考虑可以优化下几种选择事件，让这种情况更好处理下

大佬幸苦了，这个demo确实有如上问题，我也是研究了一阵子，也没找到原因
如果进行如下操作:全选任意两页⇒进行一次任意的翻页操作
结果 :被选中的勾就再也取不掉了（数据也乱了）
