### ISSUE TITLE
期望表格增加双击事件

### ISSUE THREAD

**Issue by kanyxmo** [arco-design/arco-design-vue#1316]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
表格增加双击事件

## What problem does this feature solve?
因为想实现双击单元格或者行弹出编辑框

**Comment by HeiShuXianSheng** [comment]
感觉你可以试试用tr插槽自定义点击事件试一试
![image](https://user-images.githubusercontent.com/57590348/175199681-c076dd00-4293-48f8-a3d2-0fd410bb2987.png)
