### ISSUE TITLE
table使用column中的 ellipsis: true, tooltip: true时。tooltip中显示了下一行的数据

### ISSUE THREAD

**Issue by HeiShuXianSheng** [arco-design/arco-design-vue#1318]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.29.0
- **框架版本:** "vue": "^3.2.33",
- **浏览器版本:** chrome102.0.0.0

## 复现步骤
```js
<a-table  :columns="columns" ...>
const columns = [
      {
        title: '项目名称',
        dataIndex: 'name',
        ellipsis: true,
        tooltip: true,
      },
      ...
]
```
![demogif](https://user-images.githubusercontent.com/57590348/174969140-3ec5e6bb-0518-4084-9359-9bc71134ea0a.gif)

不是每次都会出现这种问题，一般来说是鼠标从下往上移动时，可能会出现。出现后，鼠标从<td />的上方移入该td时，又会正常显示该项的内容

**Comment by yanbowe** [comment]
感觉跟这个问题很类似[#1310 ](https://github.com/arco-design/arco-design-vue/issues/1310)
