### ISSUE TITLE
tooltip部分场景导致页面抖动

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#1321]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.31.0
- **Browser:** chrome102.0.5005.124

在一个滚动的`drawer`中，如果`tooltip`刚好靠边，且内容较多。此时hover触发显示`tooltip`，并立即将鼠标移动到`tooltip`上，此时页面就会抖动，目测是`tooltip`检测到内容已经靠边了，需要换行，又没有换行成功导致的，过程中可以看到`tooltip`换行后又立马变为一行了。

**Comment by flsion** [comment]
@llk2yq 这个抖动是在动画中发生的吗，在显示后会出现问题吗？

**Comment by hehehai** [comment]
该问题长时间无反馈，先关闭了。

**Comment by llk2yq** [comment]
我尝试提供一下复现链接吧

**Comment by mengxk2018** [comment]
我也遇到了，手机模式下，table有滚动条，td 中的span tooltip  placement=“right”，hover时，会自动排版到左边，就会在左右来回切换，导致页面抖动

**Comment by nuagecen** [comment]
> 该问题长时间无反馈，先关闭了。

https://github.com/arco-design/arco-design-vue/issues/2216  和这个应该是一个问题吧？ zoom-in-fade-out  动画就出现这个抖动。好像trigger组件第一次计算宽度好像不太对，导致 body 产生滚动条了。 挺好复现的，你用 position="right" 然后内容写多一些，多到能顶到右侧超出。就能复现。

**Comment by llk2yq** [comment]
body 加上overflow:hidden就行了。

**Comment by nuagecen** [comment]
已收到您的邮件~我会尽快给您回复的哦~
