### ISSUE TITLE
选择框组件BUG

### ISSUE THREAD

**Issue by mark980828** [arco-design/arco-design-vue#1322]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.31.0
- **Framework version:** Vue@3.2.36
- **Browser:** chrome102.0.5005.63
- **Reproduction Link:** https://stackblitz.com/edit/angular-lyhrun?file=src%2FApp.vue

## Steps to reproduce
在select组件内搜索   用输入法输入汉字控制台会报错

**Comment by hehehai** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/12692552/175260755-58527769-0e56-4063-a53f-19411330af59.png">
