### ISSUE TITLE
TableColumn bug

### ISSUE THREAD

**Issue by jsonleex** [arco-design/arco-design-vue#133]
```
<template>
  <a-table :data="data">
    <template #columns>
      <a-table-column title='works' dataIndex='name'></a-table-column>
      <a-table-column title='not works' data-index='name'></a-table-column>
    </template>
  </a-table>
</template>

<script lang='ts' setup>
 const data = [{ name: 'arco table columl' }, { name: 'arco table columl' }]
</script>
```

![image](https://user-images.githubusercontent.com/25883665/141263559-b478a397-e091-4171-b43b-9c3f0d08268c.png)

上面相同的代码

在 **单文件模板** 中使用 _短横线_ 属性传 props，col 渲染为空白。

在 **codepen** 中使用 _驼峰命名_，col 渲染为空白。

**Comment by Flsion** [comment]
@jsonleex 

- 2.1.0版本修复了 **单文件模板** 中不能使用 _短横线_ 的问题，可以升级试一下。
- codepen的html中不支持大写的属性，我们在逐步改下有这个问题的DEMO代码
