### ISSUE TITLE
`Table`空数据时，底部边框重合

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#1333]
![image](https://user-images.githubusercontent.com/22813922/175511076-f947e25e-8c41-4a89-9f7d-4189b1fdce2f.png)

**Comment by flsion** [comment]
> ![image](https://user-images.githubusercontent.com/22813922/175511076-f947e25e-8c41-4a89-9f7d-4189b1fdce2f.png)

你好，能够提供一个复现的地址吗？

**Comment by llk2yq** [comment]
可能是我使用了template的方式吧，直接写一个最简单的`table`即可复现：
```vue
 <a-table :data="list">
    <template #columns>
        <a-table-column title="姓名" align="center"></a-table-column>
        <a-table-column title="操作" :width="220"></a-table-column>
    </template>
</a-table>
```

**Comment by hehehai** [comment]
@llk2yq 可以提供下版本吗？可以在下面的 demo 上测试下

目前最新版本(2.32.0)没有成功复现 https://stackblitz.com/edit/angular-e3nvk9?file=src%2FApp.vue
