### ISSUE TITLE
表单在 required 为 true 的时候 无法隐藏 * 导致表格出现问题

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#134]
假设一个表单，我不需要使用 label， 仅仅使用 input + prefix 的布局，但是 required 为 true 的时候确无法隐藏 * 号。

希望能自动判断 label 是否为空，来决定 * 是否出现，或者给个强制开关解决这个问题。

![image](https://user-images.githubusercontent.com/21995186/141269597-5cd199fe-a32c-4e15-a5f4-248fe2cec3c8.png)

**Comment by Flsion** [comment]
@fangjc1986 form-item 有 hide-asterisk 属性可以不显示这个星号
