### ISSUE TITLE
Descriptions可以添加tableLayout功能吗

### ISSUE THREAD

**Issue by liziwork** [arco-design/arco-design-vue#1345]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
tableLayout	描述中表格样式的 layout-fixed，当设置成 fixed 时，宽度会均分。	'auto' | 'fixed'	auto
https://arco.design/react/components/descriptions#api

## 预期解决问题
可以实现让表格等分布局

**Comment by liziwork** [comment]
![image](https://user-images.githubusercontent.com/19724731/175841212-e9f35183-e22a-4736-ac8f-bde5251d7bcc.png)

**Comment by flsion** [comment]
@liziwork 收到，新版本会加上
