### ISSUE TITLE
给typography-text添加了自定义click事件，如果同时开启copyable，点击copy时，会同时触发copy和自定义click事件

### ISSUE THREAD

**Issue by shoo-be-doo** [arco-design/arco-design-vue#1349]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.32.0
- **Framework version:** Vue
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/vibrant-wilson-s2nfwc

## Extra info
期望能只触发copy事件

## What is expected?
click 事件和 copy 一起触发

## Steps to reproduce
点击copy图标

**Comment by hehehai** [comment]
@flsion 或许需要给 copy，edit， expand 事件加个 stop 描述符，阻止冒泡，你觉得呢？

https://github.com/arco-design/arco-design-vue/blob/b4bd141ce11102093ec8229cf935015285cc060c/packages/web-vue/components/typography/operations.vue#L16-L27

https://github.com/arco-design/arco-design-vue/blob/b4bd141ce11102093ec8229cf935015285cc060c/packages/web-vue/components/typography/operations.vue#L4-L6

https://github.com/arco-design/arco-design-vue/blob/b4bd141ce11102093ec8229cf935015285cc060c/packages/web-vue/components/typography/operations.vue#L30-L38
