### ISSUE TITLE
求助:多关键词带提示搜索功能

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#1351]
我想实现一个支持多关键字带提示的搜索功能，类似于现在API文档搜索功能，目前尝试魔改了自动补全，(标签输入框+触发器)和选择器,但都是困难重重。主要原因是现有输入框部分跟下拉框部分互动性太强，两部分数据关联也太紧密，导致不好完成需求。
可能需要自己封装一个组件，但没有很好的思路，有没有好心人支支招啊~

**Comment by hehehai** [comment]
@yymjku18 你好，看需求应该需要自己封装一下，结构的话，应该是 input + search result list（可能涉及到虚拟列表） 就可以，这里主要是自动补全，[模糊匹配](https://github.com/superhuman/command-score)的问题（可以下 kbar 的依赖）。功能的话，可以参考[官方物料 arco-site-navbar ](https://arco.design/material/detail?name=@arco-design/arco-site-navbar) 。

可以参考下这个 https://github.com/timc1/kbar

**Comment by yymjku18** [comment]
@hehehai 谢谢指导，我还需要了解的是自动补全或选择器的下拉框键盘可操作是如何实现的。

**Comment by hehehai** [comment]
> @hehehai 谢谢指导，我还需要了解的是自动补全或选择器的下拉框键盘可操作是如何实现的。
自动补全参考 模糊匹配，键盘事件做下事件监听，[timc1/kbar](https://github.com/timc1/kbar) 这个项目功能应该都有

**Comment by yymjku18** [comment]
@hehehai 3q3q,不好意思，我还想问下自动补全想实现自动聚焦好实现么，如果只是单纯的input组件内置了focus事件和focus方法，通过focus()或$emit("focus")都可以实现。可是自动补全该怎么办呢。

**Comment by hehehai** [comment]
@yymjku18 可以到飞书群里交流
![飞书20220628-173459](https://user-images.githubusercontent.com/12692552/176146458-39e11321-7fb2-4b55-866e-e542444e1384.png)
