### ISSUE TITLE
导入组件运行报错

### ISSUE THREAD

**Issue by CatsAndMice** [arco-design/arco-design-vue#1352]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.32.0
- **Browser:** Microsoft Edge 版本 103.0.1264.37 (正式版本)
组件库下载，导入项目后 按文档**全局安装**使用，运行后直接报错
![image](https://user-images.githubusercontent.com/58327088/176105636-a8413740-2d5f-4138-8543-e5457e9c487b.png)
下面是报错信息：
![image](https://user-images.githubusercontent.com/58327088/176105385-2250f2dc-9555-4813-ac43-00fffb323bab.png)
![image](https://user-images.githubusercontent.com/58327088/176105393-988564e4-a7b3-4f58-ae30-982d2e192192.png)

**Comment by hehehai** [comment]
@CatsAndMice 你好，麻烦发一下，arco 安装和组件使用的代码吧。
