### ISSUE TITLE
动态表单重置无效

### ISSUE THREAD

**Issue by liziwork** [arco-design/arco-design-vue#1353]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.32.0
- **框架版本:** vue
- **浏览器版本:** chrome102.0.0.0

## 复现步骤
如果将数据进行splice，调用restFields无法重置数组至初始状态。删除的数组无法重置回来，新增的无法删除掉。

**Comment by hehehai** [comment]
@liziwork 你好，麻烦提供一个复现吧

**Comment by flsion** [comment]
@liziwork  form中是以引用的方式保存的初始值，splice 方法由于没有修改引用导致内部判断值没有改变。这里可以改成保存个新值，调用restFields 时用新值替代。
