### ISSUE TITLE
Textarea在表格中存在样式问题

### ISSUE THREAD

**Issue by liziwork** [arco-design/arco-design-vue#1354]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.32.0
- **框架版本:** vue
- **浏览器版本:** chrome102.0.0.0

## 复现步骤
表格中插入textarea，样式会出现问题，审查元素发现是块级元素的问题，将.arco-textarea-wrapper的inline-block设置成block或者inline-flex即可解决。
![image](https://user-images.githubusercontent.com/19724731/176346048-279da26f-6503-4738-9987-42551b747178.png)
![image](https://user-images.githubusercontent.com/19724731/176346079-baa51f07-0423-42fd-bab6-a9a9233ec840.png)
![image](https://user-images.githubusercontent.com/19724731/176346101-86b39c9b-c40d-460c-92c9-56b870f38d82.png)
![image](https://user-images.githubusercontent.com/19724731/176346159-c26138b1-494d-4e70-9958-ee18fc07bf5e.png)

**Comment by hehehai** [comment]
@liziwork 你好，这里[复现](https://stackblitz.com/edit/angular-qdh9kn?file=src/App.vue)，看起来没什么问题。

**Comment by hehehai** [comment]
长时间无回复，暂时关闭了。
