### ISSUE TITLE
当给modal设置了最大高度，打开modal上的控件在滚动滑轮，modal上控件不跟着model滚动

### ISSUE THREAD

**Issue by lirongzhu** [arco-design/arco-design-vue#1356]
当在modal中打开一个组件，然后滚动滑轮会出现以下效果，好像是跟着body的位置进行定位的，没有根据modal的位置
<img width="682" alt="微信截图_20220629151329" src="https://user-images.githubusercontent.com/8097432/176375300-eefb34cc-0020-4531-8a0d-9a0f6339ecb4.png">
<img width="675" alt="微信截图_20220629151421" src="https://user-images.githubusercontent.com/8097432/176375240-de9dd89d-fe91-4833-abb1-5e6ac268f947.png">

**Comment by flsion** [comment]
@lirongzhu 可以开启 select 组件 trigger-props 的 updateAtScroll 处理这个问题，要是场景比较多，可以用 ConfigProvider 全局开启

**Comment by flsion** [comment]
可以设置 :trigger-props="{trigger:'focus'}" 指定focus时打开
