### ISSUE TITLE
Typography和a-link一起使用，在使用省略属性时，会使a-link失效

### ISSUE THREAD

**Issue by wou101771** [arco-design/arco-design-vue#1361]
I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
Basic Info
Package Name And Version: @arco-design/web-vue@2.32.0
Framework version: "vue": "^3.2.25",
Browser: chrome101.0.0.0

**Comment by flsion** [comment]
@wou101771  Typography 组件的省略是针对纯文本的，不支持富文本内容
