### ISSUE TITLE
Input不能是整数，希望修复

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1375]
用Input后，只要是整数就提示Invalid prop: type check failed for prop "modelValue". Expected String with value "0", got Number with value 0. ，但表单不一定是数字也可能是字符。

希望解决修复

**Comment by flsion** [comment]
@xiaomilaaz input处理的是字符串类型，如果需要数字类型可以使用input-number或者自己对值进行转换处理

**Comment by xiaomilaaz** [comment]
> @xiaomilaaz input处理的是字符串类型，如果需要数字类型可以使用input-number或者自己对值进行转换处理

这个很不人性化了，太麻烦了

**Comment by flsion** [comment]
@xiaomilaaz  可以去除 value 类型的限制，但是 input 组件的默认输出是固定 string 类型的

**Comment by hehehai** [comment]
重复 #1520
