### ISSUE TITLE
a-input-tag 组件在设置 max-tag-count 属性且超出后 使用键盘删除触发的 remove 事件不正确

### ISSUE THREAD

**Issue by U888888** [arco-design/arco-design-vue#1378]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.32.1
- **浏览器版本:** chrome103.0.0.0
- **复现地址:** https://stackblitz.com/edit/kpw326?file=src/App.vue

## 预期结果
1. removed 的值应为 five
2. value 的值应为 ['one', 'two', 'three', 'four']

## 复现步骤
1.点击输入框
2.键盘点击 Backspace 键
3.查看控制台

**Comment by s7venteen** [comment]
确实有这个问题
