### ISSUE TITLE
Tree组件动态加载时，选中父节点，加载出来的子节点值没有更新。

### ISSUE THREAD

**Issue by yuhan0709** [arco-design/arco-design-vue#138]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** 最新版本
- **系统版本:** null
- **浏览器版本:** null
- **复现地址:** https://codepen.io/yuhan0709/pen/OJjwBZa?editors=1010

## 预期结果
1. 该节点下的所有子节点被选中
2. 开启虚拟列表后没问题。
3. default-checked-keys 无效

## 复现步骤
1. 选中Trunk0-0
2. 展开该节点
3. 该节点下的所有子节点未被选中
4. 而且开启虚拟列表会出问题。

**Comment by kirazxyun** [comment]
default-checked-keys 的问题已经在 #131 中解决
