### ISSUE TITLE
How to Using Vue 3 in IE11 ?

### ISSUE THREAD

**Issue by zhangyuhan2016** [arco-design/arco-design-vue#1380]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info
I noticed that there is a label on the document, which can increase Polyfill to support the IE browser.
But there is no relevant successful experience on the public Internet. 
Can you supplement the document or a simple reply?

## What are the similar cases of this feature
/

## What problem does this feature solve?
Better documentation support

## Extra info
[Using Vue 3 in IE11 ? -- stackoverflow](https://stackoverflow.com/questions/64836337/using-vue-3-in-ie11)

**Comment by flsion** [comment]
@zhangyuhan2016 It is possible to polyfill using the babel plugin, but there are still some issues with this. The component library use CSS variables as the base value for style, which is also not supported on IE. We do not recommend using the component library on IE.

docs: https://cli.vuejs.org/guide/browser-compatibility.html

**Comment by zhangyuhan2016** [comment]
我检索到了一种解决 CSS 变量的替换方案。

[css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill)。

但是我觉得不应该投入过多的精力来兼容 IE，所以我建议从文档移除这些特殊的提示文案。

**Comment by flsion** [comment]
Yes, I also think it would be better to remove the description for IE, which is now deprecated
