### ISSUE TITLE
drawer无mask时不支持drawer外区域的交互

### ISSUE THREAD

**Issue by joeywongz** [arco-design/arco-design-vue#1383]
drawer去掉遮罩之后无法在外面操作页面元素

**Comment by joeywongz** [comment]
Basic Info
Package Name And Version: @arco-design/web-vue@2.32.1
Framework version: vue3.2.37
Browser: chrome 103.0.5060.66

**Comment by hehehai** [comment]
重复问题，后续转到 #1363
