### ISSUE TITLE
【FR】a-tree组件的checked-strategy希望能增加返回所有关联的节点

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#1386]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
例如目前有节点
- 1
  - 1.1
  - 1.2

不知道现在权限配置这块用a-tree如何来实现，目前我们是关闭check-strictly，通过让用户去点每一个节点来获取，但是权限多了操作非常繁琐
而如果关闭check-strictly，选择子节点又无法返回其父节点id，虽然可以用递归来获取，但是获取了之后，比如点击了`1.1`，可以通过计算得到[1, 1.1]，但是回显的时候设置check-keys为[1, 1.1]，界面上就会变成`1.2`也被勾选了，这时候又得手动计算把所有父节点中子节点没有全被选择的剔除

## What are the similar cases of this feature
希望选中某个子节点时，能获取选择子节点及其关联所有父节点
![image](https://user-images.githubusercontent.com/93666053/177458776-db5188ba-8793-42be-92c6-7d8a95394110.png)

## What problem does this feature solve?
在系统中很常见的角色管理中的用户权限配置

**Comment by kirazxyun** [comment]
@seepine 你好，选择节点后要获取其父节点可以自行遍历一下树节点来获取的。

**Comment by kirazxyun** [comment]
@seepine 你好，选择节点后要获取其父节点可以自行遍历一下树节点来获取的。

**Comment by hehehai** [comment]
@seepine hi, 这里暂时未实现，可以先自己做下选中节点的子节点遍历，全部标记为选中即可。
