### ISSUE TITLE
webpack自定义组件样式

### ISSUE THREAD

**Issue by Booshaw** [arco-design/arco-design-vue#1387]
vue自定义主题发布后, 基础(颜色)样式正常, 组件样式被默认组件样式覆盖;
qiankun加载多个css, 自定义样式被覆盖;
主、子应用都是用arco-design-vue, 加载同样的自定义文件;

**Comment by hehehai** [comment]
@Booshaw hi, 这里的问题是？没懂

**Comment by hehehai** [comment]
该问题暂时关闭，请补充更多描述信息，或提供参考后可再开启。
