### ISSUE TITLE
fix:upload preview error

### ISSUE THREAD

**Issue by ttsimon** [arco-design/arco-design-vue#1389]
项目中使用的Vue版本  使用了官方提供的按需加载方案
```
<a-upload
    v-if="props.type === 'multiple'"
    list-type="picture-card"
    accept="image/png,image/jpeg,image/gif"
    :file-list="fileList"
    image-preview
    :custom-request="fileUpload"
    :on-before-remove="removeImage"
  />

```
image-preview 增加之后点击查看图标 没有弹出大图

**Comment by hehehai** [comment]
@ttsimon 你好，是否有错误信息（控制台或终端）？

**Comment by hehehai** [comment]
长时间无反馈，暂时关闭，后续补充内容后可重新开启。

**Comment by maopixin** [comment]
> 长时间无反馈，暂时关闭，后续补充内容后可重新开启。

没有报错、不加image-preview也会有小眼睛图标，加不加点击都没用。

**Comment by AidenChen** [comment]
我也遇到了一样的问题，引入样式文件import "@arco-design/web-vue/dist/arco.css";能解决这个问题，只是这样太不优雅，希望官方能给出一个解释

**Comment by JawilX** [comment]
> 我也遇到了一样的问题，引入样式文件import "@arco-design/web-vue/dist/arco.css";能解决这个问题，只是这样太不优雅，希望官方能给出一个解释

我也遇到了，看到你这个才反应过来是css问题，被迫 import '@arco-design/web-vue/es/image/style/css'
