### ISSUE TITLE
a-menu组件问题

### ISSUE THREAD

**Issue by lwh795** [arco-design/arco-design-vue#1392]
![IMG_8175](https://user-images.githubusercontent.com/20041248/177578686-55855a42-f3e2-407d-8a94-b4a096d4ab47.JPG)
如图menu有两种模式，因为mode只绑定在menu上且是唯一值无法方便实现该功能，建议修改为submenu同样支持mode属性的定义。

**Comment by kirazxyun** [comment]
你好，submenu 支持单独设置为弹出模式的
![image](https://user-images.githubusercontent.com/10192144/180355549-e2503c13-e1e7-43f0-8cb7-b1b75416bb8e.png)

**Comment by lwh795** [comment]
感谢你的邮件，后面我再实现看看。
谢谢～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design-vue] a-menu组件问题 (Issue #1392)





 
你好，submenu 支持单独设置为弹出模式的

**Comment by lwh795** [comment]
修改submen的popup属性可以实现
