### ISSUE TITLE
Tree 组件的 check-strictly 属性逻辑不对

### ISSUE THREAD

**Issue by yy981420974** [arco-design/arco-design-vue#14]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info
- **依赖包名 及 版本:**  @arco-design/web-vue:2.0.2
- **系统版本:** Windows 10  20H2
- **浏览器版本:** Microsoft Edge  95.0.1020.30 （64bit）
- **复现地址:** https://codepen.io/yy981420974/pen/dyzRWOR

## 预期结果
初始化取消关联父子节点，也就是将 checked-keys 里面的节点选中，然后开启 父子关联属性之后，已初始化选中的节点不再发生变化，当下一次进行节点的选中/取消，如果有子节点，子节点也响应的选中或取消。

现在的情况是，只要启用父子节点，那么 checked-keys 属性的 选中节点等于没用，因为只要有节点包含数据，无论子节点是否选中，都会默认给你全部选中。

## 复现步骤
1.设置 Tree 组件的 check-strictly 为 true
2.设置 Tree 组件的 checked-keys 默认选中节点，选中节点必须包含子节点
3.使用 setTimeout 模拟数据初始化完成之后，将 check-strictly 设置为 false 
4.观察 Tree 组件的 选中节点以及子节点的 变化过程

**Comment by ChuChencheng** [comment]
Branch 0-0-0 这个节点确实保持选中了

因为开启了父子关联，其下的子节点在改变 `check-strictly` 后都被选中了，这是符合预期的，否则就不符合 `check-strictly: false` 这个逻辑了

如果想忽略 `checked-keys` 中的子节点，不妨试试 `checked-strategy` 这个属性

**Comment by seepine** [comment]
目前的选择结果是符合预期的

只不过我想，提问者是想要实现这个场景，如图
![image](https://user-images.githubusercontent.com/93666053/141233678-ad91c451-a1bf-4d53-9f00-f6319f02a4be.png)
勾选了子节点，真实返回的选中数据是    ['账号管理']
而提问者想要返回    ['系统管理', '账号管理']

当然这个可以自己计算得到，但是当设置checkedKeys =  ['系统管理', '账号管理'] 时
![image](https://user-images.githubusercontent.com/93666053/141233956-e019fec4-0c0d-4b63-ad30-e651a21c159d.png)
会变成这个情况，视图上全是勾选的

**Comment by kirazxyun** [comment]
> 目前的选择结果是符合预期的
> 
> 只不过我想，提问者是想要实现这个场景，如图 ![image](https://user-images.githubusercontent.com/93666053/141233678-ad91c451-a1bf-4d53-9f00-f6319f02a4be.png) 勾选了子节点，真实返回的选中数据是 ['账号管理'] 而提问者想要返回 ['系统管理', '账号管理']
> 
> 当然这个可以自己计算得到，但是当设置checkedKeys = ['系统管理', '账号管理'] 时 ![image](https://user-images.githubusercontent.com/93666053/141233956-e019fec4-0c0d-4b63-ad30-e651a21c159d.png) 会变成这个情况，视图上全是勾选的

了解，如果是这个场景的话，最终数据可以用另外的变量来存储，不要影响到 checkedKeys。
