### ISSUE TITLE
tree与treeselect这两个组件存在问题.请尽快解决

### ISSUE THREAD

**Issue by keyes2003** [arco-design/arco-design-vue#1403]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.32.1
- **Framework version:** 2.32.1
- **Browser:** chrome103.0.5060.114

## What is expected?
尽快修复

## Steps to reproduce
在没有默认的数据下.. 异步请求数据后无法渲染选项问题. 
既: :data="xxx"  xxx=ref([]) 
然后异步请求的树形数据
xxx.value = await get()
组件即会报错.

如果是

xxx.value = [{}, {}, {}] 手动赋值就可以渲染...很纠结.

我的代码
![image](https://user-images.githubusercontent.com/25757810/178103536-b9aff6fb-3be8-4380-8db2-923a6dd5bf8a.png)

由于load-more 在没有数据的情况下不会触发.也建议新增一个初始化数据的属性.或回调 现在这个情况使用起来很无语.

![image](https://user-images.githubusercontent.com/25757810/178103445-e726d8c8-0357-49f1-ad8a-1d631b8beead.png)

**Comment by deftliang** [comment]
@keyes2003 你好, 可以提供一个重现的代码么?

**Comment by keyes2003** [comment]
HELLO 
      我已收到您的来信，我会及时回复邮件。

**Comment by keyes2003** [comment]
HELLO 
      我已收到您的来信，我会及时回复邮件。
