### ISSUE TITLE
[Modal] Should `arco-modal-title-align-undefined` be used instead of `arco-modal-title-align-default` ? 

### ISSUE THREAD

**Issue by jsonleex** [arco-design/arco-design-vue#1412]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.33.0
- **框架版本:** vue
- **浏览器版本:** chrome103.0.0.0
- **复现地址:** https://github.com/arco-design/arco-design-vue/blob/163a2750196572bf3151d05621ee3f68a189ddfc/packages/web-vue/components/modal/__test__/__snapshots__/index.test.ts.snap#L13

**Comment by flsion** [comment]
This is a bug, the default should be `arco-modal-title-align-center`
