### ISSUE TITLE
date-pick 组件 format 支持函数类型

### ISSUE THREAD

**Issue by SeigeC** [arco-design/arco-design-vue#1414]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
date-pick 组件 format 支持函数类型

## 预期解决问题
date-pick 组件 format 支持函数类型

**Comment by kirazxyun** [comment]
你好，日期是支持函数的
![image](https://user-images.githubusercontent.com/10192144/180355910-ca940d90-0eec-4c3c-bcaf-e2149b377227.png)
