### ISSUE TITLE
slider components   cant select `min` value for `range` model on mobile device

### ISSUE THREAD

**Issue by hanrea** [arco-design/arco-design-vue#1415]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.33.0
- **Framework version:** Vue
- **Browser:** chrome103.0.0.0

**Comment by hehehai** [comment]
@hanrea hi, arco-design-vue mobile is not supported. Mobile component library is recommended [Arco Mobile](https://arco.design/mobile/react)

**Comment by hanrea** [comment]
> @hanrea hi, arco-design-vue mobile is not supported. Mobile component library is recommended [Arco Mobile](https://arco.design/mobile/react)

Thanks！
