### ISSUE TITLE
a-link href 和 @click跳转的路由结果不一致

### ISSUE THREAD

**Issue by chenxi2015** [arco-design/arco-design-vue#1416]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.31.0
- **Browser:** chrome103.0.0.0

## Steps to reproduce
一、vue-router配置了一个二级目录
```
const router = createRouter({
  // history: createWebHashHistory(),
  history: createWebHistory('/bs/'),
  routes
})
```

二、push方式访问
```
this.$router.push('/transaction');
```
可直接访问到 /bs/transaction

使用了 
```
<a-link :href="/transaction">更多></a-link>
```
访问路由错误

**Comment by hzgotb** [comment]
:href 里面应该写字符串。你前后加个单引号？
```vue
<a-link :href="'/transaction'">更多></a-link>
```
或者
```html
<a-link href="/transaction">更多></a-link>
```

**Comment by jiatiejun** [comment]
实测似乎不行

href 只要前面带有 “/” 就不理会 createWebHistory 的 BASE_URL 参数
但是 this.$router.push 正确

有办法让两种连接跳转一致么？
