### ISSUE TITLE
表格选中行高亮

### ISSUE THREAD

**Issue by zhangjinjinggit** [arco-design/arco-design-vue#1417]
想要实现点击表格中的某一行时，这一行高亮。尝试通过row-click来实现，失败了。 初次使用该框架，望得到详细回复，谢谢

**Comment by SleepDevil** [comment]
![image](https://user-images.githubusercontent.com/55879038/179717353-c22e5b78-6bb4-443a-bdb9-27ed72ed3e99.png)
这个可以满足你的需求吗

**Comment by zhangjinjinggit** [comment]
> ![image](https://user-images.githubusercontent.com/55879038/179717353-c22e5b78-6bb4-443a-bdb9-27ed72ed3e99.png) 这个可以满足你的需求吗

@SleepDevil 谢谢你 但是这个方法必须选中单选按钮才能实现高亮  不满足需求

**Comment by SleepDevil** [comment]
@zhangjinjinggit 可以通过@row-click里获取到点击的row key，加入到selectedKeys中即可。
这里需要设置row-selection为true。

**Comment by jianmofeng** [comment]
我也遇到了同样的问题，用了操作dom的方式解决的，因为分页，不会有很多条，这样写写也可以
```typescript
const curRowEl: Element = e.target?.closest('.arco-table-tr');
if (!hasClass(curRowEl, 'highlight')) {
  curRowEl.classList.add('highlight');
}
```
希望官方可以出一个api，便于设置行高亮显示
