### ISSUE TITLE
a-tabs希望新增hover触发函数

### ISSUE THREAD

**Issue by Baiyuetribe** [arco-design/arco-design-vue#1420]
- [ √] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 预期解决问题
当前为点击tabs后切换页面，希望鼠标hover时也能自动切换，类似it之家的热榜切换
![160227377-a55275e1-b876-4552-ae5b-abd25e688f10](https://user-images.githubusercontent.com/43716063/179678609-972010fd-5818-49ce-9290-3af4496cd192.gif)

## 现有案例
`<n-tabs type="line" trigger="hover">`
可参考案例：https://www.naiveui.com/zh-CN/os-theme/components/tabs

**Comment by xuxucode** [comment]
没啥特别的理由，对于动态事件绑定，能否使用 v-on 的 object 语法来代替 v-bind：
https://vuejs.org/api/built-in-directives.html#v-on:~:text=%3C!%2D%2D%20object%20syntax%20%2D%2D%3E
