### ISSUE TITLE
优化tooltip的鼠标响应

### ISSUE THREAD

**Issue by andantei** [arco-design/arco-design-vue#1425]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
可参考VSCode的图标按钮在hover时的tooltip

## What problem does this feature solve?
当前tooltip的默认行为是鼠标移到tooltip上会保持tooltip可见。当tooltip跟其他元素挨在一起的时候，tooltip content常常会挡住用户本来想点击的内容。再加上tooltip有一定的fade out延迟，导致用户常常需要把鼠标移走，等待一段时间，再移回来，才能点到想点的内容。如果移回来太快了，tooltip又会出现，如此反复，较为影响用户体验。

提议：
1. 默认禁用tooltip content的鼠标响应(pointer-events: none)，这样鼠标移开tooltip载体之后tooltip content会立即消失
2. 添加一个参数(e.g. keepTooltipContentOnHover)，让这个参数为true时tooltip content仍能响应鼠标hover并保持可见，默认值为false。
3. (Optional) 支持在组件参数中配置popup fade in 和fade out的时间，这样在大量需要tooltip的场景下可以将fade in 和fade out时间调低。

**Comment by flsion** [comment]
@andantei 这个移回显示的问题在 2.32.0 版本有处理，可以看下本地安装的是什么版本，升级下看看

**Comment by andantei** [comment]
感谢信息，刚才看了一下，跟我们的需求还稍有不同。我们是需要tooltip不响应鼠标hover，目前通过
```
.arco-tooltip {
    pointer-events: none;
}
```
来实现了
