### ISSUE TITLE
导航栏自动缩进判断异常

### ISSUE THREAD

**Issue by suKarXiao** [arco-design/arco-design-vue#1429]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.33.0
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/zealous-field-dqlexj?file=/src/App.vue

## Steps to reproduce
当a-sub-menu结尾标签与下一个a-sub-menu开始标签处于同一行时，如：   </a-sub-menu> <a-sub-menu> 
缩进判断会按照总长度的一半进行缩进，不符合预期

**Comment by suKarXiao** [comment]
只有长度一半就开始自动省略
![image](https://user-images.githubusercontent.com/52072212/179959948-0baf9337-ee92-4a1b-97c9-7cba7860c1cf.png)

**Comment by suKarXiao** [comment]
`<template>
  <div class="menu-demo">
    <a-menu mode="horizontal" :default-selected-keys="[]">
      <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu> <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>  <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>  <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>  <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>   <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>   <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>   <a-sub-menu>
        <template #title>Navigation 2</template>
        <a-menu-item key="1">Home</a-menu-item>
        <a-menu-item key="2">Solution</a-menu-item>
      </a-sub-menu>
    </a-menu>
  </div>
</template>
<style scoped>
.menu-demo {
  box-sizing: border-box;
  width: 100%;
  padding: 40px;
  background-color: var(--color-neutral-2);
}
</style>
`

由于保存会被prettier自动调整代码，可能导致看不到，这里只能直接粘贴进去才能复现

**Comment by suKarXiao** [comment]
起因是我用tsx 渲染 menu ，但是发现超出长度的导航栏，总是会被从中间砍一半，后来发现和标签不换行有关系惊呆了

**Comment by suKarXiao** [comment]
> 起因是我用tsx 渲染 menu ，但是发现超出长度的导航栏，总是会被从中间砍一半，后来发现和标签不换行有关系惊呆了

![企业微信截图_16583141132647](https://user-images.githubusercontent.com/52072212/179964598-d7998f10-9f0f-4a20-86f9-24de81014c65.png)

**Comment by kirazxyun** [comment]
@suKarXiao 我用你提供的 demo 发现并不能复现你的问题，不知道你现在是否已经解决了呢

**Comment by hehehai** [comment]
该问题长时间无反馈，先关闭了。
