### ISSUE TITLE
优化在线性主题情况下 a-input-group 里面相邻组件间边框叠加导致粗的问题

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#1432]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
https://www.antdv.com/components/input-cn

**Comment by hehehai** [comment]
@lin-97 hi, 是指现在官网的主题吗（官网现在看着是正常的）？还是其他主题才会出现？

**Comment by hehehai** [comment]
长时间无回复，暂时关闭了。
