### ISSUE TITLE
a-input-password 图标表达意思显示错误

### ISSUE THREAD

**Issue by zhuxianglong** [arco-design/arco-design-vue#1434]
![image](https://user-images.githubusercontent.com/17524804/180161084-e81d56a1-edb9-4870-8951-a113af55923a.png)
这个眼睛应该没有斜线的，设置反了

**Comment by flsion** [comment]
vue 组件这里是参照 Chrome 和 windows 密码输入框设置的图标。Icon 内容代表按下去的效果，和 button 同理
![image](https://user-images.githubusercontent.com/29793175/180354109-de5163f5-9fe8-4192-9069-d55a30bee657.png)

**Comment by LadyChatterleyLover** [comment]
@flsion 我看其他组件库显示内容的时候都是没有斜线的，包括element-plus、ant design

**Comment by zhuxianglong** [comment]
![image](https://user-images.githubusercontent.com/17524804/181146869-f1a55a4e-c6a6-4b10-acaf-2efe99d22eab.png)
我看了一下其他的框架确实是的

**Comment by zhuxianglong** [comment]
这个有什么标准吗？似乎表达的意思想法不一样

**Comment by LadyChatterleyLover** [comment]
@zhuxianglong 我也不知道具体什么标准，可能设计理念是这样的

**Comment by xuxucode** [comment]
不固定，twitter 和 facebook 就不一样：

<img width="360" alt="Screen Shot 2022-07-27 at 7 38 39 PM" src="https://user-images.githubusercontent.com/8274162/181238091-debabb6a-345b-4723-9192-1641ec5540e6.png" caption="twitter" title="twitter"><img width="398" alt="Screen Shot 2022-07-27 at 7 41 36 PM" src="https://user-images.githubusercontent.com/8274162/181238398-6fda4793-7224-4557-89f1-cd78bade70ca.png" caption="facebook" title="facebook">

**Comment by xuxucode** [comment]
不固定，twitter 和 facebook 不一样：
<img width="350" alt="Screen Shot 2022-07-27 at 7 46 51 PM" src="https://user-images.githubusercontent.com/8274162/181239327-acfc5820-e775-461e-84f1-19346caa367c.png" title="twitter"><img width="398" alt="Screen Shot 2022-07-27 at 7 41 36 PM" src="https://user-images.githubusercontent.com/8274162/181239355-ab283267-60e9-4c2d-9804-ecc6132d4634.png" title="facebook">

**Comment by flsion** [comment]
这里好像没有明确的规范，看了一下目前国内的平台上隐藏时带斜线的居多，组件库中的在下个中版本也来统一下

**Comment by LadyChatterleyLover** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月5日(星期五) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design-vue] a-input-password 图标表达意思显示错误 (Issue #1434)





 
这里好像没有明确的规范，看了一下目前国内的平台上隐藏时带斜线的居多，组件库中的在下个中版本也来统一下
