### ISSUE TITLE
vue版文档导航设计样式不统一 [ 做设计的表示看着很难受 😄 ]

### ISSUE THREAD

**Issue by sroxck** [arco-design/arco-design-vue#144]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

选择语言这块与其他按钮排版不统一,整体高出一截,这是个微小小小问题,但是设计师[像素眼]表示看着很难受,我就是提一嘴,前端同学别来打我
![image](https://user-images.githubusercontent.com/51316180/141429510-e3d664e9-6156-440e-b18f-d7a388c7dd00.png)
![image](https://user-images.githubusercontent.com/51316180/141429525-074844e2-f761-40db-acab-5221409cc3b8.png)

**Comment by kirazxyun** [comment]
收到，这个没对齐确实难受，我们改。
