### ISSUE TITLE
modal   draggable 和 :align-center="false" 冲突，拖拽时位置偏移

### ISSUE THREAD

**Issue by baoxiaowang** [arco-design/arco-design-vue#1446]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.33.1
- **Browser:** chrome103.0.0.0

## Disclaimer 

 Submitting offensive issues will result in being blocked from arco-design organization.

**Comment by flsion** [comment]
@baoxiaowang 可以提供一个复现地址吗，我这里本地测试没有复现出来

**Comment by hehehai** [comment]
长时间无回复，问题暂时关闭了，有新信息的话，可再次开启。
