### ISSUE TITLE
【question】arco 主题包只支持 react 版本吗？

### ISSUE THREAD

**Issue by ddaylucifer** [arco-design/arco-design-vue#145]
主题包创建时选择对应 arco 版本只有 react 的版本号，并且实际引用时，生成的 less 文件只有 react 的目录， 直接引用css 文件会导致样式错误（react 与 vue 版本 部分结构不一样，class名称也有区别），很多样式不一样，如果只支持 react 版本，那有没有计划支持 vue 版本？

**Comment by Flsion** [comment]
@ddaylucifer 你好，目前主题包是根据react适配的，vue会有一些小的差别，我们会在近期推出vue版的主题配置。目前要在vue中使用的话，可以引入主题包的token.less，是兼容的

**Comment by ddaylucifer** [comment]
@Flsion 好的，谢谢

**Comment by yinkaihui** [comment]
具体使用可参考: #22

**Comment by suKarXiao** [comment]
> @ddaylucifer 你好，目前主题包是根据react适配的，vue会有一些小的差别，我们会在近期推出vue版的主题配置。目前要在vue中使用的话，可以引入主题包的token.less，是兼容的

你好，礼貌问vue版的主题配置在大概什么时间可以推出？
