### ISSUE TITLE
希望能增加一个colorpicker组件

### ISSUE THREAD

**Issue by ysredcity** [arco-design/arco-design-vue#1458]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://github.com/aesoper101/vue3-colorpicker这算是能找到的还不错的，不过存在着些问题，也不能自定义默认颜色

## 预期解决问题
目前vue3靠谱的颜色选择项目比较少，都存在着些bug，希望能补充一个

**Comment by flsion** [comment]
@ysredcity Hi，你好~ 组件库目前还没有增加 ColorPicker 组件的计划。针对类似的场景我们希望和开发者共建一个官方物料库，用来收集和规范一些优秀的组件，如果有兴趣的话可以联系我

**Comment by Charles7c** [comment]
> 你好，不知道你所说的是不是官网物料平台的贡献方式。我们正在基于Arco来搭建我们企业的基础业务组件库和无代码平台，像类似的场景或许是可以贡献一些物料的。 在 2022-08-05 15:35:51，"Flsion" ***@***.***> 写道： @ysredcity Hi，你好~ 组件库目前还没有增加 ColorPicker 组件的计划。针对类似的场景我们希望和开发者共建一个官方物料库，用来收集和规范一些优秀的组件，如果有兴趣的话可以联系我 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

https://github.com/arco-design/official-material-vue
