### ISSUE TITLE
 Rollup failed to resolve import "XXX/node_modules/@arco-design/web-vue/es/button-group/style/css.js" from XXX

### ISSUE THREAD

**Issue by li-xiaoyin** [arco-design/arco-design-vue#1459]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.33.1
- **Framework version:** 3
- **Browser:** chrome103.0.0.0

## Steps to reproduce
基于Arco Design开发组件 正常按下面的方式使用组件 run dev 没问题 当执行 yarn run build 时，报上面的错误。实际在 node_modules目录中，确实没有 button-group目录，只有button目录。
<a-button-group size="mini">
  some code here
</a-button-group>

**Comment by flsion** [comment]
这个是样式插件的一些配置问题，可以参考下 https://arco.design/vue/docs/pro/faq#%E6%9E%84%E5%BB%BA%E7%9B%B8%E5%85%B3
