### ISSUE TITLE
new component - Scrollbar

### ISSUE THREAD

**Issue by laizp** [arco-design/arco-design-vue#1462]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
see https://www.naiveui.com/zh-CN/os-theme/components/scrollbar

## What problem does this feature solve?
need a customed styled scrollbar container

**Comment by flsion** [comment]
You can find it in 2.30.1-beta.1, the official version is expected to be released in 2.35.0
