### ISSUE TITLE
希望表格组件可以支持"多列排序"

### ISSUE THREAD

**Issue by 0xSa9** [arco-design/arco-design-vue#1471]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
--

## 预期解决问题
经常会用Table组件展示多种数据,单列排序无法直观的过滤出自己想要的结果,所以如果有多列排序功能的话,就会方便太多. 虽然知道可以在服务端处理多列排序, 但实际原因是有一些列的数据是在客户端动态计算的,像目前API里面提示的Sorter可以自定义就很好的解决了这个问题. 但在服务端处理的话会增加无谓的消耗..
所以希望可以支持多列排序功能,但如果开发比较复杂的话,可以考虑两步走
1. 先导出相应API, 让需要的人自己处理多列排序
2. 后期再增加默认的多列排序算法

**Comment by hehehai** [comment]
@0xSa9 你好，这里多列排序建议使用服务端做处理（sql+缓存）。前端处理的话仅是单页（当前拿到的数据）做多条件排序，且多条件排序对当前的接口以及UI/UX都有影响（排序状态，优先级等）。
