### ISSUE TITLE
The popup arrow of the slider component is in the wrong position

### ISSUE THREAD

**Issue by bntol** [arco-design/arco-design-vue#1475]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.34.0
- **Browser:** chrome103.0.0.0

## What is expected?
When you drag the slider to 15, the arrow of Popup is not above the slider.

## Steps to reproduce
<a-slider :default-value="2" :style="{ width: '300px' }" show-input :max="15"/>

**Comment by hehehai** [comment]
补充

### win10 + chrome 103
![2022-09-17 22-19-31 2022-09-17 22_20_39](https://user-images.githubusercontent.com/12692552/190861863-65c0a395-db98-4deb-bbf0-57e4f9a8e2c0.gif)

### win10 + firefox 102

![2022-09-17 22-22-48 2022-09-17 22_23_32](https://user-images.githubusercontent.com/12692552/190861906-6f1c2ede-6055-4f64-af47-a4e25a7f9f79.gif)
