### ISSUE TITLE
能否给table增加一个显示序号的功能

### ISSUE THREAD

**Issue by XYGR** [arco-design/arco-design-vue#1481]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.34.0
- **框架版本:** Vue3
- **浏览器版本:** chrome103.0.0.0
- **复现地址:** https://element-plus.gitee.io/zh-CN/component/table.html#table-column-%E5%B1%9E%E6%80%A7

## 预期结果
类似elementPlus的 type="index" 功能

## 额外补充
https://element-plus.gitee.io/zh-CN/component/table.html#table-column-%E5%B1%9E%E6%80%A7

**Comment by tazyong** [comment]
没有必要单独为序号出个 API，有很多方式可以实现，都很简单。
@hehehai 可以关闭该 issue 了

示例：
https://codesandbox.io/s/suspicious-raman-it4bz2?file=/src/App.vue

**Comment by sj7112** [comment]
这个很有必要，比如类似这种，因为必须显示在checkbox之前，arco现有框架支持不了。
 有可能加上吗？
![1674631891065](https://user-images.githubusercontent.com/15377016/214505275-9369c30f-e00b-4d7f-9b65-38900661694f.png)
