### ISSUE TITLE
Select组件下拉选项没有 鼠标划过样式，显得很生硬。

### ISSUE THREAD

**Issue by yunuo-tech** [arco-design/arco-design-vue#1482]
React版本的有

**Comment by hehehai** [comment]
@yunuo-tech 麻烦提个复现吧，现在使用 option hover 的样式的

**Comment by yunuo-tech** [comment]
> @yunuo-tech 麻烦提个复现吧，现在使用 option hover 的样式的

文档上就能复现：https://arco.design/vue/component/select

**Comment by hehehai** [comment]
暂时关闭了，问题还有出现的话，可以提个动图。或者可以在飞书群中沟通
![飞书20220912-142432](https://user-images.githubusercontent.com/12692552/189586783-cc6046f5-2941-484a-9140-98eafaa5598e.png)
