### ISSUE TITLE
Select选中值被从选项中移除会有问题

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#1484]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.34.0
- **Browser:** chrome103.0.0.0

## What is expected?
期望选中的项从option移除后，选中项也会跟着移除

## Steps to reproduce
![image](https://user-images.githubusercontent.com/93666053/182816009-47c9ce93-b9f9-4082-9b3d-367be9ba00ed.png)

```vue
<a-option v-for="child in children" :key="child.id" :value="child.id" />
```
通过option渲染选项后，选择其中一项，然后再动态将那一项从children中移除，选项还会存在且显示的是id

**Comment by flsion** [comment]
这个建议在业务中封装一下，选项改变时清空值。
select 组件默认会把不存在的选项的值展示出来，也可以通过将 :fallback-option="false" 关闭这个特性
