### ISSUE TITLE
在谷歌浏览器使用menu组件会报错，Found a 'popup' attribute。

### ISSUE THREAD

**Issue by wou101771** [arco-design/arco-design-vue#1486]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': <URL>. This usage will *likely cause site breakage* when the popup API ships: <URL>.
## 现有案例
![image](https://user-images.githubusercontent.com/52279380/182986975-95579817-f0fe-49d2-9706-4b5a1e3f2cfc.png)

**Comment by JasperPan** [comment]
补充一下，Chrome升级至104版本后出现这个问题

**Comment by MinGlizz** [comment]
版本 104.0.5112.79。也遇到了这个问题

**Comment by SleepDevil** [comment]
不慌，马上修复

**Comment by GodRuiCollection** [comment]
我也遇到了，等修复了...

**Comment by jacksonyu** [comment]
升级到 "@arco-design/web-vue": "^2.34.1",
问题仍然没有修复

**Comment by SleepDevil** [comment]
@jacksonyu 你好，请删除node_modules重装一下。有可能是由于vite的缓存导致的

**Comment by jacksonyu** [comment]
> 

谢谢，重装后解决了

**Comment by Otto-J** [comment]
可以考虑把这个放到醒目位置，比如menu 的网页组件介绍里，方便及时收到这个提示，后续大量用户的浏览器缓慢升级了，会持续遇到这个问题

**Comment by 18782944209** [comment]
删除缓存node_modules后重装恢复了
