### ISSUE TITLE
DatePicker 时间范围显示错误

### ISSUE THREAD

**Issue by MrCat33** [arco-design/arco-design-vue#1489]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.34.0
- **浏览器版本:** chrome103.0.0.0

## 额外补充
在官网组件用法中 vue分类下的datePicker中时间范围，也同样有这个问题。

## 预期结果
开始时间选择2022-10，下次重新选择月份应该也同样显示2022-10

## 复现步骤
在选择时间范围的时候，选择下个月也只会显示当前系统时间月份。
当第二次进行操作选择时间范围，也只会显示当前系统时间的月份，并不会显示所选择日期的月份

**Comment by hehehai** [comment]
@MrCat33 你好，我这边检查是正常的，会出现选择的月份，方便的话麻烦提供一个复现吧
