### ISSUE TITLE
vue component library On-demand Import

### ISSUE THREAD

**Issue by KelseyYau** [arco-design/arco-design-vue#15]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
null

## 预期解决问题
can't find On-demand Import guide in doc

**Comment by WJCHumble** [comment]
@KelseyYau you can use `babel-plugin-import` or `vitei-plugin-style-import` to import component on demand. For example, in the`vite` project:

```javascript
// vite.config.js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

export default defineConfig({
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  },
  plugins: [
    vue(),
    styleImport({
      libs: [
        {
          libraryName: '@arco-design/web-vue',
          esModule: true,
          resolveStyle: (name) => {
            return `@arco-design/web-vue/es/${name}/style/index`
          },
        }
      ]
    })
  ]
})

```

And then, you can import component on demand:

```javascript
<script setup>
import { Button } from "@arco-design/web-vue"
</script>

<template>
    <Button type="primary">Primary</Button>
</template>

<style>
</style>
```

But, it's important to note that the component name doesn't have a default prefix, and I create issue #39 .

**Comment by LuckyHookin** [comment]
@WJCHumble 你的方法更加完善，并且让我发现了我导入的是普通 css 而不是 less，所以无法定义 less 变量，还让我认识到了 vite-plugin-style-import 这个按需导入样式的库，谢谢！

**Comment by Flsion** [comment]
@KelseyYau Get it, we will add On-demand Import guide in docs

**Comment by techrex** [comment]
如果使用`babel-plugin-import`该如何配置

**Comment by Flsion** [comment]
调研了一下，近期会先添加一下 https://github.com/antfu/unplugin-vue-components 插件的支持，方便使用自动引入功能

**Comment by ishowman** [comment]
> 调研了一下，近期会先添加一下 https://github.com/antfu/unplugin-vue-components 插件的支持，方便使用自动引入功能

新项目就等着这基础功能了

> @WJCHumble 你的方法更加完善，并且让我发现了我导入的是普通 css 而不是 less，所以无法定义 less 变量，还让我认识到了 vite-plugin-style-import 这个按需导入样式的库，谢谢！
> 
> ~上面的配置对我无效，我用的是：~ 上面的配置在 windows 和 Linux 中表现不一致，可用下面这个保持一致：
> 
> ```js
> const { resolve } = require('path')
> styleImport({
>       libs: [
>         {
>           libraryName: '@arco-design/web-vue',
>           esModule: true,
>           resolveStyle: (name) => {
>             return resolve(__dirname+'/node_modules/', '@arco-design/web-vue/es/' + name + '/style/index')
>           },
>         }
>       ]
>     })
> ```



> @WJCHumble 你的方法更加完善，并且让我发现了我导入的是普通 css 而不是 less，所以无法定义 less 变量，还让我认识到了 vite-plugin-style-import 这个按需导入样式的库，谢谢！
> 
> ~上面的配置对我无效，我用的是：~ 上面的配置在 windows 和 Linux 中表现不一致，可用下面这个保持一致：
> 
> ```js
> const { resolve } = require('path')
> styleImport({
>       libs: [
>         {
>           libraryName: '@arco-design/web-vue',
>           esModule: true,
>           resolveStyle: (name) => {
>             return resolve(__dirname+'/node_modules/', '@arco-design/web-vue/es/' + name + '/style/index')
>           },
>         }
>       ]
>     })
> ```

有没有试过打包后是否 tree shaking 了呢？

**Comment by llk2yq** [comment]
@Flsion 请问`unplugin-vue-components`插件有什么进展吗？

**Comment by seepine** [comment]
> @Flsion 请问支持`unplugin-vue-components`插件有什么进展吗？

+1

**Comment by Flsion** [comment]
Already merged https://github.com/antfu/unplugin-vue-components/pull/252, wait for `unplugin-vue-components` release version
