### ISSUE TITLE
项目使用pnpm管理，使用 Arco Design Lab发布的主题，使用npm安装失败

### ISSUE THREAD

**Issue by lnool** [arco-design/arco-design-vue#1506]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.34.1
- **Framework version:** Vue3.x
- **Browser:** chrome104.0.5112.81

## Extra info
PS D:\project\cms> npm i @arco-themes/vue-didoee@0.0.1
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @eslint/eslintrc@1.3.0
npm WARN Found: peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/registry.npmmirror.com @eslint eslintrc@1.3.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.3.0
npm WARN   node_modules/.pnpm/registry.npmmirror.com @eslint eslintrc@1.3.0/node_modules/@eslint/eslintrc
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/registry.npmmirror.com @eslint eslintrc@1.3.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.3.0
npm WARN   node_modules/.pnpm/registry.npmmirror.com @eslint eslintrc@1.3.0/node_modules/@eslint/eslintrc
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\software\nodejs\node_cache\_logs\2022-08-11T10_12_15_121Z-debug-0.log

**Comment by hehehai** [comment]
@lnool 你好，尝试使用 yarn 或 pnpm 直接安装下，还有问题的话，就发一下 package.json 的代码吧

**Comment by hehehai** [comment]
该问题长期无跟踪暂时关闭，后面有补充再可开启。
