### ISSUE TITLE
a-button设置属性html-type="submit"的情况下，通过点击按钮触发表单的submit事件，并将loading属性设置为true，在此情况下，仍然可以通过重复点击此按钮多次触发submit事件

### ISSUE THREAD

**Issue by xiehao135** [arco-design/arco-design-vue#1511]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.34.1
- **Browser:** chrome102.0.0.0

**Comment by hehehai** [comment]
复现（查看 Console）：https://codesandbox.io/s/dazzling-germain-262hni?file=/src/App.vue

**Comment by xiehao135** [comment]
您好，我是谢淏，您的邮件已收到，我会尽快给您回复，谢谢。
