### ISSUE TITLE
a-date-picker设置了value-format后赋值是否可以将值尽可能的转化为value-format的格式而不是错误显示

### ISSUE THREAD

**Issue by rkrv01** [arco-design/arco-design-vue#1515]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.0
- **Framework version:** Vue
- **Browser:** chrome104.0.5112.81
- **Reproduction Link:** https://codesandbox.io/s/confident-payne-ubqnmw?file=/src/App.vue

## What is expected?
希望可以将值尽可能的转化为value-format的格式显示而不是错误显示

## Steps to reproduce
修改不同的的value-format或者date

**Comment by hehehai** [comment]
@ray8367 你好，建议用以下任意方式解决

- 若仅是展示的问题，请使用 format 的函数参数形式，来判断如何处理为可展示的格式
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12692552/185728670-52e620ad-6da2-4335-b042-915917230bca.png">

- value-format 是值的格式，它应该是必须要和 value 匹配的
<img width="999" alt="image" src="https://user-images.githubusercontent.com/12692552/185728759-5fa13e2c-38a6-43b3-bdb6-17d37f9d5101.png">

**Comment by ray8367** [comment]
> @ray8367 你好，建议用以下任意方式解决
> 
> * 若仅是展示的问题，请使用 format 的函数参数形式，来判断如何处理为可展示的格式
> 
> <img alt="图像" width="1019" src="https://user-images.githubusercontent.com/12692552/185728670-52e620ad-6da2-4335-b042-915917230bca.png">
> 
> * value-format 是值的格式，它应该是必须要和 value 匹配的
> 
> <img alt="图像" width="999" src="https://user-images.githubusercontent.com/12692552/185728759-5fa13e2c-38a6-43b3-bdb6-17d37f9d5101.png">



回复： 是的，我明白value-format必须和value匹配才合理，但希望可以将这个匹配的操作能够放在picker本身去完成

**Comment by ray8367** [comment]
> @ray8367 你好，建议用以下任意方式解决
> 
> * 若仅是展示的问题，请使用 format 的函数参数形式，来判断如何处理为可展示的格式
> 
> <img alt="image" width="1019" src="https://user-images.githubusercontent.com/12692552/185728670-52e620ad-6da2-4335-b042-915917230bca.png">
> 
> * value-format 是值的格式，它应该是必须要和 value 匹配的
> 
> <img alt="image" width="999" src="https://user-images.githubusercontent.com/12692552/185728759-5fa13e2c-38a6-43b3-bdb6-17d37f9d5101.png">



回复： 是的，我理解value-format必须和value匹配才合理，但实际上value的值有可能是通过后台得到的，后台传递来的值不一定符合前端的格式要求，这时候就不得不在使用value前将value做format处理，数据如果稍稍复杂些就会产生冗余代码，并且提高出错率，所以希望可以将这个匹配的操作能够放在picker本身去尝试通过用户设置的value-format去格式化，而不是比较在UI上显示错误的信息
![22](https://user-images.githubusercontent.com/38169959/185734680-1dd0eafa-42fe-4a05-bb12-4d36ad35fe1a.png)

![11](https://user-images.githubusercontent.com/38169959/185734416-6446fb76-5371-4413-a1f3-5155d03f12dd.png)

**Comment by hehehai** [comment]
@ray8367 嗯，明白的。这里值的不确定性（后端拿到或者用户输入）具体转换格式的规则是由业务决定的，值得校验或转换也是写在业务中的。组件仅吃开发者给的参数即可。
