### ISSUE TITLE
循环中使用popover，不能正常关闭

### ISSUE THREAD

**Issue by ddamowang** [arco-design/arco-design-vue#1519]
我在table中尝试使用popover组件，并在popover中使用button，希望能够使用button关闭popover。
我为每个popover绑定不同的 :popup-visible，然后通过点击事件修改popover的展示状态，可以实现这一功能，
但如果我点击打开一个popover后不关闭，再打开其他的popover则可以打开多个卡片。
代码：
![image](https://user-images.githubusercontent.com/49475299/184843789-832812c2-6a99-4304-9b16-b468e5f9c191.png)
效果实例：
![image](https://user-images.githubusercontent.com/49475299/184844028-8f2979ed-da7c-49b3-aba7-87ff78960774.png)
请问我该如何修改，或如何关闭当前已经打开的popover？

**Comment by hehehai** [comment]
> ”但如果我点击打开一个popover后不关闭，再打开其他的popover则可以打开多个卡片。“

@ddamowang 你好, 你的意思是要保证每次只有一个 popover 是打开的是吗？是的话，这里建议维护一个 `openedId` 来保存要打开的 popover, `:popup-visible="popoverId === openedId"`

**Comment by ddamowang** [comment]
> > ”但如果我点击打开一个弹出框不关闭，再打开其他弹出框则可以打开多个折叠后。”
> 
> @ddamowang你好，你的英文是一定要打开一个弹出框是吗？是的话，这里建议维护一个`openedId`来保存弹出框，`:popup-visible="popoverId === openedId"`

这样可以的，多谢多谢！
