### ISSUE TITLE
input输入框 v-model 支持number类型

### ISSUE THREAD

**Issue by keisunique** [arco-design/arco-design-vue#1520]
` <a-input v-model="id"/>`  

inputs输入框v-model现在绑定number 类型时， ts检测提示: `不能将类型“number | undefined”分配给类型“string | undefined”`

希望能支持number类型！

**Comment by yymjku18** [comment]
@keisunique number数据建议使用<a-input-number/>,里面提供了更好的数字相关的方法

**Comment by flsion** [comment]
这里是一个取舍的问题，input 组件输入为 number 时，也会在修改内容后变为字符串格式，相当于只是在 props 的输入检查增加 number 的类型而已。因为这种情况不是太符合 **输入输出类型一致** 的问题，所以这里我们没有提供 number 类型的支持
