### ISSUE TITLE
a-sub-menu, a-menu-item 的 key 属性在条件判断中会导致vue的语法报错，应改为 menu-key 或者 unique-key

### ISSUE THREAD

**Issue by jiankafei** [arco-design/arco-design-vue#1522]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.0
- **Browser:** chrome104.0.5112.81

## What is expected?
a-sub-menu, a-menu-item 的 key 属性改为 menu-key 或者 unique-key.

## Steps to reproduce
a-sub-menu, a-menu-item 不应该使用  key 作为唯一属性的名称，key作为vue的关键字不应该被使用，在使用条件判断时会造成语法提示的错误（v-if/else branches must use unique keys. vue），应该改为使用 menu-key 或者unique-key.

```vue
<a-sub-menu :key="menu.path" v-if="menu.children && menu.children.length">
  <template #icon><icon-archive :size="18" /></template>
  <template #title>{{menu.meta.title}}</template>
  <SingleMenu v-for="childMenu of menu.children" :key="childMenu.path" :menu="childMenu"></SingleMenu>
</a-sub-menu>
<a-menu-item :key="menu.path" v-else>{{menu.meta.title}}</a-menu-item>
```

**Comment by tjHong** [comment]
该问题会在近期优化吗？

**Comment by oljc** [comment]
#2978
