### ISSUE TITLE
How to use ArcoIcon in Nuxt3

### ISSUE THREAD

**Issue by Linxiaoxxx** [arco-design/arco-design-vue#1524]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.0
- **Framework version:** 3
- **Browser:** chrome104.0.0.0

## Steps to reproduce
使用 <icon-skin /> 等icon组件，会提示 [Vue warn]: Failed to resolve component: icon-skin
`// ...plugins/ArcoIcon.ts
import ArcoVueIcon from '@arco-design/web-vue/es/icon'

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(ArcoVueIcon)
})`

**Comment by hehehai** [comment]
@Linxiaoxxx 你好，可以参考这个 [demo](https://stackblitz.com/edit/nuxt-starter-e3nbgk?file=plugins/arco-icon.ts), 看起来是正常的。

- "nuxt": "3.0.0-rc.8"
- "@arco-design/web-vue": "^2.35.1"
