### ISSUE TITLE
trigger 双向绑定，无法被赋值手动关闭

### ISSUE THREAD

**Issue by LuckyHookin** [arco-design/arco-design-vue#1525]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.35.0
- **框架版本:** vue 3
- **浏览器版本:** chrome104.0.0.0
- **复现地址:** https://stackblitz.com/edit/angular-3tskd8?file=src%2FApp.vue

## 预期结果
点击弹窗的 close 按钮后关闭弹窗。

## 复现步骤
点击按钮，后点击弹窗的 close 按钮。

**Comment by flsion** [comment]
v-model 需要添加后缀
![image](https://user-images.githubusercontent.com/29793175/185602470-e56ec285-0232-4d9d-a5db-145cb66a7b67.png)
