### ISSUE TITLE
Cascader组件搜索时没有overflow scroll

### ISSUE THREAD

**Issue by immzz** [arco-design/arco-design-vue#153]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @acro-design/web-vue: 2.2.0
- **System:** MacOS
- **Browser:** Chrome 95.0
- **Reproduction Link:** https://www.awesomescreenshot.com/image/16655983?key=09c289f2454230f75bc15f3a77a98ebe

## What is expected?
搜索结果应该允许overflow scroll以查看所有结果

## Steps to reproduce
* 使用如下template
<template>
  <a-cascader v-model="selectedInstrumentValue" :options="instrumentOptions" :format-label="formatLabel" allow-search />
</template>

* 在输入框中输入一个存在的值
* 结果列表不允许overflow scroll导致无法查看所有结果（请看截图）

**Comment by Flsion** [comment]
@immzz 收到，下个版本会修复一下
