### ISSUE TITLE
table tr插槽怎么不能使用

### ISSUE THREAD

**Issue by asher886** [arco-design/arco-design-vue#1531]
![企业微信截图_16608993989811](https://user-images.githubusercontent.com/99728849/185584458-d26e275b-6d02-4c03-b5d4-7547a93239e3.png)
![企业微信截图_16608994459311](https://user-images.githubusercontent.com/99728849/185584473-dab9262c-1e85-43ad-9288-9feb5e58a826.png)

**Comment by flsion** [comment]
@asher886 tr插槽的record数据是 2.26 版本添加的，如果需要用的话可以升级一下
![image](https://user-images.githubusercontent.com/29793175/185594446-2d688bc1-5d6b-44e1-9cae-ed381e63c1e5.png)
