### ISSUE TITLE
AutoComplete 怎么像 Input 一样添加前缀或后缀图标

### ISSUE THREAD

**Issue by deluxedeluxe** [arco-design/arco-design-vue#1532]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
AutoComplete 怎么像 Input 一样添加前缀或后缀图标

## What problem does this feature solve?
AutoComplete 怎么像 Input 一样添加前缀或后缀图标

**Comment by hehehai** [comment]
@deluxedeluxe 你好，AutoComplete 内部使用了 Input 组件，是支持前后插槽的（这个组件文档中会加下插槽说明）

```vue
<template>
  <a-auto-complete
    :data="data"
    @search="handleSearch"
    :style="{ width: '360px' }"
    placeholder="please enter something"
  >
    <template #prefix>
      <icon-star-fill />
    </template>
    <template #suffix>
      <icon-palette />
    </template>
  </a-auto-complete>
</template>
```
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12692552/185724481-41288685-5def-48f2-990d-4f88553f82a2.png">

**Comment by deluxedeluxe** [comment]
谢谢解答
