### ISSUE TITLE
在项目内加入`@arco-design/web-vue`后，会导致`app.config.globalProperties`上增加的properties通过typescript类型扩展做的typings在vscode中失效

### ISSUE THREAD

**Issue by pzgz** [arco-design/arco-design-vue#1535]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.1
- **Framework version:** vue 3.2.37
- **Browser:** safari/605.1.15
- **Reproduction Link:** https://github.com/pzgz/arco-vue-issue-test

## What is expected?
希望在使用arco design vue之后，还是可以通过typescript的类型扩展，来扩展在`app.config.globalProperties`中增加的属性，让这些属性在vscode中可以获取正确的类型。

## Steps to reproduce
https://github.com/pzgz/arco-vue-issue-test

这个repo，我做了main和dev两个分支，main里面没有加arco design vue，dev里面加了，两者没有其它区别。

在main分支里面，用vscode打开后，看App.vue模版中使用的 `$filters`，是有正确的typing，在dev分支中，再用vscode打开的话，就发现typing没了，typescript类型扩展的代码是一样的，就是添加arco design vue后，就出问题了，今天就这个问题跟了很久，做了很多测试以后，最后就定位在arco design vue的库上，有没有什么线索可以分享一下？

代码运行是正常的，就是vscode中显示有问题。

**Comment by hehehai** [comment]
@pzgz 你好，我尝试了 dev 分支在 vscode 中是正常的（请尝试重载项目窗口或检查下 volar 和 volar typescript 的安装和最新版本）
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/12692552/185724083-791b38ff-60e1-40dd-a8c7-9d8eeb2ae754.png">

**Comment by pzgz** [comment]
@hehehai 看到了，非常感谢，也很奇怪，这其实是我用来debug的一个测试项目，昨天因为这个问题，我耗费了几乎半天在查问题，重新加载项目窗口和重启vscode几乎是每次都做的。typescript我的版本是4.7.4，vscode也尝试过regular版本和insiders版本，insiders版本的typescript是4.8.1，问题还是一样，但的确在你机器上的截图看上来，是想要的状态，请问你的typescript 4.9.0版本是如何安装的，另外vscode和volar的版本能告知一下吗？我的volar是0.40.1

**Comment by hehehai** [comment]
@pzgz 
- vscode, volar, volar-ts 都是 latest
- typescript 的 vscode 版本可以参考 vue 官方的 [Volar Takeover Mode](https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json)

> 这里若仅是类型提示的问题（开发，构建，lint都正常），建议也不需要太关注具体是什么问题（vscode 的 ts 依赖较复杂）

**Comment by pzgz** [comment]
``

> @pzgz
> 
> * vscode, volar, volar-ts 都是 latest
> * typescript 的 vscode 版本可以参考 vue 官方的 [Volar Takeover Mode](https://vuejs.org/guide/typescript/overview.html#configuring-tsconfig-json)
> 
> > 这里若仅是类型提示的问题（开发，构建，lint都正常），建议也不需要太关注具体是什么问题（vscode 的 ts 依赖较复杂）

嗯，是的，我现在就是暂时放弃了，就是突然碰到强迫症犯了，就想解决掉，不过经过各种尝试，发现也非常不稳定，后来拿了另外一个repo，arco work的代码，却发现他们没有问题，但仔细研究后发现，在他们的repo里 arco design注入的 $message和$notification等等不能用了。

非常感谢你的时间，我会再研究一下

**Comment by pzgz** [comment]
@hehehai 更新一下，我把typescript更新到4.9.0，和你一样，问题就没了，4.7和4.8都有这个问题，但这样来说，就不是arco里面有什么问题，应该是typescript自己在类型扩展上，有什么问题，多谢了
