### ISSUE TITLE
table   CheckBox  问题

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1538]

**Comment by cgrain1998** [comment]
想问一下，复选框怎么清空？

```
      <a-table row-key="id" :columns="table_config.columns" :pagination="pagination" :data="table_config.data"
        :bordered="true" :hoverable="true" :stripe="true" :show-header="true" :loading="table_config.loading"
        :selected-row-keys="selectedRowKeys" :row-selection="rowSelection" @select="getAllSelection"
        @select-all="getAllSelectdRow" @page-change="onPageChange" >

</a-table>

```
这段代码， 我尽管 设置 ```selectedRowKeys.value =[]; ```  ，页面上的``` CheckBox  ``` 还是选中状态,但是实际上  ```selectedRowKeys.value ```   已经是空的了

**Comment by hehehai** [comment]
@cgrain1998 你好，参考 [demo](https://stackblitz.com/edit/angular-myrfyn?file=src/App.vue)

**Comment by flsion** [comment]
需要使用 v-model 绑定

**Comment by cgrain1998** [comment]
好的，爱你们  

> @cgrain1998 你好，参考 [演示](https://stackblitz.com/edit/angular-myrfyn?file=src/App.vue)



> 需要使用 v-model 绑定

**Comment by niceMoonMaker** [comment]
怎么获取选中的row数据？方法里没有，找了半天没找到
