### ISSUE TITLE
希望在表单form上增加rules属性

### ISSUE THREAD

**Issue by he675724590** [arco-design/arco-design-vue#154]
希望在表单form上可以增加统一的rules属性，虽然form-item可以单独设置rules但是相对来说比较麻烦

**Comment by Kigoal** [comment]
这个问题短期不会支持吗？我也有这个需求，在每个 `Form.Item` 上写 `rules` 影响代码可读性和繁琐😂

**Comment by Flsion** [comment]
2.7版本已经添加了~

**Comment by gaowujie2004** [comment]
> 2.7版本已经添加了~

React版，在官网并没有看到 ~
