### ISSUE TITLE
table thead slot bug

### ISSUE THREAD

**Issue by OverTree** [arco-design/arco-design-vue#1548]
https://codesandbox.io/s/vigorous-fog-xrqlek?file=/src/App.vue

使用thead slot 时出现了[Object object]

**Comment by hehehai** [comment]
@flsion 问题可能来自于这里

https://github.com/arco-design/arco-design-vue/blob/54571f1b2ca9783b25bc9058612c94bebb038b03/packages/web-vue/components/table/table-thead.tsx#L8

**Comment by flsion** [comment]
@OverTree thead 插槽使用时需要传入一个单一的元素或者组件，此元素或组件的 children 将由table组件填充
![image](https://user-images.githubusercontent.com/29793175/187175415-7b6fa2f8-3844-43b5-81b4-d714cf2dd20a.png)

**Comment by flsion** [comment]
新版本会给 table 的元素插槽加一些说明，到时可以看一下
