### ISSUE TITLE
table row-class 怎么没效果，都不进入函数中，使用版本是2.23

### ISSUE THREAD

**Issue by asher886** [arco-design/arco-design-vue#1553]
![image](https://user-images.githubusercontent.com/99728849/186103100-e49064c8-67d6-4fa2-adbf-f9b6ef2494a8.png)
![image](https://user-images.githubusercontent.com/99728849/186103157-f115fcc0-a4cd-4525-b317-a45fe88e5475.png)

**Comment by hehehai** [comment]
fix docs: 

- zh: 表格行元素的类名。`2.34.0` 版本增加函数值支持。
- en: The class name of the table row element . The `2.34.0` version adds support for function values

https://github.com/arco-design/arco-design-vue/blob/54571f1b2ca9783b25bc9058612c94bebb038b03/packages/web-vue/components/table/table.tsx#L282-L292
