### ISSUE TITLE
Table 组件 ，开启 ellipsis 和 tooltip, 分页切换下一页，tooltip 就展示不出来了，省略符还有

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-vue#1555]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.1
- **Browser:** chrome104.0.0.0

**Comment by hehehai** [comment]
@981433814 hi, 是在 tooltip 一直可见的情况下，切换分页后出现问题的吗？方便的话，麻烦补充一个复现吧。

**Comment by 981433814** [comment]
> @981433814 hi, 是在 tooltip 一直可见的情况下，切换分页后出现问题的吗？方便的话，麻烦补充一个复现吧。

复现有点困难，再详细描述一下就是，比如第一页
![image](https://user-images.githubusercontent.com/45874392/186356855-0b7f3cda-6230-436e-bfd0-9aa19adf3583.png)
第三页相同的位置，但是没有省略号
![image](https://user-images.githubusercontent.com/45874392/186357258-57e6f85c-125a-480a-8298-268417483208.png)

**Comment by 981433814** [comment]
感觉是切换分页后，tooltip保留了上一页的状态

**Comment by flsion** [comment]
数据中有 key 字段吗，表格中会使用这个作为 row 的 key

**Comment by 981433814** [comment]
> 数据中有 key 字段吗，表格中会使用这个作为 row 的 key

确实可以了~感谢
