### ISSUE TITLE
穿梭框 Transfer 添加 title 的插槽 

### ISSUE THREAD

**Issue by latte03** [arco-design/arco-design-vue#1557]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Semi Design /naiveui 默认模式下优点类似arco design 的simple，也是带有全选按钮。

## What problem does this feature solve?
可以自定义一些功能放在 title 位置，或者对title可以更好的定制化。
目前我需要解决的是，在simple模式下，添加一个全选按钮，我希望放在title位置。

**Comment by hehehai** [comment]
title 将支持 slot, 插槽属性可传递（属性来自 Arco React）

``` ts
type TransferListTitle =
  | string
  | ((params: {
      countTotal: number;
      countSelected: number;
      clear: () => void;
      checkbox: ReactNode;
      searchInput: ReactNode;
    }) => ReactNode);
```
