### ISSUE TITLE
Transfar 穿梭框标题超出ellipsis未生效

### ISSUE THREAD

**Issue by latte03** [arco-design/arco-design-vue#1558]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.1
- **Framework version:** "vue": "^3.2.37"
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/angular-cvn2vk?file=src/App.vue

## What is expected?
标题超出应该是出现...的，最好可以带上tooltips

## Steps to reproduce

```
:title="[
      '标题过长，但是ellipsis未能生效',
      '标题过长，但是ellipsis未能生效',
    ]"
```

<img width="345" alt="image" src="https://user-images.githubusercontent.com/33367218/186198464-dd0965bd-af08-4ef0-89b6-e599693920dd.png">

flex 的原因。

**Comment by hehehai** [comment]
补充：普通模式和 simple 都存在该问题 [复现](https://stackblitz.com/edit/angular-2ppcrw?file=src/App.vue)

- simple模式：问题来自 `.arco-transfer-view-header-title` 的 `flex`
- 普通模式: 问题来自 `.arco-checkbox-label` css 文本溢出样式未正常设置
