### ISSUE TITLE
在请求数据之后table没有展开所有行

### ISSUE THREAD

**Issue by mccmcmxci** [arco-design/arco-design-vue#1559]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.35.1
- **框架版本:** Vue 3.2.31
- **浏览器版本:** chrome104.0.0.0

## 复现步骤
初始化table数据:  const renderData = ref([]);
设置默认展开属性 :default-expand-all-rows: "true"
请求数据: const { data } = await queryByState(params);
赋值: renderData.value=data
表格渲染正常, 但是没有展开所有行
## 额外信息
直接给表格data赋值, 不经过请求可以展开所有行

**Comment by flsion** [comment]
@mccmcmxci  默认展开只会在表格初始化时执行一次，如果需要后续展开内容，可以手动调用 table 组件外露的 expandAll 方法
