### ISSUE TITLE
文本框增加mesk掩码功能

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#156]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://www.jq22.com/yanshi540

## 预期解决问题
与jquery的masked input 插件一样 为文本框增加掩码功能可以让用户输入自定义格式规则的内容

**Comment by flsion** [comment]
可以通过受控实现这个功能，组件库目前暂不会添加此功能
