### ISSUE TITLE
arco 文档 config 与代码不一致

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1560]
![image](https://user-images.githubusercontent.com/35121432/186567707-0df4b660-7ff0-4518-afe0-18f13c7241c3.png)

![image](https://user-images.githubusercontent.com/35121432/186567753-f6cae6ac-e260-48e5-ab30-c54bd003fcac.png)

![image](https://user-images.githubusercontent.com/35121432/186567609-6bb6ea4f-cf87-4fb4-9606-6edb3e3a9fdd.png)

好像没有width 这个属性

![image](https://user-images.githubusercontent.com/35121432/186567942-41677b79-2bff-4eec-9ad9-a081ce1a1d92.png)

文档写了，但是代码没有体现出来

**Comment by cgrain1998** [comment]
![image](https://user-images.githubusercontent.com/35121432/186572926-ba147320-610c-48f8-8be9-d22be1a654b6.png)


代码坚持会过不去，开发环境下查看，功能显示是正常的

**Comment by flsion** [comment]
![image](https://user-images.githubusercontent.com/29793175/187169186-54d5a04a-6588-4db2-b1ab-5639de0cbf00.png)
可以升级下版本，2.27 有补全信息
