### ISSUE TITLE
在NUXT中 date-picker组件无法正常运行

### ISSUE THREAD

**Issue by phcent** [arco-design/arco-design-vue#1565]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.1
- **Browser:** chrome103.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/nuxt-starter-jj4i3n?file=app.vue

## What is expected?
解决问题

## Steps to reproduce
时间选择组件全部不能用报错报错

**Comment by ItsRyanWu** [comment]
相关问题已反馈给 Nuxt 社区待解决命名冲突
https://github.com/nuxt/nuxt/issues/20954

**Comment by ItsRyanWu** [comment]
@flsion Issue 可关闭，升级至 Nuxt v3.5.3 可解决。
