### ISSUE TITLE
VUE版本的sider伸缩按钮图标位置偏上

### ISSUE THREAD

**Issue by hiipeng** [arco-design/arco-design-vue#1566]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/32444545/186606420-080609a3-518d-4efa-b66a-c9496623ac34.png">

React版本是正常的
<img width="309" alt="image" src="https://user-images.githubusercontent.com/32444545/186606547-85778429-c7c8-439f-996e-0354be3e88d6.png">

**Comment by flsion** [comment]
好眼神~😃
