### ISSUE TITLE
Layout组件缺少interface文件

### ISSUE THREAD

**Issue by qzp199510** [arco-design/arco-design-vue#1568]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
添加interface文件，便于组件的二次开发中ts类型定义

**Comment by qzp199510** [comment]
dropdown 也未抛出ts定义类型

**Comment by hehehai** [comment]
Repeat #1319
