### ISSUE TITLE
Layout组件没有抛出ts类型定义

### ISSUE THREAD

**Issue by 94ashui** [arco-design/arco-design-vue#1569]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.1
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://github.com/arco-design/arco-design-vue/tree/main/packages/web-vue/components/layout

## What is expected?
和react版本一样抛出一些layout相关的类型

## Steps to reproduce
对layout组件进行封装时需要提供layout类型

**Comment by hehehai** [comment]
Repeat https://github.com/arco-design/arco-design-vue/issues/1319
