### ISSUE TITLE
怎么使用本地图片显示不了，本地显示正常，打包到测试环境就不正常了

### ISSUE THREAD

**Issue by asher886** [arco-design/arco-design-vue#1572]
![image](https://user-images.githubusercontent.com/99728849/186891820-2fd97099-35af-44d3-9010-10fcbb32d428.png)
![image](https://user-images.githubusercontent.com/99728849/186891859-fd2e75fa-a97b-4837-8bcd-868155868c40.png)
![image](https://user-images.githubusercontent.com/99728849/186891976-3e94f184-ea6d-4e68-987c-11270dcd24a2.png)
![image](https://user-images.githubusercontent.com/99728849/186892105-52992c71-4de0-4684-b111-9adc2350ed11.png)

**Comment by asher886** [comment]
其他小一点的图片又正常

**Comment by flsion** [comment]
检查一下网络请求和打包器的配置，可能是图片没有请求到

**Comment by asher886** [comment]
> 检查一下网络请求和打包器的配置，可能是图片没有请求到



> 检查一下网络请求和打包器的配置，可能是图片没有请求到

都正常的，小于4k的图片又正常

**Comment by up-ndd** [comment]
> > 检查一下网络请求和备份器的配置，可能是图片没有请求到
> 
> > 检查一下网络请求和备份器的配置，可能是图片没有请求到
> 
> 都正常的，小于4k的图片也正常

同遇到这个问题 麻烦问下 如何解决的？
