### ISSUE TITLE
Slider 组件在移动端上无法进行滑动选择，只能点击

### ISSUE THREAD

**Issue by vVvlife** [arco-design/arco-design-vue#1575]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.35.1
- **框架版本:** Vue3
- **浏览器版本:** chrome105.0.0.0
- **复现地址:** https://pl2ozs.csb.app/

## 预期结果
可以进行滑动选择

## 复现步骤
打开F12，切换手机设备

## 额外补充
![image](https://user-images.githubusercontent.com/20148964/187020341-90933e0a-e23b-48a6-a221-521b578d4da9.png)

**Comment by flsion** [comment]
@vVvlife 后续版本会优化下 slider 组件，基本支持下移动端滑动

**Comment by vVvlife** [comment]
> 

Thanks

**Comment by vVvlife** [comment]
> @vVvlife 后续版本会优化下 slider 组件，基本支持下移动端滑动

Thanks

**Comment by hehehai** [comment]
暂时关闭，将在后续开发计划中跟进。

**Comment by Dwjem** [comment]
> @vVvlife 后续版本会优化下 slider 组件，基本支持下移动端滑动

@flsion 请问现在支持了吗
