### ISSUE TITLE
能否让复选框组也支持 value-key 属性？

### ISSUE THREAD

**Issue by GodRuiCollection** [arco-design/arco-design-vue#1582]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 信息
- **Package Name And Version:** @arco-design/web-vue@2.35.2
- **Browser:** chrome104.0.0.0

## 需求
希望复选框： a-checkbox-group 也可以像 a-select 一样支持 value-key 属性

## 说明
现在的情况是我需要将复选数据设置成对象，因为目前的业务比较复杂，需要携带尽可能多的属性。但是我发现如果先设置了 default-checked 复选框无法正常回显。
希望将来可以支持 value-key属性，谢谢了

**Comment by hehehai** [comment]
@GodRuiCollection hi，麻烦提供一个具体的功能场景吧。

**Comment by y1324** [comment]
> 

比如表格复制到另一个表格内，大体场景，表格里的多选，那么需要把当条的数据，传给接口。而不是这条的某个key。后端那里就不需要一个个查某个表下的key，在组装后，添加到另一个表。按这场景下，它们只需要把数据塞到另一个表即可。前端也不需要根据某个key去遍历完整选择的这条数据。

**Comment by hehehai** [comment]
> 比如表格复制到另一个表格内，大体场景，表格里的多选，那么需要把当条的数据，传给接口。而不是这条的某个key。后端那里就不需要一个个查某个表下的key，在组装后，添加到另一个表。按这场景下，它们只需要把数据塞到另一个表即可。前端也不需要根据某个key去遍历完整选择的这条数据。

@y1324 嗯，明白了，这个组件库目前没有实现数据的缓存的。这里还是建议做遍历取值（数据根据业务自己管理）。之后讨论看是否有必要将选中数据的整条信息在事件接口中返回。

**Comment by hehehai** [comment]
@GodRuiCollection hi，这个问题先关闭了，这里建议 key 如果需要携带较多参数可以使用 `${var}-${var}` 的形式处理为字符串或者 JSON，之后在做格式处理。（有其他问题的话，请再开启这个问题）
