### ISSUE TITLE
轮播图片支持错误状态显示

### ISSUE THREAD

**Issue by Kefeng2017** [arco-design/arco-design-vue#1588]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://arco.design/vue/component/carousel

## What problem does this feature solve?
目前轮播图加载失败是裂图样式，可以添加一个选项以支持轮播图片加载失败的候选显示。

![image](https://user-images.githubusercontent.com/33170776/187641879-8fdf02ef-d303-49b6-ade8-b8295c98da87.png)

**Comment by tazyong** [comment]
轮播图提供的是插槽，你可以自由插入任意内容，你的问题自己就能处理，不需要对轮播图做任何修改。

**示例：**
https://codesandbox.io/s/withered-butterfly-pkj2m9?file=/src/App.vue

如果没有问题请关闭该 issue
