### ISSUE TITLE
Rendering error when the icon is a string

### ISSUE THREAD

**Issue by guocailee** [arco-design/arco-design-vue#1590]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.35.2
- **Framework version:** vue@3.2.37
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/arco-tree-render-error-by8mi1?file=/src/App.vue

## Extra info
```bash
TypeError: this.renderFunc is not a function
```

## What is expected?
Tree component render success

## Steps to reproduce
1. import Tree component
2. define tree data like:
```javascript
import { h } from "vue";
import { IconStar, IconDriveFile } from "@arco-design/web-vue/es/icon";

export default {
  components: {
    IconStar,
  },
  setup() {
    return {
      treeData,
    };
  },
};

const treeData = [
  {
    title: "Trunk",
    key: "node1",
    children: [
      {
        title: "Leaf",
        key: "node2",
      },
    ],
  },
  {
    title: "Trunk",
    key: "node3",
    children: [
      {
        title: "Leaf",
        key: "node4",
        icon: "nothing",
      },
      {
        title: "Leaf",
        key: "node5",
        icon: () => h(IconDriveFile),
      },
    ],
  },
];
```

**Comment by guocailee** [comment]
之所以提这个问题，是因为我认为数据不应该跟渲染函数绑定一起，这样不利于data/view的隔离。

**Comment by flsion** [comment]
icon 参数接收的是 render 函数，这是支持渲染自定义元素的构造

**Comment by guocailee** [comment]
> icon 参数接收的是 render 函数，这是支持渲染自定义元素的构造
是的，但是我认为这样并不妥当，icon有可能是需要序列化的到数据库的字段。 为何不支持传入iconRender，或者icon slot来支持自定义元素呢？而通过这样跟data绑定一起的自定义渲染呢？

**Comment by tazyong** [comment]
> 之所以提这个问题，是因为我认为数据不应该跟渲染函数绑定一起，这样不利于data/view的隔离。

对于组件库来说，没有 data/view 隔离的说法，所有的状态都是组织呈现效果使用的，既是 data 也是 view。
你可以格式化请求回来的数据，以符合组件需要的状态，也可以使用 `field-names` 属性来自定义渲染。
没有其它问题就**关闭**该 issue 吧。

**相关文档：**
https://arco.design/vue/component/tree#API
![image](https://user-images.githubusercontent.com/24738011/189270876-04f49624-d6da-47e1-a1d9-a581d2d836b4.png)

**示例：**
https://codesandbox.io/s/arco-tree-render-error-forked-xjjo9b?file=/src/App.vue
![image](https://user-images.githubusercontent.com/24738011/189270631-da842f9a-e5dc-455f-971f-1186205f49e9.png)
