### ISSUE TITLE
最新版本按钮点击有黑框

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1601]
如图
![QQ截图20220904024625](https://user-images.githubusercontent.com/88036648/188284391-4df2f078-4ce2-40ad-ab36-39a1b372b50a.png)

**Comment by hehehai** [comment]
@xiaomilaaz hi，看起来像 聚焦后 outline 的问题，#1306

- 浏览器版本是什么呀？

**Comment by xiaomilaaz** [comment]
已经解决，自己的问题

> @xiaomilaaz hi，看起来像 聚焦后 outline 的问题，#1306
> 
> * 浏览器版本是什么呀？
