### ISSUE TITLE
关a-modal before-ok表单验证问题

### ISSUE THREAD

**Issue by chenyongxiong** [arco-design/arco-design-vue#1613]
a-modal写的提交之前表单先验证@before-ok="handleBeforeOk" 

    <a-modal
      v-model:visible="visibleModal"
      :title="modelTitle"
      @ok="handleOk"
      @cancel="handleCancel"
      @before-ok="handleBeforeOk"
    >
      <a-form ref="formRef" :model="formDataModel">

 const handleBeforeOk = async (done: any) => {
    const res = await formRef.value?.validate();
    if (!res) {
      done();
    }
    done(false)
  };

 npm run build 打包的时候提示报错，Type '() => Promise<boolean>' is not assignable to type '(done: (closed: boolean) => void) => boolean | void'.
  Type 'Promise<boolean>' is not assignable to type 'boolean | void'.
    Type 'Promise<boolean>' is not assignable to type 'void'.
请问应该是怎写才正确呢？？

**Comment by tazyong** [comment]
在 js/ts 中 async 修饰的函数会返回 Promise 对象，on-before-ok 接收的参数是一个返回布尔值或者没有返回值的函数，返回值不一样，所以类型不符。

async 相关文档：
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function

正确写法：
```ts
const handleBeforeOk = (done: (closed: boolean) => void) => {
  if (formRef.value) {
    formRef.value.validate()
      .then(res => done(!res ? true : false))
      .catch(error => done(false));
  } else {
    done(true);
  }
};
```
Duplicate of #1612

**Comment by chenyongxiong** [comment]
试过可以了，这个返回不是异步的。谢谢了
