### ISSUE TITLE
2.36.0 更新日志涉台问题

### ISSUE THREAD

**Issue by G-Akiraka** [arco-design/arco-design-vue#1615]
https://arco.design/vue/docs/changelog

其中一条
增加繁体中文（台湾）支持 ([#1551](https://github.com/arco-design/arco-design-vue/pull/1551))

为什么将台湾标注为国家，而不是中国台湾

**Comment by G-Akiraka** [comment]
[1.png](https://postimg.cc/Kkzd8zkD)

**Comment by G-Akiraka** [comment]
[![vHd4Ug.png](https://s1.ax1x.com/2022/09/07/vHd4Ug.png)](https://imgse.com/i/vHd4Ug)

**Comment by tazyong** [comment]
如果和中国的各个省份放一起，这是没问题的。
但如果和国家名称并列，必须要加中国前缀！

支持楼主！我推个 PR 去修正它！

**Comment by flsion** [comment]
抱歉，这里疏忽没有留意，是「中国台湾」，我会修正一下

**Comment by flsion** [comment]
@G-Akiraka @tazyong 更新日志内容已经修正
