### ISSUE TITLE
select option 中 value 参数能不能支持空，并且不从内容中获取

### ISSUE THREAD

**Issue by su-qiu** [arco-design/arco-design-vue#1617]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
大部分场景下拉选择框有全部选项，如果选择为全部，则传空给后台用于查所有

## What problem does this feature solve?
大部分场景下拉选择框有全部选项，如果选择为全部，则传空给后台用于查所有

**Comment by fairySusan** [comment]
把这个show-extra-options设置为false

**Comment by tazyong** [comment]
不选择就是全部了

**Comment by flsion** [comment]
value 不支持空字符串、null、undefined，这些都会当作未传值处理。如果有类似场景，可与自行封装组件，将一个特殊值转换为空值
