### ISSUE TITLE
标签输入框 InputTag组件，希望能够增加插槽已实现自定义tag内容

### ISSUE THREAD

**Issue by youhuan** [arco-design/arco-design-vue#1621]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
例如：标签输入框 InputTag组件中tag前能够显示icon

**Comment by tazyong** [comment]
InputTag 组件是有插槽的，官网没有写出来，你使用 tag 插槽就可以了

### `<input-tag>` Slots

|插槽名|描述|参数|
|---|:---:|---|
|tag|输入框标签的显示内容|data: `TagData`|
|prefix|前缀元素|-|
|suffix|后缀元素|-|

**Comment by youhuan** [comment]
好的，多谢
