### ISSUE TITLE
Modal组件移动端

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#1624]
Modal组件移动端适应好差哦，希望可以优化，固定width 移动端就不行
自适应又没全屏

**Comment by flsion** [comment]
有类似可以提供参考的 PC 组件库吗，目前的 modal 不建议在移动端下使用

**Comment by Aganivi** [comment]
表单Modal 在移动端时，执行input 操作之后有机率出现可滑动现象，mask 之下的内容变得可滑动。
