### ISSUE TITLE
使用了a-year-piker 组件用 打包报错

### ISSUE THREAD

**Issue by HaZhu** [arco-design/arco-design-vue#1627]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.36.1
- **Framework version:** 2.30.2
- **Browser:** chrome105.0.0.0

## Extra info
Rollup failed to resolve import "/Users/WindOnJune/Desktop/艺术家档案馆/artist-archives/node_modules/@arco-design/web-vue/es/year-picker/style/css.js" from "src/views/home/components/cv.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

## What is expected?
赶紧修复

## Steps to reproduce
打包的时候报错，运行的时候没问题

**Comment by HaZhu** [comment]
在styleimplrt.js里面价格映射就行

**Comment by thislyc** [comment]
@HaZhu 这个咋解决的 可以详细说一下吗
感觉是组件的问题呀 为啥close了

**Comment by unloserv** [comment]
a-week-picker也有同样的问题 请问怎么解决的额？
