### ISSUE TITLE
能否新加个icon 选择框组件

### ISSUE THREAD

**Issue by renjiali666** [arco-design/arco-design-vue#1630]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.36.1
- **Framework version:** vue3
- **Browser:** chrome105.0.0.0

## What is expected?
图标下拉框，可选择图标

## Steps to reproduce
后台管理中，动态路由，希望可动态修改图标

**Comment by hehehai** [comment]
@renjiali666 hi, 官方组件库暂时没有计划支持该组件。

**Comment by peng0928** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
> 
> ## Basic Info
> * **Package Name And Version:** @arco-design/web-vue@2.36.1
> * **Framework version:** vue3
> * **Browser:** chrome105.0.0.0
> 
> ## What is expected?
> 图标下拉框，可选择图标
> 
> ## Steps to reproduce
> 后台管理中，动态路由，希望可动态修改图标



动态路由图标实现，可以尝试修改/src/components/menu/index.vue文件：
我这边使用的是IconFont, IconFont的安装就不介绍了。
1.在main.ts进行全局注册：
`
import ArcoVue, { Icon } from '@arco-design/web-vue';
const IconFont = Icon.addFromIconFontCn({
  src: 'https://at.alicdn.com/t/c/font_4722668_05iwmjsyurv4.js',
});
app.component('IconFont', IconFont);
`
2.在menu/index.vue导入使用
`import {resolveComponent} from 'vue';
  const IconFont = resolveComponent('IconFont')
  const icon2 = element?.meta?.icon2;
  const icon = element?.meta?.icon
                ? () => h(compile(`<${element?.meta?.icon}/>`))
                : () => h(IconFont, {
                  type: icon2,
                  size: '16',
                })
`
3.设置路由，定义icon2
`
 {
            path: 'task',
            name: 'Task',
            component: () => import('@/views/home/index.vue'),
            meta: {
                locale: 'menu.task',
                requiresAuth: true,
                roles: ['*'],
                icon2: 'icon-tasks',
            },
}
`

![Image](https://github.com/user-attachments/assets/76923e95-3f57-4b9a-987f-38a0e4494078)
