### ISSUE TITLE
2.36.1版本，drawer组件ok事件不触发，@ok="handleOk"，handleOk不执行

### ISSUE THREAD

**Issue by bluefantasy728** [arco-design/arco-design-vue#1633]
在之前的版本中，`on-before-ok`的`done`函数不加参数true，也可以触发`ok`事件。
但是升级到2.36.1后，一定要在`done`函数中传`true`，才能触发`ok`事件。
希望可以兼容之前的版本，不传参数true时可以默认是true
```
function beforeOK(done){
  console.log('done');
  done() // 2.36.1这样写是不会触发ok事件的，一定要写成done(true)
}
function handleOk() {
  console.log('hanleOK');
  visible.value = false
}
```

- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.36.1
- **Browser:** chrome105.0.0.0

**Comment by flsion** [comment]
嗯，有个相关的 PR，这个会在新版中考虑一下
https://github.com/arco-design/arco-design-vue/pull/1628
