### ISSUE TITLE
2.37.0版本a-list 组件BUG

### ISSUE THREAD

**Issue by itlanjing** [arco-design/arco-design-vue#1637]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.0
- **Browser:** chrome102.0.0.0

## Steps to reproduce
a-list 组件不能使用了，最基本使用a-list-item不显示

**Comment by hehehai** [comment]
@itlanjing hi，有复现案例吗？这里是正常的[demo](https://codesandbox.io/s/elastic-heisenberg-ze7gd6?file=/src/App.vue)

**Comment by itlanjing** [comment]
之前用的版本2.30.2`<a-list :grid-props="{ span: 0 }"><a-list-item>123<a-list-item></a-list>`一直没有问题，正常的，升级之后不显示item,排查发现span: 0原因，具体为啥结果有差异未知，打扰到您，应该是我这边问题

**Comment by hehehai** [comment]
@itlanjing 嗯，可以参考[官网](https://arco.design/vue/component/list#grid)的写法。

代码里的判断是 grid-props 存在且 span 无效（0 的话也是无效），所有会被视为使用 “网格布局”，这里 span 的使用也不建议设置为 0 。
https://github.com/arco-design/arco-design-vue/blob/fa924d87e1399706ef72864e674b97ea4ae4a2ad/packages/web-vue/components/list/list.tsx#L208
