### ISSUE TITLE
【级联组件】期望增加类似react版本的changeOnSelect属性

### ISSUE THREAD

**Issue by jiangxuzh** [arco-design/arco-design-vue#164]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://arco.design/react/components/cascader#%E9%80%89%E6%8B%A9%E5%8D%B3%E6%94%B9%E5%8F%98

## What problem does this feature solve?
希望实现级联组件一级可选

**Comment by Flsion** [comment]
@jiangxuzh 收到，这个功能后续会添加
