### ISSUE TITLE
Support displaying footer on empty options for <a-select>

### ISSUE THREAD

**Issue by FerricIon** [arco-design/arco-design-vue#1644]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
None.

## What problem does this feature solve?
Currently footer slot will not be shown on empty options. If a filter is put in the footer and a user updates the filter resulting in empty options, the filter will disappear. In that case no more actions could be made, and the options are gone forever. A boolean prop can be added to <a-select> to support displaying footer on empty options.

**Comment by zhanghaoyan** [comment]
我也遇到了这个问题，当选项为空时，footer不显示了，请尽快修复此bug

**Comment by LIjiAngChen8** [comment]
#2429
