### ISSUE TITLE
a-table 设置 自定义css 的有关问题

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1647]
这里不知道为什么 span  一直有间隙

![image](https://user-images.githubusercontent.com/35121432/190981689-e03358d2-c616-42bc-af7f-97eaced37229.png)

然后想自定义设置 cell 的style ,但是发现没有什么方法，大哥们，能不能类似我下面这个链接这样，能够自定义测试 单个cell的样式，
类似这样

![image](https://user-images.githubusercontent.com/35121432/190981952-7b900862-b82e-4984-bc51-218139cccc7e.png)
 

https://vxetable.cn/#/table/base/dynamicStyle

万分感谢

**Comment by flsion** [comment]
@cgrain1998 单元格整体背景色定义可以使用 body-cell-style 或者 body-cell-class。全局修改直接修改 td 元素的样式

**Comment by cgrain1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cgrain1998** [comment]
thx

> @cgrain1998 单元格整体背景色定义可以使用 body-cell-style 或者 body-cell-class。全局修改直接修改 td 元素的样式
这里不能 箭头函数设置 cell -style 的~~~
