### ISSUE TITLE
a-table 传递了pagination的prop，期望一页15条数据，表格还是渲染10条数据

### ISSUE THREAD

**Issue by fairySusan** [arco-design/arco-design-vue#1654]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.1
- **Framework version:** 2.35.0
- **Browser:** chrome105.0.0.0

## What is expected?
希望渲染15条数据

## Steps to reproduce
<a-table
        :columns="columns"
        :data="data.list"
        :pagination="pagination"
        :loading="loading"
        @page-size-change="onSizeChange"
        @page-change="onCurrentChange"
      >
</a-table>

// pagination

const pagination = reactive({
    'total': 0,
    'current': 1,
    'page-size': 15,
    'show-total': true,
    'show-page-size': true,
    'default-page-size': 15,
    'page-size-options': [10, 15, 20, 25, 30]
  })

**Comment by flsion** [comment]
@fairySusan vue 对象属性中的 key 统一使用驼峰形式的命名，这里应该写为
```
const pagination = reactive({
total: 0,
defaultPageSize: 15,
})
```
