### ISSUE TITLE
【Select】当Select 有滚动条时，滚动下拉框后再次打开会报错

### ISSUE THREAD

**Issue by kkkisme** [arco-design/arco-design-vue#1656]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.37.1
- **框架版本:** vue ^ 3.2.0
- **浏览器版本:** chrome105.0.0.0
- **复现地址:** https://arco.design/vue/component/select#scroll

## 预期结果
不报错

## 复现步骤
1、打开Select选项，滚动选项到底部
2、选中任意选项
3、再次打开Select选项, 此时console报错

**Comment by kkkisme** [comment]
![image](https://user-images.githubusercontent.com/18638401/191468506-a42c755b-f5d9-4007-a08f-26adaefe3321.png)

**Comment by hehehai** [comment]
@kkkisme hi，请 2.37.2 版本已修复该问题，可以升级下看
