### ISSUE TITLE
建议icon图标添加一个复制svg的功能？

### ISSUE THREAD

**Issue by ckvv** [arco-design/arco-design-vue#1666]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://element-plus.org/zh-CN/component/icon.html#%E5%9B%BE%E6%A0%87%E9%9B%86%E5%90%88

## What problem does this feature solve?
可以复制icon内容会更方便使用

**Comment by hehehai** [comment]
@ckvv hi，Arco 的完整图标已在 [IconBox](https://arco.design/iconbox/lib/89/0) 中开放。
