### ISSUE TITLE
notification 的 footer 参数如何使用，文档没有

### ISSUE THREAD

**Issue by chenxi2015** [arco-design/arco-design-vue#1675]
请问footer参数如何使用，想加自定义按钮

**Comment by hehehai** [comment]
@chenxi2015 hi, footer 是支持渲染函数的，参考[demo](https://stackblitz.com/edit/angular-qkd3a8?file=src%2FApp.vue)

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/12692552/192123663-dc651a7a-46f6-44d0-9367-ec71bf8378d7.png">

**Comment by chenxi2015** [comment]
> @chenxi2015 hi, footer 是支持渲染函数的，参考[demo](https://stackblitz.com/edit/angular-qkd3a8?file=src%2FApp.vue)
> 
> <img alt="image" width="1010" src="https://user-images.githubusercontent.com/12692552/192123663-dc651a7a-46f6-44d0-9367-ec71bf8378d7.png">

好的 谢谢
