### ISSUE TITLE
a-table  滚动条位置的小疑问

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1679]
这是官方的
![image](https://user-images.githubusercontent.com/35121432/192283681-f962f1f8-8fc7-4279-9152-a0647532b7b7.png)

这是自己的项目

![image](https://user-images.githubusercontent.com/35121432/192283902-4372c8f8-a019-4a1f-89ae-5f4d474b01c3.png)

为什么滚动条是这样的

很奇怪，框架升级到
"@arco-design/web-vue": "2.37"

本来想提个复现的，发现 官方没问题

![image](https://user-images.githubusercontent.com/35121432/192284319-6693d59a-fca7-45ad-a2b6-c49d97ff6bb9.png)

![image](https://user-images.githubusercontent.com/35121432/192284420-3f4ec531-fa98-4481-9e73-e7813a90712c.png)

**Comment by flsion** [comment]
@cgrain1998 2.37.1 版本后内置了虚拟滚动条，默认是浮动在内容之上的

**Comment by cgrain1998** [comment]
> 
呜呜呜
 又想提个bug了   👀👀👀

**Comment by hehehai** [comment]
暂时关闭了，有问题复现再开启吧
