### ISSUE TITLE
modal 如何设置 v-html

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1689]
后端 返回 html 类型文字，如何 使用 modal  把返回值渲染成v-html

```
Modal.info({
        title: 'Info Title',
        content:  res.msg
      });


```

**Comment by hehehai** [comment]
@cgrain1998 hi, 这里可以使用 jsx 形式, 或 h 函数 [demo](https://codesandbox.io/s/shy-darkness-g01dvi?file=/src/App.vue)

**Comment by cgrain1998** [comment]
> @cgrain1998 hi, 这里可以使用 jsx 形式, 或 h 函数 [demo](https://codesandbox.io/s/shy-darkness-g01dvi?file=/src/App.vue)

哥，你这么强悍的渲染方式，我的vscode 会报错哎

![image](https://user-images.githubusercontent.com/35121432/192504833-ec265233-104c-4eda-9237-29d673a480a8.png)

**Comment by cgrain1998** [comment]
好的，哥我尝试一下
