### ISSUE TITLE
a-list组件，arco-list-item类名下没有默认padding

### ISSUE THREAD

**Issue by Jquank** [arco-design/arco-design-vue#1697]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.3
- **Browser:** chrome100.0.4896.60

**Comment by hehehai** [comment]
@Jquank hi, 这里的问题是？或者可以补充一个问题复现。
