### ISSUE TITLE
spin中自定义图标设置spin:false无效

### ISSUE THREAD

**Issue by joyexpr** [arco-design/arco-design-vue#1701]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.3
- **Browser:** chrome78.0.3904.108

## What is expected?
spin当loading=true且有自定义图标时，自定义图标可自行设置是否自动旋转。

需求场景可参写飞书pc端，当登录二维码过期失效时，提示刷新二维码，图标不需要旋转

**Comment by hehehai** [comment]
@joyexpr hi, 自定义图标的情况可以使用 `element` 不会自动旋转
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/12692552/193377988-08788858-1792-4bb3-87e9-b795440222b0.png">
