### ISSUE TITLE
Can not change icon size in Spin via `size` prop

### ISSUE THREAD

**Issue by freedomlang** [arco-design/arco-design-vue#1716]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome104.0.0.0

**Comment by hehehai** [comment]
@freedomlang hi, 提个复现吧，是使用的 size 关键字参数吗？spin 的 size 仅支持数值的。
