### ISSUE TITLE
Multiple select problem with search method

### ISSUE THREAD

**Issue by orozot** [arco-design/arco-design-vue#1728]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/angular-ircqp6?file=src/App.vue

## Steps to reproduce
1.  Enter `test` in the select
2. Select any option, for example `test-Option1`
3. Enter `new-str` in the select
4. You can see that the previously selected `test-Option1` has become `test-id-1`

## Screenshot
<img width="474" alt="image" src="https://user-images.githubusercontent.com/20898968/194831302-45f29963-fe7a-4d3e-a9e7-5cd74f6f34c0.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/20898968/194831499-924b3d7c-5b15-4f76-b03b-af1a439e3cf0.png">

**Comment by hehehai** [comment]
> The problem seems to be due to the fact that after entering a new string, only the previously selected `value` is saved and not the `label`.

@orozot hi, yep! Within the component, `value` of the current value will be selected to query `label` in the preset. If there is no match, `value` will be displayed directly. 

I think this is normal. Do you have any other suggestions?

**Comment by orozot** [comment]
@hehehai Thanks for your reply. I think in the case of remote search, we should save the option `value` and `label` that the user has selected. 

Because the `value` is usually the back-end storage id, `label` is the field that the user can understand, if we show `value` directly to the user, it will cause confusion to them.

**Comment by orozot** [comment]
Just created a quick PR to fix that ☝️
