### ISSUE TITLE
表格组件固定列和可调整列宽冲突

### ISSUE THREAD

**Issue by MaybeAyan** [arco-design/arco-design-vue#1729]
## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Framework version:** 3.x
- **Browser:** chrome106.0.0.0

## What is expected?
固定列在给定宽之后，调整列宽后滑动，后面的数据会显示在固定列调整列宽后空出来的位置

![image](https://user-images.githubusercontent.com/93271587/194841997-56499425-6fe3-430f-9ac4-f68fe9be2988.png)

**Comment by hehehai** [comment]
@MaybeAyan hi, 麻烦补充个复现吧。

**Comment by MaybeAyan** [comment]
> 
![image](https://user-images.githubusercontent.com/93271587/194981139-f44a6b59-a414-44f1-8584-93cb422b23c2.png)
固定列调整列宽后，横向滚动表格，后面的数据会跑到空白的地方...

**Comment by MaybeAyan** [comment]
@hehehai 我设置了多行固定列，给死了宽度，大概是调整列宽后，仍固定在计算好的固定列宽度位置，就会导致这个情况，求一个解决方案，按照官网提到了，至少一列不设置宽度，但仍然是会有这个问题。

**Comment by hehehai** [comment]
@MaybeAyan 谢谢回复，麻烦使用 [CodeSandBox](https://codesandbox.io/s/5l94wy?file=/demo.tsx) 或其他在线 coding，分享一个复现地址吧。这会更快的帮助我们复现解决该问题。
