### ISSUE TITLE
在线性主题下，a-input-group 里面相邻组件的边框叠加的问题，希望可以优化一下

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#1737]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://www.antdv.com/components/input-cn

## What problem does this feature solve?
样式问题

## Extra info
arco的
<a href="https://imgse.com/i/xUTjbD"><img src="https://s1.ax1x.com/2022/10/12/xUTjbD.png" alt="xUTjbD.png" border="0" /></a>

antdv 的
<a href="https://imgse.com/i/xUTMnO"><img src="https://s1.ax1x.com/2022/10/12/xUTMnO.png" alt="xUTMnO.png" border="0" /></a>

**Comment by hehehai** [comment]
@lin-97 hi, 可以提个复现，（版本，系统，浏览器也可以发下）。这里最新版本 Mac + Chrome 看起来是正常的 参考：[demo](https://codesandbox.io/s/agitated-lovelace-b8bytc)

**Comment by lin-97** [comment]
你给的demo肯定看不出啊，你的又不是线性主题，就是input   select这些没有背景色的，只有边框色，由于官网的不是线性主题，是看不出的，你要找个风格配置平台的线性主题才知道，或者你可以在官网切个线性主题试试，然后去input那里看
<a href="https://imgse.com/i/xacapF"><img src="https://s1.ax1x.com/2022/10/13/xacapF.png" alt="xacapF.png" border="0" /></a>

**Comment by lin-97** [comment]
你给的demo肯定看不出啊，你的又不是线性主题，就是input   select这些没有背景色的，只有边框色，由于官网的不是线性主题，是看不出的，你要找个风格配置平台的线性主题才知道，或者你可以在官网切个线性主题试试，然后去input那里看
<a href="https://imgse.com/i/xacapF"><img src="https://s1.ax1x.com/2022/10/13/xacapF.png" alt="xacapF.png" border="0" /></a>

**Comment by hehehai** [comment]
@lin-97 嗯，明白了，谢谢回复。

**Comment by Summer-Shen** [comment]
acro-design-vue 如何使用线性主题？我注意到线性主题只支持 acro-design (React)。
