### ISSUE TITLE
自动补全 AutoComplete 不应该只显示包含用户输入字符串的选项

### ISSUE THREAD

**Issue by selegiline** [arco-design/arco-design-vue#1738]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Framework version:** 3.2.40
- **Browser:** chrome106.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/hardcore-lake-r23uuc?file=/src/App.vue

## What is expected?
1.应该显示五个选项
2.应该显示五个选项

## Steps to reproduce
1.输入1
2.输入7

**Comment by hehehai** [comment]
@selegiline hi，这里看起来仅是 demo 的问题，组件提供 search 触发，而内容逻辑取就决于开发者的定义了。
