### ISSUE TITLE
穿梭框元素列表无法滚动

### ISSUE THREAD

**Issue by cuipeiyu** [arco-design/arco-design-vue#1742]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome106.0.0.0

**Comment by flsion** [comment]
@cuipeiyu 感谢反馈，新版虚拟滚动条的样式有些问题，下版本会修复下，目前可以降级到2.37.0使用
