### ISSUE TITLE
通知提醒框 Notification, 参数showIcon不工作

### ISSUE THREAD

**Issue by selegiline** [arco-design/arco-design-vue#1748]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Framework version:** lateset
- **Browser:** chrome106.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/wizardly-stitch-g2pp3d?file=/src/App.vue

**Comment by hehehai** [comment]
@selegiline hi, 这个问题已修复，可使用 [2.38.0-beta.1](https://github.com/arco-design/arco-design-vue/releases/tag/2.38.0-beta.1) 版本，参考 [demo](https://codesandbox.io/s/wispy-fog-tqqvz9?file=/package.json)
