### ISSUE TITLE
表头做国际化无法切换语言

### ISSUE THREAD

**Issue by fairySusan** [arco-design/arco-design-vue#1761]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome106.0.0.0

## What is expected?
切换语言的时候，表头的不会切换，请问有什么好的解决方案

## Steps to reproduce
```
import i18n from "@/locale"
const t = i18n.global.t

export const columns: TableColumnData[] = [
  {
    title: t('socialAccount.device'),
    dataIndex: 'device',
  },
]
```

**Comment by tazyong** [comment]
你的用法不对
`t()` 就是个普通函数而已，执行后就返回当前语言对应的文本，切换语言的时候必须重新执行才是有效的
而你定义的 `columns` 只是个普通对象，再怎么切换也不可能给你修改对象的值啊，这里需要使用 vue 的 `computed()` 或者 响应式对象+`watch()`
