### ISSUE TITLE
数字输入框 InputNumber    动态改变max参数  步骤钮还是禁用状态

### ISSUE THREAD

**Issue by Gs19990801** [arco-design/arco-design-vue#1773]
![bb162722c6192d65f55edf76f2fafd8](https://user-images.githubusercontent.com/81606230/197338246-3e6ce886-2d7a-4e16-a6ac-a74df75df043.jpg)
![94b846877e0b83e617021e94b82dd18](https://user-images.githubusercontent.com/81606230/197338256-220459b2-8401-41c6-8067-67b72907ffb8.jpg)
![3bfe3bda0b5daa84e057b1e5a7404db](https://user-images.githubusercontent.com/81606230/197338258-ecad24fc-9b1a-4277-9035-831ff21bf840.jpg)

**Comment by pzgz** [comment]
的确是有这个问题，`max`和`min`两个属性感觉响应没做好

**Comment by Gs19990801** [comment]
收到修复1777

**Comment by Gs19990801** [comment]
> 的确是有这个问题，和两个属性感觉响应没做好`max``min`

收到修复 #1777

**Comment by Gs19990801** [comment]
收到修复 #1777
