### ISSUE TITLE
vue版本tree默认展开所有节点不生效问题解决办法

### ISSUE THREAD

**Issue by luyanghtml** [arco-design/arco-design-vue#1776]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome106.0.0.0

## Extra info
a-tree上加v-if 有数据的时候再让节点dom渲染

**Comment by luyanghtml** [comment]
if the data reuqeste from server , you may have this question. add 'v-if' on the 'a-tree' tag

**Comment by hehehai** [comment]
Repeat: #1610
