### ISSUE TITLE
虚拟化列表的滚动条跟默认的滚动条样式不一致

### ISSUE THREAD

**Issue by zj-kenzhou** [arco-design/arco-design-vue#1781]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome106.0.0.0

![image](https://user-images.githubusercontent.com/37363187/197487926-18f1e373-df17-4a1f-9434-a9e39de9f81d.png)

**Comment by flsion** [comment]
@zj-kenzhou 目前虚拟列表中还没有使用虚拟滚动条，预计会在 2.39.0 版本进行替换

**Comment by hehehai** [comment]
重复：#1640
