### ISSUE TITLE
输入框输入中文的时候 ，用拼音输入一段很长的中文按回车键键入 ，会找不到光标

### ISSUE THREAD

**Issue by fiveo0** [arco-design/arco-design-vue#1783]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Browser:** chrome106.0.0.0

**Comment by flsion** [comment]
可以提供一个复现地址和方法吗，我本地没有复现出来

**Comment by fiveo0** [comment]
![WechatIMG347](https://user-images.githubusercontent.com/50072115/200218306-c793e7d6-2e50-49b4-b27b-90dd2c17b8b6.png)
就是正常输入中文 光标被隐藏到后面了，输入的中文越长隐藏得约后面
