### ISSUE TITLE
date-picker 复制过来的时间是正确的能不能不在打开弹框

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#1786]
![image](https://user-images.githubusercontent.com/35121432/197936578-50908a45-bb9e-4531-a0b5-53aecc7ac1a3.png)

如上，我复制过来的时间是正确的，还要打开弹窗点一下确认，能不能省略这一步，反人类~~~~

**Comment by flsion** [comment]
选择弹窗是在 input 聚焦时弹出，失焦时消失的，复制完点击空白处或者tab到一下个就可以了
