### ISSUE TITLE
 Arco Vite 插件 引入主题包运行问题

### ISSUE THREAD

**Issue by CHENLiver** [arco-design/arco-design-vue#1787]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.37.4
- **框架版本:** vue
- **浏览器版本:** chrome106.0.0.0

## 复现步骤
vite 使用@arco-plugins/vite-vue 在window 运行出现 [vite] Internal server error: path.replaceAll is not a function

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/13173587/197992552-5e4029e8-cb55-44f7-a75f-c847319a487c.png">

**Comment by CHENLiver** [comment]
在mac运行正常

**Comment by tazyong** [comment]
node.js 升级到 15.x 以上才支持，建议使用 16.x 版本
[replaceAll 兼容性](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7)
