### ISSUE TITLE
popup、trigger 的zIndex 不能手动控制

### ISSUE THREAD

**Issue by kkkisme** [arco-design/arco-design-vue#1788]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
elementUI  为弹出窗的container 添加类名，用户可以更好的控制弹出窗的展现形式。
![image](https://user-images.githubusercontent.com/18638401/198000055-fe783b79-fe20-48c2-8bdf-aa033d6a3fc8.png)

## 预期解决问题
modal 、trigger 这些弹出窗口的zIndex 需要手动控制

trigger 只有popup-style 而没有 对应的popup-class

**Comment by tazyong** [comment]
好的设计就不应该让用户关心 `zIndex`

**Comment by kkkisme** [comment]
> 好的设计就不应该让用户关心 `zIndex`

我说的“用户” 是指 “开发者”😂。
当一个页面上 有modal、有dropdown 有header吸顶、有spin ，这个时候还是需要自定义下某些组件的zIndex 的

**Comment by flsion** [comment]
@kkkisme 可以使用 style 自定义 z-index。https://codesandbox.io/s/dreamy-austin-91oxqj?file=/src/App.vue
目前 modal 因为覆盖优先级有些问题，这次处理下
