### ISSUE TITLE
建议给vue版的select加上扩展菜单、自定义标签样式以自定义模板功能

### ISSUE THREAD

**Issue by puppetsheep** [arco-design/arco-design-vue#179]
## 现有案例
[扩展菜单](https://arco.design/react/components/select#%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95)
[自定义标签样式](https://arco.design/react/components/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E7%AD%BE%E6%A0%B7%E5%BC%8F)
[自定义模板](https://element-plus.gitee.io/zh-CN/component/select.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF)
## 预期
扩展菜单及自定义标签在react版本中有，自定义模板功能可以参考element-plus那种形式。

**Comment by Flsion** [comment]
@puppetsheep 自定义选项和页脚功能已经添加，自定义标签预计会在下个版本添加

**Comment by cgrain1998** [comment]
哥，自定义样式的是忘记加了嘛

> @puppetsheep 自定义选项和页脚功能已经添加，自定义标签预计会在下个版本添加
