### ISSUE TITLE
 暗黑模式下表格加斑马纹内容被穿透 

### ISSUE THREAD

**Issue by KaneLeung** [arco-design/arco-design-vue#1791]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.37.4
- **框架版本:** VUE3.2.41
- **浏览器版本:** chrome106.0.0.0

## 额外补充
![微信截图_20221027161540](https://user-images.githubusercontent.com/24695053/198232351-3569b229-45dc-4651-bd16-4e7e8f8b565f.png)
![微信截图_20221027161717](https://user-images.githubusercontent.com/24695053/198232344-9629a5f9-06da-429c-8bea-fc4f82eb5d28.png)

## 预期结果
 fixed的内容不被后面的内容穿透

## 复现步骤
 表格 斑马纹 选择框或设置了fixed,fixed的内容被后面的内容穿透

**Comment by KaneLeung** [comment]
升级到@arco-design/web-vue": "2.38.0-beta.2 问题依旧

**Comment by zhaoxin0523** [comment]
@KaneLeung   设置一下选中行单元格的类名可以解决 .arco-table-tr-checked .arco-table-td
