### ISSUE TITLE
跪求大佬写一个带渐变带吸附的颜色选择器

### ISSUE THREAD

**Issue by ChenWeihua123** [arco-design/arco-design-vue#18]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
现有组件不满足需求

## 预期解决问题
想要一个带渐变选择、带颜色吸取器的 color-picker 组件

**Comment by PengJiyuan** [comment]
可以在物料平台 https://arco.design/material 提交一个物料
