### ISSUE TITLE
Update Lark Icon

### ISSUE THREAD

**Issue by kaikaibenkai** [arco-design/arco-design-vue#1800]
## 现有案例
![svg file](https://user-images.githubusercontent.com/99722991/198834196-01b26f39-c65c-4c6e-b380-1041d6c2344a.svg)

## 预期解决问题
Lark logo had been updated last year. But Arco hasn't updated it yet.
飞书logo早就更新了，Arco考虑跟进一下？

**Comment by flsion** [comment]
@kaikaibenkai 感谢提醒，我们会更新下最新的 icon
