### ISSUE TITLE
【FR】【tabs】允许tabs关闭滑块切换动画

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#1802]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
当滑块充当路由切换功能时，active-key需要跟随路径变化，导致每次切换页面，滑块动画都会从第一个切换到所点击的那个

**Comment by hehehai** [comment]
@seepine hi, 这个里建议先尝试自己覆盖过渡样式

<img width="331" alt="image" src="https://user-images.githubusercontent.com/12692552/198837121-90923179-92e5-43ac-8be2-24e1ddcaca96.png">

动画开关要讨论下
