### ISSUE TITLE
Message 是否支持鼠标移入时，取消定时关闭，鼠标移除再开启定时

### ISSUE THREAD

**Issue by a145789** [arco-design/arco-design-vue#1821]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
参考 [Element Plus](https://element-plus.gitee.io/zh-CN/component/message.html)

## 预期解决问题
Message 是否支持鼠标移入时，取消定时关闭，鼠标移除再开启定时

**Comment by flsion** [comment]
@a145789 你好~目前暂时没有这个功能，后续可以考虑添加下

**Comment by a145789** [comment]
这个功能接受PR么

**Comment by flsion** [comment]
> 这个功能接受PR么

嗯，可以的
