### ISSUE TITLE
Modal组件消息提示框添加Cancel按钮

### ISSUE THREAD

**Issue by WilsonXinxin** [arco-design/arco-design-vue#1827]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
Modal组件消息提示框添加Cancel按钮
比如 [Element Message](https://element-plus.gitee.io/zh-CN/component/message-box.html#%E7%A1%AE%E8%AE%A4%E6%B6%88%E6%81%AF)

**Comment by luckyship** [comment]
![image](https://user-images.githubusercontent.com/22162049/199936137-d3076261-503d-42ee-874a-77cae6695258.png)
![image](https://user-images.githubusercontent.com/22162049/199936182-b0e780b9-8006-4734-8c33-70ff030a919a.png)

**Comment by WilsonXinxin** [comment]
> ![图像](https://user-images.githubusercontent.com/22162049/199936137-d3076261-503d-42ee-874a-77cae6695258.png) ![图像](https://user-images.githubusercontent.com/22162049/199936182-b0e780b9-8006-4734-8c33-70ff030a919a.png)
謝謝!
