### ISSUE TITLE
[FR] 希望Tooltip和Popover在hover显示时，增加支持延迟xx毫秒才显示（如 :delay=500）的prop

### ISSUE THREAD

**Issue by joyexpr** [arco-design/arco-design-vue#1830]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.38.0
- **Browser:** chrome78.0.3904.108

## What is expected?
希望Tooltip和Popover在hover显示时，增加支持延迟xx毫秒才显示（如 :delay=500）的prop，有时只是不小心划过，或者已经知道要显示的内容，太快显示会干扰用户

**Comment by flsion** [comment]
可以使用继承的 trigger 组件的 mouse-enter-delay 属性设置
