### ISSUE TITLE
Badge设置本文时再设置color，文字背景变成小圆点

### ISSUE THREAD

**Issue by KaneLeung** [arco-design/arco-design-vue#1831]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.0
- **框架版本:** 3.2.41
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://codesandbox.io/s/focused-tereshkova-9xm8k5

![image](https://user-images.githubusercontent.com/24695053/199906437-b3241f66-6e48-4531-ade9-04ebb9c336d9.png)

## 预期结果
设置的背景色覆盖整个文字

## 复现步骤
a-badge text="HOT" color="#165DFF"

**Comment by flsion** [comment]
@KaneLeung 你好~ 目前 Badge 组件是这样设计的，在设置 color 后会显示为小圆点，并把文字放在后面。这里可以新增一个属性，用来控制下这里的显示效果

**Comment by KaneLeung** [comment]
原来如此，明白
