### ISSUE TITLE
评论 comment

### ISSUE THREAD

**Issue by xutian111** [arco-design/arco-design-vue#1833]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
csdn，和掘金的评论皆可收起

## 预期解决问题
可以收起嵌套的评论

**Comment by flsion** [comment]
折叠功能可以自己实现下，在嵌套 Comment 外增加一层 collapse 效果
