### ISSUE TITLE
开发模式下路由不会出现问题 ，但是构建时说 AppRouteRecordRaw 类型不匹配

### ISSUE THREAD

**Issue by Aichen517** [arco-design/arco-design-vue#1838]
![image](https://user-images.githubusercontent.com/76988466/200128974-979721e6-ff82-4a14-9b8f-5629aa6d3dde.png)
大家有遇到过吗 我刚从官网下拉也是能运行 但是不能构建

**Comment by hzgotb** [comment]
放一下 router/index.ts 的内容。

**Comment by Aichen517** [comment]
index.ts
![image](https://user-images.githubusercontent.com/76988466/203670346-6ebc04ff-ed5a-4f78-9b4f-7583e2cae04c.png)
base.ts
![image](https://user-images.githubusercontent.com/76988466/203670397-7b2419b6-7340-4f07-bd50-db843fb1b485.png)

**Comment by Aichen517** [comment]
> 放一下 router/index.ts 的内容。

index.ts

![image](https://user-images.githubusercontent.com/76988466/203670618-72085b18-a176-4e47-a9c3-02d07ca3d471.png)


base.ts

![image](https://user-images.githubusercontent.com/76988466/203670574-246461e7-b7bd-4f75-b136-fddba285e062.png)

**Comment by tazyong** [comment]
这是很普通的 ts 类型不兼容情况
要么把 `appRoutes`、`REDIRECT_MAIN`、`NOT_FOUND_ROUTE` 全部声明为 `RouteRecordRaw` 类型
要么在使用它们的时候，后面加个 `as RouteRecordRaw` 或者 `as any`

**Comment by Aichen517** [comment]
> 这是很普通的 ts 类型不兼容情况 要么把 `appRoutes`、`REDIRECT_MAIN`、`NOT_FOUND_ROUTE` 全部声明为 `RouteRecordRaw` 类型 要么在使用它们的时候，后面加个 `as RouteRecordRaw` 或者 `as any`

谢谢大佬 刚学的vue不是很熟练

**Comment by tazyong** [comment]
> > 这是很普通的 ts 类型不兼容情况 要么把 `appRoutes`、`REDIRECT_MAIN`、`NOT_FOUND_ROUTE` 全部声明为 `RouteRecordRaw` 类型 要么在使用它们的时候，后面加个 `as RouteRecordRaw` 或者 `as any`
> 
> 谢谢大佬 刚学的vue不是很熟练

这个跟 vue 没关系，是 typescript 的问题，只要开发 typescript 项目都会遇到的，无论是 vue、react、angular、nodejs 还是别的，学会看错误代码和描述，以后类似的问题都是一样处理就好了

**Comment by hzgotb** [comment]
> 这是很普通的 ts 类型不兼容情况 要么把 `appRoutes`、`REDIRECT_MAIN`、`NOT_FOUND_ROUTE` 全部声明为 `RouteRecordRaw` 类型 要么在使用它们的时候，后面加个 `as RouteRecordRaw` 或者 `as any`

as any 这样处理就 anyscript 了。这个问题就是类型冲突。仔细研究一下 interface 就能解决。
他项目就是由 arco-design-pro 创建的。而 `src/router/routes/types.ts` 的 `AppRouteRecordRaw` 本身就是为了 pro 项目的路由写的定义。后面他自己改了路由，有可能存在不适配。要做的事情不是去 anyscript 。而是找到不兼容的类型，或者是结合项目路由结构去修改 `AppRouteRecordRaw`
