### ISSUE TITLE
select 开启多选时会很卡，几十个数据就有卡顿，200多数据特别卡

### ISSUE THREAD

**Issue by zhonghuaifang** [arco-design/arco-design-vue#1844]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.1
- **框架版本:** Vue
- **浏览器版本:** chrome107.0.0.0

**Comment by czq297297** [comment]
最好给个复现地址

**Comment by zhonghuaifang** [comment]
这个不用复现，是一直存在的问题，官网用多选实例，加上虚拟列表就能看到卡顿的状态了，然后关闭多选，瞬间流畅
https://stackblitz.com/edit/angular-ftnp6s?file=src%2FApp.vue

**Comment by flsion** [comment]
@zhonghuaifang 大数据下可以开启虚拟列表 http://localhost:2233/vue/component/select#virtual-list。
https://codesandbox.io/s/fancy-night-br2rc0?file=/src/App.vue
