### ISSUE TITLE
日期范围（range-picker）组件时间默认值选择问题

### ISSUE THREAD

**Issue by Shiuwn** [arco-design/arco-design-vue#1850]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.2
- **框架版本:** vue 3.2.44
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://vue-fs41kh.stackblitz.io

## 预期结果
按照预期的默认值顺序
input 里面回填的结果 "XXXX-XX-XX 00:00:00" - “XXXX-XX-XX 23:59:59”

## 复现步骤
1，先点击“结束日期” input 框
![image](https://user-images.githubusercontent.com/11333822/201037899-9ca11c50-e2f6-4997-a9e0-fc07a868621f.png)

2，时间范围弹层出现后，任意选中一个开始日期
![image](https://user-images.githubusercontent.com/11333822/201037987-74c2c50c-8f46-4cae-b043-2fb63c7608f4.png)

3，选中一个结束日期，结束日期晚于开始日期
![image](https://user-images.githubusercontent.com/11333822/201038065-45298c6e-9ada-41a7-9fb8-0a3759540ab3.png)

4，input 里面回填的结果 “XXXX-XX-XX 23:59:59” - "XXXX-XX-XX 00:00:00"
![image](https://user-images.githubusercontent.com/11333822/201038124-141a8a28-0752-4aaf-ba8c-8ca41e8c754d.png)

**Comment by Panda2Chan** [comment]
同样的问题

**Comment by Panda2Chan** [comment]
> 

官网可以复现

**Comment by cyole** [comment]
same issue
