### ISSUE TITLE
Table 使用元素插槽时控制台会抛出[Vue warn]警告

### ISSUE THREAD

**Issue by DevilSpiderX** [arco-design/arco-design-vue#1851]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.2
- **框架版本:** Vue3.2.41
- **浏览器版本:** edge107.0.1418.35
- **复现地址:** https://codesandbox.io/s/amazing-mendel-zfbbwt?file=/src/App.vue

## 复现步骤
根据文档https://arco.design/vue/component/table#1.%20%E5%85%B3%E4%BA%8E%E5%85%83%E7%B4%A0%E6%8F%92%E6%A7%BD%E7%9A%84%E4%BD%BF%E7%94%A8 里的说明《1. 关于元素插槽的使用 例2》来使用Table的元素插槽时，控制台会抛出[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.

**Comment by flsion** [comment]
@DevilSpiderX 感谢反馈~ 检查了一下内部在调用时可以避免这个问题，这次会发版时会修复一下
