### ISSUE TITLE
table sticky-header 属性失效

### ISSUE THREAD

**Issue by Zhangbansen** [arco-design/arco-design-vue#1852]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.38.2
- **Browser:** chrome106.0.0.0

## What is expected?
解决表头不能吸顶问题

**Comment by hehehai** [comment]
@Zhangbansen hi, 提供个复线吧

**Comment by wcldyx** [comment]
> @Zhangbansen hi, 提供个复线吧

官方案例就是失效的

**Comment by eicoder** [comment]
> @Zhangbansen hi, 提供个复线吧
arco-table-header-sticky放在滚动组件内，滚动组件内有一层arco-scrollbar arco-scrollbar-type-embed与arco-table-header-sticky等高，导致sticky无法生效。将arco-table-header-sticky类放在滚动组件的那个容器上可以生效

**Comment by zhangzhenfei** [comment]
官方提供的案例无法生效

**Comment by phoock** [comment]
官方提供的案例无法生效

**Comment by NickZhangjin** [comment]
官方案例就是完美的复现

**Comment by leif0419** [comment]
还没解决方案吗

**Comment by eicoder** [comment]
> 还没解决方案吗

:has(> .arco-table-header-sticky) {
      position: sticky;
      top: 0;
      z-index: 100;
    }

**Comment by westng** [comment]
哥，这个修复了吗？
