### ISSUE TITLE
a-tag组件新增type属性以及shape属性

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#1854]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://tdesign.tencent.com/vue-next/components/tag

## What problem does this feature solve?
类似按钮一样，具有丰富的样式类型，还有形状

## Extra info
type属性 = 'default' |  'dark' | 'light' | 'outline' | 'light-outline'
参考：https://tdesign.tencent.com/vue-next/components/tag

shape属性  = square(默认)   |   round(圆角)    |    mark(半圆角)

color属性支持：primary | success | warning | danger 主题色
参考：https://www.antdv.com/components/tag-cn

可能会对现有样式存在破坏性更新，但是我感觉用户还是能接受的
color=red 跟 color=#f42424一样  默认改为dark样式，就是背景色为red，字体色为白色
如果想要字体为red色，背景为淡红色，那么把type改为light就行，这样可以对color进行样式类型统一，且破坏更新是比较低的方案

**Comment by hehehai** [comment]
@lin-97 hi，谢谢建议！这里更建议做自定义样式类来处理，Arco 的组件样式需要伴随生态的 UI&UX 等编码协调，期待下一个大版本吧。
