### ISSUE TITLE
select组件的option插槽不能加入tooltip组件

### ISSUE THREAD

**Issue by zhonghuaifang** [arco-design/arco-design-vue#1855]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.2
- **框架版本:** Vue
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://stackblitz.com/edit/angular-qnuj17?file=src%2FApp.vue

## 预期结果
有些选项过长的需要鼠标移上去提示完整信息

**Comment by hehehai** [comment]
@zhonghuaifang hi, 可以参考下面的写法。

```vue
<a-select :style="{ width: '320px' }" placeholder="Please select ...">
      <a-option>Beijing</a-option>
      <a-option>Shanghai</a-option>
      <a-option>
        <a-tooltip content="This is tooltip content">
          <span>Mouse over to display tooltip</span>
        </a-tooltip>
      </a-option>
      <a-option disabled>Disabled</a-option>
</a-select>
```

**Comment by zhonghuaifang** [comment]
> 



> @zhonghuaifang hi, 可以参考下面的写法。
> 
> ```
> <a-select :style="{ width: '320px' }" placeholder="Please select ...">
>       <a-option>Beijing</a-option>
>       <a-option>Shanghai</a-option>
>       <a-option>
>         <a-tooltip content="This is tooltip content">
>           <span>Mouse over to display tooltip</span>
>         </a-tooltip>
>       </a-option>
>       <a-option disabled>Disabled</a-option>
> </a-select>
> ```



> @zhonghuaifang hi, 可以参考下面的写法。
> 
> ```
> <a-select :style="{ width: '320px' }" placeholder="Please select ...">
>       <a-option>Beijing</a-option>
>       <a-option>Shanghai</a-option>
>       <a-option>
>         <a-tooltip content="This is tooltip content">
>           <span>Mouse over to display tooltip</span>
>         </a-tooltip>
>       </a-option>
>       <a-option disabled>Disabled</a-option>
> </a-select>
> ```
谢谢，可以了，之前也是这种写法没生效，刚知道tooltip组件内容必须用标签包裹

**Comment by zhonghuaifang** [comment]
> @zhonghuaifang hi, 可以参考下面的写法。
> 
> ```
> <a-select :style="{ width: '320px' }" placeholder="Please select ...">
>       <a-option>Beijing</a-option>
>       <a-option>Shanghai</a-option>
>       <a-option>
>         <a-tooltip content="This is tooltip content">
>           <span>Mouse over to display tooltip</span>
>         </a-tooltip>
>       </a-option>
>       <a-option disabled>Disabled</a-option>
> </a-select>
> ```

@hehehai 谢谢，可以了，之前也是这种写法没生效，刚知道tooltip组件内容必须用标签包裹
