### ISSUE TITLE
table组件闪动

### ISSUE THREAD

**Issue by loulangogogo** [arco-design/arco-design-vue#1856]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.38.1
- **Framework version:** vue3.2.44
- **Browser:** Edge

## Extra info
@arco-design/web-vue 2.37.2以及以上版本会出现这个问题，2.37.1以及以下没有问题

## What is expected?
正常滚动条不闪动

## Steps to reproduce
table如果设置了属性scroll之后，只要横向x轴的滚动条一出现，整个表格就会闪动不停。

**Comment by hehehai** [comment]
@LoulanGithub hi, 补充个复线或操作视频吧。
