### ISSUE TITLE
textarea组件当输满整行的时候，最后几个字会被字数限制挡住

### ISSUE THREAD

**Issue by HGJ0707** [arco-design/arco-design-vue#1861]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.3
- **框架版本:** Vue
- **浏览器版本:** chrome107.0.0.0

## 预期结果
输入的文字不会被字数限制提示遮住

**Comment by hehehai** [comment]
重复： #1545
