### ISSUE TITLE
DatePicker默认时间bug

### ISSUE THREAD

**Issue by Curtain11** [arco-design/arco-design-vue#1862]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.3
- **框架版本:** vue:  3.2.37
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://codesandbox.io/s/recursing-hertz-o9oo5l?file=/src/App.vue

## 复现步骤
点击DatePicker的前半部分
![image](https://user-images.githubusercontent.com/47772133/201818680-6376bb1f-5135-4981-a889-c09957e7b2f1.png)

先后选择11月15日与11月11日，给出的结果为：[ "2022-11-11 23:59:59", "2022-11-15 00:00:00" ]
![image](https://user-images.githubusercontent.com/47772133/201818624-accba75c-ff89-476e-86a1-d5e6246f7715.png)

## 预期结果
输出结果为[ "2022-11-11 00:00:00", "2022-11-15 23:59:59" ]

**Comment by tazyong** [comment]
看了源码的处理逻辑，默认值是按顺序先赋到范围选择器中的，并不是选择完日期再加上时间值的，所以后续无论怎么操作，第一个选择的日期肯定会和第一个时间值合成值，最后再排序组合成后的值的顺序。导致结果不一致无法避免，你在你的例子上加上 showTime 属性可以看出选择过程的处理。
![image](https://user-images.githubusercontent.com/24738011/202115104-ebd7b869-8477-4fed-a1ca-e61065d757ae.png)

这个 bug 应该不会在中小版本修复，因为会改动很多相当于重构，而且目前没有很好的设计支持。
建议还是自行处理，例如：
https://codesandbox.io/s/clever-aj-u04bpj?file=/src/App.vue

如果业务中有很多需要这样处理的，可以考虑二次封装组件。
