### ISSUE TITLE
Vue版本为什么没提供CDN方式，只有react版本提供了

### ISSUE THREAD

**Issue by ysysdzz** [arco-design/arco-design-vue#1865]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
react版本有提供cdn引入方式

## What problem does this feature solve?
希望能提供vue的cdn版本，方便后端开发使用

**Comment by kkkisme** [comment]
https://unpkg.com/browse/@arco-design/web-vue@2.38.3/dist/
这个应该可以，国内似乎也能用

**Comment by w-e-i** [comment]
https://www.jsdelivr.com/package/npm/@arco-design/web-vue?path=dist
