### ISSUE TITLE
tabs组件通过:default-active-key或:active-key设置选中的标签时，active-key指定的tab可以出现在tab栏可视范围内

### ISSUE THREAD

**Issue by youhuan** [arco-design/arco-design-vue#1867]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
https://stackblitz.com/edit/angular-zogjng?file=src%2FApp.vue
页面有12个tab，:active-key设置为第10个tab时，tab 10没出现到可视范围内，必须通过多次点击tab栏的右箭头才能将tab 10切换可视范围内

**Comment by Saber-Kurama** [comment]
可以等tabs渲染完成后再设置 activeKey 的值
好像是activeKey此时还不知道是否要出现滚动，是按照没有出现滚动处理的

```
const activeKey = `ref("0");`
setTimeout(() => {
  activeKey.value = "11";
}, 0);
```

**Comment by youhuan** [comment]
好的，我试试，多谢
