### ISSUE TITLE
upload组件image-preview属性错误

### ISSUE THREAD

**Issue by maopixin** [arco-design/arco-design-vue#1869]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.38.3
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://codesandbox.io/s/prod-architecture-2yhcby

## 额外补充
真实项目   是使用的快速上手中的按需加载（模板）方式

## 预期结果
1. 去掉image-perview时，页面上不展示眼睛图标
2. 加上image-perview 可以正常查看大图

## 复现步骤
1. 去掉image-perview属性
2. 元素上还会有眼睛图标，点击无效（在我们的项目里面就算加上image-perview属性，点击眼睛也无法查看大图）

**Comment by MrWeilian** [comment]
> 

你好，请问一下：“在我们的项目里面就算加上image-perview属性，点击眼睛也无法查看大图” 这个怎么复现，有链接提供吗～

**Comment by flsion** [comment]
@maopixin @MrWeilian 你好，这是个组件的历史遗留问题，初始时，upload 组件仅显示“眼睛”图标，需要用户自己监听 on-preview 事件打开浏览。在后面的版本增加内置了图片预览并增加了 image-preview 属性，所以这个属性仅控制是否启用内置的图片预览，不会影响“眼睛”图片的显示。新版本会增加一个 showPreviewButton 属性，用来控制图标的显示
