### ISSUE TITLE
【Discuss】关于table的筛选图标，是不是靠左对齐比较好

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#187]
### 现状
目前筛选图标是最靠右，效果上反而更像是右边那列的筛选选项，特别是列宽越多这种情况越明显，是不是可以改成靠左对齐会好一点(比如element是靠左)，或者设置成可配置靠左靠右的

### 截图对比
arco-table
![image](https://user-images.githubusercontent.com/93666053/142395885-7b011860-4303-4558-8d26-c3c67862bb7e.png)

element-table
![image](https://user-images.githubusercontent.com/93666053/142395635-319a76df-ab8d-4663-a66b-29c7a14b011f.png)

**Comment by Flsion** [comment]
@seepine 好的，这里可以加个属性控制一下

**Comment by Flsion** [comment]
目前图标的选中效果，直接移到左边会比较奇怪，2.7版本先不添加这个功能，我尝试修改一下放到左边的效果，ok后添加上

**Comment by seepine** [comment]
还没结果吗，要不然我关闭工单了，毕竟这个问题筛选根本不能用，我们已经全改成搜索的形式了

**Comment by Flsion** [comment]
不好意思，这个功能会添加，下个版本优先处理下
