### ISSUE TITLE
【BUG】【tree】关于auto-expand-parent与expanded-keys属性冲突问题

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#1870]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.38.3
- **Browser:** chrome107.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/angular-hkvfet?file=src%2FApp.vue

## 
`auto-expand-parent`为自动展开已展开节点的父节点
`expanded-keys`表示展开节点

那么当`expanded-keys`只有子节点时，树展示上不应该也把其父节点也展开吗

代码如下

```vue
<template>
  <a-tree :data="treeData" v-model:expanded-keys="expandedKeys" />
</template>
<script setup>
import { ref } from 'vue';
const treeData = [
  {
    title: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Branch 0-0-0',
        key: '0-0-0',
        children: [
          {
            title: 'Leaf',
            key: '0-0-0-0',
          },
          {
            title: 'Leaf',
            key: '0-0-0-1',
          },
        ],
      }
    ],
  },
];

const expandedKeys = ref([]);
setTimeout(() => {
  expandedKeys.value = ['0-0-0'];  // 不会展开
  expandedKeys.value = ['0-0', '0-0-0'];  // 才会展开
}, 1000);
</script>

```

## What is expected?

希望能父节点也随之展开

**Comment by hehehai** [comment]
@seepine hi, `auto-expand-parent` 目前仅在首次执行

**Comment by Mr54233** [comment]
现在的auto-expand-parent默认是true了，使用expanded-keys依然无法自动展开父节点
