### ISSUE TITLE
手动将radio group组件重置，radio的高亮依旧存在

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-vue#1871]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.38.3
- **Framework version:** vue
- **Browser:** chrome107.0.0.0

## Steps to reproduce
v-model="form.deviceTag"
formEl.value.resetFields(['deviceTag']);

**Comment by flsion** [comment]
@ZhangTomLiang 2.39.0 版本可以尝试一下 https://codesandbox.io/s/silent-cherry-x674kd
