### ISSUE TITLE
select组件设置unmountOnClose为true后v-model将失效

### ISSUE THREAD

**Issue by bbfpl** [arco-design/arco-design-vue#1874]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **浏览器版本:** firefox107.0
- **框架版本:** vue3
- **依赖包名 及 版本:** @arco-design/web-vue@2.39.0

## 复现步骤
给a-select添加:unmountOnClose="true"后v-model="value"渲染的是value的值 而不是lable

**Comment by luckyship** [comment]
好像无法复现，能给个例子嘛

**Comment by tazyong** [comment]
表现正常，没到遇到你描述的问题
https://codesandbox.io/s/quirky-butterfly-u5w8d0?file=/src/App.vue

**Comment by flsion** [comment]
@bbfpl 设置unmountOnClose为true后需要通过 `options` 参数传入数据，不再支持模板数据的方式。这个是由模板数据的捕获方法导致的，如果不在DOM中显示是无法捕获到数据的
