### ISSUE TITLE
Pagination分页不支持google的SEO

### ISSUE THREAD

**Issue by guozhaomin** [arco-design/arco-design-vue#1875]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
希望能兼容google的seo，提供<a href= >，在可见的没一个按钮的时候。例如可见1、2、3...99，那么允许动态填充对应地址
<a href="/list/2.html">2</a>
<a href="/list/3.html">3</a>
...
<a href="/list/99.html">99</a>

## What problem does this feature solve?
目前acro的Pagination分页用的是js形式实现页面跳转，而不是谷歌爬虫预期识别的按扭上的<a href= >，所以无法实现google的SEO

**Comment by flsion** [comment]
@guozhaomin 这个功能可以通过自定义 page-item 实现，可以参考下 https://codesandbox.io/s/late-moon-bjoxrd
