### ISSUE TITLE
Table @select-all 方法可不可以加上 selectedRows, changeRows这种有关此操作被选中行信息的参数呢

### ISSUE THREAD

**Issue by sulimi** [arco-design/arco-design-vue#1877]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
像ant design vue 那样
https://antdv.com/components/table-cn
onSelectAll	用户手动选择/取消选择所有列的回调	Function(selected, selectedRows, changeRows)	

## What problem does this feature solve?
const onSelectedAll = (checked: boolean, records: Stock[]) => {
  // 选中加购物车
  commit('addBagData', records);
};

**Comment by Chanzhaoyu** [comment]
话说这个有什么应用场景吗？我觉得这应该就和你写的代码一样的效果了吧

```
const onSelectedAll = (checked: boolean) => {
   commit('addBagData', checked ? data.filter((item) => !item.disabled) : [])
}
```

**Comment by sulimi** [comment]
@Chanzhaoyu 您好，这个场景是：有多个表格，每个表格用的不是同一个data，但是要同时加入同一个购物车。
然后考虑的点是：
1、如果用filter item.disabled的话，filter出来后，加购肯定是不能直接覆盖，只能push。push后得去对比一下哪些已经存在购物车中，或者去重；
2、表格的data是前端分页的，数据量大的话循环data又循环购物车感觉不太好（不过这个确实可以后台分页）。
所以就产生一个偷懒的幻想：能不能给一批全选按钮操作到的changeRows，或许这个issues表达的不是很准确，大概就是这样。或者还有什么我没有想到的方法呢？？？

**Comment by tazyong** [comment]
一个 watch selectedKeys 就能搞定了
