### ISSUE TITLE
Trigger、 Popover、Select等弹出框组件可以添加一个 是否添加遮罩层 参数吗？以供用户点击其他地方只关闭弹出框而不触发其他事件

### ISSUE THREAD

**Issue by fiveo0** [arco-design/arco-design-vue#1878]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.0
- **Browser:** chrome107.0.0.0

**Comment by yuhan0709** [comment]
抱歉，不太符合通用逻辑所以不会支持。
Popover，Trigger 这种组件本身只是一个弹出提示的作用，Select 也是个表单元素。
