### ISSUE TITLE
构建时类型报错

### ISSUE THREAD

**Issue by AgoniNemo** [arco-design/arco-design-vue#1880]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.0
- **Framework version:** vue 3.2.37
- **Browser:** chrome107.0.0.0

## What is expected?
正常构建

## Steps to reproduce
打包报错，运行正常
```
Type '(value: number, ev: Event) => void' is not assignable to type '(value: string | number | Record<string, any> | undefined, ev: Event) => any'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'string | number | Record<string, any> | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.

               <a-dropdown @select="handleSelect">
```

```
const handleSelect = (value:number,ev:Event) => {
}
```

官方的 `union` 类型怎么使用

![image](https://user-images.githubusercontent.com/13228978/203504554-03f97a20-1215-4ee9-83cc-3914600c52b4.png)

**Comment by hzgotb** [comment]
Dropdown的onSelect的定义是这样的。
https://github.com/arco-design/arco-design-vue/blob/c7e1ae3a642dfff210376143a1d4343f15d332d7/packages/web-vue/components/dropdown/dropdown.vue#L97-L106

你只要将 `value:number` 改成 `value?:number` 就可以了。

**Comment by tazyong** [comment]
`value: number` 改成 `value: any` 即可，这个是 vue 的问题，和组件库没太大关系，目前无完美解决方案

```ts
const handleSelect = (value: any, ev: Event) => {
}
```

**Comment by hzgotb** [comment]
> `value: number` 改成 `value: any` 即可，这个是 vue 的问题，和组件库没太大关系，目前无完美解决方案
> 
> ```ts
> const handleSelect = (value: any, ev: Event) => {
> }
> ```

没看出来是vue的问题。。说一下？

**Comment by tazyong** [comment]
> > `value: number` 改成 `value: any` 即可，这个是 vue 的问题，和组件库没太大关系，目前无完美解决方案
> > ```ts
> > const handleSelect = (value: any, ev: Event) => {
> > }
> > ```
> 
> 没看出来是vue的问题。。说一下？

抱歉！我说得不严谨，不是 vue 的问题，只是 vue 的事件无法支持定义以下类型，
如：onSelect 的类型应该为
`(value: string | number | Record<string, any> | undefined, ev: Event)) => void`
`(value: string, ev: Event) => void`
`(value: number, ev: Event) => void`
`(value: Record<string, any>, ev: Event) => void`
`(value: undefined, ev: Event) => void`

这样才能支持楼主的用法

```ts
const handleSelect = (value: number, ev: Event) => {
}
```

**Comment by AgoniNemo** [comment]
解决方案：

```
const handleSelect = (value:any,ev:Event) => {
const val = value as number
}
```
