### ISSUE TITLE
2.39 升级版本后打包异常 _@arco-design_web-vue@2.39.0@/@arco-design 路径不存在

### ISSUE THREAD

**Issue by lirongzhu** [arco-design/arco-design-vue#1881]
![image](https://user-images.githubusercontent.com/8097432/203505082-8ad23b2f-80a2-4dd0-89cc-4898f7e3ae5b.png)
![image](https://user-images.githubusercontent.com/8097432/203505438-2c920a3d-652e-48e8-b074-9f05f21d58ba.png)
实际路径为：_@arco-design_web-vue@2.39.0@@arco-design
这个怎么处理？

**Comment by flsion** [comment]
@lirongzhu 这个应该是构建工具配置的问题，没有匹配到对应的包，可以检查一下

**Comment by xiatianFun** [comment]
请问解决了吗
