### ISSUE TITLE
Design Lab 中主题编辑器 颜色选择器卡死。

### ISSUE THREAD

**Issue by popdo** [arco-design/arco-design-vue#1886]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.0
- **Framework version:** vue 3.25+ 
- **Browser:** Microsoft Edge 版本 107.0.1418.56 (正式版本) (x86_64)

## Steps to reproduce

Design Lab 中的主题编辑器 颜色选择器无法正常工作，一选颜色，颜色选择器就直接卡死，完全没有办法正常使用，只能从外面配置好颜色，再输入颜色值！ 我电脑系统是macos 13.0.1、浏览器是Microsoft Edge 版本 107.0.1418.56 (正式版本) (x86_64)

![](https://files.catbox.moe/is7r8y.png)

**Comment by sHow8e** [comment]
@popdo hihi 可以尝试换一下Chrome再进行使用。

**Comment by popdo** [comment]
@sHow8e 一样的。chrome也是一样的情况，点击一个颜色有2-3秒延迟 颜色滑块根本无法拖动！

**Comment by hehehai** [comment]
@popdo hi, 这个到飞书群反馈吧，谢谢
![飞书20221212-111612](https://user-images.githubusercontent.com/12692552/206953425-79c93b21-abe5-4535-8939-17e0f567f9af.png)
