### ISSUE TITLE
组件按需引入无效！！！

### ISSUE THREAD

**Issue by popdo** [arco-design/arco-design-vue#1891]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.0
- **Framework version:** vue 3.2.45
- **Browser:** chrome93.0.4577.63
- **Reproduction Link:** https://arco.design/vue/docs/start#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD%EF%BC%88%E6%A8%A1%E6%9D%BF%EF%BC%89

## Steps to reproduce
按照官方文档的 “按需加载（模板）” 的方法配置后。没用到的组件css样式一样被引入进去。最后npm build出来的css也是全部组件的样式代码。

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite';
import { ArcoResolver } from 'unplugin-vue-components/resolvers';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    AutoImport({
      resolvers: [ArcoResolver()],
    }),
    Components({
      resolvers: [
        ArcoResolver({
          sideEffect: true
        })
      ]
    })
  ]
});
```

是我哪里没有配置对吗？

**Comment by tazyong** [comment]
使用 [@arco-plugins/vite-vue](https://github.com/arco-design/arco-plugins) 官方插件来处理按需要导入，如果问题已解决请关闭 issue 吧
