### ISSUE TITLE
table组件滚动条样式bug

### ISSUE THREAD

**Issue by Curtain11** [arco-design/arco-design-vue#1894]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.39.1
- **框架版本:** vue 3.2.33
- **浏览器版本:** chrome107.0.0.0
- **复现地址:** https://codesandbox.io/s/still-forest-967ppg?file=/src/App.vue:11-41

## 预期结果
滚动条隐藏

## 复现步骤
当table设置bordered="false"时，如果columns中有fixed为right的项，表头部分会出现竖向的滚动条
![image](https://user-images.githubusercontent.com/47772133/204218397-61beb379-a437-4fda-9c6f-de0b1000c725.png)

**Comment by Curtain11** [comment]
补充一下，当同时出现scroll="{ minWidth: 600 }"，:bordered="false"，以及columns中有fixed: "right"时，这个滚动条就会出现

**Comment by yuyachong** [comment]
![image](https://user-images.githubusercontent.com/73475361/206980116-78d4191d-626a-4096-a122-456a7acf7c2e.png)

"@arco-design/web-vue": "^2.40.0"

**Comment by yuyachong** [comment]
style="height: 800px"，:scroll="{x: '100%', y: '100%'}"
