### ISSUE TITLE
vue版本分页组件的previous、next、total等可以自定义组件顺序么？

### ISSUE THREAD

**Issue by alittlesister** [arco-design/arco-design-vue#1895]
vue版本分页组件的previous、next、total等可以自定义组件顺序么？

**Comment by baiwusanyu-c** [comment]
![image](https://user-images.githubusercontent.com/32354856/204414885-dfcf48be-1a7e-4f8c-baa9-d7662748aaa3.png)
You can use slots to achieve

**Comment by flsion** [comment]
@alittlesister 你好，Pagination 组件中这些内容的顺序是固定的，无法自定义顺序
