### ISSUE TITLE
a-tree组件，某个节点，disable状态下，子节点选中，父节点状态是未选中状态，更无半选状态

### ISSUE THREAD

**Issue by wangziqin123** [arco-design/arco-design-vue#1902]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.1
- **Browser:** chrome107.0.0.0
- **Reproduction Link:** https://arco.design/vue/component/tree#checkable

## What is expected?
https://user-images.githubusercontent.com/20764518/198926067-3a6097aa-a867-4804-9a94-e49fdba152ce.png
此处应该是半选，除此之外，如果全是disable状态的话，子节点默认全部设置了选中状态后，父节点也无全选状态哦

## Steps to reproduce
a-tree组件，某个节点，disable状态下，子节点选中，父节点状态是未选中状态，更无半选状态

**Comment by hehehai** [comment]
重复：#1756
