### ISSUE TITLE
数据穿梭框 Transfer 能否增加 自由移动 选择的顺序

### ISSUE THREAD

**Issue by deluxebear** [arco-design/arco-design-vue#1908]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
如图

![updown](https://user-images.githubusercontent.com/485793/205247178-0617b3f7-618f-4bde-aeac-1ec0bc8f36d3.png)

## 预期解决问题
在 Transfer 右边，增加向上和向下的箭头，选择一个值后可以将其往下排列或者往上排列

**Comment by hehehai** [comment]
重复：#1502
