### ISSUE TITLE
Form 中Input使用allow-clear，清空操作不会触发validator自定义校验规则

### ISSUE THREAD

**Issue by sulimi** [arco-design/arco-design-vue#1911]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
**依赖包名 及 版本:** "@arco-design/web-vue": "^2.39.0"
**框架版本:** "vue": "3.2.45"
**复现地址:** https://codesandbox.io/s/damp-glitter-h935dq

## 预期结果
非必填项，在输入错误，出现提示的情况下，清空输入内容，想要错误提示消失。

## 复现步骤
  
![image](https://user-images.githubusercontent.com/63625158/205263246-62a74ee5-b76e-4932-9ee7-d211809e3dd3.png)
![image](https://user-images.githubusercontent.com/63625158/205263313-86229bba-126d-4638-ab25-79244f1d22c9.png)
![image](https://user-images.githubusercontent.com/63625158/205263715-92134598-f5c1-46ae-a23f-7e570a9d066c.png)
![image](https://user-images.githubusercontent.com/63625158/205264605-60bbb903-669e-4015-a432-af4190375b57.png)

**Comment by flsion** [comment]
@sulimi 这个是因为 input 组件 change 事件设计的原因产生的，如果 input 在 blur 后发现 value 与 focus 时没有发生改变，不会触发 change 事件，导致这里没有再触发校验功能。如果需要兼容这个场景，可以给 clear 事件上增加下 form 校验的调用

**Comment by tazyong** [comment]
这里的 Input 组件的清除功能有逻辑问题，已经修复，等下个版本更新吧。
当前版本可以先把光标移开触发 blur 事件再点击清除也能正常表现。

**Comment by lq9958** [comment]
请问自定义表单校验器如何写呢？和element-ui一样吗？试了一下好像不太行啊
