### ISSUE TITLE
i18n西班牙语等其他国家语言支持

### ISSUE THREAD

**Issue by clark-tan** [arco-design/arco-design-vue#1915]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
ant-design支持大部分语言

## What problem does this feature solve?
目前支持的语言太少了，国际化系统使用支持度不够高

**Comment by hehehai** [comment]
🥰 欢迎提供更多语言支持，可以参考 ArcoReact 提交 PR 哦 👋。

**Comment by yinkaihui** [comment]
#2011

**Comment by Sevenposs** [comment]
问一下哈：目前支持的语言太少，如何手动自己翻译后给项目中加上，并且如何引用生效？
