### ISSUE TITLE
nuxt3.0 如使用arco组件 打开浏览器 f12  无法展示文字

### ISSUE THREAD

**Issue by Yacj** [arco-design/arco-design-vue#1924]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.2
- **Framework version:** 2.39.2
- **Browser:** chrome107.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/nuxt-starter-jcm2eu?file=package.json,app.vue

## What is expected?
element 组件是可以展示 不知道是配置问题 还是 代码问题 arco也应该正常显示

## Steps to reproduce
 1 nuxt3.0 配置好 arco 运行 
2 打开浏览器 f12 如果是原生div包裹的会有文字 如果是 arco组件包裹的 比如 card tab 文字 无法展示

**Comment by hehehai** [comment]
@Yacj hi, 这里应该是使用方式的问题，看到控制台显示，并没有找到 `a-card` 组件，也就是在服务端没渲染出来

```vue
<template>
  <div>
    <Card>arco组件</Card>
    <div>原生div</div>
  </div>
</template>

<script lang="ts" setup>
import { Card } from '@arco-design/web-vue';
</script>
```

我尝试这样直接使用是正常的。

**Comment by Yacj** [comment]
可以了 请问下 官方 能不能在文档出一个nuxt使用规范或教程  有 全局引用  自动引用这些 element naiveui都有

**Comment by hehehai** [comment]
@Yacj 嗯，是的 ArcoVue 在 Nuxt 中的部门组件支持有问题，且相关也文档较少，但目前 Nuxt 相关问题的处理优先级不高，也更期待社区有更多的使用反馈与技巧分享。

**Comment by Yacj** [comment]
> @Yacj  请问你是如何解决的？？我也出现了这种情况，yarn build 后 然后运行 node .output/server/index.mjs，浏览器查看网页源代码，使用arco组件的没有在服务端渲染出来！
> 我的arco使用，配置是（ ./plugins/arco.ts ）：
> `import ArcoVue from '@arco-design/web-vue';
> import { Message, Notification } from '@arco-design/web-vue';
> import '@arco-design/web-vue/dist/arco.css';
> 
> export default defineNuxtPlugin((app) => {
>   app.vueApp.use(ArcoVue);
>   return {
>     provide: {
>       message: Message,
>       notification: Notification,
>     },
>   };
> })`
我这边 按照上面的 在页面引入组件调用 不是自动引入 就是可以展示 但是message dialog 这种没试过

**Comment by Yacj** [comment]
@lvreninfo 我这边按照上面的提示 
在单独的页面import组件 不是自动引入
就有html 但 message dialog 这种没试过
