### ISSUE TITLE
input组件word-length计算字符的长度不会被max-length限制

### ISSUE THREAD

**Issue by lbczbl** [arco-design/arco-design-vue#1926]
## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.27.1
- **框架版本:** ^3.2.25
- **浏览器版本:** chrome98.0.4758.9
- **复现地址:** https://codesandbox.io/s/magical-bash-1iw5wj?file=/src/App.vue

## 额外补充
代码https://github.com/arco-design/arco-design-vue/blob/afcb25edb9c7a4aad32b42647f2614b7184357ec/packages/web-vue/components/input/input.tsx#L339

```
const handleInput = (e: Event) => {
      const { value } = e.target as HTMLInputElement;

      if (!isComposition.value) {
        if (
          maxLength.value &&
          !maxLengthErrorOnly.value &&
          computedValue.value.length >= maxLength.value &&
          getValueLength(value) > maxLength.value &&
          (e as InputEvent).inputType === 'insertText'
        ) {
          keepControl();
          return;
        }
        updateValue(value);
        emit('input', value, e);
        eventHandlers.value?.onInput?.(e);
        keepControl();
      }
    };
```
这里判断条件computedValue即v-model传递的value长度也要大于最大长度才成立，而getValueLength才是自己写的长度计算方法得到的值，这样的话word-length这个属性就没什么用

## 预期结果
超出长度限制后不能再输入

## 复现步骤
需求是限制字数不能超过8个汉字或16个字母，用word-length计算字符把一个汉字长度等于两个字母
在输入框输入汉字

**Comment by Zz-ZzzZ** [comment]
#1942

**Comment by Saber-Kurama** [comment]
自定义 `wordSlice` 还是得配合`wordSlice` 一起使用

**Comment by Zz-ZzzZ** [comment]
@Saber-Kurama 老哥和我的pr冲突了，刚在你不久前提交

**Comment by Saber-Kurama** [comment]
@Zz-ZzzZ   很奇怪我pull的时候 ，还特意看了一下这个 issue ，没有看到才提pr的

**Comment by Saber-Kurama** [comment]
@Zz-ZzzZ 你遗留了一处没有修改，并且我个人认为应该用 `valueLength.value` 来判断

**Comment by Saber-Kurama** [comment]
@Zz-ZzzZ  我已经关闭了我的pr了， 你可以关联到这个issue上

**Comment by Zz-ZzzZ** [comment]
@Saber-Kurama 已关联
