### ISSUE TITLE
tabs建议竖向支持高度撑满

### ISSUE THREAD

**Issue by yuyachong** [arco-design/arco-design-vue#1933]
`a-tabs style=height:100%

style
.arco-tabs-content {
overflow: auto;
}`

建议增加竖向高度撑满，可以满足一些场景需要tab内容出现滚动条

**Comment by hehehai** [comment]
@yuyachong hi，这里更建议在 tab-content 里做容器元素自己处理（可以使用 https://arco.design/vue/component/scrollbar）

**Comment by yuyachong** [comment]
> @yuyachong hi，这里更建议在 tab-content 里做容器元素自己处理（可以使用 [https://arco.design/vue/component/scrollbar）](https://arco.design/vue/component/scrollbar%EF%BC%89)

好的， 建议scrollbar其他组件能使用上，  形成统一
