### ISSUE TITLE
手动将a-checkbox-group组件绑定的值重置，checkbox的高亮依旧存在

### ISSUE THREAD

**Issue by moomhub** [arco-design/arco-design-vue#1939]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.40.0
- **框架版本:** vue@3.2.0
- **浏览器版本:** chrome108.0.0.0
- **复现地址:** https://codesandbox.io/s/arco-checkbox-r8x4jt

## 预期结果
重置a-checkbox-group组件，关联高亮取消

**Comment by hehehai** [comment]
可能是这里的判断问题: https://github.com/arco-design/arco-design-vue/blob/87f2e933342d45850a3e58aff37e46d04e89bd5f/packages/web-vue/components/checkbox/checkbox-group.tsx#L146-L153
