### ISSUE TITLE
建议datePicker增加一个editable属性

### ISSUE THREAD

**Issue by GarlandQian** [arco-design/arco-design-vue#1946]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://element-plus.gitee.io/zh-CN/component/date-picker.html

## 预期解决问题
datePicker组件readonly属性可以使input输入框无法选中但此属性也会导致选择器的trigger无法弹出，新增的属性能控制用户只使用选择的值，而不会填写不符合规范的值。elementPlus组件是有此属性的。

**Comment by kaikaibenkai** [comment]
@GarlandQian #2072 实现了这个功能，可以参考一下

**Comment by GarlandQian** [comment]
@kaikaibenkai 看了下我的应用场景和你一致，也是在移动端。希望官方能加下这个属性吧，蛮有用的
