### ISSUE TITLE
input search组件，在失去焦点时会触发change事件

### ISSUE THREAD

**Issue by abnereel** [arco-design/arco-design-vue#1954]
<a-input-search  />组件在失去焦点时会触发change事件，实际上并未输入任何内容，仅仅是获取焦点以及失去焦点，按理来说未更改内容不应该触发change事件，在2.39.1版本是正常的，更新到2.40.0版本发现了该问题。

**Comment by abnereel** [comment]
初始情况下不会出现上面这个情况，在输入一些内容，然后清理掉内容之后，再获取焦点、失去焦点，就会触发change事件

**Comment by flsion** [comment]
@abnereel 2.40.1 版本修复了 input change 事件的问题。
