### ISSUE TITLE
Notification的footer vnode渲染button组件

### ISSUE THREAD

**Issue by clark-tan** [arco-design/arco-design-vue#1966]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.40.0
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/still-surf-eiqpzg?file=/src/App.vue

## What is expected?
希望可以在Notification的footer渲染button组件

## Steps to reproduce
 const handleNotification = () => {
   const id = `${Date.now()}`;
   const closeNotification =  Notification.error({
     id,
     title:'Notification',
     content:'This is a notification!',
     duration: 0,
     footer: h => {
          return h(
            'a-button',
            {
              props: {
                type: 'primary',
                size: 'small',
              },
              on: {
                click:  () => Notification.remove(id),
              },
            },
            'Confirm',
          );
     },
  });
}

**Comment by flsion** [comment]
@clark-tan 
![image](https://user-images.githubusercontent.com/29793175/208038914-008e6ca6-4a8e-4e2e-9cc8-aad4fce5a09b.png)
h函数直接传入 Button 组件就可以
