### ISSUE TITLE
tabs组件在设置了:hide-content="true"  :justify="true" .arco-tabs-nav元素不会撑满tabs高度

### ISSUE THREAD

**Issue by sakura-he** [arco-design/arco-design-vue#1967]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.40.0
- **Framework version:** vue3.2
- **Browser:** chrome102.0.0.0

## What is expected?
当设置了hide-content='true'时 .arco-tabs-nav 元素希望加个flex-grow:1; 让tab栏拉伸为.arco-tabs高度

## Steps to reproduce
:hide-content="true"  :justify="true"

**Comment by flsion** [comment]
@sakura-he `justify` 属性是给 pane 面板撑满高度使用的，tabs-nav 有自己的高度和 size 属性控制，撑满高度会破坏组件的展示样式。如果有相应的需求可以自己覆盖下组件的样式处理
