### ISSUE TITLE
Table组件中TableColumnData[]类型有关columns预料之外的类型错误提示

### ISSUE THREAD

**Issue by 379949990** [arco-design/arco-design-vue#1968]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Framework version:** "vue": "^3.2.40",
- **Browser:** 108.0.5359.98（正式版本） (x86_64)

## Extra info
一个复现问题的最简单的组件（可直接替换arco-design-pro-vue简单版项目中src/views/dashboard/workplace/index.vue的内容以快速复现问题）：
``` javascript
<template>
  <div class="container">
    <a-table :columns="columns" :data="tableData" :bordered="false"> </a-table>
  </div>
</template>

<script lang="ts" setup>
  const columns = [
    {
      title: '名称',
      dataIndex: 'name',
      align: 'center',
    },
    {
      title: '昨天',
      dataIndex: 'lastDay',
      align: 'center',
    },
    {
      title: '较前日',
      dataIndex: 'lastChange',
      align: 'center',
    },
  ];
  const tableData = [
    { name: '牛只总数', lastDay: 231, lastChange: ' 23' },
    { name: '犊牛', lastDay: 232, lastChange: ' 23' },
    { name: '育成牛', lastDay: 231, lastChange: '0' },
    { name: '青年牛', lastDay: 231, lastChange: '-23' },
    { name: '涌乳牛', lastDay: 231, lastChange: ' 23' },
    { name: '干奶牛', lastDay: 231, lastChange: ' 23' },
  ];
</script>

<script lang="ts">
  export default {
    name: 'Dashboard',
  };
</script>
```

## Steps to reproduce
- 通过cli创建一个arco-design-pro-vue简单版项目；
- 创建一个基础的Table组件；
- columns中添加“align: 'center'”配置，Table的columns属性将会提示类型错误：
    ->“不能将类型“{ title: string; dataIndex: string; align: string; }[]”分配给类型“TableColumnData[]”。 不能将类型“{ title: string; dataIndex: string; align: string; }”分配给类型“TableColumnData”。”
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/66375788/208222188-7c8c6b7a-aa98-42cf-ae1d-9ed962f2fc8e.png">

- 运行“yarn build”进行构建时会抛出更明确的错误提示：
    -> Types of property 'align' are incompatible.
        Type 'string' is not assignable to type '"center" | "left" | "right" | undefined'.

**Comment by Aganxx** [comment]
const columns: TableColumnData[] = []
需要给他一个类型，这个是类型是框架自带的。

**Comment by 0xSa9** [comment]
如楼上所说就可以解决，不过别忘了导入。
  import { TableColumnData } from '@arco-design/web-vue';
