### ISSUE TITLE
【bug】form / textarea 不进行二次验证

### ISSUE THREAD

**Issue by kaikaibenkai** [arco-design/arco-design-vue#1976]
## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.39.2
- **框架版本:** Vue 3.2.45
- **浏览器版本:** chrome108.0.0.0
- **复现地址:** https://stackblitz.com/edit/angular-uy74wr?file=src%2FApp.vue

## 预期结果
正确输入 Q2 后可以正常提交。

## 复现步骤
1. 输入年龄
2. 在 Q1 中输入几个字，Q2 留空
3. 点击提交，发现 Q2 显示“本项必填”（到这里很正常）
4. 在 Q2 中输入几个字
5. 点击提交，发现还显示“本项必填” **（与预期不一致）**

![20221220081235_rec_](https://user-images.githubusercontent.com/99722991/208552138-5ce2601b-55cd-4a5d-acc4-213a79a58209.gif)

**Comment by kaikaibenkai** [comment]
抱歉，Vue 基础不牢忙，忘记了

**Comment by kaikaibenkai** [comment]
@Artsmp 感谢您的解答

**Comment by Artsmp** [comment]
> @Artsmp 感谢您的解答

小事情啦~~不用客气
