### ISSUE TITLE
a-radio-group 组件，当 v-model 设置为 null 时，组件依然保持之前的选中状态

### ISSUE THREAD

**Issue by FullStackPlayer** [arco-design/arco-design-vue#1979]
vue 版本：3.2.28
@arco-design/web-vue 版本：2.37.2

------------------------------------------------------------

当前的处理方案，v-model 的值指定为 '' 空字符串可以解决这个问题，但是其它组件 v-model 为 null 时都会呈现初始状态，建议 a-radio-group 组件与其它在行为上保持一致。

**Comment by flsion** [comment]
@FullStackPlayer 可以升级到 2.38.1 版本以上，有解决这个问题
