### ISSUE TITLE
upload组件清空所选的文件

### ISSUE THREAD

**Issue by HeiShuXianSheng** [arco-design/arco-design-vue#1982]
场景：

第一步，选择一次文件，此时upload展示所选的所有文件；
第二步，再选择一次文件，此时清空第一次选择的全部文件，只展示第二步选择的所有文件；

官方有支持这个方法吗？或者这个问题可以简化成upload有清空文件的api吗？

**Comment by yuhan0709** [comment]
通过重置 `file-list` 去处理，可以看下这个例子：
https://codesandbox.io/s/dreamy-tereshkova-fknuvr?file=/src/App.vue

**Comment by HeiShuXianSheng** [comment]
@yuhan0709 单独控制清空文件可以实现，但是如果是在第二次选择文件触发`change`时，`fileList`如何清空第一次选择的全部文件，并将第二次选择的所有文件赋给`fileList`呢，此时fileList应该就只是第二次选的多个文件？

**Comment by yuhan0709** [comment]
> @yuhan0709 单独控制清空文件可以实现，但是如果是在第二次选择文件触发`change`时，`fileList`如何清空第一次选择的全部文件，并将第二次选择的所有文件赋给`fileList`呢，此时fileList应该就只是第二次选的多个文件？

看下我发的那个 Demo 好嘛。你可以在 `on-button-click` 的时候就把 fileList 的值清空，在 change 的时候再给 fileList 赋值呀，受控。

**Comment by HeiShuXianSheng** [comment]
@yuhan0709 多谢
