### ISSUE TITLE
a-table中row-class 函数添加行背景颜色设置不生效

### ISSUE THREAD

**Issue by myzjx** [arco-design/arco-design-vue#1987]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.39.2
- **Framework version:** Vue
- **Browser:** chrome108.0.0.0

## Extra info
css 为less文件，放在全局样式中

## What is expected?
设置行的背景颜色

## Steps to reproduce
<script lang="ts" setup>
const column = [
  { title: '测试1', dataIndex: 'test1' },
  { title: '测试2', dataIndex: 'test2' },
  { title: '测试3', dataIndex: 'test3' }
]
const data = [
  { id: 0, test1: '测试1', test2: '测试2', test3: '测试3' },
  { id: 1, test1: '测试1', test2: '测试2', test3: '测试3' },
  { id: 2, test1: '测试1', test2: '测试2', test3: '测试3' },
  { id: 3, test1: '测试1', test2: '测试2', test3: '测试3' }
]
const tableRowClass = (record: any, rowIndex: number) => {
  if (rowIndex === 1) {
    return 'aa'
  }
}
</script>
<template>
  <section class="p-3">
    <a-table :columns="column" :data="data" :row-class="tableRowClass"></a-table>
  </section>
</template>

// -css部分-
:deep(.arco-table-tr .aa) {
  background-color: #37a1ff;
}

**Comment by myzjx** [comment]
猜出来，样式的class 写法有点特殊

**Comment by coderlcb** [comment]
请问怎么解决？

**Comment by myzjx** [comment]
> 请问怎么解决？
--- html
<a-table
      ***
      :row-class="tableRowClass"
/>

--- js/ts
const rowArr = ref([] as number[])
const tableRowClass = (record: any, rowIndex: number) => {
  if (rowArr.value.includes(rowIndex)) {
    return 'row-warn'
  }
}

--- css
row-warn的css样式

**Comment by coderlcb** [comment]
> > 请问怎么解决？
> > --- html
> > <a-table
> > ***
> > :row-class="tableRowClass"
> > />
> 
> --- js/ts const rowArr = ref([] as number[]) const tableRowClass = (record: any, rowIndex: number) => { if (rowArr.value.includes(rowIndex)) { return 'row-warn' } }
> 
> --- css row-warn的css样式

谢谢 已经解决了 style去掉scoped就好了

**Comment by Nicenonecb** [comment]
> > > 请问怎么解决？
> > > --- html
> > > <a-table
> > > 
> > > :row-class="tableRowClass"
> > > />
> > 
> > 
> > --- js/ts const rowArr = ref([] as number[]) const tableRowClass = (record: any, rowIndex: number) => { if (rowArr.value.includes(rowIndex)) { return 'row-warn' } }
> > --- css row-warn的css样式
> 
> 谢谢 已经解决了 style去掉scoped就好了

我去掉scoped 还是没有改变
<template>
  <a-table
    :data="dataSource"
    :columns="columns"
    :row-class="genRowClass"
    class="table"
  >
  </a-table>
</template>

<script setup>
import { ref } from "vue";

const dataSource = [
  { name: "张三", age: 18 },
  { name: "李四", age: 20 },
  { name: "王五", age: 22 },
];
const columns = [
  {
    title: "nanme",
    dataIndex: "name",
  },
  {
    title: "age",
    dataIndex: "age",
  },
];
const genRowClass = (record) => {
  const { raw } = record;
  if (raw.age < 20) {
    return "age-lower";
  } else {
    return "age-higher";
  }
};
</script>

<style>
.age-lower {
  color: #00b42a;
  background-color: #00b42a;
}

.age-higher {
  background-color: red;
  color: red;
}
</style>

**Comment by Nicenonecb** [comment]
带scoped解决办法如下
.table:deep(.row-disabled) td {
  color: #9999;
  cursor: not-allowed;
}
其中table是a-table的class，.row-disabled 是动态样式类名

**Comment by miaokela** [comment]
只有鼠标悬浮才有颜色，默认还是覆盖不了为啥
