### ISSUE TITLE
表单验证项设置为required，输入值后，仍然会提示xxx is required

### ISSUE THREAD

**Issue by bytrix** [arco-design/arco-design-vue#1999]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.40.1
- **Framework version:** Vue 3.2.45
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/modest-fire-50c5n1?file=/src/App.vue

## What is expected?
不应该出现"name is required"
![image](https://user-images.githubusercontent.com/7734124/209749284-9f285ca7-f151-4216-8793-7a68ddb8613d.png)

## Steps to reproduce
输入框中输入文字

**Comment by luo0412** [comment]
form要设置model为formData，不然没法对应

**Comment by yuhan0709** [comment]
楼上正解～ 

<img width="803" alt="image" src="https://user-images.githubusercontent.com/23137528/212244190-17a9ed81-c94b-4889-9a99-b22ae3fa52ac.png">

**Comment by luo0412** [comment]
您好：我已收到您的邮件，我将尽快查收处理。祝您生活愉快
