### ISSUE TITLE
Icon 在tsx中 使用onClick 会有类型声明的错误，希望可以支持 onClick 的声明

### ISSUE THREAD

**Issue by Saber-Kurama** [arco-design/arco-design-vue#2015]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.41.0
- **浏览器版本:** chrome108.0.0.0

## 额外补充
可以考虑增加 `emits['click']`
或者 `props`继承 `HTMLAttributes` `interface IconProps extends HTMLAttributes `

## 预期结果
希望可以支持 onClick 的声明

## 复现步骤
ts 的错误提示
```
TS2322: Type '{ class: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & Partial<{ strokeWidth: number; strokeLinecap: string; strokeLinejoin: string; spin: boolean; }> & Omit<Readonly<{ size?: unknown; strokeWidth?: unknown; strokeLinecap?: unknown; strokeLinejoin?: unknown; rotate?: unknown; spin?: unknown; } & { ...; } & { ...; }> & VNodeProps & AllowedComponentP...'.
```

**Comment by flsion** [comment]
@Saber-Kurama 这里考虑在 icon 上增加 onClick 的属性会更方便些，vue组件在继承HTML属性上目前没有找到太好的方式
