### ISSUE TITLE
select选择器组件没有选中的背景【bug】

### ISSUE THREAD

**Issue by qq575792372** [arco-design/arco-design-vue#2016]
select当选择一个时候，是有选中背景的，但是鼠标滑过一下就没有选中背景了，这样根本都不知道选择的是哪个，官网的示例Select组件随便一个都可以复现。

**Comment by flsion** [comment]
@qq575792372 嗯，现在的形式在鼠标离开后，不能辨别出选中的选项，我和设计同步下这个问题
