### ISSUE TITLE
Table样式问题

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#2018]
## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.41.0
- **Browser:** chrome108.0.0.0

`scrollbar`为`true`时：

![image](https://user-images.githubusercontent.com/22813922/210684085-0d2e21de-78d2-443a-9929-8c2742f7eb4e.png)

`scrollbar`为`false`时没有这个问题。

`table`的`scroll`设置为`x:'100%'`，然后table滚动到最右边会有此问题。

**Comment by flsion** [comment]
@llk2yq 你好，可以提供一个简单的复现地址，方便排查下问题
