### ISSUE TITLE
select组件下拉框空状态在使用a-option时无法二次回显

### ISSUE THREAD

**Issue by liushun-ing** [arco-design/arco-design-vue#2023]
<img width="763" alt="企业微信截图_16728198659279" src="https://user-images.githubusercontent.com/67847279/210735650-10f13a13-e787-45e6-9f23-cac7923bbf53.png">
自行遍历a-option，初始化时有options数据，之后点击xxx按钮，清空data数组之后，空状态无法显示，只显示如下的一个细条
<img width="289" alt="2222" src="https://user-images.githubusercontent.com/67847279/210735685-13bd4f44-00a5-4c89-9619-665ea7c6eb37.png">
但是换成options属性传入a-select组件，清空data之后，能正确显示空状态
<img width="658" alt="4444444444" src="https://user-images.githubusercontent.com/67847279/210736401-cf570c8a-2217-43c5-b1d9-2aeb490b4327.png">

<img width="294" alt="企业微信截图_16728209436090" src="https://user-images.githubusercontent.com/67847279/210736254-1d142cba-b108-4172-aab7-836c16dbb1ac.png">

**Comment by flsion** [comment]
@liushun-ing 你好，请提供一个能够复现的地址看一下。可以从官网 DEMO 快速打开 codesandbox

**Comment by liushun-ing** [comment]
> @liushun-ing 你好，请提供一个能够复现的地址看一下。可以从官网 DEMO 快速打开 codesandbox

https://codesandbox.io/s/vibrant-james-d7ldei?file=/src/App.vue
两种写法，点击清除后，一个有空状态一个没有

**Comment by Zz-ZzzZ** [comment]
很奇怪，我把codesandbox的代码复制到demo中并未出现这个情况，而codesandbox确实出现了
![image](https://user-images.githubusercontent.com/48228016/213091247-a0997577-cda1-4a9a-a9f7-cb3896c4dac9.png)

**Comment by SunYuanOnly** [comment]
@flsion 确实存在上面的问题  https://codesandbox.io/s/strange-jang-0537ou?file=/src/App.vue

**Comment by oljc** [comment]
fix #2265
