### ISSUE TITLE
select组件model-value不在选项中，能否不自动显示

### ISSUE THREAD

**Issue by sj7112** [arco-design/arco-design-vue#2026]
```
<a-select v-model="eqForm.eqReason" style="width:174px;" allow-clear="">
    <a-option v-for="item in eqFormPar.eqReason.list" :value="item.value" :key="item.value">{{item.label}}</a-option>
</a-select>

......

  mounted(() => {
    axios加载list...
  });

  created(() => {
    eqForm.eqReason = 3
  });
```

数据如：
{1:’辞职',2:'停薪留职',3:'退休'}

在created时候设置，在mount时候通过ajax加载

问题：
在ajax返回之前，先显示3；ajax返回之后，自动变成”退休“
即便改到nextTick里面赋初值，还是同样的效果！

![a1](https://user-images.githubusercontent.com/15377016/210930219-c368af0c-581a-4b7c-9a53-f39479104c75.png)

**Comment by flsion** [comment]
@sj7112 设置 `:fallback-option="false"` 可以不显示不存在的选项。https://arco.design/vue/component/select#fallback
