### ISSUE TITLE
select  value 为false 时  无法显示

### ISSUE THREAD

**Issue by 2011shao** [arco-design/arco-design-vue#2040]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.41.1
- **浏览器版本:** chrome108.0.0.0

## 预期结果
select 选择选项value 为false 时,无法显示

## 复现步骤
value值为false 时,  选项显示, 但是 选择后对应的值 "否" 不显示, 其实 v-model 绑定的值已经为false
`<a-option :value="false">否</a-option>`

**Comment by flsion** [comment]
@2011shao 目前 option 的 value 还不支持 boolean 类型，可以使用字符串替代下。
![image](https://user-images.githubusercontent.com/29793175/212253155-b0767943-3c19-4aa7-ad76-5e36d6255bac.png)
