### ISSUE TITLE
有计划支持ArcoVue作为externals依赖引入吗？

### ISSUE THREAD

**Issue by damnwenxi** [arco-design/arco-design-vue#2047]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
目前使用vite-plugin-resolve-external处理还是会存在一些问题

## What problem does this feature solve?
目前在无界微前端环境中，主应用和子应用都用的是ArcoDesign作为UI框架，是否支持子应用通过externals的方式引入Arco呢，这样可以减少一半的打包体积。

**Comment by flsion** [comment]
@Kefeng2017 组件库可以直接在 vite 的打包配置中直接 external 掉，可以详细描述下遇到的问题吗？
