### ISSUE TITLE
引入a-dgroup，打包构建报错

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-vue#2052]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.42.0
- **Framework version:** Vue 3.2.31
- **Browser:** chrome109.0.0.0

## What is expected?
当引入下拉框组件的分组功能a-dgroup时，打包构建就会这个报错

## Steps to reproduce
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:

**Comment by flsion** [comment]
@ZhangTomLiang 请补充下错误信息和构建配置

**Comment by ZhangTomLiang** [comment]
Build configuration(dependcies): 
 "@arco-design/web-vue": "^2.42.0",
    "@arco-themes/vue-glaucus": "^0.0.12",
    "@types/mockjs": "^1.0.4",
    "@vueuse/core": "^9.5.0",
    "acorn": "^8.8.1",
    "animate.css": "^4.1.1",
    "arco-design-pro-vue": "^2.5.11",
    "axios": "^0.24.0",
    "dayjs": "^1.10.7",
    "echarts": "^5.2.2",
    "lodash": "^4.17.21",
    "markdown-it-highlightjs": "^4.0.1",
    "mitt": "^3.0.0",
    "monaco-diff": "^1.1.1",
    "monaco-editor": "^0.34.1",
    "pinia": "^2.0.9",
    "query-string": "^7.0.1",
    "vue": "^3.2.31",
    "vue-echarts": "^6.0.0",
    "vue-i18n": "^9.2.0-beta.17",
    "vue-router": "^4.0.14",
    "vue3-markdown-it": "^1.0.10"

Error log:
[vite]: Rollup failed to resolve import "/Volumes/Application/project_station/glaucus-manage-front/node_modules/@arco-design/web-vue/es/dgroup/style/css.js" from "src/views/product/decision/form/components/UseCode.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "/Volumes/Application/project_station/glaucus-manage-front/node_modules/@arco-design/web-vue/es/dgroup/style/css.js" from "src/views/product/decision/form/components/UseCode.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Volumes/Application/project_station/glaucus-manage-front/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
    at onwarn (file:///Volumes/Application/project_station/glaucus-manage-front/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
    at Object.onwarn (file:///Volumes/Application/project_station/glaucus-manage-front/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///Volumes/Application/project_station/glaucus-manage-front/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///Volumes/Application/project_station/glaucus-manage-front/node_modules/rollup/dist/es/shared/rollup.js:22119:26
error Command failed with exit code 1.

**Comment by ZhangTomLiang** [comment]
"devDependencies": {
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^12.0.1",
    "@types/lodash": "^4.14.177",
    "@types/nprogress": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "@vitejs/plugin-vue": "^1.9.4",
    "@vitejs/plugin-vue-jsx": "^1.2.0",
    "@vue/babel-plugin-jsx": "^1.1.1",
    "cross-env": "^7.0.3",
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-import-resolver-typescript": "^2.4.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^8.3.0",
    "husky": "^7.0.4",
    "less": "^4.1.2",
    "lint-staged": "^11.2.6",
    "mockjs": "^1.1.0",
    "prettier": "^2.2.1",
    "rollup-plugin-visualizer": "^5.6.0",
    "stylelint": "^13.8.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-order": "^4.1.0",
    "typescript": "^4.5.5",
    "unplugin-vue-components": "^0.19.3",
    "vite": "^3.2.5",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.3.0",
    "vite-plugin-imagemin": "^0.6.1",
    "vite-plugin-style-import": "1.4.1",
    "vite-svg-loader": "^3.1.0",
    "vue-tsc": "^0.34.15"
  },

**Comment by Chanzhaoyu** [comment]
你先参考下这个处理下 [Link](https://github.com/arco-design/arco-design-vue/issues/2043)

**Comment by Chanzhaoyu** [comment]
@ZhangTomLiang 你在 `arco-pro-vue` 根目录 `config/plugin/styleImport.ts` 中的 `ignoreList` 数组后面加上 `dsubmenu` 和 `dgroup` 解决

**Comment by ZhangTomLiang** [comment]
感谢，用了这个方法解决啦
