### ISSUE TITLE
日期选择器-季度范围选择器用v-model绑定，面板展示错误

### ISSUE THREAD

**Issue by Free0520** [arco-design/arco-design-vue#2057]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.40.0
- **Browser:** chrome108.0.0.0

![image](https://user-images.githubusercontent.com/24885499/212800350-b535efc4-5212-40b2-bc73-552255d90cca.png)

**Comment by Free0520** [comment]
@flsion 2.24.1版本还是没解决这个问题

**Comment by nba2007382** [comment]
看了下源码发现是dayjs不支持季度解析导致的
