### ISSUE TITLE
Drawer组件能提供before-open和before-close事件吗？

### ISSUE THREAD

**Issue by Curtain11** [arco-design/arco-design-vue#2061]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
Modal 对话框

## 预期解决问题
打开弹窗同时需要执行内部的一些方法，例如发起请求

**Comment by Chanzhaoyu** [comment]
其实可以用 `watch` 监听  `visible` 的 `true ｜ false` 来达到效果
