### ISSUE TITLE
a-dropdown组件能否支持弹出层菜单子项不隐藏属性

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-vue#2066]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
需要做一个可持续性的操作，当点击完后，弹出层被隐藏，又需要重复打开。可以参考element的做法，添加hide-on-click属性。

**Comment by flsion** [comment]
@ZhangTomLiang 感谢反馈，我会记录一下，后面的版本会添加这个功能
