### ISSUE TITLE
数值显示 Statistic 组件在数据错误的时候显示 “Invalid Date”，单词拼写错误

### ISSUE THREAD

**Issue by wtusmchen** [arco-design/arco-design-vue#2074]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.42.0
- **Browser:** chrome109.0.0.0

**Comment by flsion** [comment]
@wtusmchen 没太明白， “Invalid Date” 是拼写正确的

**Comment by wtusmchen** [comment]
@flsion 是不是应该Invalid Data？这个跟日期无关，我只是输入了字符串，应该是数值

**Comment by hehehai** [comment]
> @flsion 是不是应该Invalid Data？这个跟日期无关，我只是输入了字符串，应该是数值

@wtusmchen 这里意思是输入的内容 ”不是有效的日期“（不关心具体的输入，只关心输入是否可转换为有效日期）
