### ISSUE TITLE
tree-select 有没有树形可以默认折叠数据

### ISSUE THREAD

**Issue by cgrain1998** [arco-design/arco-design-vue#2083]
上图是有数据的情况，默认是展开的
![image](https://user-images.githubusercontent.com/35121432/216525547-f3391fb8-6e58-4b83-be71-a1bb839bd414.png)

有没有特性可以折叠它？
想要的效果
![image](https://user-images.githubusercontent.com/35121432/216525718-6566e385-f1d3-4bbb-9e88-ae3a4c9a52e5.png)

tree这个组件可以，但是tree-select 没找到对应的api 
![image](https://user-images.githubusercontent.com/35121432/216525826-b475c758-8b98-4c80-a90f-42d6d32a4cf2.png)

**Comment by cgrain1998** [comment]
答案是没有，

**Comment by Wjinlei** [comment]
tree-props 这个属性可以控制 `:tree-props="{ defaultExpandAll: false }"`
