### ISSUE TITLE
dropdown 设置class时使用:deep()无效

### ISSUE THREAD

**Issue by zhonghuaifang** [arco-design/arco-design-vue#2093]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.42.1
- **框架版本:** Vue
- **浏览器版本:** chrome109.0.0.0
- **复现地址:** https://stackblitz.com/edit/angular-hmramb?file=src%2FApp.vue

## 复现步骤
```
<a-dropdown class="custom-dropdown">
...
</a-dropdown>
<style lang="less" scoped>
.custom-dropdown {
  :deep(.arco-dropdown-option) {
    line-height: 26px;
  }
}
</style>
```
:deep()不生效

**Comment by xSandie** [comment]
drawer有一样的问题 [解决方案](https://github.com/arco-design/arco-design-vue/issues/2101)

**Comment by tazyong** [comment]
有一种东西叫 css module，vue 的同学怎么总会忽视它呢？直接看代码吧
https://stackblitz.com/edit/angular-hmramb-uv9jen?file=src%2FApp.vue

**Comment by zhonghuaifang** [comment]
@xSandie @tazyong 谢谢，看来只能写全局样式了
