### ISSUE TITLE
a-table的row-class无效

### ISSUE THREAD

**Issue by coderlcb** [arco-design/arco-design-vue#2096]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.41.1
- **Framework version:** vue 3.2.41
- **Browser:** chrome109.0.0.0

## What is expected?
根据字段改变某一行的文字颜色

## Steps to reproduce
```
 <a-table :data="bondData" :columns="columns" :row-class="genRowClass">
  </a-table>
```
```
  const genRowClass = (record: any): string => {
    const { raw } = record;
    console.log(raw);

    if (parseFloat(raw.highest) > 400) {
      return 'error-row';
    }
    return 'normal-row';
  };
```
```
 .normal-row {
    color: #00b42a;
    background-color: #00b42a;
  }
  .error-row {
    color: #f53f3f;
    background-color: #00b42a;
  }
```

**Comment by coderlcb** [comment]
已解决 style不能加scoped

**Comment by miaokela** [comment]
只有悬浮才有颜色啊
