### ISSUE TITLE
新版upload picture-card警告

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#211]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.6.0
- **System:** MacOS
- **Browser:** Google

## Steps to reproduce

![image](https://user-images.githubusercontent.com/93666053/142816846-1c77ae40-8cde-4fd3-887c-7d750a58948c.png)

**Comment by Flsion** [comment]
2.6.1版本已经修复
