### ISSUE TITLE
The watch inside the component cannot accurately capture every change of the v-model:props

### ISSUE THREAD

**Issue by Autumn-one** [arco-design/arco-design-vue#2115]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.43.0
- **Framework version:** vue 3.2.45
- **Browser:** chrome110.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/romantic-williams-c7c02w?file=/src/App.vue

## What is expected?
期望输出 aaa 和 bbb, 实际却答应了2个aaa

## Steps to reproduce
点击触发按钮，之后查看控制台打印

**Comment by Saber-Kurama** [comment]
2个aaa是因为第一个Test组件的watch调用了两次
不打印bbb是因为  watch 中执行了 `emit("update:foo", false);`，对于弹窗中Test组件来说 foo值没有发生修改，所以也就不会触发watch

**Comment by Autumn-one** [comment]
> 

Thank you for your answer. The question has been answered
