### ISSUE TITLE
ImagePreviewGroup component use trigger warning

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#212]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.6.0
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 95
- **复现地址:** https://arco.design/

## 复现步骤

```vue
<!-- vue3 code -->
<Image.PreviewGroup :src-list="['']">
  <Button>Test</Button>
</Image.PreviewGroup>
```

## 额外补充

`Image.Preview` component warning:

> [Vue warn]: Extraneous non-props attributes (disabled, error, size) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

**Comment by Flsion** [comment]
@Kigoal 可以给个复现的Codepen吗

**Comment by kirazxyun** [comment]
duplicate with #279
