### ISSUE TITLE
<a-table> dataIndex 不能有小数点

### ISSUE THREAD

**Issue by sj7112** [arco-design/arco-design-vue#2127]
dataIndex = "far.boo"，表格不输出结果

**Comment by nanarino** [comment]
dataIndex = "far.boo" 它对应这样：
js```
const tableData = reactive([{
      far: { boo: 1 },
}]),
```
🤔

**Comment by nanarino** [comment]
```
class StringNotPath extends String{
  split(){
    return [this.toString()]
  }
}

const columns = [
      {
        title: 'Name',
        dataIndex: new StringNotPath('far.boo'),
      },
]
```
🤔 这样绕过了

**Comment by sj7112** [comment]
这个有点绕不过来。tableData本就是上面的结构，最好是能自动处理，否则得双向转换，最终自己解决，用的是这种：
// $转换小数点（arco的table补丁：column.dataIndex不能用"."）- 第一位允许$不处理
String.prototype.dollar2Dot = function dollar2Dot() {
  const str = String(this);
  return str[0] + str.substring(1).replace(/\$/g, '.');
};

// 小数点转换$（arco的table补丁：column.dataIndex不能用"."）- 第一位允许$不处理
String.prototype.dot2Dollar = function dot2Dollar() {
  const str = String(this);
  return str[0] + str.substring(1).replace(/\./g, '$');
};

**Comment by nanarino** [comment]
那么你的tableData是什么形状的🤔 。不是以"far.boo"直接作为字典的key吗。 而我的办法在CodeSandbox里试了一下是可以绕过path的。

**Comment by sj7112** [comment]
哦，tableData确实是这种的：far: { boo: 1 },
之前代码里面已经做过转换了，所以用'far.boo'去调的

**Comment by sj7112** [comment]
确实行得通，不错不错，这个问题可以close了。
