### ISSUE TITLE
表格排序回调需要有当前列信息和排序方向用来做异步排序

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#213]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
当点击列排序时给表格的sorter-change事件返回当前列信息和当前排序的方向 可通过这两个信息请求异步数据做异步排序使用

## 预期解决问题
让排序可以支持异步数据的自定义排序

**Comment by Flsion** [comment]
@duxphp 这个问题用 @sorter-change 可以实现了吧
