### ISSUE TITLE
Typography component use trigger warning

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#214]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.6.0
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 95
- **复现地址:** https://arco.design/

## 复现步骤

```vue
<!-- vue3 code -->
<Typography.Title>Test</Typography.Title>
```
## 额外补充

`Typography.Base` component warning:

> [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by flsion** [comment]
fixed
