### ISSUE TITLE
a-table有无doubleclick事件

### ISSUE THREAD

**Issue by sj7112** [arco-design/arco-design-vue#2140]
目前有row-click鼠标单击事件，能否增加一个row-dblclick鼠标双击事件

**Comment by sj7112** [comment]
另外建议row-click提供3个参数：
record: TableData
**index: seq**
ev: Event

比如序号相关数据不一定存在row里面的。。。

**Comment by zijingsong** [comment]
我们也遇到这个问题，没有双击事件很不方便，还请开发组暴露一下，谢谢！
