### ISSUE TITLE
使用tree组件出现异常

### ISSUE THREAD

**Issue by SilverFT** [arco-design/arco-design-vue#2144]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.43.1
- **Framework version:** vue3.2.45
- **Browser:** chrome110.0.0.0

## What is expected?
解决问题或解答

## Steps to reproduce
<a-tree :data="treeData[index]" @node-click="handleNodeClick" />
const treeData = ref<any[]>([]);
treeData赋示例的数据
控制台报错Uncaught (in promise) TypeError: tree.forEach is not a function

**Comment by Saber-Kurama** [comment]
` :data="treeData[index]"` 中 `treeData[index]` 不是数组吧

**Comment by SilverFT** [comment]
灯下黑，灯下黑，低级错误了，感谢感谢
