### ISSUE TITLE
Table component `fixed` style improvement

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#216]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 

want to add a `box-shadow` style to the `TableColumn.fixed` attribute of the `Table`

## 预期解决问题

UI Style

## 额外补充

Before:
![middle_img_v2_e834b36d-6e73-4e57-b371-6275b0f3c0bg](https://user-images.githubusercontent.com/21240282/142828423-11d6c8fd-05a3-4d0c-85f4-0dd9e1fabb4e.png)

After(by Naive UI):
![middle_img_v2_b11eb546-cdd8-47a2-b095-b420752b14ag](https://user-images.githubusercontent.com/21240282/142828456-51fddb63-c056-4dd8-86b5-174da19c911b.png)

**Comment by Flsion** [comment]
@Kigoal 固定列默认是有阴影的，https://codepen.io/flsion/pen/XWaQyEy?editors=001。这个问题可以在codepen里复现一下吗

**Comment by Kigoal** [comment]
@Flsion 我大概发现原因了，缺少 `arco-table-has-fixed` 和 `arco-table-scroll-postion-middle` className导致无法触发css样式造成的。
根据源码，我看到这两个class是由 `tableCls` 函数生成，而这个函数包了一层 `computed` 但是里面的 `getTableFixedCls` 和 `getTableScrollCls` 函数是普通箭头函数，所以当 `columns` prop的值变化时是不会触发计算的。


我的使用场景刚好是先传递一个 `columns = []` 然后通过后端获取数据后更新值 `columns = [{...},{...},{...}]` ，这样 `tableCls` 函数就不会触发更新了

codepen:
![image](https://user-images.githubusercontent.com/21240282/142872425-ecfa90d5-d0bd-4c27-aa12-e19fbb77d3ff.png)

我的代码：
![image](https://user-images.githubusercontent.com/21240282/142872453-f5955bdb-168b-42a4-8aae-1c53c9995e0f.png)
