### ISSUE TITLE
图片-->单独使用预览组件 BUG

### ISSUE THREAD

**Issue by LiuXIn011** [arco-design/arco-design-vue#2163]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.43.1
- **Framework version:** vue
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** https://arco.design/vue/component/image#component-preview-group

## Steps to reproduce
正常使用组件，图片轮播左右翻页图标定位错误
![image](https://user-images.githubusercontent.com/48080203/220849463-d0ecbb0b-ad3e-4153-bda7-a2703dc11aec.png)
拖到图片，很卡顿，而且会自动回到中心位置

希望加入功能：
滚动鼠标滚轮可以放大缩小图片

**Comment by flsion** [comment]
@LiuXIn011 这里可能是本地环境的某些样式或布局影响了按钮的位置，可以提供下具体出现问题的原因。我这里检查官网上的 DEMO 没有发现这个问题
![image](https://user-images.githubusercontent.com/29793175/221129732-808c1778-e2a9-4de8-8036-b7ee3ab3fec8.png)

**Comment by LiuXIn011** [comment]
> @LiuXIn011 这里可能是本地环境的某些样式或布局影响了按钮的位置，可以提供下具体出现问题的原因。我这里检查官网上的 DEMO 没有发现这个问题 ![image](https://user-images.githubusercontent.com/29793175/221129732-808c1778-e2a9-4de8-8036-b7ee3ab3fec8.png)

指示器的定位不太对，position应该为fixed，而使用的是absolute，当父级元素没有定位的时候是正常的，当父级元素继承到任何的定位属性，指示器就会依据父级元素定位。
