### ISSUE TITLE
关于 <image-preview-group> 自动切换原图和缩略图的功能需求

### ISSUE THREAD

**Issue by SoXunwa** [arco-design/arco-design-vue#2165]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 绑定到 image 组件的json 数据
{ 
  id:number, 
  // 图片源文件
  src:string,
 // 图片缩略图
  thumbnail_src:string
}

## 现有案例
image-preview-group 会搜集 image 的 src 进行预览，
如果给 image 配置 thumbnail_src 字段，那预览的是缩略图，将毫无意义。
如果给 image 配置 src 字段，那 thumbnail_src（缩略图）字段将毫无意义。
重新提取封装一个  image-preview-group 的 src-list 数组也会额外浪费内存资源，无法实现数据的复用。

## 预期解决问题
image 绑定的数据中，有 src 和 thumbnail_src 字段，默认情况的下会给image的src配置thumbnail_src字段，
希望  image-preview-group 的 src-list 在打开预览的过程中，自动切换成数据源 src，而不是使用默认 image的src，这样就不需要二次提取封装一个 src-list 的数组。

**Comment by flsion** [comment]
@SoXunwa 嗯，这是个很好的建议，后面会优化下这个地方

**Comment by SoXunwa** [comment]
还有一个功能需求建议：希望增加一个视频预览组件，可以像预览图片一样预览视频文件。

**Comment by pluto369** [comment]
需求建议：希望预览图片时可以使用鼠标滚轮对图片进行缩放🎈
