### ISSUE TITLE
关于级联组件<a-cascader />的bug，紧急！！！！

### ISSUE THREAD

**Issue by Estherwuu** [arco-design/arco-design-vue#2166]
问题描述：级联组件可以禁用选项，当参数multiple=true时，可支持多选。这时禁用子级，当父级点击全选时仍会把已禁用的子级选择上。

举例：级联组件拿来做选择省市区的功能——当【北京市】的子级【朝阳区】disabled=true的情况下，禁止选中。这时再点击北京市，仍然能把北京市下面的城市全部选中，包括已禁用的【朝阳区】。

预期解决：当子级禁用时，选择父级的全选框，自动过滤已禁用的子级。

**Comment by flsion** [comment]
@Estherwuu 可以检查下组件库版本，最新版是正常的  https://codesandbox.io/s/interesting-ace-niyoci -> DEMO
