### ISSUE TITLE
【tree】树节点增加 data-level 和 data-key 数据属性

### ISSUE THREAD

**Issue by Saber-Kurama** [arco-design/arco-design-vue#2191]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
参照  TDesign
https://tdesign.tencent.com/vue-next/components/tree?tab=demo

## 预期解决问题
树节点增加 `data-level` 和 `data-key`，可以方便使用者根据这个对特定层级的节点或者特定数据的节点，做样式的修改

## 额外补充
TDesign 中是`data-value`。`data-key`可能更符合我们的数据格式

**Comment by lanseria** [comment]
@Saber-Kurama 请问一下，这次提交将 `level` 层级信息放在了 `data-level` 里，那如何在 `vue3` 中 
```vue
<template #extra="nodeData">
</template>
```
`slot` 插槽中如何获取到data-这种类型的数据呢，如这里要的 `data-level` 
看了 `js` 的使用方法
```js
var article = document.querySelector("#electriccars");

article.dataset.columns; // "3"
article.dataset.indexNumber; // "12314"
article.dataset.parent; // "cars"
```
这类都比较麻烦吧
