### ISSUE TITLE
新增一个调色板组件

### ISSUE THREAD

**Issue by lhlyu** [arco-design/arco-design-vue#2197]
- [X] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://juejin.cn/post/6844903492511891470

## What problem does this feature solve?
用来选取颜色

**Comment by hehehai** [comment]
@lhlyu 可以发布到物料平台 https://arco.design/material/
