### ISSUE TITLE
复杂的表单结构，如何进行表单验证？

### ISSUE THREAD

**Issue by popdo** [arco-design/arco-design-vue#2200]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
例如 一个表单数据是这样的：

```ts
const form = reactive({
  _id: '',
  name: '',
  data: {
    list: [{ id: 001, desc: 'xxx' }],
    createDate:'2021-01-01'
  },
});
```

例如我要验证 `form.data.createDate` 或者 `form.data.list[0].desc`

formItem上如何填写field？rules又该如何配置呢？

**Comment by flsion** [comment]
@popdo field 属性传入路径即可 https://arco.design/vue/component/form#dynamic
