### ISSUE TITLE
官网vue范围选择器，年份选择存在bug，

### ISSUE THREAD

**Issue by cmwaiwj** [arco-design/arco-design-vue#2213]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.43.2
- **Browser:** chrome111.0.0.0

## What is expected?
上一条被删除了，你们线上版本都有问题，请给予重视！！！如已解决，可忽略

## Steps to reproduce
vue-组件-日期选择器 DatePicker-范围选择-年份

**Comment by kaikaibenkai** [comment]
具体描述问题

**Comment by cmwaiwj** [comment]
vue-组件-日期选择器 DatePicker-范围选择-年份选择出现bug，这随便测一下就知道啊，复现地址：https://arco.design/vue/component/date-picker

**Comment by kaikaibenkai** [comment]
> vue-组件-日期选择器 DatePicker-范围选择-年份选择出现bug，这随便测一下就知道啊，复现地址：https://arco.design/vue/component/date-picker

你不说是什么 bug ，怎么测

**Comment by flsion** [comment]
repeat #2229
