### ISSUE TITLE
vue日期年份范围选择存在bug

### ISSUE THREAD

**Issue by cmwaiwj** [arco-design/arco-design-vue#2229]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.44.1
- **浏览器版本:** chrome111.0.0.0
- **复现地址:** https://arco.design/vue/component/date-picker

## 额外补充
请尽快解决，急

## 预期结果
可正常选择

## 复现步骤
日期选择器-范围选择-年份，选择具体日期多次弹出错误提示

**Comment by czq297297** [comment]
补充具体复现地址：https://stackblitz.com/edit/angular-gvy6rx?file=src%2FApp.vue

**Comment by flsion** [comment]
@cmwaiwj 已确认问题，下个版本会修复一下
