### ISSUE TITLE
tree虚拟列表显示错误

### ISSUE THREAD

**Issue by zhonghuaifang** [arco-design/arco-design-vue#2251]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.44.2
- **框架版本:** Vue
- **浏览器版本:** chrome111.0.0.0
- **复现地址:** https://stackblitz.com/edit/angular-fy16hz?file=src%2FApp.vue

## 复现步骤
tree开启虚拟列表，高度设置>=690，下面的部分数据不展示

**Comment by kairyou** [comment]
@zhonghuaifang 找到解决方案了吗？我今天也发现了这个问题
