### ISSUE TITLE
2.44.2 select组件清空后无法展示placeholder

### ISSUE THREAD

**Issue by bojhkaka** [arco-design/arco-design-vue#2254]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.44.2
- **Browser:** chrome111.0.0.0

## What is expected?
select组件allow-clear后展示placeholder

![image](https://user-images.githubusercontent.com/6252290/226330112-8eabdfe5-2639-4dab-92e3-93e6d4414ae7.png)

**Comment by Saber-Kurama** [comment]
这个是修复下拉选项支持空字符串，考虑不全造成的问题

**Comment by a327958099** [comment]
我也遇到了同样的问题，你解决没？怎么解决的？

**Comment by a327958099** [comment]
> > 我也遇到了同样的问题，你解决不了？怎么解决的？
> 
> 等官方更新吧，或者退回2.44.1版本

退回版本这个bug也存在，我试过很多个低版本的，问题依然存在，2.44.1是你测试过可行的吗？我现在的解决办法是在清空事件时使用一个延迟函数v-if刷新一下，缺点是会闪一下
