### ISSUE TITLE
[FR] tooltip: 希望支持在宿主按钮节点被点击时不显示tooltip

### ISSUE THREAD

**Issue by joyexpr** [arco-design/arco-design-vue#2258]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
未考察

## 预期解决问题
tooltip通常用来替代原生title的功能，即hover在宿主按钮节点上N秒显示tooltip，通常在用户未熟悉按钮功能时用于提示，

但当用户已知按钮功能进行点击（如点击后弹出popover）时，如果点击后还弹出tooltip遮住popover，对用户体验很差

希望可以增加一个属性，当宿主按钮节点被点击后，tooltip就不再显示

**Comment by Przeblysk** [comment]
1. tooltip 的使用场景应该是下面这种补充说明

![CleanShot2023-04-18at15 29 21@2x](https://user-images.githubusercontent.com/18001272/232703836-24fd3b4d-cf4a-4023-b598-deee7d1d350f.png)

2. tooltip遮住popover
可以使用位置分别定位让他们不重叠

3. 当宿主按钮节点被点击后，tooltip就不再显示
我觉得这是你的业务逻辑你可以自己控制

**Comment by joyexpr** [comment]
![1681815736303](https://user-images.githubusercontent.com/4078122/232758060-caee9faa-c53b-4ca3-acf4-ee756d8d7ceb.jpg)

上图就是我提FR的场景

你所提的2、3两点，自己来做又麻烦代码又没意义，实在不是好的方案，而且这个跟我的业务一点关系都没有
我觉得tooltip组件提供这个参数是最优方案

目前我选择的保底方案是使用 mouse-enter-delay，尽量设长一点，这样当用户意图是点击的，大多数情况不会到达阈值导致tooltip弹出
