### ISSUE TITLE
InputNumber 组件 onChange 类型验证问题

### ISSUE THREAD

**Issue by jekip** [arco-design/arco-design-vue#228]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue: 2.6.0
- **System:** windows
- **Browser:** 谷歌
- **Reproduction Link:** https://arco.design/vue/component/input-number

## What is expected?
期望是，类型验证通过

## Steps to reproduce
InputNumber 组件，当使用 v-bind 传入 onChange 的时候，onChange方法类型验证失败，onChange 变成一个数组包含一个传入的onChange方法，和 组件内部的，validateField() 方法，虽然这样功能是正常的，只是会存在类型验证失败警告
type check failed for prop "onChange". Expected Function, got Array

**Comment by Flsion** [comment]
@jekip 收到了。这个涉及到所有为JSX额外提供的Props的声明修改，目前已经在处理中了~

**Comment by Flsion** [comment]
2.6.1已经修复
