### ISSUE TITLE
treeSelect没有控制树节点展开收起的属性，能不能新增属性控制下拉树节点的展开收起，最好有默认展开节点的属性

### ISSUE THREAD

**Issue by xw19999** [arco-design/arco-design-vue#2281]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
当下拉树的子级节点较多时，打开下拉树、展示的数据较多且较为杂乱，希望能控制默认展开节点控制树选择器展示的数据。

**Comment by Curtain11** [comment]
:tree-props="{'default-expanded-keys': default}"
default是需要展开的节点id集合

**Comment by 13262113871** [comment]
自定义 data 的字段名称 不管用

**Comment by tyg6** [comment]
能不能继承Tree组件的方法啊？比如expandAll、expandNode
现在treeSelect一个方法都没有。感谢！

**Comment by LIjiAngChen8** [comment]
[TreeSelect](https://arco.design/vue/component/tree-select#API) 组件的 `tree-props` 接受所有 [Tree](https://arco.design/vue/component/tree) 组件的Props。
示例 : [Demo](https://codesandbox.io/p/sandbox/arco-issues-2281-nfdzwv)

> [!TIP]
> 这边先关闭该 issue 了，如有问题可再次打开 :shipit:

**Comment by li1615882553** [comment]
> [TreeSelect](https://arco.design/vue/component/tree-select#API) 组件的 `tree-props` 接受所有 [Tree](https://arco.design/vue/component/tree) 组件的Props。 示例 : [Demo](https://codesandbox.io/p/sandbox/arco-issues-2281-nfdzwv)
> 
> Tip
> 
> 这边先关闭该 issue 了，如有问题可再次打开 :shipit:

确实tree-props可以接受tree组件的Props,但是他们有办法调用到tree暴露出来的方法，比如：expandAll、checkAll等等
