### ISSUE TITLE
list组件滑动到底部会触发两次reach-bottom

### ISSUE THREAD

**Issue by L1nYong** [arco-design/arco-design-vue#2283]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.44.5
- **Framework version:** vue 3.2.40
- **Browser:** chrome111.0.0.0

## What is expected?
滑动到底部只触发一次reach-bottom

**Comment by L1nYong** [comment]
> @L1nYong hi，补充一个复现吧
> 
> https://codesandbox.io/s/7cj4zt?file=/src/App.vue:158-167

就这个默认的代码就能复现，滑动到底部时会打印多次reach bottom

**Comment by hehehai** [comment]
@flsion 这里好像向上滚动，也会触发，感觉是个 bug

**Comment by hehehai** [comment]
> @flsion 这里好像向上滚动，也会触发，感觉是个 bug

@L1nYong 除了这个问题，向下滚动，反复触发这个是正常的
