### ISSUE TITLE
select 组件v-model 绑定的值不能清空, 提示文本无法回显

### ISSUE THREAD

**Issue by 107236074** [arco-design/arco-design-vue#2287]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.44.3
- **Browser:** chrome111.0.0.0

**Comment by 107236074** [comment]
<div>
   
<a-select v-model="form.section" placeholder="Please select ..."  allow-clear>
        <a-option value="section one">Section One</a-option>
        <a-option value="section two">Section Two</a-option>
        <a-option value="section three">Section Three</a-option>
      </a-select>

      <a-button @click="()=>{ form.section=null}">重置</a-button>
</div> 

@hehehai   allow-clear 引起的无法重置

**Comment by lilifan1598** [comment]
我也出现这个问题了，将form对象置为{}，但是select组件的视图并没有改变。我试图回滚到2.43.2版本，同样操作清空form的同时组件视图也会更新清空。应该是某个版本中修改出的问题

**Comment by weiguanglai** [comment]
<a-button @click="()=>{ form.section=''}">重置</a-button>
试试
