### ISSUE TITLE
组件文档中无vue组合式API的使用方式

### ISSUE THREAD

**Issue by AgentRich** [arco-design/arco-design-vue#2297]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
隔壁ele的文档都是支持的，咱也支持一下吧。

## What problem does this feature solve?
希望可以支持vue3中组合式API的书写方式，目前组件使用方式都是选项式的，其中有一些属性比如`this.$message`在组合式中无法使用。

**Comment by rainrcn** [comment]
自己改成组合式就行了.
message那个这么写，官方文档里有：
import { Message } from '@arco-design/web-vue';

**Comment by AgentRich** [comment]
> 自己改成组合式就行了. message那个这么写，官方文档里有： import { Message } from '@arco-design/web-vue';

感谢帮助，后来翻文档看见了，写的位置跟别的组件不一样，找半天。。
