### ISSUE TITLE
有虚拟滚动条scrollbar吗？类似el-scrollbar

### ISSUE THREAD

**Issue by gcxfd** [arco-design/arco-design-vue#23]
## 现有案例
Vue的自定义滚动，我用el-scrollbar
https://segmentfault.com/a/1190000015068613
https://jsfiddle.net/chenfangxu/jfn5gzcw/

## 预期解决问题
有scrollbar吗？类似el-scrollbar

**Comment by LuckyHookin** [comment]
期待~

**Comment by Flsion** [comment]
@LuckyHookin 好的，这个组件已经在规划中了，会在后续的版本推出

**Comment by gcxfd** [comment]
@Flsion https://gitee.com/rmw-link/web/blob/master/src/lib/scrollbar.vue
我自己写了一个，仅供参考

**Comment by seepine** [comment]
期待

**Comment by bzw1204** [comment]
期待，希望内置组件的滚动条样式同时优化下，现在风格真的是不能说有风格，而是好有个性

**Comment by hehehai** [comment]
自定义滚动条已在 [beta](https://github.com/arco-design/arco-design-vue/tree/beta) 发布，待近期测试稳定后将正式发布。
