### ISSUE TITLE
Select 组件或类似有 @change 事件组件在验证字段中存在报警问题

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#231]
党 Form-item 的 validate-trigger 中带有 "change" 事件的时候，子组件监听相同事件便会有报警提示；

估计所有类似 input 等其他事件可能也会有类似问题；

![image](https://user-images.githubusercontent.com/21995186/142991209-c6f93954-e775-4dc6-ad62-8d44c9b22888.png)
![image](https://user-images.githubusercontent.com/21995186/142991244-f4621761-970a-409c-8ec0-e1b0d4a9a7f4.png)

**Comment by Flsion** [comment]
2.6.1版本已经修复~
