### ISSUE TITLE
可编辑表格的data在重新赋值后字段的输入框不显示

### ISSUE THREAD

**Issue by AgentRich** [arco-design/arco-design-vue#2317]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.0
- **Framework version:** "@arco-design/web-vue": "^2.42.1"
- **Browser:** chrome111.0.0.0

## Steps to reproduce
可编辑表格的data属性绑定了pinia定义的一个store中的ref 
进入页面后点击按钮给ref赋值
但是表格其他数据可以正常显示，可编辑列的字段输入框不显示。
请问这种业务场景改如何配置表格让他在赋值之后仍然是可编辑的呢？

**Comment by Przeblysk** [comment]
给个复现demo吧

**Comment by AgentRich** [comment]
> 给个复现demo吧
感谢支持，前几天网络出问题无法回复，问题已解决。是因为表格的columns中需要一个slotName属性，动态赋值的时候给漏掉了。
