### ISSUE TITLE
[Cascader] 启用多选模式multiple和可搜索allow-search时，搜索结果展示异常

### ISSUE THREAD

**Issue by ZhongMingKun** [arco-design/arco-design-vue#2324]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.0
- **Framework version:** 3.2.0
- **Browser:** chrome112.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/happy-ramanujan-pprs06

## Extra info
发现把".arco-cascader-search-panel"的"justify-content: center;"去掉就可以了，但是没测试过去掉之后的其他情况
![image](https://user-images.githubusercontent.com/33282718/230825347-05dacc3c-9ba0-4b8b-8614-b07399bce339.png)

## What is expected?
可正常展示搜索结果的全部内容

## Steps to reproduce
1. 设置比较短的长度
2. 启用多选模式
3. 启用可搜索
![image](https://user-images.githubusercontent.com/33282718/230825325-d1021316-8bf9-42e0-8d3e-0c08d32b0dab.png)

**Comment by flsion** [comment]
@ZhongMingKun 感谢 PR~
