### ISSUE TITLE
希望descriptions的value支持换行

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#233]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 

descriptions一般展示对象信息，对象有可能是textarea输入的内容，目前的description不能显示换行，自己每次用到都写css太麻烦了，希望直接支持显示换行

**Comment by Flsion** [comment]
目前value的内容有换行效果，可以复现下什么情况下需要换行吗？

![image](https://user-images.githubusercontent.com/29793175/143557229-ce315b75-3089-4252-ac39-4755f2024930.png)

**Comment by seepine** [comment]
不是文字长自动换行，而是输入回车换行
![image](https://user-images.githubusercontent.com/93666053/143560259-779567e1-4859-4e89-a8ce-f99b60e9fd17.png)

**Comment by seepine** [comment]
加个css就行
```
.arco-descriptions-item-value {
  word-wrap: break-word;
  word-break: break-all;
  white-space: pre-wrap;
}
```
