### ISSUE TITLE
Table开启虚拟列表横向滚动条会多出来一段

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#2334]
代码
https://codesandbox.io/s/competent-black-pdywm8?file=/src/App.vue

![image](https://user-images.githubusercontent.com/30397859/231642647-6930dec4-0ce2-4527-9c45-d79f49a7473e.png)

**Comment by ListenToMee** [comment]
2.55.2既然存在这个问题
![image](https://github.com/arco-design/arco-design-vue/assets/74313306/d9e4fcb6-9073-4f70-af3e-3d8cf2b244f3)
