### ISSUE TITLE
webstorm 2023.1版本中template里的组件事件会报Type () => void is not assignable to type MouseEvent 错误

### ISSUE THREAD

**Issue by sx1989827** [arco-design/arco-design-vue#2338]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.1
- **Browser:** chrome111.0.0.0

## What is expected?
事件处理代码不报错

## Steps to reproduce
1.升级webstorm到2023.1版本，并且开启<script setup lang="ts">
2，类似<a-button type="primary" size="mini" @click="onToday"> Today \</a-button>这样的代码会报错误，显示Type () => void is not assignable to type MouseEvent
3.如果不用arco的组件，用原生element，比如div就不会报错
4.定位到arco的index.d.ts文件显示$emit: (event: "click", ev: MouseEvent) => void; 这个定义应该有些问题，之前vue也遇到类似的错误，后来在新版本修复了 https://github.com/vuejs/language-tools/issues/1985
5.该错误并不影响编译和运行

**Comment by mengdongbao** [comment]
+1

**Comment by thikiiii** [comment]
一堆类型错误，tsc能正常通过,编辑器就不行

**Comment by czq297297** [comment]
+1

**Comment by sx1989827** [comment]
> 把 @click="onToday" 改成 @click="onToday($event) " 试试，但这只是缓兵之计，不能用于返回复数参数且需要使用的情况

这个方法我试过，但是就像你说的，局限性很大，我现在用的方法是进入到它的d.ts文件里面 ，将定义直接修改成如下：
$emit: (event: "click", ev: MouseEvent|((...args: any) => any) ) => void;
这样一劳永逸，老项目也不用一个个来修改了，但是最好还是等官方来发布补丁修复这个问题

**Comment by flsion** [comment]
@sx1989827 vue 是什么版本的，我使用 WebStorm 2022.3.1 没有复现这个问题

**Comment by sx1989827** [comment]
@flsion vue用的是最新版本，2022.3.1是正常的，2023.1才有问题

**Comment by czq297297** [comment]
更新到2023.1.1-preview 就没这个问题了

**Comment by sx1989827** [comment]
> 更新到2023.1.1-preview 就没这个问题了

请问怎么更新到2023.1.1-preview版本 我在官网找了没找到

**Comment by xiaou66** [comment]
WebStorm  更新到 2023.1.1 版本可以解决

**Comment by flsion** [comment]
WebStorm 更新到最新版可以解决这个问题了
