### ISSUE TITLE
Menu组件类型提示错误

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#234]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.6.0
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 95
- **复现地址:** https://arco.design/

## 额外补充

![Ejv3S5qhd6](https://user-images.githubusercontent.com/21240282/143163825-f795e4b8-3309-4538-999c-4dbf6d793d82.png)
![q02TGD2P11](https://user-images.githubusercontent.com/21240282/143163832-3e8515f3-9e7e-47f6-aca3-e21f492dd5dc.png)

## 预期结果
没有错误提示

## 复现步骤
```vue
<Menu onMenuItemClick="handleMenuItemClick" />
```

**Comment by agileago** [comment]
修复了个寂寞？
