### ISSUE TITLE
Table的columns属性，align赋值导致vue代码报警

### ISSUE THREAD

**Issue by holyrong** [arco-design/arco-design-vue#2350]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.1
- **Browser:** chrome112.0.0.0

## What is expected?
不要报警

## Steps to reproduce
配置columns时，增加了align:'right'，vue代码中:columns="columns" 报警：不能将xxxx属性赋值给xxxx

**Comment by flsion** [comment]
@holyrong 可以给 columns 属性指定组件库附带的 TableColumnData 类型
