### ISSUE TITLE
Input-tags 中的文字不支持鼠标选中

### ISSUE THREAD

**Issue by Holmessr** [arco-design/arco-design-vue#2351]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
文字复制

## What problem does this feature solve?
鼠标文字选中方便复制

**Comment by flsion** [comment]
@Holmessr 检查了一下，输入框（包括tag）的默认行为会在点击后让 input 元素获得焦点，使得 tag 元素无法获取焦点。这个复制文字在目前的交互方式下有冲突，无法实现
