### ISSUE TITLE
Select组件不显示placeholder属性

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#236]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.6.0
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 95
- **复现地址:** https://arco.design/

## 额外补充

这样写不显示
![ZSAijyoViO](https://user-images.githubusercontent.com/21240282/143164253-4dd5c2ff-10bf-4423-ba94-a682005c2185.png)
![swl7gVDjuW](https://user-images.githubusercontent.com/21240282/143164234-19fb7fe6-9a54-4b7c-89aa-39ddda2f20cb.png)

这样写就显示 
![AhLREhgvqr](https://user-images.githubusercontent.com/21240282/143164270-e36fbb37-3f7b-4371-a11a-e09c8eb7b595.png)
![thSTCqDcNv](https://user-images.githubusercontent.com/21240282/143164275-f4a798dd-1303-4e22-bdd9-317ed24acfb7.png)

## 预期结果
正确显示 `placeholder`

## 复现步骤
```vue
// tsx
<Select placeholder="test">
  <Select.Option>{'Text'}</Select.Option>
</Select>
```
提示以下错误
> [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by Flsion** [comment]
@Kigoal 这个是目前select内部处理方式导致的警告，使用了slots函数来获取数据，后面会用 provide 重构下select组件来解决这个问题，需要一些时间。

**Comment by Kigoal** [comment]
> @Kigoal 这个是目前select内部处理方式导致的警告，使用了slots函数来获取数据，后面会用 provide 重构下select组件来解决这个问题，需要一些时间。

`V2.7.0`版本安排得上吗，已经影响到功能的正常使用。`select` 选择选项后 `label` 不会更新而是触发 `warning`

> [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by Flsion** [comment]
@Kigoal 你试下给<option>加个label属性能够解决这个问题吗。这个的改动涉及的内容比较多，下个feature版本如果处理完成的话会带上

**Comment by Kigoal** [comment]
> @Kigoal 你试下给加个label属性能够解决这个问题吗。这个的改动涉及的内容比较多，下个feature版本如果处理完成的话会带上

👌，我试了一下给 `Select.Option`  加 `label` 可以正常使用了

**Comment by Flsion** [comment]
@Kigoal Select组件这次的改动比较大，我会再测试一下，防止出现较大的问题，这个应该能跟上下周三的版本
