### ISSUE TITLE
Modal组件的渲染会导致当前页面滚动条消失，关闭后才会出现

### ISSUE THREAD

**Issue by lq9958** [arco-design/arco-design-vue#2367]
![chrome-capture-2023-3-25 (1)](https://user-images.githubusercontent.com/34290782/234212308-57087314-a90c-4db9-ab37-061ed80bf55d.gif)
关闭对话框后滚动条会出现，导致页面宽度出现一个滚动条宽度的伸缩

**Comment by LuckyHookin** [comment]
@lq9958 这是模态框的标准行为，不是 bug，可以参考别的组件库：如ant-design：https://ant.design/components/modal-cn

**Comment by hahacium** [comment]
> @lq9958 这个是正常现象，开启 modal 后会锁定窗口的滚动，防止打开时页面内容会滚动

为什么不做滚动条位置补偿呢？开启 modal 后直接粗暴的隐藏滚动条，页面抖动很影响体验
