### ISSUE TITLE
Menu组件建议增加 `selected-keys` 自动展开父级菜单

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#237]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例

现在是这样显示，分组没有被展开
![5Xq1Yowyx1](https://user-images.githubusercontent.com/21240282/143164463-b7c7b6ff-3d65-4cbd-b303-d8be8cec5ba0.png)

## 预期解决问题

最好能根据设置的 `selected-keys` 自动展开所在的分组。配合 `auto-scroll-into-view` 一起使用
![vzf5BxYHmC](https://user-images.githubusercontent.com/21240282/143164471-887c314a-b174-4da6-b27d-7481c60fee64.png)

**Comment by kirazxyun** [comment]
收到，考虑增加一个配置项来做这件事情，非常感谢您的建议～
