### ISSUE TITLE
Statistic组件希望增加文本类型的支持

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#239]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
参照 `Ant Design Pro`  的页面设计。
![xky5xUMGvL](https://user-images.githubusercontent.com/21240282/143168092-7c01ca96-6704-4d52-8977-2c868c074dec.png)

## 预期解决问题
增加文本类型的支持。
如果有针对此类的设计标准也可以，主要不会设计。

**Comment by Flsion** [comment]
@Kigoal 这个可以用 Descriptions 组件实现，https://codepen.io/flsion/pen/mdMZVVE 。下个版本会增加一个右对齐的属性，可以更简单设置对齐方式

**Comment by hyingreborn** [comment]
描述与统计数值样式不一致，需要人工覆写样式。
用这个组件的时候，我需要在一堆statistic中，将部分指标显示为短字符串，如果能支持最好了 @flsion ，下面是图例：
<img width="1227" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/1283261/36e60820-95ac-4c3b-b0de-4fed023d35a9">

**Comment by hyingreborn** [comment]
@flsion 可以考虑一下这个问题吗
