### ISSUE TITLE
栅格Flex中使用Table滚动条无效

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#2397]
https://codesandbox.io/s/sleepy-river-ogej7q

![image](https://user-images.githubusercontent.com/30397859/236757044-32d0b1f5-8d87-4330-b555-e4457458c119.png)

**Comment by flsion** [comment]
@svipchao 这个是flex布局的特性导致的，可以修改下样式内容
https://codesandbox.io/s/modest-ptolemy-bwtvpp?file=/src/App.vue

**Comment by svipchao** [comment]
> @svipchao 这个是flex布局的特性导致的，可以修改下样式内容 https://codesandbox.io/s/modest-ptolemy-bwtvpp?file=/src/App.vue

滚动虽然解决了，因为右侧宽度不固定，所以会换行

https://codesandbox.io/s/blazing-architecture-rm62e4

![image](https://github.com/arco-design/arco-design-vue/assets/30397859/a63d0d72-65d9-4301-963a-d8a782390a34)
