### ISSUE TITLE
Table文档，row-class的函数支持，第一个参数类型错误

### ISSUE THREAD

**Issue by qq326943819** [arco-design/arco-design-vue#2399]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.45.3
- **Framework version:** vue@^3.2.47
- **Browser:** chrome112.0.0.0
- **Reproduction Link:** https://arco.design/vue/component/table#API

## What is expected?
文档注明record的类型是TableData，但是实测是TableDataWithRaw

**Comment by flsion** [comment]
@qq326943819 这个在 2.38.1 版本修复过，可以检查一下本地的版本

**Comment by qq326943819** [comment]
> @qq326943819 这个在 2.38.1 版本修复过，可以检查一下本地的版本

但是我本地版本是2.45.3啊……
