### ISSUE TITLE
No matches found: "--scope=@arco-design/{vite-plugin-arco-vue-docs,arco-vue-scripts}" 这是为什么

### ISSUE THREAD

**Issue by ZephyrTan** [arco-design/arco-design-vue#2402]
https://github.com/arco-design/arco-design-vue/blob/deac6645cfe2406278d6aecb0bb5a85f3812ae39/package.json#L7

**Comment by littleCareless** [comment]
同，我也出现了该问题。老铁有解决方法吗

**Comment by Zz-ZzzZ** [comment]
` "init": "lerna run build --stream --scope=@arco-design/vite-plugin-arco-vue-docs && lerna run build --stream --scope=@arco-design/arco-vue-scripts && lerna link && lerna run build --scope=@arco-design/arco-vue-docs-navbar && lerna run init --scope=@arco-design/web-vue",
`

我也有出现这个问题，我是把大括号内的两个模块拆开同时执行就可以了，具体原因没有仔细研究

**Comment by ZephyrTan** [comment]
> 同，我也出现了该问题。老铁有解决方法吗

我也是拆开了

**Comment by ZephyrTan** [comment]
> `"init": "lerna run build --stream --scope=@arco-design/vite-plugin-arco-vue-docs && lerna run build --stream --scope=@arco-design/arco-vue-scripts && lerna link && lerna run build --scope=@arco-design/arco-vue-docs-navbar && lerna run init --scope=@arco-design/web-vue",`
> 
> 我也有出现这个问题，我是把大括号内的两个模块拆开同时执行就可以了，具体原因没有仔细研究

我也是拆开了。还有好多地方有问题，我打包也有问题

**Comment by littleCareless** [comment]
> > `"init": "lerna run build --stream --scope=@arco-design/vite-plugin-arco-vue-docs && lerna run build --stream --scope=@arco-design/arco-vue-scripts && lerna link && lerna run build --scope=@arco-design/arco-vue-docs-navbar && lerna run init --scope=@arco-design/web-vue",`
> > 我也有出现这个问题，我是把大括号内的两个模块拆开同时执行就可以了，具体原因没有仔细研究
> 
> 我也是拆开了。还有好多地方有问题，我打包也有问题

对对我也是拆开的...我想打包看看效果啥的。我另一个项目已经给改造成pnpm的了（vue也改成2.7了），怕很多效果和官方的不一样 想看看官方的效果...

**Comment by Zz-ZzzZ** [comment]
> > `"init": "lerna run build --stream --scope=@arco-design/vite-plugin-arco-vue-docs && lerna run build --stream --scope=@arco-design/arco-vue-scripts && lerna link && lerna run build --scope=@arco-design/arco-vue-docs-navbar && lerna run init --scope=@arco-design/web-vue",`
> > 我也有出现这个问题，我是把大括号内的两个模块拆开同时执行就可以了，具体原因没有仔细研究
> 
> 我也是拆开了。还有好多地方有问题，我打包也有问题

init不能正确执行完毕吗，哪里需要用到打包

**Comment by ZephyrTan** [comment]
> 

不能正确执行，react上出问题了

**Comment by Zz-ZzzZ** [comment]
> > 
> 
> 不能正确执行，react上出问题了

不对吧，这是Vue版本的

**Comment by littleCareless** [comment]
我拆开后运行
 PS D:\Desktop\Vue.js-UI-Library\arco-design-vue> yarn run init
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@arco-design/vite-plugin-arco-vue-docs"
lerna info filter [ '@arco-design/vite-plugin-arco-vue-docs' ]        
lerna info Executing command in 1 package: "yarn run build"
lerna success run Ran npm script 'build' in 1 package in 5.3s:
lerna success - @arco-design/vite-plugin-arco-vue-docs        
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter including "@arco-design/arco-vue-scripts"
lerna info filter [ '@arco-design/arco-vue-scripts' ]      
lerna info Executing command in 1 package: "yarn run build"
@arco-design/arco-vue-scripts: src/scripts/docgen/utils/parse-interface.ts(62,31): error TS2345: Argument of type '{ displayName: string; 
exportName: string; props: PropDescriptor[]; }' is not assignable to parameter of type 'ComponentDoc'.
@arco-design/arco-vue-scripts:   Property 'tags' is missing in type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' but required in type 'ComponentDoc'.
lerna ERR! yarn run build exited 2 in '@arco-design/arco-vue-scripts'

**Comment by ZephyrTan** [comment]
> 不能正确执行，react上出问题了



> > > 
> > 
> > 
> > 不能正确执行，react上出问题了
> 
> 不对吧，这是Vue版本的

你看下arco-vue-docs-navbar是什么写的。不过我给这个在init的时候删掉了

**Comment by ZephyrTan** [comment]
> 我拆开后运行 PS D:\Desktop\Vue.js-UI-Library\arco-design-vue> yarn run init lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/vite-plugin-arco-vue-docs" lerna info filter [ '@arco-design/vite-plugin-arco-vue-docs' ] lerna info Executing command in 1 package: "yarn run build" lerna success run Ran npm script 'build' in 1 package in 5.3s: lerna success - @arco-design/vite-plugin-arco-vue-docs lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/arco-vue-scripts" lerna info filter [ '@arco-design/arco-vue-scripts' ] lerna info Executing command in 1 package: "yarn run build" @arco-design/arco-vue-scripts: src/scripts/docgen/utils/parse-interface.ts(62,31): error TS2345: Argument of type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' is not assignable to parameter of type 'ComponentDoc'. @arco-design/arco-vue-scripts: Property 'tags' is missing in type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' but required in type 'ComponentDoc'. lerna ERR! yarn run build exited 2 in '@arco-design/arco-vue-scripts'

我走一步卡一步，想基于他这个重新封装一套UI库，打包完了在应用的时候又有问题，不知道是我们个人电脑环境问题还是咋的，真不知道他们自己团队怎么跑通的

**Comment by littleCareless** [comment]
> > 我拆开后运行 PS D:\Desktop\Vue.js-UI-Library\arco-design-vue> yarn run init lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/vite-plugin-arco-vue-docs" lerna info filter [ '@arco-design/vite-plugin-arco-vue-docs' ] lerna info Executing command in 1 package: "yarn run build" lerna success run Ran npm script 'build' in 1 package in 5.3s: lerna success - @arco-design/vite-plugin-arco-vue-docs lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/arco-vue-scripts" lerna info filter [ '@arco-design/arco-vue-scripts' ] lerna info Executing command in 1 package: "yarn run build" @arco-design/arco-vue-scripts: src/scripts/docgen/utils/parse-interface.ts(62,31): error TS2345: Argument of type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' is not assignable to parameter of type 'ComponentDoc'. @arco-design/arco-vue-scripts: Property 'tags' is missing in type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' but required in type 'ComponentDoc'. lerna ERR! yarn run build exited 2 in '@arco-design/arco-vue-scripts'
> 
> 我走一步卡一步，想基于他这个重新封装一套UI库，打包完了在应用的时候又有问题，不知道是我们个人电脑环境问题还是咋的，真不知道他们自己团队怎么跑通的

巧了嘛这不是 我也是基于这个二次开发

**Comment by ZephyrTan** [comment]
> > > 我拆开后运行 PS D:\Desktop\Vue.js-UI-Library\arco-design-vue> yarn run init lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/vite-plugin-arco-vue-docs" lerna info filter [ '@arco-design/vite-plugin-arco-vue-docs' ] lerna info Executing command in 1 package: "yarn run build" lerna success run Ran npm script 'build' in 1 package in 5.3s: lerna success - @arco-design/vite-plugin-arco-vue-docs lerna notice cli v4.0.0 lerna info versioning independent lerna notice filter including "@arco-design/arco-vue-scripts" lerna info filter [ '@arco-design/arco-vue-scripts' ] lerna info Executing command in 1 package: "yarn run build" @arco-design/arco-vue-scripts: src/scripts/docgen/utils/parse-interface.ts(62,31): error TS2345: Argument of type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' is not assignable to parameter of type 'ComponentDoc'. @arco-design/arco-vue-scripts: Property 'tags' is missing in type '{ displayName: string; exportName: string; props: PropDescriptor[]; }' but required in type 'ComponentDoc'. lerna ERR! yarn run build exited 2 in '@arco-design/arco-vue-scripts'
> > 
> > 
> > 我走一步卡一步，想基于他这个重新封装一套UI库，打包完了在应用的时候又有问题，不知道是我们个人电脑环境问题还是咋的，真不知道他们自己团队怎么跑通的
> 
> 巧了嘛这不是 我也是基于这个二次开发

哥们，加个联系方式：tanzhifei@imotorlinx.com沟通一下。一直在踩坑。

**Comment by JedediahXu** [comment]
> @ZephyrTan 有具体的报错信息吗，这里的 init 是按顺序执行了下几个子包的构建，如果不行可以尝试到子包中单独运行下对应的命名

您好，就在刚刚不久前，我拉取下来之后，按照CONTRIBUTING.zh-CN.md的执行步骤去操作（没有修改任何问题），但是还是会遇到报错。  请问 这是因为我本地环境的问题吗？ 谢谢
![image](https://github.com/arco-design/arco-design-vue/assets/44160015/356719d3-e0a6-444b-bbf2-feb4f88d3985)

**Comment by oljc** [comment]
执行 `yarn run init` 报错：
```bash
No matches found: "--scope=@arco-design/{vite-plugin-arco-vue-docs,arco-vue-scripts}". Note: Brace expansion of arbitrary strings isn't currently supported. For more details, please read this issue: https://github.com/yarnpkg/berry/issues/22
```
### 解决方案：
1. 使用 `npm run init` 执行

2. 拆分大括号脚本
```js
"init": "lerna run build --stream --scope=@arco-design/vite-plugin-arco-vue-docs --scope=@arco-design/arco-vue-scripts && lerna link && lerna run build --scope=@arco-design/arco-vue-docs-navbar && lerna run init --scope=@arco-design/web-vue",
```
