### ISSUE TITLE
Table 组件 scrollbar（默认开启） 和 sticky-header 同时开启时，吸顶功能会失效

### ISSUE THREAD

**Issue by AnyaSeven** [arco-design/arco-design-vue#2411]
Table 组件 scrollbar（默认开启） 和 sticky-header 同时开启时，吸顶功能会失效

原因：scrollbar 开启时，会在arco-table-header 外层包裹一层 arco-scrollbar arco-scrollbar-type-embed，与 arco-table-header等高，导致吸顶失效

**Comment by zhangzhenfei** [comment]
问题影响很大，希望尽快处理

**Comment by fangwenzheng88** [comment]
好久了，一直没有修复
