### ISSUE TITLE
选择器下拉菜单的页脚页头中设置了输入框无法聚焦

### ISSUE THREAD

**Issue by jundaychan** [arco-design/arco-design-vue#2421]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.46.0
- **Framework version:** vue3
- **Browser:** chrome113.0.0.0

## What is expected?
可以聚焦

## Steps to reproduce
      <a-select
        :model-value="selectedTopic.id"
        :input-valuel="inputTopicTitle"
        :style="{ width: '100%' }"
        placeholder="请选择当前选题"
        :bordered="false"
        allow-search
        allow-create
        @change="handleChange"
      >
        <a-option
          v-for="tp in topicList"
          :key="tp.id"
          :value="tp.id"
          :label="tp.title"
        />
        <template #arrow-icon> <icon-down /> </template>
        <template #header>
          <div>
            <a-input-search
              class="edit-topic-input"
              placeholder="右键修改当前选题"
              search-button
              @search="handleTitleChange"
            >
              <template #button-icon>
                <icon-pen-fill />
              </template>
            </a-input-search>
          </div>
        </template>
      </a-select>

**Comment by flsion** [comment]
@jundaychan 可以设置 trigger-props 中的 preventFocus:false

**Comment by suKarXiao** [comment]
@flsion select本身能否preventFocus置为false，因为有个需求是需要用鼠标拉选选中值，现在select本身不能聚焦，无法拉取文字并复制
