### ISSUE TITLE
如何在表格内部放置图标（a-icon）？

### ISSUE THREAD

**Issue by Jake-00** [arco-design/arco-design-vue#2425]
### Discussed in https://github.com/arco-design/arco-design-vue/discussions/2423

<div type='discussions-op-text'>

<sup>Originally posted by **Jake-00** May 15, 2023</sup>
最近在尝试用 arco design 写前端，尝试在表格 table 放入图标但是表格不显示，过来请教下社区伙伴 🖐️ 
![image](https://github.com/arco-design/arco-design-vue/assets/60967034/75a041f2-aa3f-40d2-b087-b89c76563f2f)
demo 参考自：https://arco.design/vue/component/table#custom
```vue
<a-table :data="data" style="margin-top: 30px">
<template #columns>
<a-table-column title="Name">
    <a-table-column title="First Name" data-index="first"></a-table-column>
    <a-table-column title="Last Name" data-index="last"></a-table-column>
</a-table-column>
<a-table-column title="Salary" data-index="salary"></a-table-column>
<a-table-column title="Address" data-index="address"></a-table-column>
<a-table-column title="Email" data-index="email"></a-table-column>
<a-table-column title="Optional">
    <template #icon-check-circle>
        <icon-check-circle/>
    <!-- <a-button @click="$modal.info({ title:'Name', content:record.name })">view</a-button> -->
    </template>
</a-table-column>
</template>
</a-table>
```
</div>

**Comment by LIjiAngChen8** [comment]
给你写了三种方式的你自己看看吧
示范： https://codesandbox.io/s/answer-issues-2425-1toigq?file=/src/App.vue

**Comment by Jake-00** [comment]
> 给你写了三种方式的你自己看看吧 示范： https://codesandbox.io/s/answer-issues-2425-1toigq?file=/src/App.vue

很厉害，非常感谢你的耐心回复，完全解决了我的问题。不知道老哥是否是项目维护者，有没有可能将作为 demo 放进官方文档呢

**Comment by Jake-00** [comment]
@LIjiAngChen8 确实没看明白，再次感谢你的出手相助 😄
