### ISSUE TITLE
部分组件希望能优化下滚动条（类似 TimePicker 、Select）

### ISSUE THREAD

**Issue by Exclusive-gfj** [arco-design/arco-design-vue#243]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://element.eleme.cn/#/zh-CN/component/select

https://semi.design/zh-CN/input/timepicker

## What problem does this feature solve?
在 windows 系统中的滚动条实在不好看

**Comment by bzw1204** [comment]
期待，希望组件的默认滚动条样式可以同时优化下

**Comment by hehehai** [comment]
@Exclusive-gfj @bzw1204 hi, 自定义滚动条已经在 [beta](https://github.com/arco-design/arco-design-vue/tree/beta) 中，待测试稳定后会发布。
