### ISSUE TITLE
希望可以增加颜色选择组件

### ISSUE THREAD

**Issue by yplove156** [arco-design/arco-design-vue#2431]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
类似于这样https://www.naiveui.com/zh-CN/os-theme/components/color-picker

## 预期解决问题
如题

**Comment by flsion** [comment]
@yplove156 你好，arco 目前没有增加 color-picker 的计划，可以看下第三方组件
