### ISSUE TITLE
希望spin能有全屏的方式

### ISSUE THREAD

**Issue by YuukiLa** [arco-design/arco-design-vue#2453]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
当我想要全屏转圈圈的时候

## What problem does this feature solve?
现在spin只能套在容器外层， 没有全屏展示的方式

**Comment by shijian-Fan** [comment]
以指令的形式调用，全局loading遮罩的功能确实很有必要

**Comment by Zz-ZzzZ** [comment]
目前可以放在根组件里用pinia维护loading状态，以全屏展示的方式的话用函数形式调用会方便一些

**Comment by kaikaibenkai** [comment]
建议放在根组件里，套在页面组件外面

**Comment by wupeiwen** [comment]
> 以指令的形式调用，全局loading遮罩的功能确实很有必要

刚需！！！

**Comment by kaikaibenkai** [comment]
强烈建议自行在 `App.vue` 里放个 `<a-spin>`，通过 provide 的方式传递到子组件，让子组件可以设置 loading 状态。
这样方便维护，逻辑也很清晰。
如果是 Arco 来做，所有用 Arco 的页面都会多一层 `div`，影响太大

**Comment by YuukiLa** [comment]
目前是在app.vue套了一层a-spin，然后把状态放在pinia维护
