### ISSUE TITLE
【警告提示 Alert】 居中显示

### ISSUE THREAD

**Issue by QYG2297248353** [arco-design/arco-design-vue#2455]
顶部公告
通过设置 banner，可将警告提示作为顶部公告使用（去除边框和圆角）。
[https://arco.design/vue/component/alert#banner]([](https://arco.design/vue/component/alert#banner))

没有居中显示，首先既然是顶部公告，那么就希望居中显示，组件就是即用即走，改样式太麻烦了。
但是官方首页的公告就是居中显示。
经过排查 flex: 1; 出的问题，为了照顾其他的提示
`.arco-alert-body {
    position: relative;
    flex: 1;
}`
![image](https://github.com/arco-design/arco-design-vue/assets/56836951/d9849853-4c6c-4c2f-b243-cf3e87ae1b91)

希望的结果
![image](https://github.com/arco-design/arco-design-vue/assets/56836951/9dba7a38-9746-49c1-9f4b-e55b768a1951)

**Comment by flsion** [comment]
@QYG2297248353 是个功能点，目前没有居中的展示UI，可以增加一下
