### ISSUE TITLE
[select] 为什么select选择器value不能为boolean布尔值？？？

### ISSUE THREAD

**Issue by shijian-Fan** [arco-design/arco-design-vue#2457]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.46.0
- **Framework version:** vue
- **Browser:** chrome112.0.0.0

## What is expected?
能够使用Boolean作为value

## Steps to reproduce
当v-model绑定值为false时，select不能正常回显

**Comment by kaikaibenkai** [comment]
```vue
<a-select v-model='false' />
```

会被 Vue 编译器展开为

```vue
<a-select :modelValue='false' @update:modelValue='(v) => false = v' />
```

所以 `v-model` 必须是一个左值
