### ISSUE TITLE
2.46.1组件Modal 的width怎么失效了？设置的都没有用。

### ISSUE THREAD

**Issue by Aweerrweer** [arco-design/arco-design-vue#2459]
如题

**Comment by Zz-ZzzZ** [comment]
@Aweerrweer 麻烦提供一下复现链接哈

**Comment by Zz-ZzzZ** [comment]
2.46.1修复的是全屏的问题，你可以看一下修改记录，只加了一个是否定义全屏的prop判断

**Comment by Aweerrweer** [comment]
我刚更新，发现所有设置的width全部失效了，都变成默认的520了

**Comment by Zz-ZzzZ** [comment]
@Aweerrweer 回退2.46.0是正常的吗

**Comment by Aweerrweer** [comment]
是的，我现在回退2.46.0了

**Comment by Zz-ZzzZ** [comment]
@Aweerrweer   #2441 这个pr的改动有些问题，先不要用2.41.1

**Comment by jbhvip** [comment]
2.46.0，2.46.1两个版本都没办法设置modal宽度

**Comment by lq9958** [comment]
问题已经修复了，目前暂时请回退到上一个小版本😰

**Comment by jbhvip** [comment]
> 

上一个版本是哪个版本？ 可以设置？

**Comment by lq9958** [comment]
> > 
> 
> 上一个版本是哪个版本？ 可以设置？

2.46.0 可用

**Comment by jbhvip** [comment]
2.46.0modal可以设置宽度

**Comment by SunYuanOnly** [comment]
遇到相同的问题

**Comment by llk2yq** [comment]
看来测试覆盖不全面呀。
