### ISSUE TITLE
在vue3.3.4中，drawer报警告

### ISSUE THREAD

**Issue by ywenhao** [arco-design/arco-design-vue#2471]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.46.2
- **Framework version:** vue3.3.4
- **Browser:** chrome113.0.0.0
![image](https://github.com/arco-design/arco-design-vue/assets/37856060/42a98e99-710f-4393-9065-313078436258)

## What is expected?
警告消失

## Steps to reproduce
 [Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.

**Comment by Zz-ZzzZ** [comment]
麻烦提供一下复现链接，drawer组件没有定义`emit`事件`update:modalValue`只有`update:visible`，也没有对应的触发emit代码
