### ISSUE TITLE
Menu组件折叠后Item丢失data-v属性

### ISSUE THREAD

**Issue by Wykyoyo** [arco-design/arco-design-vue#248]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** "@arco-design/web-vue": "^2.6.0",
- **System:** win11
- **Browser:** chrome
- **Reproduction Link:** 

## What is expected?
折叠菜单后不丢失data-v属性

## Steps to reproduce
将菜单折叠

**Comment by hehehai** [comment]
@Wykyoyo hi, 这边测试是正常的，麻烦升级最新版本后看下，有问提的话可以提一个复现，再开启该问题。
