### ISSUE TITLE
tree-select 在开启虚拟滚动的情况下，点击复选框无效

### ISSUE THREAD

**Issue by fangwenzheng88** [arco-design/arco-design-vue#2482]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.47.0
- **Framework version:** 3.2.0
- **Browser:** chrome113.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/keen-gwen-2qnzvk?file=/src/App.vue

## What is expected?
选项未被选中，闪一下就没了。

## Steps to reproduce
1. 输入过滤条件“111”
2. 点击复选框，一定要点击复选框部分

**Comment by ZemarLi549** [comment]
修复了还是不行呀

**Comment by shitouguai** [comment]
该问题还是存在

**Comment by xjmango** [comment]
版本2.54.6，问题依旧存在
