### ISSUE TITLE
menu的事件问题

### ISSUE THREAD

**Issue by lyzerodragon** [arco-design/arco-design-vue#2486]
需要怎么写才能让 menu-item-click、sub-menu-click生效？我试了好几种方法都不行。
![image](https://github.com/arco-design/arco-design-vue/assets/51778235/52041e49-7526-432d-9b39-7358fb6e4a96)
![image](https://github.com/arco-design/arco-design-vue/assets/51778235/463452c8-6406-41bd-9cb7-2a84e16d0f28)

**Comment by flsion** [comment]
@lyzerodragon 可以使用 @menu-item-click="subMenuClick" 绑定事件
