### ISSUE TITLE
a-input-number组件在按顺序增加属性最小值min，步长setp，精度percision时，精度不生效

### ISSUE THREAD

**Issue by smile-sky20** [arco-design/arco-design-vue#2490]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.37.4
- **Framework version:** "arco-design-pro-vue": "^2.5.14"
- **Browser:** chrome114.0.0.0

## What is expected?
希望能说明或者修改这个bug，因为这个问题导致了我研究了一小时

## Steps to reproduce
当我使用如下的组件时
“a-input-number  v-model="form.sort" :min="1"  :step="1" :percision="0"></a-input-number>”
精度不能控制，还是能输入例如1.25255446，它是包含小数的，但是填写这些属性后效果应该是只能输入整数，就算输入小数，鼠标blur后，也会变成整数。
但是：
如果使用属性顺序发生变化的下面组件时，输入小数，鼠标blur后，会变成整数，也就是预期的效果
a-input-number  v-model="form.sort" :step="1" :min="1" :precision="0"></a-input-number>

**Comment by Saber-Kurama** [comment]
@smile-sky20   `percision` 这个单词拼错了，是`precision`

**Comment by smile-sky20** [comment]
我好捞，捞的淌口水&nbsp;


武汉加油！中国加油！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [arco-design/arco-design-vue] a-input-number组件在按顺序增加属性最小值min，步长setp，精度percision时，精度不生效 (Issue #2490)





 
@smile-sky20   percision 这个单词拼错了，是precision
