### ISSUE TITLE
date-picker组件复现显示错误

### ISSUE THREAD

**Issue by xiaomilaaz** [arco-design/arco-design-vue#2494]
代码：
<a-date-picker
                  style="width: 100%"
                  show-time
                  v-model="time"
                  format="YYYY-MM-DD hh:mm"
                />

开始选择是没有问题的，当复现比如给出 ：2023-10-20 20:00 就不显示正常  只能改成 YYYY-MM-DD hh:mm:ss

时间没有秒 就没办法复现出时间了。。

**Comment by flsion** [comment]
@xiaomilaaz 是的，这里的值需要和format保持一致

**Comment by xiaomilaaz** [comment]
> @xiaomilaaz 是的，这里的值需要和format保持一致

问题是 YYYY-MM-DD hh:mm 无法复现，只能用YYYY-MM-DD hh:mm:ss

**Comment by Booshaw** [comment]
> > @xiaomilaaz 是的，这里的值需要和format保持一致
> 
> 问题是 YYYY-MM-DD hh:mm 无法复现，只能用YYYY-MM-DD hh:mm:ss

我遇到的应该也是同样的问题, 需求就是不需要秒,即format=YYYY-MM-DD hh:mm ,数据也是2023-10-20 20:00同样的格式,但显示invalid Date;
重点是前几个版本还是好的

**Comment by Booshaw** [comment]
> > @xiaomilaaz 是的，这里的值需要和format保持一致
> 
> 问题是 YYYY-MM-DD hh:mm 无法复现，只能用YYYY-MM-DD hh:mm:ss

我遇到的应该也是同样的问题, 需求就是不需要秒,即format=YYYY-MM-DD hh:mm ,数据也是2023-10-20 20:00同样的格式,但显示invalid Date;
重点是前几个版本还是好的

**Comment by Booshaw** [comment]
> @xiaomilaaz 是的，这里的值需要和format保持一致

"@arco-design/web-vue": "2.46.1"版本下,即使format=YYYY-MM-DD hh:mm,  双向绑定的值依然为2023-08-18 21:38:02,带有ss;
