### ISSUE TITLE
<a-modal> needs a prop to disable the footer button

### ISSUE THREAD

**Issue by kaikaibenkai** [arco-design/arco-design-vue#2495]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 预期解决问题
Customizing the footer is more complex. 用自定义 footer 的话会麻烦一些。

## 额外补充
mark

**Comment by flsion** [comment]
@kaikaibenkai 没有太懂，form组件没有自带的底部 button 组件

**Comment by kaikaibenkai** [comment]
草，我是不是老年痴呆了，怎么会写成 form 😥

**Comment by oljc** [comment]
![image](https://github.com/user-attachments/assets/3a58e477-3109-4d93-97f8-354f838bcd2e)
