### ISSUE TITLE
Support `<a-input type='number'>`

### ISSUE THREAD

**Issue by kaikaibenkai** [arco-design/arco-design-vue#2504]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
```vue
<script lang="ts" setup>
import { Input } from '@arco-design/web-vue';
</script>

<template>
  <Input type='number' />
</template>
```

## 预期解决问题
When the `<a-input-number>` cannot meet the requirements, hope that `type` of `<a-input>` could be set to `number` to prevent the input of non numeric characters.
当 `<a-inupt-number>` 不能满足需求时，希望 `<a-input>` 组件的 `type` 可以设为 `number` 以阻止输入非数字的字符。

## 额外补充
mark

**Comment by flsion** [comment]
@kaikaibenkai 从设计层面我们希望数字输入由 `InputNumber` 组件支持，`Input` 组件仅支持纯文本内容。问一下是什么需求在使用 `InputNumber` 上不能够满足？

**Comment by kaikaibenkai** [comment]
> @kaikaibenkai 从设计层面我们希望数字输入由 `InputNumber` 组件支持，`Input` 组件仅支持纯文本内容。问一下是什么需求在使用 `InputNumber` 上不能够满足？

有的时候需要默认留空，而 `InputNumber` 必须有值

**Comment by Booshaw** [comment]
> > @kaikaibenkai 从设计层面我们希望数字输入由 `InputNumber` 组件支持，`Input` 组件仅支持纯文本内容。问一下是什么需求在使用 `InputNumber` 上不能够满足？
> 
> 有的时候需要默认留空，而 `InputNumber` 必须有值

你可以设置默认值为undefined,输入框就不显示“0”

**Comment by kaikaibenkai** [comment]
Link #2716
