### ISSUE TITLE
Select组件Option的value为对象,报错Maximum recursive updates exceeded in component ...

### ISSUE THREAD

**Issue by RJQingHuan** [arco-design/arco-design-vue#2515]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.47.1
- **Framework version:** 3.3.4
- **Browser:** chrome114.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/vvexmz?file=src%2FApp.vue

![uTools_1687674008930](https://github.com/arco-design/arco-design-vue/assets/53939074/d63d171d-2efe-4623-a208-57fd426e18ad)

**Comment by flsion** [comment]
@RJQingHuan 这里不能在模版中构建 value 的值对象，vue 每次渲染会创建一个新的对象并赋值给 value，导致 Option 组件一直更新。将 value 的对象放到 setup 中可以解决这个问题
https://stackblitz.com/edit/vvexmz-pxxuyr?file=src%2FApp.vue
