### ISSUE TITLE
Component <a-range-picker/> :  props (timePickerProps.defaultValue) 设置混乱

### ISSUE THREAD

**Issue by shalouzaixiayu** [arco-design/arco-design-vue#2517]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.47.1
- **框架版本:** Vue
- **浏览器版本:** chrome114.0.0.0

## 额外补充
希望尽快修复

## 预期结果
组件所显示的时分秒和给定的默认值顺序一致

## 复现步骤
<a-range-picker
    style="width: 360px; margin: 0 24px 24px 0;"
    show-time
     :time-picker-props="{
        defaultValue: ['00:00:00', '23:59:59'],
      }"
    format="YYYY-MM-DD HH:mm:ss"
  />
组件这样设置完成，用户先选择较大的时间，然后选择小的时间，组件所显示的时分秒和给定的默认值顺序不对，看了源码，组件的这个顺序是根据用户先后点击所决定的，但是事实不应该这样，要sort下。 由于没有codeOpen账户，所以粘贴下就可以复现了。

下面是图片， 如果能显示的话。
![8617e653-d8cc-4b1a-b728-41a4f37cacf0](https://github.com/arco-design/arco-design-vue/assets/62732002/4392bc54-a57e-4a49-a2ed-9238ebcd9a9e)

**Comment by shalouzaixiayu** [comment]
<a-range-picker
    style="width: 360px; margin: 0 24px 24px 0;"
    show-time
     :time-picker-props="{
        defaultValue: ['00:00:00', '23:59:59'],
      }"
    format="YYYY-MM-DD HH:mm:ss"
    @change="onChange"
    @select="onSelect"
    @ok="onOk"
  />

**Comment by liaolupup** [comment]
遇到同样的问题，找到过之前的fix（https://github.com/arco-design/arco-design-vue/pull/2302）但是没有修复成功。

**Comment by shalouzaixiayu** [comment]
@flsion 是的， 希望能在下个版本修复一下～

**Comment by Przeblysk** [comment]
@shalouzaixiayu 添加 :exchange-time="false" 属性

**Comment by liaolupup** [comment]
> @shalouzaixiayu 添加 `:exchange-time="false"` 属性
> 
> ```
>  <a-range-picker
>     style="width: 360px; margin: 0 24px 24px 0;"
>     show-time
>     :exchange-time="false"
>     :time-picker-props="{ defaultValue: ['00:00:00', '09:09:06'] }"
>     format="YYYY-MM-DD HH:mm"
>     @change="onChange"
>     @select="onSelect"
>     @ok="onOk"
>   />
> ```
> 
> 示例中这样配置是没问题的

加上`:exchange-time="false"`后确实问题解决了。谢谢大佬解惑

**Comment by shalouzaixiayu** [comment]
但是默认情况下，大部分情况下， 不都是不希望调换顺序吗，exchange-time 这个应该默认就是false啊，或者config-provider 组件可以向下派发 ？不然这样修改的地方很多很多呀。
@Przeblysk  @flsion @liaolupup

**Comment by flsion** [comment]
> 但是默认情况下，大部分情况下， 不都是不希望调换顺序吗，exchange-time 这个应该默认就是false啊，或者config-provider 组件可以向下派发 ？不然这样修改的地方很多很多呀。 @Przeblysk @flsion @liaolupup

这是个历史问题，由于之前的逻辑会自动调换时间，所以这里保留了 :exchange-time="true"，这里可以考虑为 config-provider   增加全局配置
