### ISSUE TITLE
[table] 怎么自定义thead内容

### ISSUE THREAD

**Issue by liu-xinhui** [arco-design/arco-design-vue#2524]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
把表头显示成一个文本框或者日期选择框

## What problem does this feature solve?
公司要求搜索条件加在表头中，并且是直接显示成文本框
<img width="698" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/7698511/0d3437db-dce6-4412-9ab2-acf645023f79">

**Comment by liu-xinhui** [comment]
已解决，titleSlotName可以实现

**Comment by hopegame** [comment]
怎样实现的？有例子吗？
