### ISSUE TITLE
form表单rules效验

### ISSUE THREAD

**Issue by wuxiaoyuw** [arco-design/arco-design-vue#2525]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
希望form表单rules里面能使用正则表达式直接进行效验

## What problem does this feature solve?
表单效验

**Comment by flsion** [comment]
@wuxiaoyuw 
![image](https://github.com/arco-design/arco-design-vue/assets/29793175/28eabec3-c5b7-4dc5-8b8c-f569a6400d73)
match字段支持正则表达式
