### ISSUE TITLE
Modal  ok-loading  不受控

### ISSUE THREAD

**Issue by Dongary** [arco-design/arco-design-vue#2534]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.47.0
- **Framework version:** 3.3.4
- **Browser:** Microsoft Edge 版本 114.0.1823.37 

## What is expected?
期望ok-loading属性受控

## Steps to reproduce
使用 modal 来新建一个表单弹窗， 监听on-before-ok事件在点击确定后校验表单状态、请求接口；根据接口成功再调用done（true）关闭modal；
为了让请求过程由动画，加了loading状态绑定在ok-loading上，希望 接口成功与否都有动画，但是实际在state.loading = false; 
发现动画并未停止，只有主动调用done（false）才会停止加载动画；
去掉ok-loading属性，发现只要点击button都会有加载动画，哪怕我一开始传的ok-loading属性还是为false，还是会出现，且在done（false）时才会消失；

**Comment by wforguo** [comment]
明显on-before-ok优先级更高，你用回调控制loading就可以了

![image](https://github.com/arco-design/arco-design-vue/assets/23009078/595893bc-ca74-4395-ae04-48aa825deebd)


有demo的

[https://codesandbox.io/s/q3qbwt?file=/src/App.vue](https://codesandbox.io/s/q3qbwt?file=/src/App.vue)

**Comment by Dongary** [comment]
> 明显on-before-ok优先级更高，你用回调控制loading就可以了
> 
> ![image](https://user-images.githubusercontent.com/23009078/250480084-595893bc-ca74-4395-ae04-48aa825deebd.png)
> 
> 有demo的
> 
> https://codesandbox.io/s/q3qbwt?file=/src/App.vue

👌，我还以为有bug，感谢
