### ISSUE TITLE
v2.48.0 trigged "Plugin has already been applied to target app." vue warning when using app.use(ArcoVue, {}) in main.ts

### ISSUE THREAD

**Issue by pzgz** [arco-design/arco-design-vue#2536]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.48.0
- **Browser:** chrome114.0.0.0

## What is expected?
The plugin shouldn't apply himself.

## Steps to reproduce
Upgraded arco-design-vue to 2.48.0 from 2.47.1, there will be warning: `main.ts:31 [Vue warn]: Plugin has already been applied to target app.` output in console, in the line `app.use(ArcoVue);` from main.ts. 

Reverted to 2.47.1 and the warning was gone. With new version, I commented the line which apply the arco plugin, the app still work, so the plugin might has been applied somewhere else, within v2.48.0.

**Comment by tanhh326** [comment]
![1688743576130](https://github.com/arco-design/arco-design-vue/assets/82007768/7d844019-3f64-41a1-8102-cc4807b6bd6a)
https://github.com/arco-design/arco-design-vue/blob/main/packages/web-vue/components/arco-vue.ts
这个问题出自这里

**Comment by clark-tan** [comment]
2.49.2  +1

**Comment by pzgz** [comment]
2.49.3，这个问题目前还在，挺奇怪，这应该是一个不小的问题

**Comment by pzgz** [comment]
这个问题在2.50.0版本中修复了，终于
