### ISSUE TITLE
你们这个服务器500的图标也太粗糙了吧？就像在上面乱涂了一层。

### ISSUE THREAD

**Issue by Wjinlei** [arco-design/arco-design-vue#2545]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.48.0
- **Browser:** chrome114.0.0.0

**Comment by kaikaibenkai** [comment]
talk is cheap, show me your ~~code~~ design

**Comment by Wjinlei** [comment]
> talk is cheap, show me your ~code~ design

笑死，你是项目组的吗？如果你说的话可以代表项目组的态度，那我可以关闭这个issue？
你这意思不就是说，你行你上吗？还有，你是中国人吗？你不会说中文吗？

**Comment by kaikaibenkai** [comment]
> > talk is cheap, show me your ~code~ design
> 
> 笑死，你是项目组的吗？如果你说的话可以代表项目组的态度，那我可以关闭这个issue？
> 你这意思不就是说，你行你上吗？还有，你是中国人吗？你不会说中文吗？

1. 开源项目，好好说话
2. issue helper 里明确建议使用英文
3. 请学习一下 IT 届名人名言

**Comment by Wjinlei** [comment]
666，你是可以的，我接受你的建议。
