### ISSUE TITLE
 ERROR  Failed to compile with 1 errors   

### ISSUE THREAD

**Issue by theseusyang** [arco-design/arco-design-vue#255]
ERROR  Failed to compile with 1 errors                              下午7:49:18

 error  in ./node_modules/@arco-design/web-vue/es/upload/utils.js

Module parse failed: Unexpected token (12:12)
You may need an appropriate loader to handle this file type.
|     try {
|       return JSON.parse(res);
|     } catch {
|       return res;
|     }

**Comment by kirazxyun** [comment]
你好，请提供一个可以复现的 demo，这样看我们无从下手哈

**Comment by theseusyang** [comment]
按照官方文档第一页，下载后
```
# npm
npm install --save-dev @arco-design/web-vue
```

执行命令报错

`npm run dev `

**Comment by Flsion** [comment]
@theseusyang 是安装组件库后，使用时报的错吗

**Comment by theseusyang** [comment]
启动时报错

**Comment by Flsion** [comment]
这个应该是 try...catch: Optional catch binding 的兼容性问题，如果是webpack的话，可以添加下 ES2019 的支持
