### ISSUE TITLE
table 组件的 rowClass 属性为 render 函数时, 是否要统一成传递 raw

### ISSUE THREAD

**Issue by hisland** [arco-design/arco-design-vue#2553]
- [] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

如图, 代码搜索出来,`renderSummaryRow` 和`renderRecord` 调用不一致, 是否该统一传递 raw

<img width="715" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/417448/3d087d32-57bd-448c-8966-bef19a8df5fb">

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.48.0
- **Browser:** chrome114.0.0.0

**Comment by flsion** [comment]
@hisland 嗯，应该都是使用 raw
