### ISSUE TITLE
table表格外面嵌套div添加display: flex之后滚动条出现异常

### ISSUE THREAD

**Issue by guo0588** [arco-design/arco-design-vue#2555]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.48.0
- **浏览器版本:** chrome114.0.0.0

**Comment by bert1020** [comment]
我也是 有解决吗
