### ISSUE TITLE
自定义表单规则

### ISSUE THREAD

**Issue by miaokela** [arco-design/arco-design-vue#2556]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.48.0
- **Browser:** chrome114.0.0.0

## What is expected?
文档中没有找到自定义表单校验规则的示例，我觉得示例太少了，只有字段跟方法给出来也不知道咋用，既然支持TS，那应该给出js/ts两个版本的示例，不然用起来查阅文档跟试错的成本太大了

**Comment by flsion** [comment]
@miaokela 正则匹配可以使用 match 属性，完全自定义可以使用 validator 属性，使用回调函数的方式。
示例：https://stackblitz.com/edit/pzxuy6?file=src%2FApp.vue
![image](https://github.com/arco-design/arco-design-vue/assets/29793175/b11482d7-7be0-4d36-b8c6-8aaf3f91fefe)
