### ISSUE TITLE
Menu菜单的trigger-props跟tooltip-props无效

### ISSUE THREAD

**Issue by Wykyoyo** [arco-design/arco-design-vue#256]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** "@arco-design/web-vue": "^2.6.0",
- **System:** win11
- **Browser:** chrome

## What is expected?
可以为菜单添加弹出框内容的类

## Steps to reproduce
![1 (2)](https://user-images.githubusercontent.com/32306550/143458064-ef28c295-4dc7-4277-a447-74928e8d3030.png)

![2 (2)](https://user-images.githubusercontent.com/32306550/143458090-dbd08847-4437-4d78-b4af-7bdc8d8ae86a.png)

**Comment by alphaelf** [comment]
same for `cascader` `trigger-props`
