### ISSUE TITLE
a-image-preview-group的子组件有设置preview-props的src时可以预览但是无法切换下一张

### ISSUE THREAD

**Issue by nonyotsugi** [arco-design/arco-design-vue#2574]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.48.1
- **框架版本:** 3.3.1
- **浏览器版本:** chrome114.0.0.0

## 预期结果
点击可以预览，但是无法切换下一张

## 复现步骤
<a-image-preview-group infinite>
    <a-space>
      <a-image
      :preview-props="{
        src: 'http://lake.ipindui.cn/1y/bbs/NNyMlZGaONrpstlUme0Qs/-j3dME4TQ-up-pTVM7OwQ/x9Oyfc92M9Hf8TpPeUvlQ.jpg-1080.jpg'

      }" 
      src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/cd7a1aaea8e1c5e3d26fe2591e561798.png~tplv-uwbnlip3yd-webp.webp" width="200" />
      <a-image :preview-props="{
        src: 'http://lake.ipindui.cn/1y/bbs/NNyMlZGaONrpstlUme0Qs/-j3dME4TQ-up-pTVM7OwQ/x9Oyfc92M9Hf8TpPeUvlQ.jpg-1080.jpg'

      }"  src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/6480dbc69be1b5de95010289787d64f1.png~tplv-uwbnlip3yd-webp.webp" width="200" />
      <a-image :preview-props="{
        src: 'http://lake.ipindui.cn/1y/bbs/NNyMlZGaONrpstlUme0Qs/-j3dME4TQ-up-pTVM7OwQ/x9Oyfc92M9Hf8TpPeUvlQ.jpg-1080.jpg'

      }"  src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/0265a04fddbd77a19602a15d9d55d797.png~tplv-uwbnlip3yd-webp.webp" width="200" />
      <a-image :preview-props="{
        src: 'http://lake.ipindui.cn/1y/bbs/NNyMlZGaONrpstlUme0Qs/-j3dME4TQ-up-pTVM7OwQ/x9Oyfc92M9Hf8TpPeUvlQ.jpg-1080.jpg'

      }"  src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/24e0dd27418d2291b65db1b21aa62254.png~tplv-uwbnlip3yd-webp.webp" width="200" />
    </a-space>
  </a-image-preview-group>

**Comment by Saber-Kurama** [comment]
应该是可以，将其中的一个src更换一个不同的图片试试看

**Comment by nonyotsugi** [comment]
换成arco-design示例的那些图片确实可以，但是使用我们自己的cdn图片就没法预览下一张，很奇怪...

**Comment by nonyotsugi** [comment]
操作：
![动画](https://github.com/arco-design/arco-design-vue/assets/56288345/f3ce918a-1787-41e3-8bc7-d441801ffad4)

代码：
 ```<a-image-preview-group>
        <a-image
          v-for="(path, index) in content.pic"
          :key="index"
          :width="100"
          :height="100"
          :src="imgFormat(path, '64')"
          :preview-props="{
            ...DefaultImagePreviewProps,
            src: imgFormat(path, '1080'),
          }"
          class="desc-margin desc-gap"
          style="cursor: pointer"
        />
      </a-image-preview-group>
```
