### ISSUE TITLE
当时每页条数不在条数列表中会产生空白

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#258]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-vue
- **系统版本:** 2.6.0
- **浏览器版本:** edge 95
- **复现地址:** https://codepen.io/duxphp/pen/oNeKZbR?editors=1000

## 预期结果
如果不在条目中应该显示当前设定的 pageSize 数量 而不是空白

## 复现步骤
如果开启 showPageSize 且每页条数 pageSize 不是再条目列表的数目中则会显示空白

**Comment by Flsion** [comment]
@duxphp 这个可以用 `page-size-options` 重新顶一下选择器的选项 https://codepen.io/flsion/pen/VwzozyY?editors=001
