### ISSUE TITLE
Use Drawer exception to eject and close in DropDown

### ISSUE THREAD

**Issue by miaokela** [arco-design/arco-design-vue#2589]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.1
- **Framework version:** vue3
- **Browser:** chrome115.0.0.0

## Steps to reproduce
        <a-dropdown trigger="click">
          <a-avatar
            :size="32"
            :style="{ marginRight: '8px', cursor: 'pointer' }"
          >
            <img alt="avatar" :src="userPic" />
          </a-avatar>
          <template #content>
            <a-doption>
              <a-space @click="handleClick">
                <icon-pen />
                <span>
                  {{ $t('messageBox.changePassword') }}
                </span>
                <a-drawer 
                  :width="340"
                  :visible="drawVisible" 
                  @ok="handleOk" 
                  @cancel="handleCancel"
                >
                  <template #title>
                    修改密码
                  </template>
                  <div>
                    ...
                  </div>
                </a-drawer>
              </a-space>
            </a-doption>
            <a-doption>
              <a-space @click="handleLogout">
                <icon-export />
                <span>
                  {{ $t('messageBox.logout') }}
                </span>
              </a-space>
            </a-doption>
          </template>
        </a-dropdown>
The phenomenon is that the drawer pops up before clicking the option, and the drawer pops out and disappears immediately after clicking the option. Is it my configuration problem or should I not use it this way?

**Comment by flsion** [comment]
The drop-down menu will be hidden after clicking by default, if you don't need this behavior, you can set `hide-on-select = false`
