### ISSUE TITLE
在微前端框架下作为子应用，popconfirm组件框架存在bug

### ISSUE THREAD

**Issue by eeve** [arco-design/arco-design-vue#2603]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.2
- **Browser:** chrome115.0.0.0

基座应用有一个左侧菜单，当菜单展开时效果如下（错位）

<img width="1428" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/16770728/795204fb-037f-4864-b604-c2057915cb69">

当菜单收起时，效果如下（正常，但箭头效果有误）
<img width="1432" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/16770728/aa63e725-af27-41ef-a9bd-c422d461dbfa">

代码如下
<img width="556" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/16770728/b1db4f64-b840-48f9-9b22-4f1d94a6ff82">

初步估计是left计算逻辑有问题

**Comment by LIjiAngChen8** [comment]
<img width="925" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/48879481/e5368808-f191-4fc1-b9e5-0d5c48c34ac9">
