### ISSUE TITLE
row-class设置之后，只有鼠标悬浮才有效果

### ISSUE THREAD

**Issue by miaokela** [arco-design/arco-design-vue#2606]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.40.0
- **Browser:** chrome115.0.0.0

## What is expected?
row-class设置之后，只有鼠标悬浮才有效果
<img width="1192" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/30903265/17e77f5a-f553-4f43-87ef-e027bca64e5f">
<img width="384" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/30903265/8534b1c9-3e65-4ad6-9392-61d65416b168">
<img width="462" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/30903265/903813bf-058f-4178-9c20-fd6dbd539c79">
<img width="440" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/30903265/d8d99ea9-0ca4-4cb6-8006-c5120fe3dff7">

**Comment by flsion** [comment]
@miaokela table 的颜色样式需要添加到 td 元素上，在 .rows-in-transit 中再加个 td 层

**Comment by miaokela** [comment]
能给个示例吗？使用#td插槽吗？没看明白怎么使用。

**Comment by erhsilence** [comment]
> 能给个示例吗？使用#td插槽吗？没看明白怎么使用。

```
:deep(.rows-in-transit td) {
  background-color: red;
}
```
