### ISSUE TITLE
checkbox 设置 value 无效

### ISSUE THREAD

**Issue by beloved-zh** [arco-design/arco-design-vue#2608]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.2
- **Framework version:** 3.2.0
- **Browser:** chrome115.0.0.0
- **Reproduction Link:** https://codesandbox.io/embed/cocky-paper-qrw6vs?fontsize=14&hidenavigation=1&theme=dark

**Comment by flsion** [comment]
@beloved-zh 指定值需要使用数组，const val = ref([]) ，空值情况下判定为需要 boolean 值
