### ISSUE TITLE
arco与windicss混用按钮导致出现边框

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#261]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** 2.6.0
- **系统版本:** macos
- **浏览器版本:** edge95
- **复现地址:** http://null.com

## 预期结果
按钮等焦点状态不会被 outline样式覆盖

## 复现步骤

部分第三方css框架会将 focus 状态写入outline样式，但是arco的 button 的 outline 是写到按钮上的 并非 focus 状态 导致被覆盖需要如下：
.arco-btn:focus {
  outline: none;
}

**Comment by Kigoal** [comment]
应该也没什么好办法吧，组件库也不太适合给样式加 `outline: none !important;`，这样就不利于二次开发和定制了

**Comment by flsion** [comment]
这个已经处理，如果还有问题可以再提个 issue
