### ISSUE TITLE
modal 可以设置width了，但是设置30vw这种无效，只能设置px？

### ISSUE THREAD

**Issue by fairySusan** [arco-design/arco-design-vue#2612]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.46.2
- **Framework version:** vue
- **Browser:** chrome115.0.0.0

**Comment by leslieeilsel** [comment]
![image](https://github.com/arco-design/arco-design-vue/assets/25165449/ecad9c1f-52b7-45c5-a935-9ecc6d382755)
试了下可以

**Comment by flsion** [comment]
@fairySusan 都是可以的，这里是直接加到 css
