### ISSUE TITLE
a-upload的 directory是不是不支持文件夹嵌套的文件上传？

### ISSUE THREAD

**Issue by miaokela** [arco-design/arco-design-vue#2614]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.2
- **Browser:** chrome115.0.0.0

## What is expected?
a-upload的 directory是不是不支持文件夹嵌套的文件上传？

**Comment by flsion** [comment]
@miaokela 是的，仅会上传一层的内容

**Comment by miaokela** [comment]
但是我试了，确实递归把所有文件都列出来了
