### ISSUE TITLE
排版 Typography设置 copyable 后复制按钮的Tooltip 在切换语言后仍为中文“复制”

### ISSUE THREAD

**Issue by 850036165** [arco-design/arco-design-vue#2615]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.49.2
- **浏览器版本:** chrome115.0.0.0

## 预期结果
Tooltip按语言切换

## 复现步骤
 <a-typography-paragraph copyable style="margin: 0">ABC</a-typography-paragraph>
切换为英文，鼠标放在复制按钮上Tooltip仍为中文

**Comment by flsion** [comment]
@850036165  我测试了下没有问题 https://stackblitz.com/edit/a785dn?file=src%2FApp.vue，有复现地址吗？
