### ISSUE TITLE
Pagination 组件前往功能，回车无效

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#262]
前往中输入数字 后 回车（小键盘回车键）无效， 大键盘上的 enter 是有效的。

![image](https://user-images.githubusercontent.com/21995186/143542912-45911ed3-f908-44a0-8eeb-be29150a6d87.png)

**Comment by Flsion** [comment]
@fangjc1986  https://codepen.io/flsion/pen/PoKMKpz 我试了下回车可以触发的，官网的也可以，这个可以复现一下吗

**Comment by fangjc1986** [comment]
我刚才测试了下，貌似是数字键盘中的 enter 无效， 大键盘中的 enter 是有效的。这两个 keyCode 不一样？

**Comment by fangjc1986** [comment]
> @fangjc1986 https://codepen.io/flsion/pen/PoKMKpz 我试了下回车可以触发的，官网的也可以，这个可以复现一下吗
我刚才测试了下，貌似是数字键盘中的 enter 无效， 大键盘中的 enter 是有效的。这两个 keyCode 不一样？

**Comment by fangjc1986** [comment]
> @fangjc1986 https://codepen.io/flsion/pen/PoKMKpz 我试了下回车可以触发的，官网的也可以，这个可以复现一下吗

我刚才测试了下，貌似是数字键盘中的 enter 无效， 大键盘中的 enter 是有效的。这两个 keyCode 不一样？

**Comment by Flsion** [comment]
我测试了下key一样code不一样😳，我调整一下
