### ISSUE TITLE
select组件远程搜索BUG

### ISSUE THREAD

**Issue by hackerslizc** [arco-design/arco-design-vue#2621]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.3
- **Framework version:** Vue
- **Browser:** chrome115.0.0.0

## What is expected?
搜索完成既展示

## Steps to reproduce
1. select 组件设置远程搜索
2. 填写要查询的关键词
3. 接口返回后响应的列表设置到了data 里
4. 页面上还是无数据，鼠标焦点移开，select再次获取到焦点后就会把上次的搜索结果展示出来

**Comment by vaas1993** [comment]
设置 filter-option = true
