### ISSUE TITLE
input-number能否提供控制（启用，禁用）上下按键加减功能的属性

### ISSUE THREAD

**Issue by kuzanFrozen** [arco-design/arco-design-vue#2624]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
我并不需要自动帮我上下键加减算法，比如在表单中input-number获取焦点后按了上下键盘，我想要的效果是可以切换到上下一个表单项并获得焦点

## 预期解决问题
增加属性

**Comment by kaikaibenkai** [comment]
读文档

```vue
<a-input-number hide-button />
```

**Comment by oljc** [comment]
#1983
