### ISSUE TITLE
表格第一行增加快速创建的入口

### ISSUE THREAD

**Issue by liuruibin** [arco-design/arco-design-vue#2632]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
TAPD中缺陷和需求表格上都有快速创建的操作，这个能否作为一个功能集成到表格里
<img width="843" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/23045261/ffaba892-fdbb-4927-935d-bc20c1cbf829">

## What problem does this feature solve?
可以快速增加一行数据

**Comment by flsion** [comment]
@liuruibin 这个需求比较偏业务了，可以通过组件封装实现下，类似 https://stackblitz.com/edit/2mqycf?file=src%2FApp.vue
