### ISSUE TITLE
grid布局中collapsed默认值为true时，报错，提示找不到suffix属性

### ISSUE THREAD

**Issue by zxuanhong** [arco-design/arco-design-vue#2639]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.50.0
- **Browser:** chrome115.0.0.0

## Extra info
grid布局中collapsed默认值为true时，报错，提示：TypeError: Cannot read properties of undefined (reading 'suffix'),同时布局也错乱
![iShot_2023-08-14_19 34 53](https://github.com/arco-design/arco-design-vue/assets/62740686/c5a08adf-09e3-4b0e-8f1f-af3fb30afb65)

**Comment by flsion** [comment]
@zxuanhong DEMO 中测试没有发现问题，https://stackblitz.com/edit/vkbcwg?file=src%2FApp.vue ，可以提供个复现地址看一下

**Comment by zxuanhong** [comment]
周末我写一个打上去





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2023年08月18日 19:09:13
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [arco-design/arco-design-vue] grid布局中collapsed默认值为true时，报错，提示找不到suffix属性 (Issue #2639)

@zxuanhong DEMO 中测试没有发现问题，https://stackblitz.com/edit/vkbcwg?file=src%2FApp.vue ，可以提供个复现地址看一下

**Comment by zxuanhong** [comment]
@flsion 周末我写一个demo贴上来

**Comment by lilifan1598** [comment]
当grid-item为动态删除时，确实会出现这个问题。貌似缓存了已经删除了的元素，导致去从空属性中查找suffix属性了
![image](https://github.com/arco-design/arco-design-vue/assets/39824392/7ca51a78-ee28-4eb2-b233-f2ca7b627faa)
