### ISSUE TITLE
如果我想在表格中自定义扩展行的渲染而不使用函数，怎么做？

### ISSUE THREAD

**Issue by Little-Ki** [arco-design/arco-design-vue#2650]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
不知道

## What problem does this feature solve?
类似这样的写法：
<a-table ...>
  <template #expandedRowRender="{ record }">
    ...
  </template>
</a-table>
似乎行不通，有什么方法吗

**Comment by hopegame** [comment]
我也遇到这个问题，如果expandedRowRender 需要插入其他插件就很麻烦
