### ISSUE TITLE
表格组件页码不更新

### ISSUE THREAD

**Issue by solstice-gao** [arco-design/arco-design-vue#2651]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.50.0
- **Framework version:** 2.47.0
- **Browser:** chrome115.0.0.0

## Extra info
这是一个bug

## What is expected?
表格下方的页码根据pagination进行实时更新

## Steps to reproduce
通过变量修改表格的pagination配置，表格下方的页码不会更新

**Comment by flsion** [comment]
@solstice-gao 简单测试了一下是可以的 https://stackblitz.com/edit/qg3aft?file=src%2FApp.vue

**Comment by flsion** [comment]
如果有问题可以补充一下复现地址
