### ISSUE TITLE
触发器 Trigger 的 scroll-to-close 功能缺陷

### ISSUE THREAD

**Issue by sun0225SUN** [arco-design/arco-design-vue#2652]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 

- **依赖包名 及 版本:** @arco-design/web-vue@2.50.0
- **框架版本:** Vue
- **浏览器版本:** chrome115.0.0.0
- **复现地址:** https://codesandbox.io/s/gifted-chaplygin-3279vv?file=/src/App.vue

## 复现步骤

scroll-to-close 的功能实现仅监听了 window 的 scroll，而非任意容器的 scroll。在非 window 下滚动时，弹出框不会隐藏。

![image](https://github.com/arco-design/arco-design-vue/assets/79169717/89e6fc61-d632-412b-bfa6-83abe8e6ef8d)

https://github.com/arco-design/arco-design-vue/blob/d445565dc92c29cf90d7a3279c6dfcbdde886b8f/packages/web-vue/components/trigger/trigger.tsx#L695C3-L698

## 预期结果

可参考 Trigger 的 update-at-scroll 功能实现

https://github.com/arco-design/arco-design-vue/blob/d445565dc92c29cf90d7a3279c6dfcbdde886b8f/packages/web-vue/components/trigger/trigger.tsx#L700-L712C8

## 额外补充

<del>前端萌新，不太熟悉组件的整体逻辑，PR下次一定。</del> 其实可以这样写以暂时满足需求。

``` vue
<a-trigger trigger="click" scroll-to-close update-at-scroll show-arrow>
...
</a-trigger>
```

<img height="300px" src="https://github.com/arco-design/arco-design-vue/assets/79169717/b2af1487-50fe-4fe7-9759-d04665381db7">

**Comment by flsion** [comment]
@sun0225SUN 是的，scroll-to-close 仅开启了 window 的监听，对于父级容器的监听需要统一开启 update-at-scroll 功能。如果全局需要可以使用 ConfigProvider 配置
