### ISSUE TITLE
a-table组件，可以增加定义children表头的功能吗

### ISSUE THREAD

**Issue by He-Qing-lin** [arco-design/arco-design-vue#2663]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.50.1
- **Browser:** chrome116.0.0.0

**Comment by flsion** [comment]
@He-Qing-lin https://arco.bytedance.net/vue/component/table#custom 可以通过自定义渲染的方式实现
