### ISSUE TITLE
table组件的cell-mouse-leave以及cell-mouse-enter不触发

### ISSUE THREAD

**Issue by 13873342501** [arco-design/arco-design-vue#2666]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.50.1
- **Browser:** chrome115.0.0.0

**Comment by flsion** [comment]
@13873342501 可以提供下复现地址吗，我测试了下是可以触发的 https://stackblitz.com/edit/hinrce?file=src%2FApp.vue

**Comment by 18513163335** [comment]
使用span-method 之后 不触发  cell-mouse-enter 和  cell-mouse-leave事件 请问问题解决了吗
