### ISSUE TITLE
TreeSelect组件中treeProps属性部分传入属性不生效

### ISSUE THREAD

**Issue by atom-git** [arco-design/arco-design-vue#2706]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.51.1
- **Framework version:** Vue
- **Browser:** chrome116.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/compassionate-wave-mhpt2l?file=/src/App.vue

## What is expected?
主要属性能够生效

## Steps to reproduce
修改 :treeProps="{ autoExpandParent: false, showLine: true }"的属性，部分属性不生效

**Comment by flsion** [comment]
@atom-git 检查了下，这个是因为 tree-select 默认开启了 tree 的 defaultExpandAll，这些属性是可以在tree中生效的

**Comment by atom-git** [comment]
> defaultExpandAll

建议默认开启，但是同样可以接受外部的控制，因为有时间候多级菜单非常多，展开效果不好
