### ISSUE TITLE
表格在树形数据的情况下使用合并单元格rowspan会报错

### ISSUE THREAD

**Issue by ba1q1** [arco-design/arco-design-vue#2725]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.52.0
- **浏览器版本:** chrome116.0.0.0
- **复现地址:** https://codesandbox.io/s/gracious-blackburn-7lfy7v?file=/src/App.vue

## 复现步骤
使用表格组件，传入树形数据，设置span-method并返回rowspan

![image](https://github.com/arco-design/arco-design-vue/assets/36357020/c5a178ff-42dd-471a-ae95-dfb941754b1b)

**Comment by ba1q1** [comment]
在/es/table/hooks/use-span.js文件内发现错误代码：
![image](https://github.com/arco-design/arco-design-vue/assets/36357020/7cce9142-22d6-4634-bf9d-c99c6ebf026f)
这里读取的tableData的下标不应该加上rowIndex才对，改正后代码：
![image](https://github.com/arco-design/arco-design-vue/assets/36357020/970b1a53-0dd9-4a62-a51d-c145cca9434c)
改正后运行，单元格合并正常，无报错、无样式错误
![image](https://github.com/arco-design/arco-design-vue/assets/36357020/233ac7f0-22f7-48a0-bb6e-8dc83ace66e0)

**Comment by ba1q1** [comment]
@flsion 大佬能不能尽快修复一下

**Comment by Rudy24** [comment]
大佬们赶紧修复下啊

**Comment by Rudy24** [comment]
@flsion 大佬能不能尽快修复下~~~~~~~~~~~~

**Comment by Rudy24** [comment]
@ba1q1 提个pr 让他们测试 合并到主分支上去

**Comment by ba1q1** [comment]
@flsion 还有新的问题，麻烦看看 [#2948](https://github.com/arco-design/arco-design-vue/issues/2948)
