### ISSUE TITLE
a-table sticky-header属性无效

### ISSUE THREAD

**Issue by Cheerwhy** [arco-design/arco-design-vue#2728]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.52.0
- **框架版本:** vue@3.3.4
- **浏览器版本:** chrome117.0.0.0
- **复现地址:** https://arco.design/vue/component/table#sticky

## 预期结果
表头吸顶

## 复现步骤
打开链接，也就是官方文档就可以复现

**Comment by starzeng** [comment]
最新版2.54.1也没有修复，是不是不维护了

**Comment by cyrilluce** [comment]
这个问题22年就有人提了( #1852 ), 到现在还没有修复
