### ISSUE TITLE
自动补全 AutoComplete 事件缺少 获取焦点和失去焦点

### ISSUE THREAD

**Issue by QYG2297248353** [arco-design/arco-design-vue#2734]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
输入框事件：
focus
输入框获取焦点时触发
ev: FocusEvent
blur
输入框失去焦点时触发
ev: FocusEvent
希望：自动补全也能够拥有这两个事件

## 预期解决问题
自动补全，说白了就是带有联想功能的输入框，既然是输入框那么就会由焦点的需求，当前版本只有使其获取焦点或失去焦点的方法。在事件选项中就没有获取焦点时/失去焦点时的事件。在输入框 Input 就有，但是两边不是嵌套组件无法使用，focus
输入框获取焦点时触发
ev: FocusEvent
blur
输入框失去焦点时触发
ev: FocusEvent

**Comment by flsion** [comment]
@QYG2297248353 AutoComplete 没有单独实现这两个事件，添加 focus 和 blur 事件可以透传到 input 组件，目前是可以使用的
