### ISSUE TITLE
能添加一个颜色选择器吗

### ISSUE THREAD

**Issue by zj-kenzhou** [arco-design/arco-design-vue#2752]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.1
- **Browser:** chrome118.0.0.0

**Comment by ion1ze** [comment]
确实，没有颜色选择器，没有色板

**Comment by mlsjla** [comment]
me too
