### ISSUE TITLE
Modal 国际化异常

### ISSUE THREAD

**Issue by han3sui** [arco-design/arco-design-vue#2768]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.1
- **Browser:** chrome118.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/jmq8km?file=src%2FApp.vue

## What is expected?
确认、取消文案应该是英文，实际显示中文

## Steps to reproduce
函数调用Modal

**Comment by lin-97** [comment]
ConfigProvider 配 global=true 了没有?

**Comment by han3sui** [comment]
> ConfigProvider 配 global=true 了没有?

配置了，上面有复现的链接

**Comment by lin-97** [comment]
在main.js  加上
import { Modal } from '@arco-design/web-vue';

const app = createApp(App);
Modal._context = app._context;
Modal最后面有说明

**Comment by han3sui** [comment]
> 在main.js 加上 import { Modal } from '@arco-design/web-vue';
> 
> const app = createApp(App); Modal._context = app._context; Modal最后面有说明

确实有效，感谢。没注意到这块文档

**Comment by lin-97** [comment]
有问题建议去微信群或者飞书群吧，这种小问题发在issue没人看到回复很慢的，大佬又没空理你

**Comment by han3sui** [comment]
> 有问题建议去微信群或者飞书群吧，这种小问题发在issue没人看到回复很慢的，大佬又没空理你

飞书群是官网下面挂的那个吗？没有看到微信群呢，能指下路不😄

**Comment by lin-97** [comment]
对，微信群你先加飞书群吧
