### ISSUE TITLE
upload 组件  accept 为 .mp4 的时候在 edge 浏览器，不生效 

### ISSUE THREAD

**Issue by hzfvictory** [arco-design/arco-design-vue#2769]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.1
- **Browser:** chrome116.0.0.0

**Comment by LIjiAngChen8** [comment]
@hzfvictory 你好，我这边复现是没有问题的。暂时先关闭该 issue 了。可以参考 [accept规则](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers) 、[MIME](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) ，如有问题可随时提供复现代码。
