### ISSUE TITLE
bug(watermark): 暗色模式水印字体颜色不变

### ISSUE THREAD

**Issue by Loongphy** [arco-design/arco-design-vue#2785]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.53.1
- **Browser:** chrome119.0.0.0

![image](https://github.com/arco-design/arco-design-vue/assets/42089082/a6609692-7368-43e2-8f5a-5f657ca43c95)

**Comment by C-Jeril** [comment]
<a-watermark
      :content="['arco.design', dayjs().format('YYYY-MM-DD')]"
      :gap="[180, 180]"
      :rotate="-22"
    :z-index="6"
    :alpha="1"
    :anti-tamper="true"
    :grayscale="false"
    :repeat="true"
    :staggered="false"
      >
        <div style="width: 100%; height: 300px"/>
      </a-watermark>
      我尝试了对应的解决方案，但是也同样不管用，而且还会影响暗色模式

**Comment by C-Jeril** [comment]
`  <a-watermark
      :content="['arco.design', dayjs().format('YYYY-MM-DD')]"
      :gap="[180, 180]"
      :rotate="-22"
    :z-index="6"
    :alpha="1"
    :anti-tamper="true"
    :grayscale="false"
    :repeat="true"
    :staggered="false"
      >
        <div style="width: 100%; height: 300px"/>
      </a-watermark>`

**Comment by C-Jeril** [comment]
曾经用过一个小伙伴推荐的水印感觉还不错，属于悬浮在最上一层的，且不干扰正常视觉。
`<template>
  <div class="watermark-container">
    
    <div class="watermark-text">Hello JSC</div>
  </div>
</template>

<script lang="ts">
  export default {
    name: 'GlobalWatermark',
    // TypeScript 代码，如果有的话
  };
</script>

<style scoped>
  .watermark-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    z-index: 9999;
  }
  .watermark-text {
    /* 水印文本，设置为绝对定位，使其不响应点击事件，并设置位置 */
    position: absolute;
    top: 50%;
    /* 根据需要调整位置 */
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 30px;
    /* 根据需要调整字体大小 */
    color: rgba(0, 0, 0, 0.1);
    /* 根据需要调整颜色和透明度 */
    user-select: none;
  }
</style>
`

**Comment by Loongphy** [comment]
> 曾经用过一个小伙伴推荐的水印感觉还不错，属于悬浮在最上一层的，且不干扰正常视觉。 `
> 
> Hello world
> <script lang="ts"> export default { name: 'GlobalWatermark', // TypeScript 代码，如果有的话 }; </script> <style scoped> .watermark-container { position: fixed; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; z-index: 9999; } .watermark-text { /* 水印文本，设置为绝对定位，使其不响应点击事件，并设置位置 */ position: absolute; top: 50%; /* 根据需要调整位置 */ left: 50%; transform: translate(-50%, -50%); font-size: 30px; /* 根据需要调整字体大小 */ color: rgba(0, 0, 0, 0.1); /* 根据需要调整颜色和透明度 */ user-select: none; } </style>
> `

You can custom the font color like this:
```Vue
<a-watermark :font=" { color: theme === 'light' ? 'white' : 'black' } "/>
```
