### ISSUE TITLE
ImagePreviewGroup组件触发props类型警告

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#279]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.7.0
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 96
- **复现地址:** https://arco.design

## 预期结果
正常不应该触发警告

## 复现步骤

`ImagePreviewGroup` 传递了一些 `ImagePreview` 没有的 `props` 属性导致触发警告。

```vue
<Image.PreviewGroup :src-list="['','','']" />
```

> [Vue warn]: Extraneous non-props attributes (disabled, error, size) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

**Comment by kirazxyun** [comment]
你好，我们这边无法复现这个问题，请提供一个可以复现的 demo 。

**Comment by Kigoal** [comment]
> 你好，我们这边无法复现这个问题，请提供一个可以复现的 demo 。

不好意思，这个是`Form.Item`传递的，我自己增加一下处理一下解决了
