### ISSUE TITLE
表格列排序无法触发排序事件

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#280]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco
- **系统版本:** 2.7.9
- **浏览器版本:** edge95
- **复现地址:** https://codepen.io/duxphp/pen/dyzxLLY?editors=1111

## 预期结果
可以触发该事件

## 复现步骤
将 列中的sortable 当做变量是会无法触发其中的 sorter 事件， 直接写入到列参数是偶尔也无法触发，原因不明

**Comment by duxphp** [comment]
找了问题所在了  如果为一条数据则不会触发该事件 如果为多条数据则会触发

**Comment by Flsion** [comment]
@duxphp sorter是在排序时使用的方法，事件的话可以试试 @sorter-change
