### ISSUE TITLE
富文本编辑器

### ISSUE THREAD

**Issue by lxccc812** [arco-design/arco-design-vue#2802]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://github.com/wangeditor-team/wangEditor

## 预期解决问题
提供一个官方的富文本编辑器

**Comment by LIjiAngChen8** [comment]
富文本编辑器非普通的组件需要非常大的精力维护。所以暂时不会有相关开发计划。
