### ISSUE TITLE
Select 组件 多选且固定显示数量情况下，显示闪烁bug

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#283]
组件处理逻辑貌似是，先添加再清除。

![select 多选 bug](https://user-images.githubusercontent.com/21995186/143815678-2f8f9762-049b-47fe-8389-304973b85ea7.gif)

**Comment by Flsion** [comment]
@fangjc1986 收到，这个应该是动画造成的，我试下在显示更多标签时把动画去掉可以解决吗
