### ISSUE TITLE
a-table 数据过多，会出现明显的卡顿

### ISSUE THREAD

**Issue by guo0588** [arco-design/arco-design-vue#2838]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.0
- **框架版本:** vue
- **浏览器版本:** chrome119.0.0.0

## 复现步骤
当table列超过十列，数据五十行左右 ，页面菜单缩放会出现明显的卡顿问题。还请麻烦处理一下。

**Comment by chree188** [comment]
有解决放了吗
