### ISSUE TITLE
RangePicker组件mode="year"时 弹出选择框后，点击年份翻页按钮没有反应

### ISSUE THREAD

**Issue by wwwylo** [arco-design/arco-design-vue#2851]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.3
- **框架版本:** vue 3.3.9
- **浏览器版本:** chrome119.0.0.0

## 预期结果
正常使用

**Comment by Jomorx** [comment]
看了下官网上演示的demo也不行
