### ISSUE TITLE
disabled 后  placeholder 和 数据填充的样式颜色一样 ，根本分不清 

### ISSUE THREAD

**Issue by hzfvictory** [arco-design/arco-design-vue#2866]
![image](https://github.com/arco-design/arco-design-vue/assets/38562125/1ab2caaf-c5c7-4a0b-844e-893e961c1e80)

**Comment by flsion** [comment]
@hzfvictory 默认样式是这样的，这个可以通过自定义主题或者自行修改样式处理

**Comment by hzfvictory** [comment]
> @hzfvictory 默认样式是这样的，这个可以通过自定义主题或者自行修改样式处理

可以修改那个less 变量 统一更改呢
