### ISSUE TITLE
更新到vite5.0.10以后就没办法正常dev，报错为ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by C-Jeril** [arco-design/arco-design-vue#2868]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.3
- **浏览器版本:** chrome120.0.0.0

## 预期结果
希望您能够支持vite5.0.10

## 复现步骤
报错内容
> arco-design-pro-vue@1.0.0 dev E:\hello-arco-pro\Frontend
> vite --config ./config/vite.config.dev.ts

node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './parseAst' is not defined by "exports" in E:\hello-arco-pro\Frontend\node_modules\.pnpm\vite@5.0.10_@types node@20.5.1_less@4.2.0\node_modules\rollup\package.json imported from E:\hello-arco-pro\Frontend\node_modules\.pnpm\vite@5.0.10_@types node@20.5.1_less@4.2.0\node_modules\vite\dist\node\cli.js
    at new NodeError (node:internal/errors:406:5)
    at exportsNotFound (node:internal/modules/esm/resolve:268:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:598:9)
    at packageResolve (node:internal/modules/esm/resolve:772:14)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.

更新到vite5.0.10以后就没办法正常dev，报错为ERR_PACKAGE_PATH_NOT_EXPORTED

**Comment by LIjiAngChen8** [comment]
**原因**
在 `vite5` 中官方已经内置了 [rollup](https://cn.vitejs.dev/guide/migration-from-v3.html#rollup-3) 了，而[Arco Pro](https://github.com/arco-design/arco-design-pro-vue) 的`package.json` 文件中安装了rollup且在resolutions配置项指定了rollup特定版本导致出现了这个错误。
**解决：**
移除下图中[rollup](https://github.com/arco-design/arco-design-pro-vue/blob/main/arco-design-pro-vite/package.json#L77)、[resolutions.rollup](https://github.com/arco-design/arco-design-pro-vue/blob/main/arco-design-pro-vite/package.json#L99) 后重新下载依赖即可解决此问题。
<img width="601" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/48879481/63e9fc61-c34c-42d6-a3d5-9b936024cb4b">

<img width="533" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/48879481/e84d85c9-c833-4cbb-985e-2fc81e44f337">

如果想做更多关于新版 `vite5` 配置 可以参考[arco-admin](https://github.com/LIjiAngChen8/arco-admin)模板 点个star哦💗。

**Comment by C-Jeril** [comment]
感谢，问题已解决！
