### ISSUE TITLE
modal update方法无效，无法更新content

### ISSUE THREAD

**Issue by zxuanhong** [arco-design/arco-design-vue#2873]
- [X] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
1. 配置一下更新modal content内容无效
```
let secondsToGo = 3
const model = Modal.success({
  title: '错误提示',
  content: `${secondsToGo}秒后将自动退出登录,确认立马退出!!!`,
  onOk: () => {
    console.log('-点击了ok---')
  },
})
setInterval(() => {
  secondsToGo -= 1
  model.update({
    content: `${secondsToGo}秒后将自动退出登录,确认立马退出!!!`,
  } as ModalUpdateConfig)
}, 1000)
```
2. 官方对应说明
<img width="839" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/62740686/13d210e6-4928-41dc-b41a-86acf956dc0e">

**Comment by LIjiAngChen8** [comment]
@zxuanhong 你好, 这个 update的配置是不包含 `content` 的。你的需求可以参考 [demo](https://codesandbox.io/p/sandbox/zealous-banzai-z8r5v9?file=%2Fsrc%2FApp.vue%3A30%2C20)

具体配置  [ModalUpdateConfig](https://github.com/arco-design/arco-design-vue/blob/002604fdd6fbaa19a86d9afa2fbe62e7505fef7e/packages/web-vue/components/modal/interface.ts#L223C1-L236C3)

**Comment by zxuanhong** [comment]
非常感谢你的回复一以及提供示例





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年01月18日 18:46:01
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [arco-design/arco-design-vue] modal update方法无效，无法更新content (Issue #2873)

@zxuanhong 你好, 这个 update的配置是不包含 content 的。你的需求可以参考 demo
具体配置 ModalUpdateConfig
