### ISSUE TITLE
textarea指定高度后的样式问题

### ISSUE THREAD

**Issue by GardenHamster** [arco-design/arco-design-vue#2875]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.53.3
- **Framework version:** 3.2.40
- **Browser:** chrome114.0.5735.289

我想给textarea一个初始高度，并且输入的内容超出高度后会显示滚动条
```
<a-form-item field="cookie" label="Cookie" tooltip="Cookie" feedback>
  <a-textarea v-model:model-value="formModel.cookie" :style="{ minHeight: '200px' }" placeholder="输入Cookie..." allow-clear />
</a-form-item>
```
实际结果是滚动条的高度不会自适应textarea的高度
![image](https://github.com/arco-design/arco-design-vue/assets/89188316/c8f83f0c-4686-46e0-8917-d0014540db7f)

盲猜是子元素textarea的高度没跟上，但是我又没办法调整子元素的高度
![image](https://github.com/arco-design/arco-design-vue/assets/89188316/c85ee7dd-bfaa-4582-9aeb-aeccc565a3a7)

**Comment by flsion** [comment]
@GardenHamster textarea 不会自动撑开高度，需要为内部的 textarea 元素也手动指定 minHeight。可以给内部的 .arco-textarea 样式也加上高度样式

**Comment by GardenHamster** [comment]
可否提供一个属性，方便设置内部元素的样式？

**Comment by GardenHamster** [comment]
@flsion

**Comment by GardenHamster** [comment]
在scoped中设置.arco-textarea的样式根本起不到任何效果
```html
<style scoped>
  .arco-textarea {
      height: 120px !important;
      min-height: 120px !important;
  }
</style>
```

**Comment by wangxiaocuo** [comment]
@GardenHamster 为什么不用 auto-size ？

**Comment by GardenHamster** [comment]
> @GardenHamster 为什么不用 `auto-size` ？
@wangxiaocuo auto-size指定高度后不会出现滚动条

**Comment by wangxiaocuo** [comment]
@GardenHamster 

```vue
<template>
  <a-textarea
    default-value="你好"
    :auto-size="{
      minRows: 2,
      maxRows: 5
    }"
  />
</template>
```
是要这种效果不：
<img width="769" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/16472134/8e379fea-87c7-4846-85b3-95bb61ea0227">

**Comment by wangxiaocuo** [comment]
@GardenHamster 如果需要具体的高度

```vue
<template>
  <a-textarea default-value="你好" />
</template>

<style scoped>
:deep(.arco-textarea) {
  height: 100px;
}
</style>
```

<img width="765" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/16472134/5ea48d09-6e8a-4479-aa86-7b9c99f83961">

这不就齐活了   👀

**Comment by GardenHamster** [comment]
@wangxiaocuo 感谢佬，是我理解错minRows和maxRows的意思了，

**Comment by wangxiaocuo** [comment]
客气啦～
