### ISSUE TITLE
table暗黑模式下  开启stripe 设置fixed的列 条纹背景色问题

### ISSUE THREAD

**Issue by wpp19146456770** [arco-design/arco-design-vue#2876]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.3
- **浏览器版本:** chrome120.0.0.0

**Comment by wpp19146456770** [comment]
![20231221-115912](https://github.com/arco-design/arco-design-vue/assets/88469702/5df8a635-fa0e-4970-a160-542986aef3b4)

**Comment by flsion** [comment]
@wpp19146456770 我使用 DEMO 测试是正常的，麻烦提供一个复现地址链接

**Comment by wpp19146456770** [comment]
复现地址：https://stackblitz.com/edit/d763mz?file=src%2FApp.vue,package.json,src%2Fmain.js,vite.config.js   
需要把.Preview2-iframe-xOzi5的背景色去掉（如下图）
![image](https://github.com/arco-design/arco-design-vue/assets/88469702/f8d29ba8-c326-4b21-963a-14611a47770b)
复现图（如下）：
![image](https://github.com/arco-design/arco-design-vue/assets/88469702/e5ad6cba-b9cc-4a25-aa11-661158a1ac3c)

**Comment by wpp19146456770** [comment]
@flsion
