### ISSUE TITLE
a-textarea 在限制显示字数的情况之下，会出现部分遮挡问题

### ISSUE THREAD

**Issue by guo0588** [arco-design/arco-design-vue#2883]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.3
- **框架版本:** vue
- **浏览器版本:** chrome120.0.0.0

## 复现步骤
a-textarea 在限制显示字数的情况之下，会出现部分遮挡问题

![image](https://github.com/arco-design/arco-design-vue/assets/62804573/9d70d296-8c9b-4cd0-9bcc-6e59fe2dc562)

**Comment by oljc** [comment]
![image](https://github.com/user-attachments/assets/1778f4c0-b00f-4fc5-b40f-826b2bb3300d)
