### ISSUE TITLE
无法通过npm升级至2.54.0

### ISSUE THREAD

**Issue by BlueCat918** [arco-design/arco-design-vue#2884]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.53.3
- **浏览器版本:** chrome120.0.0.0

**Comment by zxuanhong** [comment]
同样，我npm官网访问错了，这个世界还有第二个????

**Comment by classfang** [comment]
npm上看了，目前还没发版本。
