### ISSUE TITLE
arco-vue的tabs的hover状态底色没有transition，但是react版本有

### ISSUE THREAD

**Issue by shaoerkuai** [arco-design/arco-design-vue#2894]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.1
- **浏览器版本:** chrome120.0.0.0
Hover底色：
![image](https://github.com/arco-design/arco-design-vue/assets/117460332/5368449d-ebf0-4dc2-9442-a3b247909b09)
hover的底色没有transition，但是react下的效果稍微有些不同，多了一个0.2s的transition

![image](https://github.com/arco-design/arco-design-vue/assets/117460332/716dbe91-fea2-428a-8edd-1611a1cd2813)

个人认为react和vue的视觉效果应该一致会比较好些

**Comment by Loongphy** [comment]
两边不是一样的吗

![image](https://github.com/arco-design/arco-design-vue/assets/42089082/ba298a57-f64c-4f67-9976-88abad81d89b)
