### ISSUE TITLE
分页 Pagination show-total文案不能自定义

### ISSUE THREAD

**Issue by Anm520** [arco-design/arco-design-vue#290]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
antd vue  :show-total="(total, range) => `${range[0]}-${range[1]} of ${total} items`"

## 预期解决问题
show-total文案希望可以自定义

## 额外补充
change page-size-change事件能不能有个合在一起的总事件，复杂的分页器 page-size和页码点击事件肯定是混合在一起的，其中有一个变化，都要把所有的属性值拿到去做异步查询的。分开需要写多个监听函数，比较麻烦，还要手动整合

**Comment by Flsion** [comment]
今天的版本没有时间添加了，会在2.9.0添加一下
