### ISSUE TITLE
升级到3.4.6后有getCurrentInstance() called inside a computed getter 和toRefs() expects a reactive object but received a plain one两个warning

### ISSUE THREAD

**Issue by atom-git** [arco-design/arco-design-vue#2907]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Vue升级到3.4.6，arco design vue 2.54.1

## What problem does this feature solve?
Vue升级到3.4.6有getCurrentInstance() called inside a computed getter 和toRefs() expects a reactive object but received a plain one两个warning

**Comment by LIjiAngChen8** [comment]
The warning has been reverted in Vue core
[discussions](https://github.com/vuejs/core/discussions/9974)
[Vue 3.4.6](https://github.com/vuejs/core/commit/324e817ef8d00c091e5d1537789542241c876d66)
[Vue 3.4.7](https://github.com/vuejs/core/commit/2fd39057386644c8bfee426c60a51f2b07a79b09) revert
