### ISSUE TITLE
Icon 能否加个 title 属性提示

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#291]
如题；
现在为了鼠标放上去能有文本提示，需要在 icon 外部再包一层 span 之类的，感觉有点多余。

**Comment by Flsion** [comment]
这个建议用 tooltip 组件实现，组件库的图标会可能的保持一个较干净的结构

**Comment by fangjc1986** [comment]
刚才看了下，你们的 icon 是 svg 的， title属性貌似无效。。。。
