### ISSUE TITLE
Modal组件函数调用，默认的okText、cancelText 不受a-config-provider的控制，进而不支持多语言

### ISSUE THREAD

**Issue by lrxCn** [arco-design/arco-design-vue#2920]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.2
- **浏览器版本:** chrome120.0.0.0
- **复现地址:** https://codesandbox.io/p/sandbox/patient-butterfly-y5cnmc?file=%2Fsrc%2FApp.vue%3A2%2C4-2%2C22

## 额外补充
表单不能贴图片么

## 复现步骤
按钮 Modal.info function 可以复现

modal component 按钮用于对比，modal组件的okText是支持多语言的

**Comment by lrxCn** [comment]
<img width="1183" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/79679501/401f905d-83d2-4170-982d-3bd567e49937">

**Comment by lrxCn** [comment]
<img width="1207" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/79679501/e29b4ae8-ac06-45fd-b34f-1f1eed56824d">

**Comment by shanyuhai123** [comment]
参考 #2768

**Comment by lrxCn** [comment]
解决：

https://codesandbox.io/p/sandbox/hopeful-cookies-lz4qnn?file=%2Fsrc%2Fmain.js%3A5%2C46
