### ISSUE TITLE
setup 下函数式组件写 jsx ts 报错如何解决

### ISSUE THREAD

**Issue by bayniidt** [arco-design/arco-design-vue#2923]
![image](https://github.com/arco-design/arco-design-vue/assets/54383894/255346d0-d284-415d-b396-89b56e88e042)
![image](https://github.com/arco-design/arco-design-vue/assets/54383894/65575249-2b5f-402c-be0a-217f42e09305)

**Comment by flsion** [comment]
@bayniidt 这里要用 JSX 写法，https://cn.vuejs.org/guide/extras/render-function.html#jsx-tsx
