### ISSUE TITLE
日历插槽如何使用

### ISSUE THREAD

**Issue by YJ-L-2017** [arco-design/arco-design-vue#2931]
日历插槽如何使用，使用下面代码无效果
```vue
<a-calendar
          v-model="calendarValue"
          mode="month"
          :modes="['month']"
          default-mode="month"
          @change="daySelectOnChange"
        >
          <template #default="{ date }">
            <div>{{ date }}日</div>
          </template>
</a-calendar>
```

**Comment by LIjiAngChen8** [comment]
@YJ-L-2017  你好，我这边 [Demo](https://codesandbox.io/p/sandbox/arco-vue-issue-2931-nh7vrj) 是没问题的。请确保版本 2.53.0 及以上。

**Comment by YJ-L-2017** [comment]
非常感谢你的回复，使用 arco-cli生成的Arco Pro 简单项目，默认的@arco-design/web-vue 版本为2.45.0

**Comment by YJ-L-2017** [comment]
你好，我升级之后依旧没有显示，   
![image](https://github.com/arco-design/arco-design-vue/assets/32069254/4f956e9b-269e-4b2e-ab6e-44089dff4914)

**Comment by YJ-L-2017** [comment]
日历设置插槽之后，就无法使用触发change事件

**Comment by YJ-L-2017** [comment]
日历插槽在年模式下是不起作用的吗
