### ISSUE TITLE
table 左右滚动 里面的数据会重新渲染，浪费很大的性能。

### ISSUE THREAD

**Issue by wghzyy** [arco-design/arco-design-vue#2934]
<img width="751" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/52588931/20fe5277-122d-46e9-9f83-c185039309e7">
左右滚动时候 注意随机数 会来回变化。

复现链接

https://stackblitz.com/edit/nnf5sz?file=src%2FApp.vue

**Comment by wghzyy** [comment]
注意观察随机数那一列。一直再不断变化 其实表格里面的数据 不更新的情况下 不应该触发更新的 我tabledata 并未更新。v-once 我也试过 在标签里没用。所以这也是造成table 比较卡的一个原因 希望能重视哈

**Comment by LIjiAngChen8** [comment]
Duplicate of #2927

**Comment by wghzyy** [comment]
@LIjiAngChen8 这个问题能解决吗 着急 我看React 就没这个问题。老板一直催促解决

**Comment by guo0588** [comment]
@oljc 麻烦处理一下感谢
