### ISSUE TITLE
不使用脚手架搭建项目

### ISSUE THREAD

**Issue by 304541805** [arco-design/arco-design-vue#2939]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.54.3
- **Browser:** chrome115.0.0.0

## Extra info
还是要npm install   @arco-design/web-vue --save

## What is expected?
npm install --save-dev @arco-design/web-vue这样安装到开发环境就可以吗

**Comment by LIjiAngChen8** [comment]
@304541805  可以参考 [快速上手](https://arco.design/vue/docs/start#%E5%AE%89%E8%A3%85)

npm install --save-dev @arco-design/web-vue 可以但建议组件库放在 dependencies 下。
``` node
// npm
npm i @arco-design/web-vue
// yarn
yarn add @arco-design/web-vue
// pnpm
pnpm add @arco-design/web-vue
```
