### ISSUE TITLE
InputNumber有必填校验的时候，输入值仍然会显示错误提示

### ISSUE THREAD

**Issue by visionding** [arco-design/arco-design-vue#2959]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.54.4
- **Browser:** chrome121.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/vitejs-vite-bfp6d1?file=src%2FApp.vue

## What is expected?
输入值之后校验通过

**Comment by pzgz** [comment]
+1, same here
