### ISSUE TITLE
现在 input-number 控件不支持双向绑定了，而是鼓励在事件里自行更新数值吗？

### ISSUE THREAD

**Issue by GodRuiCollection** [arco-design/arco-design-vue#2965]
https://codesandbox.io/p/sandbox/frosty-wing-nhcm6s?file=%2Fsrc%2FApp.vue%3A5%2C20
如之前的演示代码，我发现修改 input 的值后 点击空白处让 input 失去焦点后 {{ value }} 的值并没有更新
但是在控制台确实显示触发了 input 和 change 事件回调
![image](https://github.com/arco-design/arco-design-vue/assets/31038675/5c3980fa-cc75-45d4-88b6-82686979d759)

我看文档的确说了触发 blur 可以更新数值
![image](https://github.com/arco-design/arco-design-vue/assets/31038675/ed3fc1a0-0aa6-4719-af64-2c48d67c68b1)

但是我发现 a-input 输入文字没有这种问题，触发 blur 后也会正常回调 change 事件
现在我把之前写的 input-number 全都加上 model-event="input" 才好起来，虽然这会有其它问题。
我想知道这是个 bug 还是这控件就是这样设计的？

**Comment by GodRuiCollection** [comment]
已解决 更新到最新的 2.54.4 即可

**Comment by liujunmm** [comment]
最新2.54.4版本依然存在这个问题
