### ISSUE TITLE
在最新版的vue3 和 vite中，a-menu 和 a-tree 会在控制台报警告信息

### ISSUE THREAD

**Issue by kanyxmo** [arco-design/arco-design-vue#2969]
- [] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.54.4
- **Browser:** chrome121.0.0.0

`package.json` 信息
![image](https://github.com/arco-design/arco-design-vue/assets/1711988/89480ea4-e7c8-4262-be43-8f985e246db2)

控制台警告信息：
![image](https://github.com/arco-design/arco-design-vue/assets/1711988/86a28f44-58bf-4dc3-b872-f2e4dc1749de)

以下是官方 a-tree 的第一个示例代码
```js
<template>
  <a-tree
    :data="treeData"
    :default-expanded-keys="['0-0-0']"
    :default-selected-keys="['0-0-0', '0-0-1']"
  />
</template>
<script>
  export default {
    data() {
      return {
        treeData,
      };
    },
  };

  const treeData = [
    {
      title: 'Trunk 0-0',
      key: '0-0',
      children: [
        {
          title: 'Branch 0-0-0',
          key: '0-0-0',
          disabled: true,
          children: [
            {
              title: 'Leaf',
              key: '0-0-0-0',
            },
            {
              title: 'Leaf',
              key: '0-0-0-1',
            }
          ]
        },
        {
          title: 'Branch 0-0-1',
          key: '0-0-1',
          children: [
            {
              title: 'Leaf',
              key: '0-0-1-0',
            },
          ]
        },
      ],
    },
  ];
</script>

```

**Comment by SunTaiBai** [comment]
+1， 烦死了

**Comment by pzgz** [comment]
和 vue.js 3.4.18 release的这个commit有关： https://github.com/vuejs/core/commit/77a804b1d0d6a3f12fb3674cdceb85ebd6481e02

**Comment by SunTaiBai** [comment]
> 和 vue.js 3.4.18 发布的这个提交涉及：[vuejs/core@ 77a804b](https://github.com/vuejs/core/commit/77a804b1d0d6a3f12fb3674cdceb85ebd6481e02)
它这么搞不想让用key， 那组件后面会把key改名么

**Comment by liuhauyao** [comment]
希望尽快适配，看着报错好难受

**Comment by liujunmm** [comment]
最新 2.54.5 版本，折叠面板collapse组件，依然存在这个警告
