### ISSUE TITLE
link 链接 添加 color 属性，自定义颜色

### ISSUE THREAD

**Issue by lxccc812** [arco-design/arco-design-vue#2979]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
类似与 a-tag 中的 color 
https://arco.design/vue/component/tag#color

## 预期解决问题
a-link 组件添加  color 变量，可以自定义颜色

## 额外补充
a-tag  与  a-link  同时使用时，颜色不能保持一致
![image](https://github.com/arco-design/arco-design-vue/assets/110974969/5c6aef39-8a95-4b0b-9ef6-1677cce2ec67)

**Comment by LIjiAngChen8** [comment]
```vue
<a-link style="color: red" href="link">Link</a-link>
```

**Comment by lxccc812** [comment]
糊涂了，忘了本质是a标签了
