### ISSUE TITLE
[建议]Tree支持最后一级节点横向排列

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#298]
树节点稍微多一点的话，移动设备甚至PC设备高度显示并不是很友好。
目前好像各大开源UI框架的Tree都不支持最后一级节点横向排列，需要手动去修改样式。
不好意思，只是建议，可能这个建议有点过分了。

**Comment by kirazxyun** [comment]
你好，请问具体长什么样子呢，可以给个 UI 吗

**Comment by svipchao** [comment]
> 你好，请问具体长子呢，可以给个 UI 吗？

![image](https://user-images.githubusercontent.com/30397859/144206836-0e020954-1c1f-4b5b-a4ff-79059fe9f351.png)

你好，这个是之前基于Layui的Tree二次改的样式。VUE刚学没多久。VUE版的没有改过
我也不太清楚有哪些场景需要用到这种样式。不过这样会让PC设备显示更加友好。

**Comment by kirazxyun** [comment]
你好，这个可以把叶子节点的样式改为 inline-flex，可以看一下这个 [demo](https://codepen.io/zhangxiaoyun_bj/pen/MWEwzQx) 是否满足需求

**Comment by svipchao** [comment]
> 你好，这个可以把叶子节点的样式改为inline-flex，可以看一下这个[demo](https://codepen.io/zhangxiaoyun_bj/pen/MWEwzQx)是否满足需求

谢谢，这样可以，麻烦了
