### ISSUE TITLE
自定义属性无法准确, 给input的id属性打包之后没在input上面

### ISSUE THREAD

**Issue by zoonware** [arco-design/arco-design-vue#2980]
![微信图片_20240220160934](https://github.com/arco-design/arco-design-vue/assets/20835399/07bcf867-6844-4ff7-8b44-b1ac48df972e)

**Comment by zoonware** [comment]
![微信图片_20240220160934](https://github.com/arco-design/arco-design-vue/assets/20835399/f49fc253-806e-4d9a-a5ec-1b0ecf689306)

**Comment by zoonware** [comment]
这导致在做UI自动化测试的时候  需要依靠xpth或者其他方式定位,  不能通过id直接定位

**Comment by LIjiAngChen8** [comment]
可以通过 `input-attrs` 属性设置
```vue
<a-input  :style="{width:'320px'}" :input-attrs="{id:'demoId'}" />
```

**Comment by zoonware** [comment]
> 可以通过 `input-attrs` 属性设置
> 
> ```
> <a-input  :style="{width:'320px'}" :input-attrs="{id:'demoId'}" />
> ```

那其他的控件没有 input-attrs   要如何处理?

**Comment by zoonware** [comment]
@LIjiAngChen8

**Comment by LIjiAngChen8** [comment]
> > 可以通过 `input-attrs` 属性设置
> > ```
> > <a-input  :style="{width:'320px'}" :input-attrs="{id:'demoId'}" />
> > ```
> 
> 那其他的控件没有 input-attrs 要如何处理?

其他控件是指哪些？
 `id`、`class` 等 attribute 默认透传添加到组件的根元素上。具体规则可参阅：[透传 Attributes](https://cn.vuejs.org/guide/components/attrs.html#attribute-inheritance)。你所提到的自动化测试似乎与组件库无关且信息很少，无法为你解答。

**Comment by iamziyue** [comment]
我借楼问一下，`a-image`组件，想给`img`标签设置`loading="lazy"`有办法吗？
文档中没有像`a-input`组件这样提供`input-attrs`属性。

**Comment by zoonware** [comment]
Thanks!
