### ISSUE TITLE
input-number 控件双向绑定失效（可能和2.54.4修复早先input-number的bug有关）

### ISSUE THREAD

**Issue by caprimoon** [arco-design/arco-design-vue#2983]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.4
- **浏览器版本:** chrome121.0.0.0
- **复现地址:** https://stackblitz.com/edit/xvabfn-tecnrs?file=src%2FApp.vue,package.json

## 额外补充
change事件是触发了的，但onUpdate:modelValue未触发。
目前该双向绑定bug在2.54.3未出现，是在2.54.4修复input-number的另一个bug后出现的

## 预期结果
双向绑定的值自动修改

## 复现步骤
1.a-input-number键盘输入值
2.双向绑定的值并未修改

![input-number-bug](https://github.com/arco-design/arco-design-vue/assets/54494427/a9a07186-603c-4ab5-b7b4-5e3a7901a0c6)

**Comment by LIjiAngChen8** [comment]
#2961

**Comment by caprimoon** [comment]
> #2961

目前最新版本2.54.4的更新文档中提到了修复了#2961，但a-input-number双向绑定确实无法使用
