### ISSUE TITLE
input-number componse step button style bug

### ISSUE THREAD

**Issue by xingkoo** [arco-design/arco-design-vue#2999]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.5
- **浏览器版本:** chrome121.0.0.0

## 复现步骤
step button position is error. when use append and preend.
![WeChat10d941bd06a862ad3ee7636a221eada6](https://github.com/arco-design/arco-design-vue/assets/2936579/16bddc8e-108a-45f9-ae69-cb3bd2697e73)

**Comment by betavs** [comment]
It can currently be solved by adding the `hide-button` attribute. I will submit a PR to deal with this issue soon.
