### ISSUE TITLE
标签页tab-bar组件问题

### ISSUE THREAD

**Issue by sd-knight** [arco-design/arco-design-vue#3004]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.0
- **Framework version:** VUE 3.3.4
- **Browser:** chrome122.0.0.0

## Extra info
问下有升级这个 tab-bar 组件计划吗？

## Steps to reproduce
1. 打开标签页都会重新刷新加载内容，没用缓存
2. 带参数的页面A 比如?id=xxx ， 新打开一个标签页B，关闭B后A页面参数丢失，重新加载后业务逻辑会报错。

**Comment by LIjiAngChen8** [comment]
这里是组件库仓库，模板相关问题请前往： [arco-design/arco-design-pro-vue](https://github.com/arco-design/arco-design-pro-vue)
