### ISSUE TITLE
Errors about the introduction method

### ISSUE THREAD

**Issue by lxccc812** [arco-design/arco-design-vue#3012]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.6
- **框架版本:** vue 3.1.21
- **浏览器版本:** chrome121.0.0.0
- **复现地址:** https://stackblitz.com/edit/vitejs-vite-bmz8ai?file=src%2Fmain.ts

## 预期结果
The component can be used normally
## 复现步骤
npm run dev

![image](https://github.com/arco-design/arco-design-vue/assets/110974969/ee8312a3-315b-4f14-94f8-df025c7da37f)
![image](https://github.com/arco-design/arco-design-vue/assets/110974969/266d7593-a1cc-44b4-bd1f-d46b785dd4c4)

**Comment by LIjiAngChen8** [comment]
@lxccc812 在你的写法中通过 `createApp` 创建了两个组件实例，一个根组件实例挂载在 #app 上，另一个无使用导致的。

应当应用在一个根组件实例上链式调用
```typescript
createApp(App).use(ArcoVue).mount('#app');
```
