### ISSUE TITLE
a-modal 单独放到组件中,无法通过esc关闭

### ISSUE THREAD

**Issue by lxccc812** [arco-design/arco-design-vue#3013]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.54.6
- **浏览器版本:** chrome121.0.0.0
- **复现地址:** https://stackblitz.com/edit/vitejs-vite-gjrrpl?file=src%2FApp.vue

## 复现步骤
npm run dev
点击 modal 2

## 额外补充
通过添加@cancel可以正常关闭
另外通过 chrome vue 插件看到visible一直是true
![image](https://github.com/arco-design/arco-design-vue/assets/110974969/cf76f26d-a117-452e-9b83-2e619f6a9efe)

**Comment by longshihui** [comment]
用v-model时为受控模式，你得emit('update:visible')才能更改props的值，不能直接v-model由props toRefs来的值
<img width="680" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/17525817/56bbd248-d99e-4c83-b91f-a414e3560dfc">
