### ISSUE TITLE
有在表头设置icon和悬浮弹窗的方式吗

### ISSUE THREAD

**Issue by kafei-fish** [arco-design/arco-design-vue#3031]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
类似这种
<img width="430" alt="e00accedda608d4a6c650cd32530858" src="https://github.com/arco-design/arco-design-vue/assets/59606360/fb588e8f-700a-4307-9039-65c9da4ac158">

## What problem does this feature solve?
在官方的文档都没有找到具体的方式 ps：我是后端来使用的前端框架，还是很熟练

**Comment by LIjiAngChen8** [comment]
没太理解你的表达，可以参考：[排序和筛选](http://localhost:2233/vue/component/table#sort)、[插槽自定义筛选菜单内容](http://localhost:2233/vue/component/table#filter)。
![image](https://github.com/arco-design/arco-design-vue/assets/48879481/1dc9b792-43c3-4866-9140-788ebcbeca4c)

![image](https://github.com/arco-design/arco-design-vue/assets/48879481/9818e44d-7c3b-4663-9023-34fe5cb89728)
