### ISSUE TITLE
table组件通过v-model设置默认激活值必须为字符串类型

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#304]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-vue
- **系统版本:** 2.7.0
- **浏览器版本:** edge 95
- **复现地址:** https://codepen.io/duxphp/pen/LYzEyzw?editors=0010

## 预期结果
应该兼容字符和数字多种类型

## 复现步骤
如果value为字符串则正常 如果为数字则无法默认选中

**Comment by Flsion** [comment]
这个感觉不是很必要，为了处理key和:key的问题，内部有把key字符串化，是有什么场景需要数字的形式吗

**Comment by duxphp** [comment]
错了 是tab组件  因为tab的key有可能是数字形式  默认值如果没办法是数字就没法默认选中
