### ISSUE TITLE
本地开发模式中，视口窗的较快缩放会引起页面报错 ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by Jarvlis** [arco-design/arco-design-vue#3046]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.0
- **Framework version:** Vue3.2.13
- **Browser:** chrome123.0.6312.59

## Extra info
![image](https://github.com/arco-design/arco-design-vue/assets/96105888/f04eec8f-507c-47f2-8c8c-c639e91bf4d4)

## What is expected?
应当正确的处理响应式的变化

## Steps to reproduce
在本地开发模式，打开控制台，快速缩放窗口，会导致页面出现报错提醒

**Comment by Jarvlis** [comment]
在线上环境中，进行再次测试不会产生这样的问题，可能因为线上环境不涉及webpack-dev-server

**Comment by fx89757** [comment]
确实，我也遇到了，不过是浏览器报错。仅仅开发环境会，上线之后仅控制台有报错。

<img width="471" alt="Image" src="https://github.com/user-attachments/assets/d411549a-6817-4c70-be53-0b89feaa27be" />

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/9f5ad130-fc0e-40a0-b6ac-a27f31337b86" />

**Comment by fx89757** [comment]
vite 项目也有这个问题，只是没有抛错

<img width="598" alt="Image" src="https://github.com/user-attachments/assets/63a84d5c-7bae-4705-8e13-58d0b37b10af" />

复现：
1. 根据 grid 自适应宽度，Select 或者 Pagination 组件。
2. 点击组件
3. 会有相关的报错

**Comment by pzgz** [comment]
目测是Menu组件引起，在 arco design pro做的项目模板内，Menu放在顶部的时候，隐藏掉以后就不会有这个问题，Menu放在侧面就不会有问题
