### ISSUE TITLE
【图标库需求】希望增加一个麦克风禁用图标

### ISSUE THREAD

**Issue by fishnb** [arco-design/arco-design-vue#3053]
![image](https://github.com/arco-design/arco-design-vue/assets/138562779/d2dfb5a2-c499-436d-bcfa-e39a365f7551)
目前只有一个麦克风图标，希望可以增加一个禁用的图标

**Comment by alphaelf** [comment]
you can use any icon in [icones.js.org](https://icones.js.org/) with [integrate unocss](https://unocss.dev/integrations/) and use [Icon Preset](https://unocss.dev/presets/icons)
