### ISSUE TITLE
数据穿梭框 Transfer在simple模式下选项在在根据数据的 disabled 属性禁用后，点击仍可以被选中。

### ISSUE THREAD

**Issue by Samuel-wyj** [arco-design/arco-design-vue#3056]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.55.1
- **框架版本:** 3.4.19
- **浏览器版本:** chrome123.0.0.0

## 预期结果
选项 item 根据 disabled 属性禁用后应不能点击穿梭

## 复现步骤
<template>
    <a-transfer :data="sourceData" v-model="selectedData" simple></a-transfer>
</template>

<script>
const sourceData = ref([
{
 value:'1',
label:'option1',
disabled:true
}
])
const selectedData = ref([])
</script>

**Comment by alphaelf** [comment]
according to this [sample](https://codesandbox.io/p/sandbox/black-sound-qc7s4w) all disable behavior are ok
what exactly is your problem ?

**Comment by Samuel-wyj** [comment]
> according to this [sample](https://codesandbox.io/p/sandbox/black-sound-qc7s4w) all disable behavior are ok what exactly is your problem ?

这个sample是select选择器，我提出的issue是数据穿梭框Transfer，在穿梭框组件添加了simple属性后，对于数据中某一条数据的disabled为true时，该条数据点击后仍然会被放入已选择的穿梭框中

**Comment by Samuel-wyj** [comment]
> according to this [sample](https://codesandbox.io/p/sandbox/black-sound-qc7s4w) all disable behavior are ok what exactly is your problem ?

`https://codesandbox.io/p/sandbox/black-sound-qc7s4w?file=%2Fsrc%2FApp.vue%3A4%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluqqjxju00063b6ii746ktzq%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluqqjxjt00023b6igs1l9lbf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluqqjxjt00033b6i86cuz1as%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluqqjxjt00053b6ittggqtsw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluqqjxjt00023b6igs1l9lbf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqqjxjt00013b6ifaaefidt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluqqjxjt00023b6igs1l9lbf%2522%252C%2522activeTabId%2522%253A%2522cluqqjxjt00013b6ifaaefidt%2522%257D%252C%2522cluqqjxjt00053b6ittggqtsw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqqjxjt00043b6ikx8f55i5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluqqjxjt00053b6ittggqtsw%2522%252C%2522activeTabId%2522%253A%2522cluqqjxjt00043b6ikx8f55i5%2522%257D%252C%2522cluqqjxjt00033b6i86cuz1as%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluqqjxjt00033b6i86cuz1as%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D`

**Comment by Samuel-wyj** [comment]
[sample](https://codesandbox.io/p/sandbox/black-sound-qc7s4w?file=%2Fsrc%2FApp.vue%3A4%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluqqjxju00063b6ii746ktzq%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluqqjxjt00023b6igs1l9lbf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluqqjxjt00033b6i86cuz1as%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluqqjxjt00053b6ittggqtsw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluqqjxjt00023b6igs1l9lbf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqqjxjt00013b6ifaaefidt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluqqjxjt00023b6igs1l9lbf%2522%252C%2522activeTabId%2522%253A%2522cluqqjxjt00013b6ifaaefidt%2522%257D%252C%2522cluqqjxjt00053b6ittggqtsw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqqjxjt00043b6ikx8f55i5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluqqjxjt00053b6ittggqtsw%2522%252C%2522activeTabId%2522%253A%2522cluqqjxjt00043b6ikx8f55i5%2522%257D%252C%2522cluqqjxjt00033b6i86cuz1as%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluqqjxjt00033b6i86cuz1as%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) @alphaelf
