### ISSUE TITLE
当 Dropdown 组件的 Dsubmenu 内容长度不一致时标签没有对齐

### ISSUE THREAD

**Issue by ikxin** [arco-design/arco-design-vue#3057]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.1
- **Browser:** chrome123.0.0.0

## Extra info

![1712067706490.png](https://img.8b5.cn/uploads/2024/04/02/660c147a9d12f.png) 

## What is expected?
Dsubmenu 文本应该向左对齐，或者支持选项配置

**Comment by LIjiAngChen8** [comment]
@ikxin  正常使用下未出现所描述的情况，未按照正常用法使用需自己控制好样式效果。
![image](https://github.com/arco-design/arco-design-vue/assets/48879481/f7843496-33c8-4967-9943-9583c34099ca)

[复现链接](https://codesandbox.io/p/sandbox/arco-vue-issue-3057-k93dlt?file=%2Fsrc%2FApp.vue%3A5%2C18)

**Comment by ikxin** [comment]
@LIjiAngChen8 感谢答复，我检查了一下代码，发现并未使用错误方式，在您提供的复现链接上面测试了一下，是一样的状态，我的问题是当存在两个 Dsubmenu 时，如果两个标签的长度不一样，就会出现未对齐的现象

复现链接：https://codesandbox.io/p/sandbox/arco-vue-issue-3057-forked-mtjtp2

<img width="1005" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/54543761/b782aa79-ef25-4965-9892-4c5c92465d49">

另外我在 #3059 中尝试修复了错位样式，但我不确定这是一个好方法
