### ISSUE TITLE
描述列表 Descriptions渲染列错误

### ISSUE THREAD

**Issue by CloudClient** [arco-design/arco-design-vue#3073]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.53.0
- **Framework version:** Vue3.3.7
- **Browser:** chrome123.0.0.0

## What is expected?
第一行审批人 第二行审批状态各自独占一行 其他四个在最后一行中，实际效果是第一行审批人  第二行 审批状态 申请时间 名称 更新时间 在第二行 备注在最后一行

## Steps to reproduce
代码
`
<a-descriptions :column="4" :align="{ label: 'left' }" bordered>
      <a-descriptions-item label="申请人" :span="4">{{ form.person }}</a-descriptions-item>
      <a-descriptions-item label="审批状态" :span="4"> {{ form.status }} </a-descriptions-item>
      <a-descriptions-item label="申请时间" :span="1">{{ form.createTime }}</a-descriptions-item>
      <a-descriptions-item label="名称" :span="1">{{ form.name }}</a-descriptions-item>
      <a-descriptions-item label="更新时间" :span="1">{{ form.updateTime }}</a-descriptions-item>
      <a-descriptions-item label="备注" :span="1">{{ form.remark }}</a-descriptions-item>
    </a-descriptions>
`

**Comment by LIjiAngChen8** [comment]
Duplicate of #3072
