### ISSUE TITLE
Cascader 级联选择器 希望提供 仅显示最后一级 能力

### ISSUE THREAD

**Issue by YILS-LIN** [arco-design/arco-design-vue#3083]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
[Element Plus 级联选择器 仅显示最后一级 功能](https://element-plus.org/zh-CN/component/cascader.html#%E4%BB%85%E6%98%BE%E7%A4%BA%E6%9C%80%E5%90%8E%E4%B8%80%E7%BA%A7)

## 预期解决问题
路径过长时显示不全，增加 仅显示最后一级 能力，可以使展现效果更好，解决这种情况下产生的问题

**Comment by lanrenbulan** [comment]
可以通过format-label来完成

[https://arco.design/vue/component/cascader#format](url)
