### ISSUE TITLE
vite 项目自动化导入 color-picker 组件 中 css 文件 自动化导入报错

### ISSUE THREAD

**Issue by duKD** [arco-design/arco-design-vue#3099]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.1
- **Browser:** chrome124.0.0.0

## Extra info
import "../../style/index.css";
import "./index.css";
style文件夹下  缺少 index.css 文件

**Comment by oljc** [comment]
#3052

**Comment by duKD** [comment]
感谢， 希望下个版本 发布
