### ISSUE TITLE
a-input-number的双向绑定还是没有效果

### ISSUE THREAD

**Issue by YiLin-Wang4ever** [arco-design/arco-design-vue#3103]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.0
- **Browser:** chrome124.0.0.0

## What is expected?
a-input-number正常能回显出来，v-model不失效

## Steps to reproduce
表格插槽使用中使用a-input-number 去修改表格的值双向绑定回显失效，之前的版本是没有这个问题的，麻烦紧急解决一下影响生产
![image](https://github.com/arco-design/arco-design-vue/assets/105864047/0e797066-2655-44a4-9b45-adcd2643780e)
![image](https://github.com/arco-design/arco-design-vue/assets/105864047/a8fc42be-0498-4fd4-aa17-90c3a0ef694a)

**Comment by briantang1117** [comment]
没遇到这个问题诶 确定后端给的是number类型？包一层Number转一下试试
