### ISSUE TITLE
使用Menu及MenuItem组件，mode为horizontal，在最后插入元素出现闪烁bug

### ISSUE THREAD

**Issue by Merlin218** [arco-design/arco-design-vue#312]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue": "^2.7.0"
- **System:** MacOS Monterey12.0.1
- **Browser:** Chrome
- **Reproduction Link:** https://codesandbox.io/s/interesting-murdock-v2bij?file=/src/components/HelloWorld.vue

## What is expected?
出现无限闪烁bug

## Steps to reproduce
在mode为horizontal的Menu的最后插入一个元素

## Extra info
    <a-menu mode="horizontal" :default-selected-keys="['1']">
      <a-menu-item key="1">Home</a-menu-item>
      <a-menu-item key="2">Solution</a-menu-item>
      <a-menu-item key="3">Cloud Service</a-menu-item>
      <a-menu-item key="4">Cooperation</a-menu-item>
      <div>插入的元素</div>
    </a-menu>

**Comment by kirazxyun** [comment]
你好，因为横向菜单做了超出收起的功能，所以限定children 必须是 menu-item 或者 sub-menu，这边不建议把额外内容放到 menu 里头。

**Comment by Merlin218** [comment]
> 你好，因为横向菜单做了超出收起的功能，所以限定children 必须是 menu-item 或者 sub-menu，这边不建议把额外内容放到 menu 里头。 可以看下这个 [demo](https://codepen.io/zhangxiaoyun_bj/pen/QWqbJdr?editors=1010)

好的了解，谢谢回复，想请教一下这种闪烁问题是否属于使用不当时出现的正常现象，还是存在可解决的优化方案呢？

**Comment by kirazxyun** [comment]
> > 你好，因为横向菜单做了超出收起的功能，所以限定children 必须是 menu-item 或者 sub-menu，这边不建议把额外内容放到 menu 里头。 可以看下这个 [demo](https://codepen.io/zhangxiaoyun_bj/pen/QWqbJdr?editors=1010)
> 
> 好的了解，谢谢回复，想请教一下这种闪烁问题是否属于使用不当时出现的正常现象，还是存在可解决的优化方案呢？

使用方式不对哈，可参考上条回复的 demo 来处理
