### ISSUE TITLE
滚动条不能自适应父级高度

### ISSUE THREAD

**Issue by lq9958** [arco-design/arco-design-vue#3125]
请问滚动条组件必须设置固定的一个高度吗？不能自适应父级元素的高度吗？
[demo](https://codesandbox.io/p/sandbox/ecstatic-albattani-49s9d6?file=%2Fsrc%2FApp.vue%3A4%2C11)

**Comment by rtpacks** [comment]
是不是忘记设置 `outer-style` 属性了，scrollbar 内部套了一层，[codesandbox](https://codesandbox.io/p/sandbox/inspiring-dirac-lfdvmk?file=%2Fsrc%2FApp.vue) 。

**Comment by lq9958** [comment]
> 是不是忘记设置 `outer-style` 属性了，scrollbar 内部套了一层，[codesandbox](https://codesandbox.io/p/sandbox/inspiring-dirac-lfdvmk?file=%2Fsrc%2FApp.vue) 。

确实是

**Comment by lq9958** [comment]
@rtpacks 确实是
