### ISSUE TITLE
考虑导出组件的 props 么, 方便二开使用

### ISSUE THREAD

**Issue by Zhang-Wei-666** [arco-design/arco-design-vue#3135]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
二开时可以直接继承导出的 props 类型及类型定义

## 现有案例
[arco-design](https://github.com/arco-design/arco-design/blob/5e771d6a98e588f12186ca839e9115e8e3097331/components/Input/interface.tsx#L10)

[naive-ui](https://github.com/tusen-ai/naive-ui/blob/a6d4b111bee328d317426131799f68d92760dbbb/src/input/src/Input.tsx#L68)

[element-plus](https://github.com/element-plus/element-plus/blob/75b935a97728600f4c4c5196ade74b528fc19ed2/packages/components/input/src/input.ts#L15)

## 预期解决问题
和 arco-design 一致

**Comment by lin-97** [comment]
你是不会用 v-bind 还有
defineOptions({ inheritAttrs: false })
 const attrs = useAttrs() 
进行二开吗？

**Comment by Zhang-Wei-666** [comment]
> 你是不会用 v-bind 还有 defineOptions({ inheritAttrs: false }) const attrs = useAttrs() 进行二开吗？

![image](https://github.com/arco-design/arco-design-vue/assets/37876877/df4fe3f7-cbe0-45af-9e13-ce110f1e6e5c)

要的是类型定义啊 😑
二开封装的组件, 继承类型定义, 组件就有代码提示了啊

**Comment by Zhang-Wei-666** [comment]
算了, 不指望了 🤷‍♂️

**Comment by lin-97** [comment]
你是没用过这种吗
import type * as A from '@arco-design/web-vue'
A.InputInstance['$props']
A.FormItemInstance['$props']

**Comment by lin-97** [comment]
个人认为，非必要尽量不要过度封装组件，经历过大大小小项目总结出来，过渡封装只会自食其果，后面慢慢变成屎山，过渡封装，新人看不懂是懒得用的，还不如跟我主页项目一样，能不封装就尽量不封装

**Comment by lin-97** [comment]
> https://mixte.moomfe.com/mixte/snippets/acro-dynamic-form#ResetButtonOptions

这个是你开发的吗

**Comment by Zhang-Wei-666** [comment]
> > https://mixte.moomfe.com/mixte/snippets/acro-dynamic-form#ResetButtonOptions
> 
> 这个是你开发的吗

是啊

**Comment by zhangsd** [comment]
建议导出props，二开更友好
