### ISSUE TITLE
[DataPicker]使用showTime时，从后往前选日期会出现时间取值出错

### ISSUE THREAD

**Issue by ZhongMingKun** [arco-design/arco-design-vue#3140]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.2
- **Framework version:** Vue3
- **Browser:** chrome121.0.0.0
- **Reproduction Link:** https://codesandbox.io/s/69yqhg?file=/src/App.vue

## What is expected?
保持已选择的时间不变

## Steps to reproduce
1. 启用showTime属性
2. start和end选择不一样的时间
3. 日期选择从后往前选， 重复两次，第二次必现时间调转

复现可看：https://www.bilibili.com/video/BV1GM4m1y7cD/

**Comment by oljc** [comment]
@ZhongMingKun  可以通过 `exchange-time` 控制时间是否会交换，如果要固定时间顺序，可将其设置为 `false`。
