### ISSUE TITLE
Modal 对话框函数调用方式能否简化下？ 

### ISSUE THREAD

**Issue by zxkv** [arco-design/arco-design-vue#3141]
Modal 对话框里的确认类型时采用函数方式调用时，配置项需要调用 h 方法重写，操作比较繁琐，能否简化下，类似配置项方式。

**Comment by lin-97** [comment]
想问问怎么繁琐了？不太明白你意思

**Comment by zxkv** [comment]
我看了下文档，Model弹窗框 按需引入采用函数声明方式调用时，需要使用 h 函数来自定义配置，能否类似 Element Plus 的 MessageBox 的配置方式来实现在JS中函数调用？

**Comment by lin-97** [comment]
有代码示例看看吗？

**Comment by lin-97** [comment]
我懂你意思了，不用h可以用jsx啊
https://juejin.cn/post/7250356064988725309
https://juejin.cn/post/7250361765052432421

**Comment by lin-97** [comment]
用h也没啥问题啊，一样可以
![GiForm-modal](https://github.com/arco-design/arco-design-vue/assets/53759423/37f301bd-9fac-4efd-b666-e6fe13d48916)

**Comment by lin-97** [comment]
哦对了，element plus的MessageBox函数相当于arco的Message函数，你不应该用Modal吧，而是Message

**Comment by zxkv** [comment]
当时想要的是一个弹框确认的模式，需要点击确认，看到只有Modal下有这个功能就尝试使用了。

**Comment by lin-97** [comment]
用Message啊，不是Modal

**Comment by zxkv** [comment]
![PixPin_2024-05-22_15-18-31](https://github.com/arco-design/arco-design-vue/assets/54396065/a135b296-8ae4-41f9-a9fc-b996530cd5e8)
这就是想要的效果图，Message里好像没有

尝试使用 h 函数实现

**Comment by lin-97** [comment]
是我错了，MessageBox不等于Message

  Modal.warning({
    title: '提示',
    content: '确认退出登录？',
    hideCancel: false,
    closable: true,
    onBeforeOk: async () => {
      try {
        await userStore.logout()
        router.replace('/login')
        return true
      } catch (error) {
        return false
      }
    }
  })
  
  Modal可以这么写

**Comment by lin-97** [comment]
是我错了，MessageBox不等于Message

`Modal.warning({
title: '提示',
content: '确认退出登录？',
hideCancel: false,
closable: true,
onBeforeOk: async () => {
try {
await userStore.logout()
router.replace('/login')
return true
} catch (error) {
return false
}
}
})`

Modal可以这么写

**Comment by lin-97** [comment]
我的错了， el的MessageBox不等于arco的Message
Modal可以这么写
![image](https://github.com/arco-design/arco-design-vue/assets/53759423/3d0eb374-dd66-4b15-817c-1cc71c540910)

**Comment by zxkv** [comment]
我看文档，可以这样处理。多谢 @lin-97

**Comment by zxkv** [comment]
关闭了
