### ISSUE TITLE
希望Vue项目能新增 通过 CDN 使用

### ISSUE THREAD

**Issue by XueNing-RJ** [arco-design/arco-design-vue#3142]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
React项目中我看到就有CDN，Vue没看见文档中有这部分。

## What problem does this feature solve?
新增CDN使用方式，可以在某些HTML页面直接使用，而不是仅限制在前端工程中

**Comment by oljc** [comment]
- 生产环境: https://unpkg.com/@arco-design/web-vue@latest/dist/arco-vue.min.js
- 图标：https://unpkg.com/@arco-design/web-vue@latest/dist/arco-vue-icon.min.js
- 样式：https://unpkg.com/@arco-design/web-vue@latest/dist/arco.min.css

或 [jsdelivr](https://www.jsdelivr.com/package/npm/@arco-design/web-vue) 网页设置选择
![image](https://github.com/arco-design/arco-design-vue/assets/48879481/7736605b-b357-4c47-aae1-c9dff6c69f5c)
