### ISSUE TITLE
a-upload官方示例点击 start upload 或者 only upload one 会报错，不会触发上传

### ISSUE THREAD

**Issue by joyf12** [arco-design/arco-design-vue#3144]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.55.2
- **框架版本:** vue3
- **浏览器版本:** chrome124.0.0.0
- **复现地址:** https://arco.design/vue/component/upload  手动上传

## 预期结果
点击 start upload 或者 only upload one 按钮触发文件上传的网络请求

## 复现步骤
选择文件，点击 start upload 或者 only upload one 控制台会报错

**Comment by oljc** [comment]
已在 #3037 中解决官网未更新
