### ISSUE TITLE
使用v-for创建选项并设置选项默认值，选择器会增加一个冗余选项

### ISSUE THREAD

**Issue by Jake-00** [arco-design/arco-design-vue#3148]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.2
- **Framework version:** Vue 3.4.23
- **Browser:** chrome124.0.0.0

**Comment by Jake-00** [comment]
reproduce link: https://stackblitz.com/edit/ju5ftu?file=src%2FApp.vue
<img width="341" alt="image" src="https://github.com/arco-design/arco-design-vue/assets/60967034/359138e0-ea86-4547-967e-ad920adfd1b1">

**Comment by ZhongMingKun** [comment]
你没写对
 ![image](https://github.com/arco-design/arco-design-vue/assets/33282718/55ddef6c-241b-4178-9fe8-9a25c4df7b86)

**Comment by LshanGuoii** [comment]
两个选项的key标识符不一样，default-value如果是字符串，那么 option上的value不能是对象item，和楼上老哥说的那样保持value是对等的。
或者default-value传入一个item项
![image](https://github.com/arco-design/arco-design-vue/assets/67221474/43cdf542-43b9-46c3-885b-f0e2862849b2)
内部选项针对key判断需不需要增加额外选项
![image](https://github.com/arco-design/arco-design-vue/assets/67221474/be12e35e-f07a-4079-9541-ddc035a523ad)

**Comment by Jake-00** [comment]
> 你没写对
> 
>  ![image](https://github.com/arco-design/arco-design-vue/assets/33282718/55ddef6c-241b-4178-9fe8-9a25c4df7b86)
> 
> 

前提是不修改 value ，区分 label 和 value 值
