### ISSUE TITLE
能否支持运行时动态主题色切换

### ISSUE THREAD

**Issue by joy-stacks** [arco-design/arco-design-vue#3163]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
能否支持运行时动态主题色切换

## What problem does this feature solve?
能否支持运行时动态主题色切换

## Extra info
能否支持运行时动态主题色切换

**Comment by ucarpediem** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
> 
> ## Basic Info
> ## What are the similar cases of this feature
> 能否支持运行时动态主题色切换
> 
> ## What problem does this feature solve?
> 能否支持运行时动态主题色切换
> 
> ## Extra info
> 能否支持运行时动态主题色切换

看看人家做的：http://arco.vueadminwork.com/

**Comment by oljc** [comment]
**运行时切换主题色：**
引入 `@arco-design/color` 动态梯度的色彩算法，运行时传入颜色即可获得从浅到深 10 个梯度颜色。通过往 body 下注入新的颜色变量覆盖组件库主题色即可实现动态主题色。

参考: https://codesandbox.io/p/sandbox/late-rgb-gw63ys?file=%2Fdemo.js%3A50%2C11

**Comment by joy-stacks** [comment]
> > * [ ]   I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
> > 
> > ## Basic Info
> > ## What are the similar cases of this feature
> > 能否支持运行时动态主题色切换
> > ## What problem does this feature solve?
> > 能否支持运行时动态主题色切换
> > ## Extra info
> > 能否支持运行时动态主题色切换
> 
> 看看人家做的：http://arco.vueadminwork.com/

thanks
