### ISSUE TITLE
日历Calendar组件modes参数无效

### ISSUE THREAD

**Issue by zzs89117920** [arco-design/arco-design-vue#3229]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.55.3
- **框架版本:** Vue
- **浏览器版本:** chrome126.0.0.0

## 额外补充
源码calendar.tsx的237行是modes={['month', 'year']}，modes不是用props传的参数
![image](https://github.com/user-attachments/assets/5eacfc63-0cd1-4bcb-b737-9e8b0c54b09e)

## 预期结果
modes参数生效

## 复现步骤
modes参数设置['month']

**Comment by chenzhe-pro** [comment]
我也发现了，看什么时候改了
