### ISSUE TITLE
打包出现@input-size-mini-height is undefined

### ISSUE THREAD

**Issue by StarHuzy** [arco-design/arco-design-vue#3233]
升级最新版仍然出现这个问题，这个项目是没人维护了吗？这个项目是KPI项目吗？好多bug都没修复

**Comment by StarHuzy** [comment]
自从color-picker组件加了之后的每个版本打包都会出现这个报错，无论怎么升级都没用。

**Comment by oljc** [comment]
@StarHuzy 你好 这个问题在2.55.2 就修复了，如还是不行，希望可以给个详细的截图排查一下。尝试清空一下依赖包重新安装呢

**Comment by StarHuzy** [comment]
重新安装依赖安装了很多次了，一直报错
![image](https://github.com/user-attachments/assets/0752e73a-cded-4750-947a-6f391f1ebd6d)

**Comment by StarHuzy** [comment]
@oljc  最新版的，一直报错，删除依赖，重新安装依然不行
![image](https://github.com/user-attachments/assets/9f46201d-8f5d-4124-9ebc-edf0e9ed926c)

**Comment by sukbearai** [comment]
更新到新版本已经修复了
