### ISSUE TITLE
如何使用dropdown里的popup-container

### ISSUE THREAD

**Issue by harvenzhang** [arco-design/arco-design-vue#3237]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
希望官方文档能够有个详细的使用说明，popup-container指的是元素的ID吗

## What problem does this feature solve?
希望官方文档能够有个详细的使用说明，popup-container指的是元素的ID吗

**Comment by oljc** [comment]
传入 id 组件内部会去找对应 HTMLElement ，也可以直接传入 HTMLElement 元素
