### ISSUE TITLE
什么时候出vue mobile

### ISSUE THREAD

**Issue by seulfish** [arco-design/arco-design-vue#3247]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
什么时候出vue mobile

## What problem does this feature solve?
什么时候出vue mobile

**Comment by geelato** [comment]
期待

**Comment by oljc** [comment]
暂时没有 Vue 版计划，Duplicate of #1573
