### ISSUE TITLE
当前最新版本是2.56.0 但是文档中的级联 options中出现了2.8.0版本才有的属性？

### ISSUE THREAD

**Issue by BenjaminCCG** [arco-design/arco-design-vue#3253]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.0
- **Framework version:** VUE
- **Browser:** chrome127.0.0.0

![image](https://github.com/user-attachments/assets/43258045-f537-4142-b07b-3982eadc7bfb)

我需要通过这个tagProps来设置父级不可选取，尝试安装2.8.0发现影响到了原来的代码，有部分方法没有导出

**Comment by BenjaminCCG** [comment]
在当前的2.56.0版本中进入options的类型里是有tagprops属性的，但是做了设置却没有生效
![image](https://github.com/user-attachments/assets/33876b02-57d8-46d6-b899-73808914013e)

**Comment by oljc** [comment]
@BenjaminCCG 你好 2.56.0 > 2.8.0 版本，tagProps 从 2.8.0 起就开始生效的。
<img width="809" alt="image" src="https://github.com/user-attachments/assets/7cf7f3e5-648c-4a13-8359-3d930ddac7cf">
