### ISSUE TITLE
动态设置了@arcoblue-6样式但按钮hover还是原来颜色怎么解决？

### ISSUE THREAD

**Issue by qianggewudi6666** [arco-design/arco-design-vue#3259]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.56.0
- **浏览器版本:** chrome127.0.0.0

**Comment by qianggewudi6666** [comment]
目前直接写死@arcoblue-6: #f80021;是没问题的但通过setProperty 动态设置`--arcoblue-6`按钮hover样式还是之前的，应该怎么动态设置呢

**Comment by D15OS** [comment]
为什么不设置@arcoblue-4
