### ISSUE TITLE
固钉 Affix

### ISSUE THREAD

**Issue by zhuxianglong** [arco-design/arco-design-vue#3284]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
其他框架的固钉 Affix好像没这个问题

## What problem does this feature solve?
我在布局头部置顶的时候发现一个问题，offset-top设置大于0才生效，在使用的时候发现设置1的时候会导致有1px的展示出来，我觉得设置0也应该生效，应该是top: 0px;而不是1px

**Comment by oljc** [comment]
@zhuxianglong 没太看明白，不过我这边验证了一下设置`offsetTop`为 0 的时候 `top: 0px` 符合预期
