### ISSUE TITLE
vue版本的3个月不更新了啊 较于react版本落后太多了 很奇怪 难道用react写后台的占多数吗？

### ISSUE THREAD

**Issue by wangmou12138** [arco-design/arco-design-vue#3287]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.1
- **Framework version:** vue
- **Browser:** chrome128.0.0.0

**Comment by MinGuoGuo** [comment]
估计他们自己项目都是react吧
