### ISSUE TITLE
神仙项目，按照文档运行都运行不起来，

### ISSUE THREAD

**Issue by whenTheMorningDark** [arco-design/arco-design-vue#3288]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.1
- **Browser:** chrome128.0.0.0

**Comment by bsuooo** [comment]
是不是 node 版本太高了
