### ISSUE TITLE
希望字节的哥哥姐姐们，继续维护下去💐💐💐💐

### ISSUE THREAD

**Issue by XueNing-RJ** [arco-design/arco-design-vue#3295]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
无

## 预期解决问题
arco-design UI做的还是很细节的，各类组件设计风格，都是颜值在线，隔壁react更新的贼频繁。希望vue也稍微加点力气。如果因为公司内部太忙，希望可以多引入其他维护人员！或者可以使用社区共同维护方式来进行整个项目的迭代更新。

**Comment by oljc** [comment]
组件库是鼓励大家参与开源的，欢迎随时 PR! 🎉

**Comment by oljc** [comment]
Duplicate of  #3289
