### ISSUE TITLE
drawer使用v-model无法打开

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#330]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.9.0
- **System:** win11
- **Browser:** edge 96
- **Reproduction Link:** https://codepen.io/raymonda/pen/NWaxrXa

## Extra info
使用`v-model`无法打开，使用`visible`可以打开，但是无法触发`close`事件。

## What is expected?
drawer正常使用

## Steps to reproduce
打开链接即可复现

**Comment by kirazxyun** [comment]
你好，请使用v-model:visible
