### ISSUE TITLE
safari 浏览器下复制文字到 多选下拉框 组件内，文字左侧有小部分会被覆盖

### ISSUE THREAD

**Issue by Xgj22** [arco-design/arco-design-vue#3310]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.3
- **Framework version:** Vue3.4
- **Browser:** safari

## Steps to reproduce
1. 打开 多选下拉框框
2. 复制粘贴文本

**Comment by oljc** [comment]
@Xgj22 这边看好像是没有问题的。也许因为文本太长粘贴进去后光标在末尾所以前面的字像是被遮挡了一样？
