### ISSUE TITLE
[建议]Grid支持flex属性

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#333]
如题

**Comment by kirazxyun** [comment]
你好，我们不太明白这个需求，请提供一下详细的功能解释和应用场景，方便我们对功能进行讨论和决策。

**Comment by svipchao** [comment]
你好，React版有这个功能，https://arco.design/react/components/grid#Flex-%E7%94%A8%E6%B3%95

**Comment by kirazxyun** [comment]
> 你好，React版有这个功能，https://arco.design/react/components/grid#Flex-%E7%94%A8%E6%B3%95

收到，加上
