### ISSUE TITLE
按需引入 unplugin-vue-components 无法正常工作

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#3337]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.3
- **Framework version:** 3.5.x
- **Browser:** chrome129.0.0.0

## Steps to reproduce
1. 通过pnpm create vue创建最新vue模版项目
2. 引入unplugin-auto-import、unplugin-vue-components、arco
3. vite.config中使用
  ```
      Components({
        resolvers: [
          ArcoResolver({
            sideEffect: false,
          }),
        ],
      }),
  ```
4.  App.vue页面中使用按钮
  ```
        <a-button>按钮</a-button>
  ```
5.  `pnpm dev` 页面出现按钮，但是vscode中组件没有类型提示，且 `components.d.ts` 没有生成AButton引入
6.  `pnpm build`，`components.d.ts` 才生成 AButton

## Ext Info
```
    "@arco-design/web-vue": "^2.56.3",
    "unplugin-auto-import": "^0.18.3",
    "unplugin-vue-components": "^0.27.4",
```

**Comment by virgoheRomAn** [comment]
是怎么可以的？

**Comment by seepine** [comment]
看看生成的ts文件是否有被tsconfig.json包含，没有手动加一个

**Comment by virgoheRomAn** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
