### ISSUE TITLE
[Feature Request]Modal相关建议

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#335]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
[ElementPlus MessageBox](https://element-plus.org/zh-CN/component/message-box.html#%E6%8F%90%E4%BA%A4%E5%86%85%E5%AE%B9)

## What problem does this feature solve?
~~1、`content`支持换行，例如通过`\n`形式或者直接解析html标签（`<br/>`、`<pre/>`这些）。~~

~~2、增加`prompt`模式，弹出输入框。~~

3、添加`width`字段，而不是用`style`来控制宽度（虽说原理一样）

**Comment by llk2yq** [comment]
@Flsion

**Comment by Flsion** [comment]
@llk2yq modal下个版本会小重构一下，到时会支持这些功能
