### ISSUE TITLE
Select在Option较长时显示问题

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#337]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.9.0
- **System:** win11
- **Browser:** edge96
- **Reproduction Link:** https://codepen.io/raymonda/pen/oNGxyGE?editors=1000

## What is expected?
option显示完全，或者超出部分显示省略号，但是目前是显示不全也没有省略号。

## Steps to reproduce
打开链接，点击select

## Extra info
或者也可以像ElementPlus一样，展开框可以自己拉长
![Element Select](https://user-images.githubusercontent.com/22813922/145136269-3a64288d-f8f5-4440-a269-069b25c5c69a.png)

**Comment by llk2yq** [comment]
![超出部分](https://user-images.githubusercontent.com/22813922/145743931-a8639e33-cd0f-4ab4-8013-0dad4f24b68f.png)

**Comment by llk2yq** [comment]
@Flsion

**Comment by Flsion** [comment]
@llk2yq  可以设置 select 组件的 trigger-props 解决这个问题，:trigger-props="{autoFitPopupMinWidth:true}"

**Comment by llk2yq** [comment]
我也去看了React版本的API才知道
