### ISSUE TITLE
补充按需导入的编辑器提示或ts提示

### ISSUE THREAD

**Issue by renjiali** [arco-design/arco-design-vue#3374]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
详见腾讯的 https://tdesign.tencent.com/vue-next/getting-started#%E7%BC%96%E8%BE%91%E5%99%A8%E6%8F%90%E7%A4%BA

编辑器提示
安装注册 TDesign 之后，在开发项目时，可以配合插件在VSCode等主流编辑器中达到提示组件名及API的效果。

推荐安装 volar，并在项目的 tsconfig.json 的 includes 属性中增加node_modules/tdesign-vue-next/global.d.ts，即可实现该效果。

## What problem does this feature solve?
按需导入无提示

**Comment by lxmfly123** [comment]
這個可以自己在 tsconfig.json 裡加上 `node_modules/@arco-design/web-vue/es/*` 就可以

**Comment by oljc** [comment]
这个 Arco 也是支持的

<img width="758" alt="image" src="https://github.com/user-attachments/assets/70cd6d8d-857d-4d39-b311-ae714ea59ac7" />

**Comment by lxmfly123** [comment]
> 这个 Arco 也是支持的
> 
> <img alt="image" width="758" src="https://private-user-images.githubusercontent.com/48879481/398608472-70cd6d8d-857d-4d39-b311-ae714ea59ac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzU4OTQsIm5iZiI6MTczNTE3NTU5NCwicGF0aCI6Ii80ODg3OTQ4MS8zOTg2MDg0NzItNzBjZDZkOGQtODU3ZC00ZDM5LWIzMTEtYWU3MTRlYTU5YWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDAxMTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MjVmZDcwNWVkOTViNWZhNGZkOTQwMjkwMjdmYjdkMDk3MTZiODYyYTFmNDk5YzQ5NTAwNTAzYmQ1YjljYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yLn-QYa0fHmOQOaUJa0IC2CcxqZnZw9E14tsDN64Z88">

其实可以在文档里加一句的
