### ISSUE TITLE
官网和文档都打不开了

### ISSUE THREAD

**Issue by ttdms** [arco-design/arco-design-vue#3382]
[arco.design](https://arco.design/)
挂梯子和不挂梯子都打不开啊，可以确定的是本地网络正常。
没文档查要蒙圈了。

**Comment by yinkaihui** [comment]
https://arco-design-vue.netlify.app/ 可以先看这个，官网我们尽快修复

**Comment by renjiali** [comment]
{"errorCode":"404ID","errorMessage":"Not found, please make sure your service has been deployed and your invoke endpoint/domain is correct"}

**Comment by ZeroJsus** [comment]
一大清早 访问不到 我还以为公司的网故障了

**Comment by Lujango** [comment]
强制下班休息

**Comment by Nopysiu** [comment]
为什么老是挂掉啊，有点无语，三两天挂一次

**Comment by luyaogod** [comment]
404下班了

**Comment by Plumliil** [comment]
文档能不能在仓库里放一份😢🥲

**Comment by yinkaihui** [comment]
已修复了哈
