### ISSUE TITLE
滚动页面时，按钮触发的Popconfirm不跟随该按钮一起移动

### ISSUE THREAD

**Issue by Yoimiya-993** [arco-design/arco-design-vue#3388]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.56.2
- **Framework version:** vue 3.4.29
- **Browser:** chrome131.0.6778.205

## What is expected?
滚动页面时，Popconfirm跟随触发它的按钮一起移动

## Steps to reproduce
a-button外层包裹一个a-popconfirm，把页面搞的很长出现滚动条，点击按钮显示出Popconfirm后滚动页面

**Comment by oljc** [comment]
设置 `update-at-scroll `解决，详见 [Trigger](https://arco.design/vue/component/trigger)

**Comment by Yoimiya-993** [comment]
感谢解答

**Comment by Yoimiya-993** [comment]
Popconfirm的API表格中没提这个属性。既然Popconfirm是基于Trigger实现的，Popconfirm的API表格中不想提重复的属性，我觉得可以像element-plus这样在文档最上面加上一句话：
![image](https://github.com/user-attachments/assets/e7179230-d950-4a84-963a-69c2827c8211)
