### ISSUE TITLE
tree组件的第一层展开按钮在hover时，背景会超出父元素会被遮挡

### ISSUE THREAD

**Issue by changzhengithub** [arco-design/arco-design-vue#339]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.7.0
- **System:** 正常
- **Browser:** 正常
- **Reproduction Link:** https://codepen.io/changzhengithub/pen/vYJbLMP

## What is expected?
hover时背景色不要超出父元素

## Steps to reproduce
默认就会超出

## Extra info
同时，steps的为direction="vertical"时，current为激活状态时的圆点也会超出父元素。其他这样hover或者active状态的组件也有可能超出。

**Comment by kirazxyun** [comment]
你好，因为我们的 hover 都是使用的额外的背景层来显示，不占位所以会有这种情况，ui设计上这样才不会影响正常元素的展示，如果你们的场景中有 overflow hidden 的情况，可以增加padding来避免这个问题哦

**Comment by changzhengithub** [comment]
是可以通过加padding来解决，但是根本原因不应该是组件本身要为这些额外背景层预留位置吗。这样每次使用就不会再为了这些有可能会被遮挡的样式而再加样式。

**Comment by changzhengithub** [comment]
> 你好，因为我们的 hover 都是使用的额外的背景层来显示，不占位所以会有这种情况，ui设计上这样才不会影响正常元素的展示，如果你们的场景中有 overflow hidden 的情况，可以增加padding来避免这个问题哦



> 你好，因为我们的 hover 都是使用的额外的背景层来显示，不占位所以会有这种情况，ui设计上这样才不会影响正常元素的展示，如果你们的场景中有 overflow hidden 的情况，可以增加padding来避免这个问题哦

是可以通过加padding来解决，但是根本原因不应该是组件本身要为这些额外背景层预留位置吗。这样每次使用就不会再为了这些有可能会被遮挡的样式而再加样式。

**Comment by changzhengithub** [comment]
是可以通过加padding来解决，但是根本原因不应该是组件本身要为这些额外背景层预留位置吗。这样每次使用就不会再为了这些有可能会被遮挡的样式而再加样式。

**Comment by changzhengithub** [comment]
> 你好，因为我们的 hover 都是使用的额外的背景层来显示，不占位所以会有这种情况，ui设计上这样才不会影响正常元素的展示，如果你们的场景中有 overflow hidden 的情况，可以增加padding来避免这个问题哦

是可以通过加padding来解决，但是根本原因不应该是组件本身要为这些额外背景层预留位置吗。这样每次使用就不会再为了这些有可能会被遮挡的样式而再加样式。

**Comment by flsion** [comment]
tree已经增加默认padding
