### ISSUE TITLE
主题商店 加载不出来

### ISSUE THREAD

**Issue by YoungGary** [arco-design/arco-design-vue#3396]
项目还维护吗

**Comment by selvinzr** [comment]
等了好几天了，项目是还维护，但是这个主题商城崩了那么多天都不修复，有点懵

**Comment by yinkaihui** [comment]
封禁没法上线，明天应该就可了

**Comment by YoungGary** [comment]
还是不行呃

**Comment by SunYuanOnly** [comment]
主题新版本发布失败
`{"message": "request to https://arco.bytedance.net/admin/api/theme/listToken failed, reason: Client network socket disconnected before secure TLS connection was established",
 "type": "system",
"errno": "ECONNRESET",
"code": "ECONNRESET"
}`

**Comment by yinkaihui** [comment]
已修复

**Comment by Allamss** [comment]
> 主题新版本发布失败 `{"message": "request to https://arco.bytedance.net/admin/api/theme/listToken failed, reason: Client network socket disconnected before secure TLS connection was established", "type": "system", "errno": "ECONNRESET", "code": "ECONNRESET" }`

这个问题我在昨晚也复现了，直到今天上午尝试多次依旧未恢复，是什么原因呢，arco.bytedance.net指向的似乎是一个内网ip地址 @yinkaihui

**Comment by CasbaL** [comment]
> > 主题新版本发布失败 `{"message": "request to https://arco.bytedance.net/admin/api/theme/listToken failed, reason: Client network socket disconnected before secure TLS connection was established", "type": "system", "errno": "ECONNRESET", "code": "ECONNRESET" }`
> 
> 这个问题我在昨晚也复现了，直到今天上午尝试多次依旧未恢复，是什么原因呢，arco.bytedance.net指向的似乎是一个内网ip地址 [@yinkaihui](https://github.com/yinkaihui)

+1

**Comment by yinkaihui** [comment]
唉 确实有点问题，已经修复了，十分钟后在试试
