### ISSUE TITLE
菜单 Menu 使用水平菜单，菜单超出宽度，折叠效果存在缺陷

### ISSUE THREAD

**Issue by jekip** [arco-design/arco-design-vue#344]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue：2.9.0
- **System:** win10
- **Browser:** 谷歌
- **Reproduction Link:** https://arco.design/vue/component/menu

## What is expected?
期望是不受这个影响，能准确计算出宽度，进行菜单折叠

## Steps to reproduce
当页面存在动态元素切换的时候，会导致，menu 组件，始终无法准确按父级宽度展示菜单（会预留消失的元素宽度），内部监这个的时候，是否可以做到等页面或者说逻辑渲染完成，在执行这个计算

**Comment by jekip** [comment]
> 你好，请提供一个可复现的 demo 方便我们定位问题，十分感谢

https://codepen.io/jekip/pen/yLzJXOg  简单上个例子，复现原理和这个差不多

**Comment by kirazxyun** [comment]
> > 你好，请提供一个可复现的 demo 方便我们定位问题，十分感谢
> 
> https://codepen.io/jekip/pen/yLzJXOg 简单上个例子，复现原理和这个差不多

可以添加一个 width 100% 试试
![image](https://user-images.githubusercontent.com/10192144/145514156-986bb3bf-a587-4c43-86ae-f0edd8ba1cc0.png)

**Comment by jekip** [comment]
> > > 你好，请提供一个可复现的 demo 方便我们定位问题，十分感谢
> > 
> > 
> > https://codepen.io/jekip/pen/yLzJXOg 简单上个例子，复现原理和这个差不多
> 
> 可以添加一个 width 100% 试试 ![image](https://user-images.githubusercontent.com/10192144/145514156-986bb3bf-a587-4c43-86ae-f0edd8ba1cc0.png)

示例写上 100%，确实可以，项目中布局场景，还是存在问题，虽然我知道，动态切换布局和css可能会导致组件内部计算错误，但我没找到具体原因，抱歉
![image](https://user-images.githubusercontent.com/19426584/145524224-04ce252f-e350-40a4-a41c-3103105e9286.png)

比如这样，宽度是对的，只是计算折叠这个，确实存在些缺陷

![image](https://user-images.githubusercontent.com/19426584/145524328-ae1394bb-c4fd-4706-8adb-07361b6df7ae.png)

**Comment by kirazxyun** [comment]
> > > > 你好，请提供一个可复现的 demo 方便我们定位问题，十分感谢
> > > 
> > > 
> > > https://codepen.io/jekip/pen/yLzJXOg 简单上个例子，复现原理和这个差不多
> > 
> > 
> > 可以添加一个 width 100% 试试 ![image](https://user-images.githubusercontent.com/10192144/145514156-986bb3bf-a587-4c43-86ae-f0edd8ba1cc0.png)
> 
> 示例写上 100%，确实可以，项目中布局场景，还是存在问题，虽然我知道，动态切换布局和css可能会导致组件内部计算错误，但我没找到具体原因，抱歉 ![image](https://user-images.githubusercontent.com/19426584/145524224-04ce252f-e350-40a4-a41c-3103105e9286.png)
> 
> 比如这样，宽度是对的，只是计算折叠这个，确实存在些缺陷
> 
> ![image](https://user-images.githubusercontent.com/19426584/145524328-ae1394bb-c4fd-4706-8adb-07361b6df7ae.png)

是的，最好不去修改内部的布局和样式，会影响判断和计算。自定义的布局最好是包裹 div 来实现。

**Comment by jekip** [comment]
> > > > > 你好，请提供一个可复现的 demo 方便我们定位问题，十分感谢
> > > > 
> > > > 
> > > > https://codepen.io/jekip/pen/yLzJXOg 简单上个例子，复现原理和这个差不多
> > > 
> > > 
> > > 可以添加一个 width 100% 试试 ![image](https://user-images.githubusercontent.com/10192144/145514156-986bb3bf-a587-4c43-86ae-f0edd8ba1cc0.png)
> > 
> > 
> > 示例写上 100%，确实可以，项目中布局场景，还是存在问题，虽然我知道，动态切换布局和css可能会导致组件内部计算错误，但我没找到具体原因，抱歉 ![image](https://user-images.githubusercontent.com/19426584/145524224-04ce252f-e350-40a4-a41c-3103105e9286.png)
> > 比如这样，宽度是对的，只是计算折叠这个，确实存在些缺陷
> > ![image](https://user-images.githubusercontent.com/19426584/145524328-ae1394bb-c4fd-4706-8adb-07361b6df7ae.png)
> 
> 是的，最好不去修改内部的布局和样式，会影响判断和计算。自定义的布局最好是包裹 div 来实现。

没有修改组件内部布局和样式，我是指动态切换项目布局，布局确实都是用div包裹起来，宽度确实没啥问题，同一个布局方式，antd vue 没这个问题，不好找原因就先关了，之后看看有没有其他小伙伴发现 哈哈
