### ISSUE TITLE
下拉菜单 Dropdown 在IPhone的Safari浏览器中，无法弹出

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#352]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.9.0
- **System:** IOS13
- **Browser:** Safari
- **Reproduction Link:** https://arco.design/vue/component/dropdown

## What is expected?
Dropdown可以正常使用，如果定位到原因最好审查其他组件是否也会有相同问题

## Steps to reproduce
正常点击触发

**Comment by Flsion** [comment]
@seepine 可以提供下详细的系统版本和Safari版本吗，我们测试了几个是正常的

**Comment by seepine** [comment]
啊我的，我发现这个问题是因为有个一去广告的扩展导致的，可能它把弹窗也当成广告去掉了，关闭扩展就可以了
