### ISSUE TITLE
`lerna bootstrap` failed when followed `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by xiangqunXiao** [arco-design/arco-design-vue#368]
Followed https://github.com/arco-design/arco-design-vue/blob/main/CONTRIBUTING.zh-CN.md#%E6%8F%90%E4%BA%A4-pull-request,
and failed from step2 `lerna bootstrap` :
```
lerna notice cli v4.0.0
lerna info versioning independent
lerna info bootstrap root only
Unknown Syntax Error: Unsupported option name ("--mutex").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'arco-design-vue-monorepo'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'arco-design-vue-monorepo'
```

**Comment by Flsion** [comment]
You can follow https://github.com/arco-design/arco-design-vue/blob/main/README.md#development to start project, use `yarn` to install and `npm run init` to init project. `CONTRIBUTING.md` is wrong, I will fix it
