### ISSUE TITLE
upload希望增强预览文件功能

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#369]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
目前是点击图片会触发preview预览事件，点击其他文件如pdf会直接打开url，而且会在当前页签直接打开，当在表单中填了很多时，点击文件会刷新页面导致填写的白填

希望
1.能直接预览，如点击了图片默认用`a-image-preview`或`a-image-preview-group`打开预览，点击pdf/md/txt等，可以直接弹窗预览内容
2.或者简单一点，将普通文件的点击预览事件也放出来，让我们自己做，别再自动跳转url（跳到新页签也就算了，结果还是直接当前页签）

**Comment by Flsion** [comment]
@seepine 收到，我们讨论看一下

**Comment by seepine** [comment]
你好还没进展吗，要不将普通文件的点击预览事件先放出来？现在项目马上上线这个问题很大

**Comment by Flsion** [comment]
这个是指照片墙模式吗，普通文件也会展示预览按钮。图片浏览的优化下个版本处理下

**Comment by seepine** [comment]
> 这个是指照片墙模式吗，普通文件也会展示预览按钮。图片浏览的优化下个版本处理下

![image](https://user-images.githubusercontent.com/93666053/147426307-d92da3de-779c-4455-a5e9-63e2dd98600a.png)
1. 期望`list-type="picture-card"`或`list-type="picture-card"`时，点击预览图标，默认单张图片通过`a-image-preview`预览，多张图片通过`a-image-preview-group`预览。
2. 当`list-type="text"`，也就是默认类型时，点击文件可以通过判断文件类型，当是图片时，也是通过image-preview来展示，当pdf/txt时通过弹a-modal展示内容，当无法展示的比如zip等通过打开新窗口触发下载
3. 或者第二点难度大的话，把点击文件的事件开放出来，因为现在预览事件`preview`只有点击图片的预览按钮才会触发，我们无法监听到点击普通文件的事件

**Comment by Flsion** [comment]
@seepine 2.13.0版本添加了 showLink 属性，关闭后此属性后，点击文本会触发 preview 事件。下个版本会添加内置图片展示处理

**Comment by seepine** [comment]
@Flsion  

>希望
1.能直接预览，如点击了图片默认用a-image-preview或a-image-preview-group打开预览，点击pdf/md/txt等，可以直接弹窗预览内容
2.或者简单一点，将普通文件的点击预览事件也放出来，让我们自己做，别再自动跳转url（跳到新页签也就算了，结果还是直接当前页签）

这个这个，不明白添加`showLink`属性的作用是什么，如我说的第二点，一般场景都是希望文件还是可点击状态，只不过希望能增加类似`preview`的时间，在用户点击非图片时能触发事件，让开发者能写展示的逻辑
```
preview | 点击图片预览时的触发 | fileItem: FileItem
```
而添加`showLink`属性，把文件直接变普通文字了，这...

**Comment by seepine** [comment]
最简单的做法
添加比如`itemClick(fileItem: FileItem)`事件，传出用户点击文件的信息
再加个比如`autoOpen`属性，设为false时，点击文件将不会自动打开文件的链接
这样就能满足了啊

比如element的upload，
https://element-plus.gitee.io/zh-CN/component/upload.html#attributes
点击文件名，不会打开文件链接（相当于autoOpen默认false）
然后e-upload有`on-preview`属性，可以让开发者知道用户点击了哪个文件

**Comment by Flsion** [comment]
showLink 设置为 false 也是这个效果呀，点击文件名不会跳转链接，而是触发 preview 事件，另外当文件不存在 url 的时候，也就是没有打开链接的时候，也会以这种形式展示
