### ISSUE TITLE
[Feature Request]Table添加height属性

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#371]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Table添加height属性

## What problem does this feature solve?
Table添加height属性，这样就可以让table始终占据一定位置，而不是随数据量而改变高度。
且当列比较多的时候，开启了scroll后，没有数据时，空白提示可以居中。

**Comment by llk2yq** [comment]
@Flsion

**Comment by flsion** [comment]
支持height属性，可参考示例 https://element-plus.org/zh-CN/component/table.html#table-%E5%B1%9E%E6%80%A7
