### ISSUE TITLE
Textarea 高度无法自定义

### ISSUE THREAD

**Issue by fangjc1986** [arco-design/arco-design-vue#373]
a-textarea 初始高度貌似只能 2 行，能否加个参数设定初始行数， 类似 textarea 中的 rows 属性；

**Comment by Flsion** [comment]
用行控制可以吗，类似这个 https://codepen.io/flsion/pen/gOGLQbK

**Comment by fangjc1986** [comment]
可以，是我没看全文档~ ，不好意思。
