### ISSUE TITLE
modal 的 before-ok 可以支持async方法吗 目前不支持

### ISSUE THREAD

**Issue by yjj5855** [arco-design/arco-design-vue#376]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
把源码修改成async方法
const result = awit props.onBeforeOk(resolve);
          if (isBoolean(result)) {
            resolve(result);
          } else {
            _okLoading.value = true;
          }

## What problem does this feature solve?
我用这个方法一般是要验证表单,然后再ajax请求, 使用async后不能及时返回false, 导致ok按钮一直loading 无法控制. 

## Extra info
目前只能这样使用

export function useFormInDialog (promise, ref_form = null) {

  const okLoading = ref(false)

  function beforeOk (done) {
    let validatePromise = ref_form ? ref_form.value.bbValidate() : Promise.resolve()
    validatePromise
      .then(() => {
        okLoading.value = true
        promise()
          .then(() => {
            okLoading.value = false
            done()
            Message.success('编辑成功!')
          })
          .catch(err => {
            okLoading.value = false
            Message.error('编辑失败')
          })
      })
      .catch(err => {
        console.warn('表单校验失败!', err)
        okLoading.value = false
      })
    return false
  }

  return {
    okLoading,
    beforeOk
  }
}

**Comment by Flsion** [comment]
@yjj5855 
```js
    handleBeforeOk(done) {
      this.$refs.formRef.validate().then(errors => {
        if (!errors) {
          // mock axios
          window.setTimeout(() => {
            done()
          }, 3000)
        } else {
          done(false)
        }
      })
    }
```
是否是这样的效果，BeforeOk会自动控制okLoading的状态，一般不需要用户再控制的

**Comment by yjj5855** [comment]
@Flsion 下面这种情况, 一般是先验证表单,然后网络请求吧. 成功才会把modal关掉, 失败只是提示错误的话, 就不能修改表单后重新确定了
![image](https://user-images.githubusercontent.com/6870430/146162787-446e4a20-e8c4-49ac-b3da-3a1604fd573d.png)

**Comment by seepine** [comment]
> ```js
> done
> ```

没毛病啊，你done(false)不就能重新确定了

**Comment by yjj5855** [comment]
@seepine @Flsion 是我傻了 done(false) 就可以了 不是 return false 学艺不精啊 感谢!

**Comment by czq297297** [comment]
@flsion 能直接返回一个promise  比较方便谢  无异常则代表成功，异常则内部done(false)
比如这样
  handleBeforeOk(done) {
     return myPromise()
    }
