### ISSUE TITLE
tab标签bug

### ISSUE THREAD

**Issue by liuyike98** [arco-design/arco-design-vue#377]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-vue的2.10.0
- **系统版本:** win10
- **浏览器版本:** electron16.0.4
- **复现地址:** http://baidu.com

## 预期结果
能自适应，在宽度合适后恢复原来的状态，而不是继续保持左右箭头标签

## 复现步骤
https://s2.loli.net/2021/12/14/tuk9MKPdrps4ciX.gif
在一开始宽度较小的情况下，出现滚动很正常，但是当界面已经更改到合适大小，依旧出现左右滚动箭头

**Comment by Flsion** [comment]
收到，这个会处理一下
