### ISSUE TITLE
tree-select 组件 选项和选择框无法在一个水平面上

### ISSUE THREAD

**Issue by duxphp** [arco-design/arco-design-vue#386]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-vue
- **系统版本:** 2.10.0
- **浏览器版本:** edge96
- **复现地址:** https://codepen.io/pen/?editors=0010

## 预期结果
使用flex做对齐

## 复现步骤
复选框和标题名称无法垂直对齐

**Comment by Flsion** [comment]
@duxphp codepen忘了保存
