### ISSUE TITLE
When importing the component on demand, the default componentPrefix does not work.

### ISSUE THREAD

**Issue by WJCHumble** [arco-design/arco-design-vue#39]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info
- **依赖包名 及 版本:** @arco-design/web-vue:  2.0.3
- **系统版本:** macos 10.15.7
- **浏览器版本:** chrome 93.0.4577.82
- **复现地址:** https://github.com/WJCHumble/acro-design-demo

## 额外补充
I found that the name of the fully imported component used `componentPrefix`  +  `Component.name`, but the name of the demand imported component only used `export name`.

## 预期结果
It can use `<a-button>` in `<template>`.

## 复现步骤
1. Create a vue3 + vite project.
2. Add `vite-plugin-import` plugin to imports component's style on demand.
3. Import component in `<script setup>`, such as `import { Button } from "@arco-design/web-vue"`, and then can't use `<a-button>` in `<template>`.

**Comment by Flsion** [comment]
You need to register the ArcoVue component library in the app before you can use the usage of `<a-button>` in the template.
https://arco.design/vue/docs/start

**Comment by WJCHumble** [comment]
@Flsion  I mean the name of  the `export` component  need a default prefix. In this way, it can distinguish the user component and library component when I **imported component on demand**.

**Comment by Flsion** [comment]
@WJCHumble In order to be more versatile, the exported variable of the component will not be prefixed by default, if want to add a prefix, you can use `import as` to rename the component name.

```vue
<script setup>
import { Button as AButton } from "@arco-design/web-vue"
</script>

<template>
    <AButton type="primary">Primary</AButton>
</template>
```

**Comment by WJCHumble** [comment]
@Flsion well, I know it can use `import as` to rename the component name, but I think it is too troublesome, maybe I will write a plugin to automatically rename the component name. Thank you for your answer.
