### ISSUE TITLE
a-select 选择框的滚动到底部无法触发 dropdown-reach-bottom 无法触发

### ISSUE THREAD

**Issue by DianaYako** [arco-design/arco-design-vue#392]
![图片](https://user-images.githubusercontent.com/65520240/146142171-aea56c4e-e098-4a5e-af89-1db0fc4b4b3a.png)
![图片](https://user-images.githubusercontent.com/65520240/146142217-e988145a-a821-4863-9d08-988caad4c677.png)

**Comment by Flsion** [comment]
@DianaYako 可以提供个codepen吗，DEMO中是正常的

![image](https://user-images.githubusercontent.com/29793175/146152806-868b01dd-35b2-4dd4-ad54-415bbb05f11d.png)

**Comment by DianaYako** [comment]
我在 codepen 中看了一下也是没问题的 是和我按需引入有关系吗？我贴一下我的package.json
![图片](https://user-images.githubusercontent.com/65520240/146154544-d6c818e9-7d59-4082-b782-1634999dc471.png)
代码
![图片](https://user-images.githubusercontent.com/65520240/146155077-36d8a06a-883e-4ca9-a2dd-85801bafddb2.png)
![图片](https://user-images.githubusercontent.com/65520240/146154625-7180ef57-b168-439a-b526-a1adfcce18c7.png)
![图片](https://user-images.githubusercontent.com/65520240/146155140-db848dc5-a103-4c0e-b99e-196e85a2710a.png)


麻烦您看一下是我哪里写的有问题吗 官方demo和codepen我也看了一下都没问题

**Comment by Flsion** [comment]
@DianaYako 升级到最新版的2.10.1试试可以吗，dropdown组件重构了

**Comment by DianaYako** [comment]
![图片](https://user-images.githubusercontent.com/65520240/146320238-ea09d8fe-9a55-49a2-b94f-6a5ab1bf48c6.png)
更新了 还是不行

**Comment by DianaYako** [comment]
可以了 谢谢
