### ISSUE TITLE
菜单在IPhone 15.1，收缩状态下显示有问题

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#395]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.10.0
- **System:** IOS15.1
- **Browser:** Safari和谷歌都是

## Steps to reproduce
![](https://www.hualigs.cn/image/61b9b982b8ec0.jpg)

**Comment by kirazxyun** [comment]
收到，我们优化一下样式

**Comment by kirazxyun** [comment]
@seepine 你好，是否修改过 menu 的样式呢，检查一下以下代码是否还生效
![image](https://user-images.githubusercontent.com/10192144/146479343-c4faff0a-c8cd-4a0c-b266-0b8cc73d9b79.png)

**Comment by seepine** [comment]
有，你可以用手机真机的Safari或google浏览器测一下，都是这样

**Comment by kirazxyun** [comment]
@seepine 你好，新增了 icon slot，将 icon 和 title 分开，以此来实现 title 的完全隐藏，新版本发布后可以试试

**Comment by seepine** [comment]
👌
