### ISSUE TITLE
tooltip显示异常

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#402]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.10.1
- **System:** win11
- **Browser:** edge 96
- **Reproduction Link:** https://codepen.io/raymonda/pen/JjrNKLK?editors=1000

## Extra info
`tooltip`内的文本，没有标签包裹时，`tooltip`不显示。

## What is expected?
`tooltip`正常工作

## Steps to reproduce
打开链接，参考注释的复现步骤

**Comment by llk2yq** [comment]
@Flsion

**Comment by Flsion** [comment]
@llk2yq tooltip和类似的trriger类组件，需要监听slot元素的事件，所以需要HTMLElement，文本的话就没有办法触发了

**Comment by llk2yq** [comment]
明白了，建议文档里加一下！
