### ISSUE TITLE
a-tab-pane :closable = "false" 不生效

### ISSUE THREAD

**Issue by Dimlt** [arco-design/arco-design-vue#403]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/arco-design-vue: ^2.9.0
- **System:** win10最新
- **Browser:** edge最新
- **Reproduction Link:** https://arco.design/arco-design-vue

## Extra info
就是这个属性没有生效而已

## What is expected?
closable ===  false 时，应该不显示【关闭按钮】

## Steps to reproduce
`
<template>
  <a-tabs type="card-gutter" :editable="true">
    <a-tab-pane v-for="(item, index) of data" :key="item.key" :title="item.title" :closable="index!==2">
      {{ item?.content }}
    </a-tab-pane>
  </a-tabs>
</template>
`

**Comment by Dimlt** [comment]
就和官方文档一样的写法，但是 closable = false 了，页面还是显示了 【关闭按钮】

**Comment by Flsion** [comment]
@Dimlt 可以升级下最新版，2.10.0修复了这个问题

**Comment by Dimlt** [comment]
OK了
