### ISSUE TITLE
tree组件expand事件，文档写错了

### ISSUE THREAD

**Issue by liuyike98** [arco-design/arco-design-vue#404]
我按照文档一直返回undefined，打印出来看了看应该是文档不对。
![image](https://user-images.githubusercontent.com/87092276/146496178-2b9b048f-9c64-4373-89be-b4934f37521b.png)
![image](https://user-images.githubusercontent.com/87092276/146496210-2f834db0-72d8-4eab-b9e9-0f9985a3cb20.png)
是expanded

**Comment by Flsion** [comment]
@liuyike98 收到，感谢反馈
