### ISSUE TITLE
a-input-password不支持prefix插槽

### ISSUE THREAD

**Issue by wraptor** [arco-design/arco-design-vue#41]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info
- **依赖包名 及 版本:** 2.0.3
- **系统版本:** macos
- **浏览器版本:** 版本 95.0.4638.54（正式版本） (arm64)
- **复现地址:** https://arco.design/vue/component/input

## 预期结果
可以和a-input一样，支持prefix

## 复现步骤
```
<a-input-password>
    <template #prefix>
        <icon-lock />
    </template>
</a-input-password>
```

**Comment by Flsion** [comment]
@wraptor 2.1.0版本会添加支持

**Comment by wraptor** [comment]
> @wraptor 2.1.0版本会添加支持

这个项目不接受pr吗，上周提了没有响应
