### ISSUE TITLE
请selector选择器组件优化

### ISSUE THREAD

**Issue by liuyike98** [arco-design/arco-design-vue#419]
![QQ录屏20211217232540](https://user-images.githubusercontent.com/87092276/146569769-babac68a-428a-4d1b-bb10-6a3b70d44d6e.gif)
由于你们是使用将选择器下拉出来的options固定到了body里，而脱离了本身，窗口发生resize后就会错位，而且你们对收缩的判断是否有改进的地方？如视频中演示，白色区域为iframe，在弹出菜单后，点击iframe区域不能收缩。我觉得应该赋予tabindex让其具有焦点，通过焦点的丢失来进行收缩，而不是监听document的点击事件

**Comment by Flsion** [comment]
@liuyike98 好的，这个问题我们讨论下怎么处理

**Comment by flsion** [comment]
在 iframe 中无法触发外部 click 事件，导致这里不会关闭，这个可以通过修改 select 下拉菜单的触发方式为 focus 来处理。
