### ISSUE TITLE
a-col的span支持0，使得可以直接控制显隐

### ISSUE THREAD

**Issue by wraptor** [arco-design/arco-design-vue#42]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

##  预期解决问题
```
<a-col    :xs="0"    :md="24">
    ......
</a-col>
```
## 现有案例
```
<a-col    class="xs-hide"   :md="24">
    ......
</a-col>
```
```
@media screen and (max-width: 576px) {
  .xs-hide {
    display: none;
  }
}
```

**Comment by kirazxyun** [comment]
你好，我们的 span 和响应式都是通过修改 width 来控制显示的大小的，直接隐藏会使得响应式失效。如果是想要不展示的话，建议通过 v-if 的方式来处理。
