### ISSUE TITLE
Modal可否加上 Esc 键关闭

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#421]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
antd

## What problem does this feature solve?
Modal可否加上 Esc 键关闭

**Comment by Flsion** [comment]
@CarmenHYC 好的，下个版本会添加下

**Comment by gaopeak** [comment]
不支持弹窗表单吗？还有验证
