### ISSUE TITLE
Affix 滚动报 [Vue warn]

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#423]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design-vue 2.11.0
- **System:** Mac
- **Browser:** chrome
- **Reproduction Link:** https://arco.design/vue/component/affix

## What is expected?
runtime-core.esm-bundler.js:6620 [Vue warn]: Extraneous non-emits event listeners (resize) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 

## Steps to reproduce
<a-affix>
        <a-page-header>
                ...
        </a-page-header>
</a-affix>

**Comment by Flsion** [comment]
@CarmenHYC 是个已知问题，我们会修复下，这个不会影响到使用
