### ISSUE TITLE
TableSortable 可否设一个绑定排序的变量

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#425]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
-

## What problem does this feature solve?
用sortOrder没有效果，由于排序是交给后台来读取数据的，如果我当前点了descend，但由于某些操作（比如刷新页面）得置了排序，此时sortOrder已经变成了空，但图标还是亮着的

**Comment by Flsion** [comment]
@CarmenHYC 这个是清空 sortOrder 后，仍然显示排序的问题吗？

**Comment by CarmenHYC** [comment]
> @CarmenHYC 这个是清空 sortOrder 后，仍然显示排序的问题吗？

是的
