### ISSUE TITLE
a-input-tag 在中文输入法输入后无法使用

### ISSUE THREAD

**Issue by zhoujianxiong** [arco-design/arco-design-vue#426]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** 3.11.0
- **系统版本:** mac
- **浏览器版本:** Google Chrome 版本 92.0.4515.159
- **复现地址:** https://arco.design/vue/component/input-tag

## 预期结果
正常生成标签

## 复现步骤
在中文输入法输入后，回车无法生效

**Comment by Flsion** [comment]
@zhoujianxiong 收到，是2.11.0版本出现的问题，我们处理一下

**Comment by Flsion** [comment]
@zhoujianxiong 可以升级下2.11.1版本，修复了这个问题

**Comment by zhoujianxiong** [comment]
试了 可以了
