### ISSUE TITLE
在组件中引入<a-modal>组件出现警告

### ISSUE THREAD

**Issue by uniwxs** [arco-design/arco-design-vue#429]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** "@arco-design/web-vue": "^2.9.0"
- **系统版本:** "vue": "^3.2.23"
- **浏览器版本:** chrome96
- **复现地址:** xxx.com

## 额外补充
[Vue warn]: Failed to resolve component: a-modal
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 

## 预期结果
如何清楚控制台警告信息

## 复现步骤
暂无

**Comment by Flsion** [comment]
问下是怎样引入的组件库，这个警告是没有解析到 Modal 组件产生的

**Comment by uniwxs** [comment]
> 问下是如何引入的组件库，这个警告是没有解析到 Modal 组件产生的

使用`babel-plugin-import`按需引入的。

**Comment by Flsion** [comment]
@uniwxs  贴下配置代码
