### ISSUE TITLE
增加颜色选择器组件

### ISSUE THREAD

**Issue by topoge** [arco-design/arco-design-vue#433]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://element-plus.org/zh-CN/component/color-picker.html

## 预期解决问题
选择颜色

**Comment by flsion** [comment]
官方组件库目前不会添加颜色选择器组件，如果感兴趣可以在物料平台上创建一个颜色选择器组件试试 https://arco.design/material/
