### ISSUE TITLE
badge在count为0时不隐藏

### ISSUE THREAD

**Issue by MistyMountain1024** [arco-design/arco-design-vue#435]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.11.1
- **系统版本:** Windows 11
- **浏览器版本:** Chrome  96.0.4664.110
- **复现地址:** https://codepen.io/mistymountain1024/pen/MWEvxdz?editors=1010

## 预期结果
在count=0时应该不显示badge

## 复现步骤
在<a-badge :count="9">处设置count=0，依然显示内容为‘0’的badge，而非隐藏；测试react版本可以正常隐藏。

**Comment by Flsion** [comment]
@MistyMountain1024 感谢反馈，下个版本会处理下
