### ISSUE TITLE
el-select能否支持选择对象

### ISSUE THREAD

**Issue by emily0228** [arco-design/arco-design-vue#436]
目前v-model的绑定至类型，只支持string | number | (string | number)[]，
如果要选择某个对象，只等通过遍历的方式获取。
比如：[{id:1,name:'name11'},{id:2,name:'name22'}],希望能同时取到id和name，并支持回显

**Comment by Flsion** [comment]
@emily0228 目前在尝试在 change 事件中抛出 OptionInfo 对象，包括所有信息。v-model 由于要做选择判断，不适合处理成对象

**Comment by emily0228** [comment]
是否可以试着像element plus那样，当v-model绑定为整个object时，设置一个value-key当成value的唯一标识，这样既能选object，又能回显。
![image](https://user-images.githubusercontent.com/26404014/147199628-6bc88228-66e8-421d-85b9-ef1646602658.png)

**Comment by emily0228** [comment]
@Flsion

**Comment by Flsion** [comment]
@emily0228 这个功能会在 2.15.0 版本支持下
