### ISSUE TITLE
form-item的rules和help不能同时存在，触发rules后不会显示且高度会变化

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#438]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.11.0
- **System:** Macos
- **Browser:** GoogleChrome

## Steps to reproduce
```vue
<a-form-item field="name" label="Username" :rules="rules" help="this is help">
      <a-input v-model="form.name" placeholder="please enter your username..." />
</a-form-item>
```
![image](https://user-images.githubusercontent.com/93666053/147100162-6bd87151-2bb7-48c5-af9e-09c9572aec78.png)
![image](https://user-images.githubusercontent.com/93666053/147100200-8d308c0c-382a-4787-a8ed-a06ae210cd21.png)

**Comment by Flsion** [comment]
@seepine 这里是个问题，错误信息应该展示在 help 之上，这个会修复下
