### ISSUE TITLE
table列表的自定义渲染展示有bug

### ISSUE THREAD

**Issue by jerryhu88** [arco-design/arco-design-vue#44]
从codeup预览能复现，样式和数据渲染异常，但是在项目中样式正常，列表无数据
![image](https://user-images.githubusercontent.com/40226377/139608881-815a0892-a0c9-44b1-9001-86be4422a35b.png)

![image](https://user-images.githubusercontent.com/40226377/139608785-be741fcd-081b-4699-aee0-30ef6169c13a.png)

**Comment by Flsion** [comment]
@jerryhu88 这个是codenpen的html模板不支持vue语法导致的，之后会换用其他方式梳理DEMO到Codepen的代码

**Comment by jerryhu88** [comment]
项目里也是空的
![image](https://user-images.githubusercontent.com/40226377/139633042-22af3dc9-128b-4aed-a225-304145856a60.png)
![image](https://user-images.githubusercontent.com/40226377/139633068-6db99950-bac7-4e25-85bb-06a12d8c8be8.png)
