### ISSUE TITLE
[Feat Req]提个关于upload上传类型判断的建议，对于特殊list-type是不是在内部判断哪些文件可以上传比较好

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#441]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
![image](https://user-images.githubusercontent.com/93666053/147213104-7c5c19a3-ae59-41b9-8adb-d33d5a256b4d.png)
例如list-type="picture"或"picture-card"，应该不让上传非图片文件，否则就会出现预览错误

**Comment by seepine** [comment]
目前我是自己封装upload，内部去判断listType改accept的值，listType为图片时accept默认为`'.png, .jpg, .jpeg, .bmp, .webp'`，在我部门几个开发上macos、window，google、edge、safari都测过，是有效果的，也能控制listType含picture时只能传图片；

但是上线后发现有用户竟然传的是pdf文件，也就是在他们电脑上accept没有生效，这个问题不知道你们有没有遇过

**Comment by Flsion** [comment]
@seepine 这个有些浏览器下是确实可能不生效，https://caniuse.com/?search=%20input%20file，我看下是否能在内部再次校验下。

**Comment by Kigoal** [comment]
可以通过使用 `image/*` 来解决，好像iOS下的Safari还不支持`.png`这样的写法。

我目前是这样设置来避免的：
```typescript
const acceptList = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/apng',
  'image/avif',
  'image/heif'
]
```

**Comment by seepine** [comment]
> 可以通过使用 `image/*` 来解决，好像iOS下的Safari还不支持`.png`这样的写法。
> 
> 我目前是这样设置来避免的：
> 
> ```ts
> const accept = [
>   'image/jpeg',
>   'image/png',
>   'image/webp',
>   'image/apng',
>   'image/avif',
>   'image/heif'
> ].join(',')
> ```

好的多谢
