### ISSUE TITLE
Message 等反馈组件通过全局方法调用时，类名前缀不生效

### ISSUE THREAD

**Issue by zhengzihan-lz** [arco-design/arco-design-vue#458]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue:2.12.0
- **System:** MacOS
- **Browser:** Edge
- **Reproduction Link:** https://codepen.io/zhengzihan-lz/pen/yLzPxox

## What is expected?
类名前缀为自定义的前缀而非默认前缀 arco

## Steps to reproduce
1. 全局配置：
``` html
<a-config-provider prefix-cls=" test-class"></a-config-provider>
```
2. 页面中调用组件：
``` js
getCurrentInstance().appContext.config.globalProperties.$message.info( '测试消息')
// 或
this.$message.info( '测试消息')
// 或
Message.info('测试消息')
```
3. 打开浏览器 DevTools 检查消息弹层的类名前缀仍为 `arco` 而非 `test-class`

**Comment by Flsion** [comment]
@zhengzihan-lz 好的，我们查看一下
