### ISSUE TITLE
自定义组件如何借助ConfigProvider适配i18n?

### ISSUE THREAD

**Issue by gcxfd** [arco-design/arco-design-vue#46]
## 现有案例
 
https://github.com/arco-design/arco-design-vue/blob/73e63ddfa9d1b2e11c934fc810d4fcda898cda8b/packages/web-vue/components/pagination/page-jumper.vue
我看了下代码，貌似是这么用的
```
import { useI18n } from '../locale';
    const { t } = useI18n();
    <span v-if="!simple">{{ t('pagination.goto') }}</span>
```
https://github.com/arco-design/arco-design-vue/blob/73e63ddfa9d1b2e11c934fc810d4fcda898cda8b/packages/web-vue/components/locale/index.ts
packages/web-vue/components/locale/lang/ 下面定义语言

## 预期解决问题

但是还是没解决我的问题，就是自定义组件如何借助ConfigProvider适配i18n。因为不太清楚locale如何指定自定义组件语言包的位置

**Comment by Flsion** [comment]
@gcxfd ConfigProvider主要是用来配置Vue组件库的，不建议用来给自己的组件适配i18n，这里可以使用 https://vue-i18n.intlify.dev/ 实现i18n
