### ISSUE TITLE
【Feature Request】希望自动补全 AutoComplete组件可以对标Input组件功能，例如前后置，前后缀槽等

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#461]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
希望自动补全 AutoComplete组件可以对标Input组件功能，例如前后置，前后缀图标/槽等

## What are the similar cases of this feature
例如目前想实现阿里云登录，可以输入用户名，点击输入框后出现自动提示历史登录过的账号，但是autoComplete又没有prefix槽（因为登录表单前面有图标）
另外也希望弹出的内容也可以自定义，比如不仅仅想展示文字，需要展示头像+文字+关闭图标，所以内容希望也能有槽可以自定义

**Comment by Flsion** [comment]
@seepine 下个版本会增加相关功能
