### ISSUE TITLE
表格的排序问题

### ISSUE THREAD

**Issue by MinZ88** [arco-design/arco-design-vue#468]
1. defaultSortOrder: 'descend' 默认设置的这个
   然后我反向排序需要点击两次才行：第一次取消当前排序 第二次才生效
   感觉怪怪的
2. 怎么动态设置默认的排序选项 动态设置貌似不生效
3. 改变排序之后 界面上更新了 但是数据为什么没有同步更新呢  我自己再去同步更新一下 界面反而不更新了。 这样的话 涉及到数据的新增和行操作处理起来就比较麻烦了
4. 我打开一个弹窗（seq字段设置了排序），点击了排序  。 再关闭弹窗。 再打开弹窗，排序状态还在，怎么重置取消掉这个排序的状态？动态修改sortOrder或者defaultSortOrder无效

**Comment by Flsion** [comment]
1. sortDirections 是不是设置了 ['ascend', 'descend']，可以改成 [ 'descend', 'ascend']
2. defaultSortOrder 是mounted后一次生效的, sortOrder 是可以受控的
3. 组件不会修改用户传入的 data，目前还没有传出排序后的数据方法，这个可以提个功能issue
4. 弹窗如果没有开启关闭销毁的话，内容状态是不会重置的。如果需要重置可以开启 `unmount-on-close`

**Comment by llk2yq** [comment]
@Flsion 额外咨询一下，`table`怎么使用服务端排序（1）呢？以及如何使用多字段排序（2）呢？文档中有类似参考例子吗？注：使用的是 **_#columns_** 的渲染模式。

**Comment by MinZ88** [comment]
> 1. sortDirections 是不是设置了 ['ascend', 'descend']，可以改成 [ 'descend', 'ascend']

这个改成 [ 'descend', 'ascend']之后 ，似乎还是有问题@Flsion

**Comment by Flsion** [comment]
> > 1. sortDirections 是不是设置了 ['ascend', 'descend']，可以改成 [ 'descend', 'ascend']
> 
> 这个改成 [ 'descend', 'ascend']之后 ，似乎还是有问题@Flsion

改完之后设置 defaultSortOrder: 'descend' ,第一次点击后不是变成 ascend 了吗？

**Comment by Flsion** [comment]
> @Flsion 额外咨询一下，`table`怎么使用服务端排序（1）呢？以及如何使用多字段排序（2）呢？文档中有类似参考例子吗？注：使用的是 **_#columns_** 的渲染模式。

目前还没有服务器端排序和多列排序的支持，这个可以提个 issue 支持下。

**Comment by Flsion** [comment]
@MinZ88 这个 issue 还有问题吗？

**Comment by bytrix** [comment]
> @MinZ88 这个 issue 还有问题吗？

第三个问题的数据同步在新版本解决了吗？
