### ISSUE TITLE
建议增加一种主题设置方式，根据主色自动生成色阶（辅助颜色）

### ISSUE THREAD

**Issue by topoge** [arco-design/arco-design-vue#475]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
element-ui的实现比较简单，是根据透明度搞的

## 预期解决问题
动态设置主色，辅色风格不会变化

## 额外补充
可以在ConfigProvider中让用户自主选择色阶方式，比如theme-colors：auto啥的

**Comment by hehehai** [comment]
@topoge 你好，建议直接使用 https://arco.design/themes 做更加细化的主题配置
