### ISSUE TITLE
放到实际项目中，列表也是空的，有数据却没显示出来

### ISSUE THREAD

**Issue by jerryhu88** [arco-design/arco-design-vue#48]
项目里也是空的
![image](https://user-images.githubusercontent.com/40226377/139633042-22af3dc9-128b-4aed-a225-304145856a60.png)
![image](https://user-images.githubusercontent.com/40226377/139633068-6db99950-bac7-4e25-85bb-06a12d8c8be8.png)

_Originally posted by @jerryhu88 in https://github.com/arco-design/arco-design-vue/issues/44#issuecomment-955977979_

**Comment by Flsion** [comment]
@jerryhu88 有定位到问题了，目前table-column只识别了dataIndex，而data-index没有处理，下个版本会修复
