### ISSUE TITLE
下拉菜单 Dropdown希望可以添加指示图标

### ISSUE THREAD

**Issue by bzw1204** [arco-design/arco-design-vue#489]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
1. 现有实现无法看出当前组件是个下拉组件

## 预期解决问题
1. 下拉菜单增加相应的指示图标
2. 参考案例 https://element-plus.gitee.io/zh-CN/component/dropdown.html#%E8%A7%A6%E5%8F%91%E5%AF%B9%E8%B1%A1

**Comment by hawind** [comment]
下拉菜单右键被禁用了，找代码也没有找到相关的定义

**Comment by Flsion** [comment]
> 下拉菜单右键被禁用了，找代码也没有找到相关的定义

这个是指哪里的，是下拉菜单选项不能右键吗？

**Comment by hawind** [comment]
> > 下拉菜单右键被禁用了，找代码也没有找到相关的定义
> 
> 这个是指哪里的，是下拉菜单选项不能右键吗？

对，比如Mneu组件有submenu的时候
Dropdown按钮，都不能点右键，不太明白为什么要禁用这个
