### ISSUE TITLE
npm run init 失败: no such file 'packages\web-vue\components\icon\@types\icon'

### ISSUE THREAD

**Issue by 0604hx** [arco-design/arco-design-vue#493]
已按照文档完成 lerna 、yarn 的全局按照，`yarn install` 执行成功

执行 `npm run init` 出现以下错误：

```
[Error: ENOENT: no such file or directory, stat 'E:\workspace\github\arco-design-vue\packages\web-vue\components\icon\@types\icon'] {  
  errno: -4058,                                                                                                                        
  code: 'ENOENT',                                                                                                                      
  syscall: 'stat',                                                                                                                     
  path: 'E:\\workspace\\github\\arco-design-vue\\packages\\web-vue\\components\\icon\\@types\\icon'                                    
}
lerna ERR! yarn run init exited 1 in '@arco-design/web-vue'                                                 
```

**环境如下：**

条目|内容
-|-
操作系统| Windows 10 家庭中文版 21H1
node|16.13.0
npm|8.3.0
yarn|3.0.2
lerna|4.0.0
vue|@vue/cli 5.0.0-rc.1

**操作步骤**

1. `yarn install`
![image](https://user-images.githubusercontent.com/3523216/148022094-b9935c18-5e22-467b-8782-b074fa65f5f9.png)

执行期间未见报错，结果显示：

```
➤ YN0000: Done with warnings in 1m 54s
```

2. `npm run init`

报错信息如下：
![image](https://user-images.githubusercontent.com/3523216/148022747-4411a94c-e4be-4d2c-b6d6-c5c38529165f.png)

![image](https://user-images.githubusercontent.com/3523216/148022782-c6ca4225-caeb-4c43-90cf-f13e927f7ba1.png)

**Comment by Flsion** [comment]
@0604hx 请提供下详细的复现步骤和环境，`npm run init` 错误可能是包安装有问题导致的

**Comment by 0604hx** [comment]
> @0604hx 请提供下详细的复现步骤和环境，`npm run init` 错误可能是包安装有问题导致的

已补充相应的信息
