### ISSUE TITLE
button新增自定义颜色功能

### ISSUE THREAD

**Issue by puppetsheep** [arco-design/arco-design-vue#496]
## 基本信息
- Package Name And Version: 2.13.0
- System: Windows10
- Browser: Microsoft Edge
## What are the similar cases of this feature
[Naive UI](https://www.naiveui.com/zh-CN/os-theme/components/button)
[elementPlus](https://element-plus.org/zh-CN/component/button.html)
## What problem does this feature solve?
新增color自定义

**Comment by Flsion** [comment]
OK，这个功能我们讨论下

**Comment by flsion** [comment]
@puppetsheep 自定义颜色建议通过风格配置平台实现 https://arco.design/themes
