### ISSUE TITLE
unplugin-vue-components 按需加载除了spin外，其他的自定义颜色失效

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#497]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue 2.13.0
- **System:** Mac
- **Browser:** Chrome
- **Reproduction Link:** https://arco.design/vue/docs/start

## What is expected?
-

## Steps to reproduce
Vite ts
使用 unplugin-vue-components按需加载
引入了@arco-design/web-vue/es/index.less
自定义主题颜色，只有spin组件有效果，menu、button、input等都是蓝色的，不起效

**Comment by Flsion** [comment]
@CarmenHYC 目前主题包还不能和按需加载同时使用，这个要等Vue的主题包功能全部完成后会支持下

**Comment by suKarXiao** [comment]
遇到同样的问题，请问vue主题包功能何时推出，因为最近一个项目需要定制UI ,如果主题包推出时间超出开发周期就可能需要选用其他库了 @Flsion

**Comment by yinkaihui** [comment]
下周

**Comment by fairySusan** [comment]
请问，现在支持了吗？
