### ISSUE TITLE
分页组件(pagination)切换页面显示条数时，不应返回第一页

### ISSUE THREAD

**Issue by puppetsheep** [arco-design/arco-design-vue#498]
## 基本信息
- Package Name And Version: 2.13.0
- System: Windows10
- Browser: Microsoft Edge
## What are the similar cases of this feature
[antd](https://next.antdv.com/components/pagination)
[Tdesign](https://tdesign.tencent.com/vue-next/components/pagination)
## What problem does this feature solve?
可以参考以上，实现如Tdesign或Antd相似的功能

**Comment by Flsion** [comment]
OK，我们考察下
