### ISSUE TITLE
表格自定义渲染时允许进行二次封装

### ISSUE THREAD

**Issue by chenkby** [arco-design/arco-design-vue#499]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
elementUI是支持的，它的table没有限制子组件名称必须是TableColumn。

## What problem does this feature solve?
比如我有一列是个switch，切换时我需要与服务器通讯。这是一个相对复杂点的流程。同时，这种列我可能在很多地方都用得到。这个时候如果能在a-table-column的基础上进行封装，会更利于业务开发。这只是其中一个功能，可能还会有许多其他类似的列，操作列、用户信息列等等。

代码如：
```
<a-table ...>
    <template #columns> <switch-column data-index="status" title="状态"></switch-column> </template>
</a-table>

switch-column:
<a-table-column data-index="status" title="状态">
    <template #cell="{record}"> <a-switch ...></a-switch> </template>
</a-table-column>
```

**Comment by Flsion** [comment]
table 因为实现方式的不同，这里会需要TableColumn作为直接子组件。这个也可以将 cell 插槽中的内容封装成组件吧，用法应该一样。
