### ISSUE TITLE
ArcoDesign 下 Vue 组件库已经发布🎉，欢迎大家加群讨论~👏🏻

### ISSUE THREAD

**Issue by Flsion** [arco-design/arco-design-vue#5]
### 飞书群：
![lark](https://user-images.githubusercontent.com/29793175/138851971-4236b3ca-3a69-4996-a7ea-adf7efeb06a7.jpeg)

因微信群满无法扫码进入，进微信群的可以加入飞书群，手动拉到微信群。

**欢迎大家关注 10 月 27 号的稀土掘金开发者大会，ArcoDesign 将会在本次大会正式亮相！**

[https://live.juejin.cn/site/4354/xdc2021?utm_source=juejinweb](https://live.juejin.cn/site/4354/xdc2021?utm_source=juejinweb)

**Comment by UILKUNP** [comment]
微信二维码过期了

**Comment by PengJiyuan** [comment]
> 微信二维码过期了

可以加下飞书群，手动拉到微信群里。

**Comment by theseusyang** [comment]
飞书群加不了，微信群过期了，能再发一个吗？

**Comment by PengJiyuan** [comment]
现在群聊超过 200 人了，不能通过二维码进入了，你只能加飞书群然后我们手动加了。。或者你进 4 群，然后我把你拉 1 群。

![middle_img_v2_d6c8adee-66f8-479a-b173-5ca6602cae2g](https://user-images.githubusercontent.com/19399269/143521516-3b2b6ef9-b165-4565-87df-a268c56df3f7.jpg)

**Comment by Flsion** [comment]
> 飞书群加不了，微信群过期了，能再发一个吗？

更新了一下飞书群二维码

**Comment by Web-Kevin** [comment]
@Flsion 飞书用的很少，能不能给我拉到微信群啊
![mmqrcode1647571041550](https://user-images.githubusercontent.com/5680712/158927451-86cc3515-0532-4a76-8a6b-cfcf8d669df9.png)
