### ISSUE TITLE
Image组件可否加入缩略图地址，用于非点开状态时加载显示

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#505]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
---

## What problem does this feature solve?
现在组件的展示跟预览都用的同一个src，如果组件用于列表显示并且原图比较大的话会消耗很多流量，建议默认展示可以传一个缩略图地址，点击放大时再加载原图地址

**Comment by kirazxyun** [comment]
@CarmenHYC 组件支持 preview 的所有 props，可以设置一下 previewProps.src 来指定预览图片地址

**Comment by CarmenHYC** [comment]
> @CarmenHYC 组件支持 preview 的所有 props，可以设置一下 previewProps.src 来指定预览图片地址

单独使用 a-image 设置 previewProps.src 是好使的，但包裹在 a-image-preview-group 就不好使了，换成配置在 a-image-preview-group 的srcList里，预览图片打不开，一直在loading

**Comment by kirazxyun** [comment]
> > @CarmenHYC 组件支持 preview 的所有 props，可以设置一下 previewProps.src 来指定预览图片地址
> 
> 单独使用 a-image 设置 previewProps.src 是好使的，但包裹在 a-image-preview-group 就不好使了，换成配置在 a-image-preview-group 的srcList里，预览图片打不开，一直在loading
给个 demo 看一下问题

**Comment by CarmenHYC** [comment]
> 



> > > @CarmenHYC 组件支持 preview 的所有 props，可以设置一下 previewProps.src 来指定预览图片地址
> > 
> > 
> > 单独使用 a-image 设置 previewProps.src 是好使的，但包裹在 a-image-preview-group 就不好使了，换成配置在 a-image-preview-group 的srcList里，预览图片打不开，一直在loading
> 
> 我这边修改一下，
> 
> 1. 收集图片的时候优先获取 previewProps.src
> 2. 第二个问题 src-list 一直 loading 的情况我没复现，你这边可以提供一下 demo 一起看看什么问题

```
<a-image-preview-group>
      <div v-for="src in images">
          <a-image :src="src + '-thumb'" :preview-props="{ src: src }" />
      </div>
  </a-image-preview-group>
```

上边代码里，images这个变量是图片上传完成后push进去地址的数组，配置preview-props的src不起作用，点开后的图片还是-thumb

```
<a-image-preview-group :src-list="images">
      <div v-for="src in images">
          <a-image :src="src + '-thumb'" />
      </div>
  </a-image-preview-group>
```

我把代码改成这样的话，点开图片不显示，一直是loadingd在转，没有加载图片，也没报错

**Comment by kirazxyun** [comment]
@CarmenHYC  第一个问题已在版本 2.14.0 处理，可以试试看
