### ISSUE TITLE
Select multiple allow-create 可否提供一个创建时的回调处理

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#509]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
-

## What problem does this feature solve?
现在的option创建是直接把输入的字符串当作value选中，而很多时候option与value非同一个，希望能提供一个创建时的回调，把需要创建的字符串生成一个value后再绑定到model-value

**Comment by Flsion** [comment]
@CarmenHYC Get it

**Comment by Flsion** [comment]
@CarmenHYC 发现目前可以用 fallbackOption 属性，这个也会对创建选项生效
