### ISSUE TITLE
希望为 Image 组件添加错误加载时替换 svg 部分的 slot

### ISSUE THREAD

**Issue by ddaylucifer** [arco-design/arco-design-vue#51]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
类似于 element ui 一样的 提供一个 slot 插槽

## What problem does this feature solve?
源码里面有一个 error slot ,但是直接使用 error slot会把整个 image-overlay 内部的内容替换掉，因为准备使用 ui 创建的 Arco 主题包，希望保留Arco 主题包内的样式的情况下 替换 error 时的 svg 图片，保留其他元素，包括 alt 部分

**Comment by kirazxyun** [comment]
收到，可以添加一个 slot 用于替换这个 icon。
