### ISSUE TITLE
Table中input-number双向绑定可能失效

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#525]
table中第一页第一行有一个`<input-number v-model="0" />`，翻页之后x页的第一行也有一个`<input-number v-model="100" />`，此时将100改成0会失效，我猜测是x页的输入框记住了第一页的0，导致再次输入0认为没有变化，所以导致v-model失效。

**Comment by llk2yq** [comment]
[复现链接](https://codepen.io/raymonda/pen/dyVqwEZ?editors=1010)

复现失败，先关闭，后续再看。

**Comment by llk2yq** [comment]
可以复现了

**Comment by Flsion** [comment]
@llk2yq vue中插槽的数据只做展示使用，不支持双向绑定。这里需要用获取到的数据修改原始的值

![image](https://user-images.githubusercontent.com/29793175/154961301-1fbfc82b-3628-4c10-aee3-fa973a4d08e3.png)

**Comment by llk2yq** [comment]
ok
