### ISSUE TITLE
radio 单选框组能再多添加个圆角样式吗？

### ISSUE THREAD

**Issue by zhubenjie** [arco-design/arco-design-vue#527]
类似这样

![](https://user-images.githubusercontent.com/21832438/148633546-bd7ba03d-5b55-4db4-806d-0d9611802243.png)

参考 <https://vue-pro.arco.design/user/setting>

**Comment by Flsion** [comment]
@zhubenjie 收到反馈，我们内部讨论一下~

**Comment by zhubenjie** [comment]
@Flsion  你好，请问讨论通过了吗？ 感觉圆角更适合现代化设计，特别是那些设计站。

**Comment by Flsion** [comment]
@zhubenjie 不好意思，回复晚了。我们讨论了下，这样的建议做成物料或者业务组件吧，可以通过样式定制一下
