### ISSUE TITLE
上传upload 照片墙预览图片点击无效

### ISSUE THREAD

**Issue by wjy18666** [arco-design/arco-design-vue#53]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue: 2.0.3
- **System:** mac os
- **Browser:** chrome 95
- **Reproduction Link:** https://arco.design/vue/component/upload

## What is expected?
点击可以预览大图

## Steps to reproduce
上传图片以及demo中的图片点击预览没有反应，不会像react版本弹窗预览大图

**Comment by Flsion** [comment]
@wjy18666 上传的DEMO目前没有绑定预览功能，这次更新会添加
