### ISSUE TITLE
 `arco-vue-scripts build`命令是否支持像`rollup-plugin-typescript2`一样，打印出 typescript 句法和语义诊断信息？

### ISSUE THREAD

**Issue by ckvv** [arco-design/arco-design-vue#535]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
 `arco-vue-scripts build`命令是否支持像`rollup-plugin-typescript2`一样，打印出 typescript 句法和语义诊断信息？
## What are the similar cases of this feature
无

## What problem does this feature solve?
效果类似https://www.npmjs.com/package/rollup-plugin-typescript2

**Comment by Flsion** [comment]
@ckvv `arco-vue-scripts dtsgen` 命令可以打印 ts 诊断信息，`build` 仅用来构建
