### ISSUE TITLE
数字输入框按钮模式下：input-number前有其他标签 表单校验异常

### ISSUE THREAD

**Issue by MinZ88** [arco-design/arco-design-vue#541]
![image](https://user-images.githubusercontent.com/95918818/148878797-7016ee7a-d5fd-41a8-a156-a9ae32c1f85e.png)
![image](https://user-images.githubusercontent.com/95918818/148878817-d0ecfacb-dcc0-42b4-b6b5-1b66366a3b5f.png)
https://codepen.io/mz88/pen/GRMYMKG?editors=1010

**Comment by Flsion** [comment]
@MinZ88 目前 form-item 会把事件和属性附加到第一子元素上，如果需要这样使用可以封装个子组件。后面有计划用context的方式重构一下，可以解决这种情况

**Comment by Flsion** [comment]
18版本后已经可以在form-item中任意位置放置输入组件了
