### ISSUE TITLE
用于提 issue 的网页中有一个 getPackageVersion API 挂了

### ISSUE THREAD

**Issue by LuckyHookin** [arco-design/arco-design-vue#545]
步骤：
打开地址：https://arco.design/issue-helper?repo=arco-design-vue
填写信息，点击提交。

得到错误如图所示：
![image](https://user-images.githubusercontent.com/45350455/148903897-50b48075-48ed-4495-bed4-e302472f27a4.png)
![image](https://user-images.githubusercontent.com/45350455/148903415-eeae9068-a31f-4a47-93f2-6f3ffc9866de.png)
![image](https://user-images.githubusercontent.com/45350455/148903526-1ef1b7f2-760c-4bc8-8a79-eea4dcde7812.png)

预期：
网页可以读取版本信息，能提 issue。

**Comment by Flsion** [comment]
@LuckyHookin 收到，我们检查一下

**Comment by yuhan0709** [comment]
hello～ 目前已经修复了哈，出现那个问题的原因是接口是内网接口，外网访问会超时～ 现在已经修复了哈
