### ISSUE TITLE
switch开关抖动

### ISSUE THREAD

**Issue by LuckyHookin** [arco-design/arco-design-vue#546]
![image](https://user-images.githubusercontent.com/45350455/148904162-d591b038-b23a-4d9d-b8b2-88c70aed1c7b.png)
地址：https://arco.design/vue/component/switch

当第一次打开时，点击开关会有一个向后退的动作：
![GIF 2022-1-11 15-49-19](https://user-images.githubusercontent.com/45350455/148904333-bd7e56a9-7f04-49d2-8437-8a96e0485346.gif)

但是我切了下屏后（如：回桌面、切换到其他窗口），他又看起来不抖动（向后退）了：
![GIF 2022-1-11 15-49-53](https://user-images.githubusercontent.com/45350455/148904520-944deb33-8f42-4630-bfec-a1e40411df1f.gif)

这是 BUG 吗？

**Comment by Flsion** [comment]
@LuckyHookin check了下，这个是浏览器在计算位置时显示动画的问题，应该是没有上面这种后退动作的。这个问题和使用环境有关，我看看能不能找个方法解决下
