### ISSUE TITLE
Error compiling >2.14.0

### ISSUE THREAD

**Issue by andantei** [arco-design/arco-design-vue#548]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design-vue
- **System:** MacOS 11.1
- **Browser:** Chrome 95
- **Reproduction Link:** https://tinyurl.com/y2pvhonc

## Extra info
"@arco-design/web-vue": "2.13.0" and below do not have the issue

## What is expected?
Should compile successfully.

## Steps to reproduce
* In package.json, use "@arco-design/web-vue": "^2.14.0"
* Run npm install and start dev server(vite here)
* Error occurs when compiling @arco-design/web-vue/es/style/color/colors.less: https://tinyurl.com/y2pvhonc

**Comment by kirazxyun** [comment]
@andantei This problem has been fixed in 2.14.2, please upgrade and try.
