### ISSUE TITLE
在 vue @2.14.2版本中的输入框组件的搜索框带了search-button属性后 placeholder属性失效！

### ISSUE THREAD

**Issue by BiliBili-ayang** [arco-design/arco-design-vue#549]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.14.2
- **系统版本:** windows 11
- **浏览器版本:** Chrome 97.0.4692.71
- **复现地址:** https://arco.design/vue/component/input

## 预期结果
正常显示placeholder！

## 复现步骤
之前在@2.11.0版本使用该组件是正常显示placeholder，今天更新了一下版本，结果就失效了，原本以为是我代码被我不小心改乱了，但是到了官网查看了一下，官网也是同样的问题！

**Comment by Flsion** [comment]
@BiliBili-ayang 收到了，这版本会 fix 下

**Comment by BiliBili-ayang** [comment]
v-model貌似也没用了，代码没动过！

**Comment by BiliBili-ayang** [comment]
@Flsion 大佬，貌似v-model也失效了！

**Comment by Flsion** [comment]
@BiliBili-ayang 升级下 2.14.3 版本试试，修复了下这个问题
