### ISSUE TITLE
vue版可拖动列功能

### ISSUE THREAD

**Issue by xzy-cat** [arco-design/arco-design-vue#553]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
react版已支持, 希望vue版也能支持

## What problem does this feature solve?
实现table列可拖动

**Comment by oaktreecode** [comment]
有计划加入这个功能吗

**Comment by Flsion** [comment]
预计 2.16.0 版本实验性支持
