### ISSUE TITLE
设置固定列后样式错乱

### ISSUE THREAD

**Issue by xzy-cat** [arco-design/arco-design-vue#554]
vue版: table设置固定列为两列时, 表格左右滑动样式错乱

**Comment by Flsion** [comment]
@xzy-cat 麻烦提供一个复现的地址，我简单看了下没有复现 https://codepen.io/flsion-the-scripter/pen/XWeyMwJ

**Comment by xzy-cat** [comment]
@Flsion 复现的地址:  https://codepen.io/sandy556/pen/dyVQEEe
貌似我加了border属性就会出现
另外, 我用Safari打开样式全乱的, 这个浏览器兼容会处理么?

**Comment by xzy-cat** [comment]
> @xzy-cat 麻烦提供一个复现的地址，我简单看了下没有复现 https://codepen.io/flsion-the-scripter/pen/XWeyMwJ
@Flsion 复现的地址: https://codepen.io/sandy556/pen/dyVQEEe
貌似我加了border属性就会出现
另外, 我用Safari打开样式全乱的, 这个浏览器兼容会处理么?

**Comment by Flsion** [comment]
我这里显示是正常的，可以提供下详细的系统和浏览器版本，以及错误的截图吗？

![Kapture 2022-01-13 at 15 57 57](https://user-images.githubusercontent.com/29793175/149289737-8002d944-680e-4b0d-99e9-9daab05d9a98.gif)

**Comment by xzy-cat** [comment]
> 我这里显示是正常的，可以提供下详细的系统和浏览器版本，以及错误的截图吗？
> 
> ![Kapture 2022-01-13 at 15 57 57](https://user-images.githubusercontent.com/29793175/149289737-8002d944-680e-4b0d-99e9-9daab05d9a98.gif)

我又重现了一下, 左侧固定的列全部重叠在一起了, 包括expand和CheckBox
可以看下这个连接: https://codepen.io/sandy556/pen/bGoObgQ
截图如下: 
![image](https://user-images.githubusercontent.com/29306894/149294886-9a88d31c-a306-4f43-b16f-6855b3441269.png)

**Comment by Flsion** [comment]
> > 我这里显示是正常的，可以提供下详细的系统和浏览器版本，以及错误的截图吗？
> > ![Kapture 2022-01-13 at 15 57 57](https://user-images.githubusercontent.com/29793175/149289737-8002d944-680e-4b0d-99e9-9daab05d9a98.gif)
> 
> 我又重现了一下, 左侧固定的列全部重叠在一起了, 包括expand和CheckBox 可以看下这个连接: https://codepen.io/sandy556/pen/bGoObgQ 截图如下: ![image](https://user-images.githubusercontent.com/29306894/149294886-9a88d31c-a306-4f43-b16f-6855b3441269.png)

开启固定列后，需要非固定的列至少有一个不设置 width，文档中有写到。删除一个 width 后还会有问题吗？

![image](https://user-images.githubusercontent.com/29793175/149475787-a726df49-53ea-4cb2-be94-076970b8a413.png)
