### ISSUE TITLE
通过设置:cellStyle="{ minWidth: '300px' }"之后，虽然没有换行，但是相应列没有撑开

### ISSUE THREAD

**Issue by lambert959** [arco-design/arco-design-vue#559]
![image](https://user-images.githubusercontent.com/23068158/149283599-d6d78db6-a880-4d09-92b6-3d9979b7729f.png)

**Comment by lambert959** [comment]
cellstyle方式设置单元格最小宽度明显不会动态撑开列宽度，只能设置颜色等不影响布局的样式
是否考虑增加column样式上，再通过动态计算剩余列的宽度呢

**Comment by flsion** [comment]
@lambert959 table 列的宽度可以在 column 上设置，是通过 col 元素实现的，表格这里没有想到什么好的办法可以实现 min-width

**Comment by iamning1993** [comment]
@lambert959 可以用 bodyCellStyle 这个属性添加min-width就好了。
