### ISSUE TITLE
table设置展开行后, 左右滑动样式有问题

### ISSUE THREAD

**Issue by xzy-cat** [arco-design/arco-design-vue#561]
添加了expandable属性之后, 左右滑动的时候table右边有一块留白,似乎跟scroll属性的x的值有关,  偶现, 就没办法贴链接, 看下能不能查看下原因, 
使用版本: "@arco-design/web-vue": "^2.14.3",
![image](https://user-images.githubusercontent.com/29306894/149295432-6c7c058e-1a9a-47a1-a7d7-686e760abfd9.png)

**Comment by qingtiantongxie** [comment]
我也出现了 调整下x的值弄好了

**Comment by flsion** [comment]
@xzy-cat @qingtiantongxie 你好，这个目前的版本还会复现吗？
