### ISSUE TITLE
组合按钮 <a-button-group> 两处 bug

### ISSUE THREAD

**Issue by LuckyHookin** [arco-design/arco-design-vue#564]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.14.3
- **System:** windows11
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://codepen.io/luckyhookin/pen/vYevEbg?editors=1010

## 描述
具体看图：
![image](https://user-images.githubusercontent.com/45350455/149309416-a78e7c02-b932-45b9-be58-8a9986bdefb6.png)
``` html
    <a-button-group>
      <a-button>Publish</a-button>
      <a-button>
        <template #icon>
          <icon-down />
        </template>
      </a-button>
    </a-button-group>

    <a-button-group>
      <a-button>Publish</a-button>
      <a-button>
        <template #icon>
          <icon-more />
        </template>
      </a-button>
    </a-button-group>

    <a-button-group>
      <a-button type="primary">
        <icon-left />
        Prev
      </a-button>
      <a-button type="primary">
        Next
        <icon-right />
      </a-button>
    </a-button-group>


```
- 问题①：
   位置向上偏移。
- 问题②：
   `prev` 文本不显示。

感谢！

**Comment by Flsion** [comment]
@LuckyHookin 问题1的样式问题会修正下，问题2是由于codepen不支持vue自闭和写法造成的，正常使用不会有问题，这个我们后面会处理下转到codepen的代码
