### ISSUE TITLE
希望提供独立的Scrollbar组件（类似Naive UI)，并且全部组件默认调用该组件

### ISSUE THREAD

**Issue by mollerzhu** [arco-design/arco-design-vue#573]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Naive UI

## What problem does this feature solve?
系统的滚动条组件非常古板和丑陋，希望统一成Arco design pro侧边栏的滚动条样式，独立出来，用户也可以更加方便的控制自定义组件的滚动条样式。请参考Naive UI

**Comment by mollerzhu** [comment]
比如Dropdown组件中‘分组选项’部分，点击后弹出的下拉菜单的滚动条，如果和arco design pro侧边栏的滚动条一致，就好了

**Comment by LuckyHookin** [comment]
之前有提过： #23
