### ISSUE TITLE
Popover组件鼠标点击body隐藏不了

### ISSUE THREAD

**Issue by jhonor777** [arco-design/arco-design-vue#58]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-vue
- **系统版本:** macOS Big Sur
- **浏览器版本:** Chrome 95.0.4638.54
- **复现地址:** https://codepen.io/pen/?&editors=001

## 预期结果
点击body，隐藏Popover

## 复现步骤
点击Popover触发显示，然后点击body，无法消失，在body宽度和高度比较小的情况可以复现
react版本没有此问题，另外select，treeselect组件也会存在此问题，点击出现下拉框，鼠标点击body，也有无法消失的情况

**Comment by Flsion** [comment]
@jhonor777 你好，提供的codepen需要保存一下才能分享给其他人。这个可能是因为codepen中的body没有撑满整个容器导致的，react版的codenpen是默认最大撑满的，而vue的body仅包裹了展示部分

**Comment by jhonor777** [comment]
> @jhonor777 你好，提供的codepen需要保存一下才能分享给其他人。这个可能是因为codepen中的body没有撑满整个容器导致的，react版的codenpen是默认最大撑满的，而vue的body仅包裹了展示部分

### vue版本
https://codepen.io/Jhonor/pen/MWvrgGP?editors=001

### react版本
https://codepen.io/Jhonor/pen/PoKEYBm?editors=001

***另外select组件，tree select组件，日期选择器等等，凡是有下拉框的都存在此问题，react的body并没有撑满全屏，附上截图***

![image](https://user-images.githubusercontent.com/31689092/139989474-e8c4fd4d-c1dd-4e21-b70b-2288887fc052.png)

**Comment by Flsion** [comment]
@jhonor777 好的，我看了下react版本将事件移到了document上，vue这里也会修改下
