### ISSUE TITLE
[Feature] 希望 popover 能够提供一个 disabled prop 

### ISSUE THREAD

**Issue by DingRui12138** [arco-design/arco-design-vue#580]
业务场景需要在某些情况通过 `disabled` 下使 `<a-popover :disabled="true"> * </a-popover>` 失效，而不是完全不可控状态

**Comment by Flsion** [comment]
@DingRui12138 这里文档上没有注明，popover 组件有继承 trigger 组件的属性，可以使用它的 disabled 属性。这里后面会在文档上增加下相关内容

**Comment by xiangshu233** [comment]
@flsion 请问为什么我手动控制 `v-model:popup-visible="popupVisible"` 后，使用 disabled 属性 缺没用了呢
```html
  <a-popover
    v-model:popup-visible="popupVisible"
    content-class="!p-0"
    trigger="click"
    :disabled="popupDisabled"
  >
```
