### ISSUE TITLE
自定义选择器select后缀图标

### ISSUE THREAD

**Issue by skyLicx** [arco-design/arco-design-vue#582]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
https://element-plus.gitee.io/zh-CN/component/select.html#select-%E5%B1%9E%E6%80%A7  （suffix-icon	自定义后缀图标组件）

## 预期解决问题
选择器select 希望可以添加一个自定义后缀图标的Slots

**Comment by Flsion** [comment]
@skyLicx 好的，下个版本会带上这个
