### ISSUE TITLE
Split组件的min无法使用px

### ISSUE THREAD

**Issue by mollerzhu** [arco-design/arco-design-vue#585]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
如何才能给每个panel设置min和max的px参数？

## What problem does this feature solve?
如何才能给每个panel设置min和max的px参数？

**Comment by xuxucode** [comment]
px 单位用字符串：
```js
// script setup
const size = ref("100") // 字符串
```
```vue
<!-- template -->
<a-split
  v-model:size="size"
  min="60"
  max="200"
>
```

**Comment by kirazxyun** [comment]
收到，安排改进
