### ISSUE TITLE
bugs: 模板 issuse 无法提交

### ISSUE THREAD

**Issue by hehehai** [arco-design/arco-design-vue#589]
![image](https://user-images.githubusercontent.com/12692552/149714378-de373a54-7c23-4e23-9fc4-3ab7fd8a41dc.png)
![image](https://user-images.githubusercontent.com/12692552/149714449-7ebc2179-9e50-4a56-980e-8d72aefbb81c.png)
![image](https://user-images.githubusercontent.com/12692552/149714533-b3b9c0cc-15a3-4be2-a2b4-39ee3cddbf68.png)

**Comment by wehuss** [comment]
挺无语的

**Comment by LuckyHookin** [comment]
![image](https://user-images.githubusercontent.com/45350455/149753252-e2137f2d-da97-4879-9dee-7f80e4ee4d82.png)
现在应该恢复了。
