### ISSUE TITLE
tree和tree select组件没有撑满宽度鼠标只能点击文字选中

### ISSUE THREAD

**Issue by jhonor777** [arco-design/arco-design-vue#59]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-vue
- **系统版本:** macOS Big Sur
- **浏览器版本:** Chrome 95.0.4638.54
- **复现地址:** https://arco.design/vue/component/tree-select

## 预期结果
节点撑满宽度，鼠标经过某个节点那一行即可选中

## 复现步骤
鼠标经过tree组件节点，或点击tree select组件下拉框出现后，鼠标经过节点，只能点击文字，没有撑满整行宽度，react版本没有此问题

**Comment by jhonor777** [comment]
图片补充
vue版本和react版本对照
![image](https://user-images.githubusercontent.com/31689092/140015504-12271321-9140-49fa-9f5a-978f5392bf96.png)

![image](https://user-images.githubusercontent.com/31689092/140015541-54621fd0-2b5b-4d72-9b90-fb23ec267103.png)

**Comment by kirazxyun** [comment]
收到，tree 有一个 block-node 的属性，这个属性为 true 的时候，节点就会是占满一行的。我们可以在 treeSelect 中将这个属性默认设置为 true 来达到你想要的效果。请关注一下 issue 状态。
