### ISSUE TITLE
table组件y轴滚动prop，百分比设置无法穿透外层组件height

### ISSUE THREAD

**Issue by puppetsheep** [arco-design/arco-design-vue#590]
## 基本信息
Arco-design-vue: 2.15.1
## 期望解决
能支持填充外部整体空间(主要是让这一块只有table，分页等于是固定在下边，方便翻页)

**Comment by Flsion** [comment]
@puppetsheep 这个会破坏table组件的基本功能。这样场景下可以把table和pagination拆开，组合使用下
