### ISSUE TITLE
级联选择 Cascader 缺少自定义字段，但官方只能是label、value

### ISSUE THREAD

**Issue by EmptyG2018** [arco-design/arco-design-vue#594]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://ant.design/components/cascader-cn/#API

## What problem does this feature solve?
自定义更加灵活

**Comment by Flsion** [comment]
@EmptyG2018 是指自定义选项和选择框内容吗？

**Comment by EmptyG2018** [comment]
> @EmptyG2018是指自定义选项和选择框内容吗？

自定义 options 中 label value children 的字段

**Comment by EmptyG2018** [comment]
自定义 options 中 label value children 的字段

**Comment by EmptyG2018** [comment]
> @EmptyG2018 是指自定义选项和选择框内容吗？

自定义 options 中 label value children 的字段
