### ISSUE TITLE
是否支持nuxt

### ISSUE THREAD

**Issue by skyblued** [arco-design/arco-design-vue#595]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
ssr

## What problem does this feature solve?
服务端渲染

**Comment by sewalsh** [comment]
See #24

**Comment by Flsion** [comment]
SSR support is being tested and expected to be released in the near future

**Comment by sewalsh** [comment]
> SSR support is being tested and expected to be released in the near future

Thank you! Appreciate all the hard work in making it work with Nuxt.

**Comment by fangzicheng** [comment]
ssr 渲染年后能搞定吗？我现在天天顶着组件未定义的报错写页面，好难受。

**Comment by Flsion** [comment]
> ssr 渲染年后能搞定吗？我现在天天顶着组件未定义的报错写页面，好难受。

已经在进行 SSR 的支持了，预计会在年后的一两个版本推出
