### ISSUE TITLE
日期选择器点击后面清除图标时会再次展开面板

### ISSUE THREAD

**Issue by zengjinwork** [arco-design/arco-design-vue#596]
日期选择器点击后面清除小图标, 只需清除输入框内容, 但现在又同时展开了面板, 这里应该加个禁止冒泡.
react版正常.
(vue版真的太粗糙了, 各种细节问题)

**Comment by kirazxyun** [comment]
收到，本期安排修改。请问能列举一下使用问题吗，我们都会安排优化。
