### ISSUE TITLE
message is missing the loading normal method than the react version of the component

### ISSUE THREAD

**Issue by djkloop** [arco-design/arco-design-vue#60]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
message is missing the loading normal method than the react version of the component
## What are the similar cases of this feature
official website

## What problem does this feature solve?
hope to maintain consistent api

**Comment by Flsion** [comment]
@djkloop will add this feature on 2.1.0
