### ISSUE TITLE
函数调用modal，按回车会无限新增modal

### ISSUE THREAD

**Issue by ShnHz** [arco-design/arco-design-vue#603]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.15.1
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://arco.design/vue/component/modal

## What is expected?
单击“回车键”后关闭modal

## Steps to reproduce
this.$modal.info({         title: 'Info Title',         content: 'This is an info message'       });
单击“回车键”

**Comment by ShnHz** [comment]
codepen:https://codepen.io/pen/?&editors=001

**Comment by flsion** [comment]
Add FocusLock Compoent
