### ISSUE TITLE
Button组件设置里href和宽度后，文本不居中显示了

### ISSUE THREAD

**Issue by shixinxin1111** [arco-design/arco-design-vue#611]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.15.1
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://codepen.io/shixinxin1111/pen/vYewaop?editors=1000

## What is expected?
Button组件设置了href属性和宽度后，文本依旧居中显示

**Comment by Flsion** [comment]
@shixinxin1111 收到👌🏻
