### ISSUE TITLE
Modal组件能否增加一个参数用来指定title的位置

### ISSUE THREAD

**Issue by wehuss** [arco-design/arco-design-vue#614]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
组件现在的居中title让我感觉怪怪的，希望可以增加一个参数用来指定它的位置

## What are the similar cases of this feature
 无

## What problem does this feature solve?
让用户能自己指定title的位置 ：left | center

![image](https://user-images.githubusercontent.com/48681136/150280332-ad222061-a2c7-4b6f-8577-b45c93585953.png)

![image](https://user-images.githubusercontent.com/48681136/150280358-2be3c68f-76d8-419c-892a-05b3181602e0.png)

**Comment by Flsion** [comment]
@wehuss 感觉这个比较实用，下个版本添加一下
