### ISSUE TITLE
[Feature Request] 级联选择性能问题

### ISSUE THREAD

**Issue by DingRui12138** [arco-design/arco-design-vue#615]
当级联选择的选项较多且开启多选时，下拉内容渲染后，失去焦点后会被移除而不是隐藏，当再次打开的下拉内容的时候，需要重新渲染，性能较慢。

预期：
下拉菜单关闭时通过 `disable: none;` 隐藏，再次打开下拉菜单时直接展示，而不是重新渲染

**Comment by kirazxyun** [comment]
可以通过设置 `triggerProps.unmountOnClose = false` 来关闭下拉菜单的卸载

**Comment by DingRui12138** [comment]
@kirazxyun 我偷懒了，没看`cascader.d.ts`，不过文档上有点太简单了哈哈哈
