### ISSUE TITLE
<a-typography-paragraph copyable>

### ISSUE THREAD

**Issue by lambert959** [arco-design/arco-design-vue#618]
问题：快速点击复制按钮出现多个复制成功状态
期望：提供成功状态消失自定义延迟设置，按钮状态设置
![image](https://user-images.githubusercontent.com/23068158/150304039-07f34923-0f11-4f8e-bc3a-6af2111f2d3c.png)

**Comment by kirazxyun** [comment]
收到，最近的版本会安排
