### ISSUE TITLE
调用Message.loading ，控制台会打印warn

### ISSUE THREAD

**Issue by zhubenjie** [arco-design/arco-design-vue#620]
![1](https://user-images.githubusercontent.com/21832438/150308263-20432316-affd-46d5-b2d2-c34c0279cdb6.jpg)
![2](https://user-images.githubusercontent.com/21832438/150308301-44044f64-4026-48bd-a135-3f800837c2c7.jpg)

**Comment by Flsion** [comment]
@zhubenjie 收到，这次会fix下
