### ISSUE TITLE
下拉选择器option宽度会继承选择控件的宽度，如果选择控件宽度过短，option会显示不全

### ISSUE THREAD

**Issue by EmptyG2018** [arco-design/arco-design-vue#621]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.15.1
- **System:** win10
- **Browser:** chrome97.0.4692.71
- **Reproduction Link:** https://arco.design/vue/component/select

## What is expected?
下拉选择option宽度需要设置最小宽度

**Comment by xuexirong** [comment]
@flsion 示例不明显，找了很久都没注意到，最后还是来这看issue才找到，建议把点击区域再缩小，弹出的列表再加宽
