### ISSUE TITLE
table component perform not expected when scroll prop only set x 

### ISSUE THREAD

**Issue by jdgjxxchy** [arco-design/arco-design-vue#64]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue: 2.0.2
- **System:** Mac Os
- **Browser:** chrome 95.0.4638.69
- **Reproduction Link:** https://arco.design/vue/component/table

## What is expected?
```<a-table :columns="columns" :data="tableData" :scroll="{x: 2500}" /> ```effect and only scroll in x axis

## Steps to reproduce
```<a-table :columns="columns" :data="tableData" :scroll="{x: 2500}" />``` not effect
```<a-table :columns="columns" :data="tableData" :scroll="{x: 2500, y: 400}" />``` effect

**Comment by jdgjxxchy** [comment]
补充，当传入scroll={x: 2500, y: -1}或者scroll={x: 2500, y: []}等奇怪的y值时，可以歪打正着的达到目的。

**Comment by Flsion** [comment]
@jdgjxxchy 恩，现在没有传y的话，x的值没有加上，2.1.0会处理下
