### ISSUE TITLE
图片预览的一些BUG和需求（可能是BUG？）

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#644]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
![image](https://user-images.githubusercontent.com/93666053/150745501-24e5ef9c-24fa-4708-b0a6-b69a407c8d2d.png)

如图
1. 提示语层级有问题吧，有时候提示语出不来
2. 左转右转功能翻了，点击右转图标，实际图片向左转
3. 【fr】希望加个下载按钮，很多用户真的连右键保存图片的操作都不会的，就得傻瓜式把功能显示出来，目前生产的项目就遇到好多个这种客户了

**Comment by kirazxyun** [comment]
收到，操作按钮将会支持自定义。
