### ISSUE TITLE
触发器 Trigger设置popup-visible (v-model)之后click-outside-to-close失效

### ISSUE THREAD

**Issue by Likunone** [arco-design/arco-design-vue#646]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://codepen.io/likunone/pen/WNXNvjq

## What is expected?
触发器 Trigger设置popup-visible (v-model)之后 click-outside-to-close可正常关闭弹出框

**Comment by gauseq** [comment]
这个情况现在还是存在,请问是如何解决的呢

**Comment by zjhzQiuShuai1997** [comment]
请问是解决了么，我现在也遇到类似的问题了
