### ISSUE TITLE
select选择器下拉框不跟随

### ISSUE THREAD

**Issue by skyLicx** [arco-design/arco-design-vue#648]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://codepen.io/skylicx/pen/wvPvOqK

## What is expected?
鼠标滚轮滑动时 下拉框跟随选择器

## Steps to reproduce
打开下拉框 用鼠标滚轮滑动滚动条 下拉框不跟随选择器

**Comment by Flsion** [comment]
@skyLicx 可以开启 trigger 的 update-at-scroll 属性来监听容器的滚动。这个会对性能有影响，默认没有开启

![image](https://user-images.githubusercontent.com/29793175/151522657-cfc442d2-c12c-4caa-a83c-f72a9f532bf0.png)
