### ISSUE TITLE
table 可以编辑和新增数据的功能

### ISSUE THREAD

**Issue by oaktreecode** [arco-design/arco-design-vue#653]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
比如其他框架的有类似的功能。

## What problem does this feature solve?
table 可以编辑和新增数据的功能，感谢你们的付出，是否有计划加入这些功能？

**Comment by Flsion** [comment]
@oaktreecode 你好~ 这个功能会更偏业务一些，用户的需求也可能不大相同，不是太适合直接内置。一般可以通过封装 table 实现这个功能，针对这个场景我会补充几个 DEMO，可以方便大家直接使用下

**Comment by oaktreecode** [comment]
这个demo，在哪里可以看到？我看2.17.0 已经发布，官方文档没找到，谢谢

**Comment by Flsion** [comment]
不好意思，这个 DEMO 给忘记了，这次的版本会加上

**Comment by flsion** [comment]
已经增加使用示例 https://arco.design/vue/component/table#editable
