### ISSUE TITLE
级联选择框

### ISSUE THREAD

**Issue by Miss-huanlove** [arco-design/arco-design-vue#654]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://arco.design/vue/component/cascader

## What is expected?
级联选择框选中的时候 v-model以数组形式保存，包含其父级的value值

**Comment by Miss-huanlove** [comment]
希望尽快修复

**Comment by Flsion** [comment]
@Miss-huanlove 是指路径模式吗 https://arco.design/vue/component/cascader#path
