### ISSUE TITLE
Multiple calls to Message at the same time result an error

### ISSUE THREAD

**Issue by jinxinkai** [arco-design/arco-design-vue#657]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
![image](https://user-images.githubusercontent.com/21239915/151659129-5bde2691-2331-412e-b76f-64a483dc4af2.png)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://arco.design/vue/component/message

## What is expected?
no error

## Steps to reproduce
```
<script lang="ts" setup>
import { Message } from '@arco-design/web-vue'
Message.error('添加失败')
Message.error('添加失败')
</script>
```

**Comment by Flsion** [comment]
@jinxinkai This problem will appear on the first simultaneous call, creating multiple instances, this version will fix it
