### ISSUE TITLE
zIndex都是1，导致有冻结列的表格在滑动的时候会被image等组件覆盖

### ISSUE THREAD

**Issue by jdgjxxchy** [arco-design/arco-design-vue#66]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue: 2.0.2
- **System:** MacOs
- **Browser:** chrome
- **Reproduction Link:** https://arco.design/vue/component/table

## What is expected?
当image滑到冻结列后时应该被冻结列盖住

## Steps to reproduce
在table中设置冻结列和scroll，并在非冻结列中放上image组件，在滑动的时候，image没有被冻结的列盖住。
![image](https://user-images.githubusercontent.com/44478385/140065864-8760612d-2842-448b-be00-ee28ebe32399.png)

**Comment by Flsion** [comment]
@jdgjxxchy 收到，我们讨论一下全局z-index的使用情况

**Comment by kirazxyun** [comment]
@jdgjxxchy 你好，我在我们的 demo 上没有复现这个问题，请问是给 image 加了 z-index 吗 ，请参考这个 demo https://codepen.io/zhangxiaoyun_bj/pen/abyQbaw?editors=1010
