### ISSUE TITLE
table组件外面包一层使用后使用v-bind="$attrs"继承属性loading为加载状态，表格数据为空

### ISSUE THREAD

**Issue by topoge** [arco-design/arco-design-vue#665]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.16.2
- **系统版本:** win10
- **浏览器版本:** chrome98.0.4758.82
- **复现地址:** https://codepen.io/pen/?&editors=001&prefill_data_id=eaf198af-2c7f-4f48-a608-5da14b96556f

## 额外补充
table组件外面包一层使用后使用v-bind="$attrs"继承属性loading为加载状态，表格数据为空
无论是否设置数据，都为只有一个加载图标，不会有个半透明遮罩层以及数据列表
虽然可以在自定义组件中定义一个loading属性解决

## 预期结果
和直接使用loading属性表现一直

## 复现步骤
```
<a-table v-bind="$attrs"></a-table>
<table :loading="true"></table>
```

**Comment by Flsion** [comment]
@topoge 这个复现地址是空的，可以再提供一个吗
