### ISSUE TITLE
Cascader的搜索

### ISSUE THREAD

**Issue by thales-jiang** [arco-design/arco-design-vue#668]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome98.0.4758.80
- **Reproduction Link:** https://arco.design/vue/component/cascader

## What is expected?
比如现在是二级菜单，北京/海淀
搜索海淀时候，只出现海淀，希望可以出现完整的路径——北京/海淀

## Steps to reproduce
  <a-cascader :options="options" allow-search/>

**Comment by Flsion** [comment]
@thales-jiang OK，会添加一个选项，来控制显示全路径还是单节点信息
