### ISSUE TITLE
级联选择 Cascader 严格选择模式设置disabled为true之后 点击最前面的圆点依然可以选中

### ISSUE THREAD

**Issue by Likunone** [arco-design/arco-design-vue#669]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.16.2
- **Browser:** chrome98.0.4758.80
- **Reproduction Link:** https://codepen.io/likunone/pen/rNYmxBJ?editors=001

## What is expected?
级联选择 Cascader 严格选择模式设置disabled为true之后 点击最前面的圆点依然不能选中

**Comment by Likunone** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/15193414/153321056-283a0c2b-a06a-428c-b4b0-2fa4eb4cd2d9.png">

**Comment by Flsion** [comment]
@Likunone 排查了下是选择器的问题，这个版本会修复下
