### ISSUE TITLE
如何全局配置组件的尺寸？

### ISSUE THREAD

**Issue by zhangzhenfei** [arco-design/arco-design-vue#680]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
如何全局配置组件的尺寸？

## 预期解决问题
如何全局配置组件的尺寸？

**Comment by Flsion** [comment]
@zhangzhenfei 可以使用<config-provider>组件 https://arco.design/vue/component/config-provider
