### ISSUE TITLE
Descriptions能否增加items用于自定义单元格显示

### ISSUE THREAD

**Issue by CarmenHYC** [arco-design/arco-design-vue#681]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
antd

## What problem does this feature solve?
现在的调用方式是传递data列表的数据，而很多时候详情页的信息展示是多元的，希望能增加item项，用于自定义每个单元展示的数据

**Comment by Flsion** [comment]
@CarmenHYC 嗯，我们也发现了这个问题，对于有些场景的使用item组件会更好，这个已经排进计划了，会加一下
