### ISSUE TITLE
请问默认模板咋都是单任务操作模式

### ISSUE THREAD

**Issue by dywxdz** [arco-design/arco-design-vue#689]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
ruoyi.vip

## What problem does this feature solve?
客户需要多任务操作方式咋办

**Comment by Flsion** [comment]
@dywxdz vue pro 的问题可以到对应的仓库提问下 https://github.com/arco-design/arco-design-pro-vue/issues
