### ISSUE TITLE
Tree组件支持icon插槽，也就是节点名左边的图标插槽，同时默认的叶子节点图标可以按需

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#696]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
有些树节点需要不同的图标

## What problem does this feature solve?
能够让用户自定义icon

**Comment by kirazxyun** [comment]
图标插槽会在最近的版本安排上，这个“默认的叶子节点图标可以按需”，是什么意思呢?

**Comment by lin-97** [comment]
showLine 模式下，叶子节点会有个默认的图标，到时候加icon插槽会两个存在吗？
还有就是showLine模式也能在非叶子节点加icon插槽吗？
