### ISSUE TITLE
input-number设置双向绑定输入数字会报错误信息

### ISSUE THREAD

**Issue by EmptyG2018** [arco-design/arco-design-vue#699]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **System:** win10
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://codesandbox.io/s/zen-goldstine-yfyrd0?file=/src/App.vue

## What is expected?
输入数字不报错误信息

## Steps to reproduce
设置双向绑定后输入数字

**Comment by Flsion** [comment]
@EmptyG2018 使用  v-model:modelValue="value" 或者 v-model="value" 都可以
