### ISSUE TITLE
The page gets stuck when uploading video files 【视频文件上传，页面失去响应，卡死】

### ISSUE THREAD

**Issue by raythunder** [arco-design/arco-design-vue#702]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://arco.design/vue/component/upload

## Extra info
There is no problem with the pictures. Only the video uploads when
图片没有问题。只有视频上传时

## What is expected?
No page lag, other operations can be performed

页面无卡顿，可进行其他操作

## Steps to reproduce
Uploading a video file of about 20M, the whole page gets stuck and unresponsive. I've tested uploads from other component libraries and there is no jamming. Is it a bug within the component? When I use it in my own project, it will lose response for a while, but it will be fine later. The example on the official website is completely dead.

上传一个20M左右的视频文件，整个页面会卡死无响应。测试了其他组件库的上传，没有出现卡死现象。是否是组件内的bug? 在自己项目中使用时，虽然会失去响应一段时候，但是等会会正常。官网的示例，就完全死掉了。

**Comment by Flsion** [comment]
@raythunder I found that this is a problem caused by the automatic generation of preview images. The next version will fix it and only generate images for the type of images.

**Comment by raythunder** [comment]
@Flsion ok.

**Comment by Kefeng2017** [comment]
> @raythunder I found that this is a problem caused by the automatic generation of preview images. The next version will fix it and only generate images for the type of images.

上传文件的时候都会执行getDataURLFromFile这个方法将文件转成base64格式的吗，对于一些大文件来说可能比较耗时，使页面失去响应，但是我看文档里面不会出现这种情况，是需要配置吗
