### ISSUE TITLE
列表 List virtual时底部会有30多像素被隐藏

### ISSUE THREAD

**Issue by liupan1890** [arco-design/arco-design-vue#703]
### BUG:底部会有30多像素被隐藏
问题已经搞明白：VirtualList使用clientHeight计算行高，当行元素有border时会导致VirtualList计算错误引发这个BUG

解决方案一：
``````
<a-list
      :virtualListProps="{
        height: winStore.GetListHeightNumber,
        estimatedItemHeight: 106  //增加这一行，强制行高，为正确的数值
      }"
    ></a-list>
``````

解决方案二：
``````
<a-list
      :virtualListProps="{
        height: winStore.GetListHeightNumber,
      }">

 <template #item="{ item, index }">
        <div :key="item.user_id">  //行的第一级子元素，不能有border
          <div :class='following' >  //给行的第二级子元素设置border
          </div>
        </div>
 </template>

</a-list>
``````
## What is expected?
正常显示

![无标题 - 副本](https://user-images.githubusercontent.com/67817756/154682384-da6d820f-2753-4cfc-8305-bb4bf3e2e430.png)

--

如图，
div.arco-list-content 高度为496px
列表项渲染高度530px，因为是通过 transform: translateY(1144px); 来移位显示的，导致无法继续向下滚动并且有34像素被遮挡

list-item高度106px,显示5行，总高度530px

``````
原始代码：
<a-list
      ref="viewlist"
      :bordered="false"
      :split="false"
      :max-height="496"
      :virtualListProps="{
        height: 496,
        isStaticItemHeight: true
      }"
      style="width: 100%"
      :data="dingyueStore.FollowingList"
      tabindex="-1"
    >
      <template #item="{ item, index }">
        <div
          :class="'following'"
          :key="item.user_id"
        >
          <a-avatar :size="80" shape="square">
            <img alt="avatar" :src="item.avatar" />
          </a-avatar>
          <div class="followingmessages">
            <div class="followingname" >{{ item.nick_name }} <a-badge v-if="item.has_unread_message" status="processing"></a-badge></div>
            <div class="followingmessage" v-for="msg in item.latest_messages" >{{ msg.createdstr }} : {{ msg.display_action }}</div>
          </div>
        </div>
      </template>
    </a-list>
``````
可以简化为
``````
<a-list
      ref="viewlist"
      :bordered="false"
      :split="false"
      :max-height="496"
      :virtualListProps="{
        height: 496,
        isStaticItemHeight: true
      }"
      style="width: 100%"
      :data="[{key:'1'},{key:'2'},{key:'3'},{key:'4'},{key:'5'},{key:'6'},{key:'7'}]"
      tabindex="-1"
    >
      <template #item="{ item, index }">
        <div style="height:106px">item row</div>
      </template>
    </a-list>
``````

**Comment by liupan1890** [comment]
data 必须有属性 “key”
不然会导致刷新错误，稍后给你截个图你就能看到了

**Comment by liupan1890** [comment]
![errkey](https://user-images.githubusercontent.com/67817756/154807116-defc4c2f-ce04-48aa-abbe-d1b88dd737fc.gif)

如图，当:data绑定的数组里的object 不包含key键时 ({key:'id',name:'name'...})  
滚动后再滚回来，会导致显示错误，不能正确的显示，dom混乱了

debug一下，看到a-list的virtualListRef里面写死了itemKey: "key" ，:data绑定的数组也会自动增加key这个属性（key:undefined）

![errkey001](https://user-images.githubusercontent.com/67817756/154807207-fd9d7cd1-5bc5-43c0-b262-2bae237092e8.png)


只有提供key时，才能正确的滚动显示,debug下virtualListRef也正常了，visibleData也正确读取到key了

![errkey002](https://user-images.githubusercontent.com/67817756/154807225-87f63b45-ba52-46c6-8c94-fb8ef7b0c683.png)

**Comment by Flsion** [comment]
> ![errkey](https://user-images.githubusercontent.com/67817756/154807116-defc4c2f-ce04-48aa-abbe-d1b88dd737fc.gif)
> 
> 如图，当:data绑定的数组里的object 不包含key键时 ({key:'id',name:'name'...}) 滚动后再滚回来，会导致显示错误，不能正确的显示，dom混乱了
> 
> debug一下，看到a-list的virtualListRef里面写死了itemKey: "key" ，:data绑定的数组也会自动增加key这个属性（key:undefined）
> 
> ![errkey001](https://user-images.githubusercontent.com/67817756/154807207-fd9d7cd1-5bc5-43c0-b262-2bae237092e8.png)
> 
> 只有提供key时，才能正确的滚动显示,debug下virtualListRef也正常了，visibleData也正确读取到key了
> 
> ![errkey002](https://user-images.githubusercontent.com/67817756/154807225-87f63b45-ba52-46c6-8c94-fb8ef7b0c683.png)

明白这个意思了，这里的 virtual list 应该内部确定下key，或者用户指定下作为key的属性，这个会修复下
