### ISSUE TITLE
列表 List virtual data频繁更新时会显示空白页，必须滚动一下才能正常显示

### ISSUE THREAD

**Issue by liupan1890** [arco-design/arco-design-vue#704]
白屏BUG修复方案：把https://github.com/arco-design\web-vue\es\list\list.js里:217行 currentPageItems.length ? createVNode(VirtualList : renderEmpty(); 换成v-show 就好了，不删除之隐藏切换显示

## What is expected?
绑定data列表刷新后正常显示

![err2](https://user-images.githubusercontent.com/67817756/154804135-f8e89017-48fc-4269-893d-34360edd3931.gif)

如图，正常的绑定data=[....],正常显示。然后通过
``````
datalist = datalist.filter(t => t.name.indexOf(searchkey)>0)
``````
修改searchkey，会刷新绑定的data，

按照此步骤操作：
第1步 .修改searchkey，让filter后datalist=[],就会导致白屏，
第2步 .继续修改searchkey让filter后datalist包含几项内容，
此时只显示滚动条，div.arco-list-content > div 的高度已经正常计算出来了，但里面不包含任何item，所以也不显示（应该显示了）

经测试只要筛选时一直不让datalist为空数组，则不会触发白屏，会正常的显示筛选后的内容

--

出现白屏后，只有通过滚动滚动条才能正确的刷新显示，此时a-list 更新绑定的data,或者a-list.$forceUpdate() 均无法解决白屏

--

![无标题](https://user-images.githubusercontent.com/67817756/154828646-9fb8c0cf-095f-4ad5-95d4-df3dcc9aece2.png)

白屏错误时，如图，data里有数据，visibleData里没有数据（应该有），data里数据继续变更时(变成4条，5条)也不会响应

分析就是a-list认为数据不在显示区域内不需要显示。既绑定的data刷新时，显示区域计算错误

**Comment by liupan1890** [comment]
样例：
``````
const baseList=[{key:'1',name:'新中国'},{key:'1',name:'新生活'},.......共15条]

const showlist=ref([])
const alistref=ref()

function handleSearch(word : string){
showlist= baseList.filter(t => t.name.indexOf(word)>0)
}

<a-input-search @input="handleSearch"  />
<a-list ref="alistref" :data="showlist" ></a-list>
``````

启动后列表正常显示(15行，有滚动条)
第一步：input输入内容=‘新’，列表正常显示 (2行)
第二步：input输入内容=‘新中’，列表正常显示 (1行)
第三步：input输入内容=‘新中错’，列表正常显示 (0行) -- 此时触发显示默认的空提示   “暂无数据”

--

第四步：input输入内容=‘新中’，列表错误显示 (0行)，应该显示1行
第五步：input输入内容=‘新’，列表错误显示 (0行)，应该显示2行
第六步：input输入内容=‘’，列表错误显示 (0行，有滚动条)，应该显示15行

既：触发显示白屏，此时只能通过滚动滚动条，触发刷新，重新恢复正常的显示，
测试重新刷新baseList无效，测试alistref.$forceUpdate()无效
第四步,第五步时因为根本没有滚动条，所以根本无法刷新，无解了

--

我是electron v12.0.9

**Comment by liupan1890** [comment]
另：默认的空提示 “暂无数据” ，暂无数据这几个字应该可以自己设置才对，antdv就可以

**Comment by liupan1890** [comment]
调试跟踪了一下，在virtual-list.vue_vue&type=script&lang.js

``````
watch([itemHeight, visibleCount, scrollTop], () => {
      if (lockScrollRef.value)
        return;
      updateRangeState();
    });
    watch(rangeState, () => {
      nextTick(() => {
        updateScrollOffset();
      });
    });
``````

问题原因是，a-list 在虚拟列表和非虚拟列表之间自由变动，虽然已经设置了:virtualListProps="{threshold: 1}"
a-list 判断想要是虚拟列表时就是虚拟列表，a-list 判断可以不是虚拟列表时（比如数据很少）就自动转换为非虚拟列表

转换为非虚拟列表后，watch([itemHeight, visibleCount, scrollTop], 一直不会被触发，导致页面一直不刷新
当数组增多时，a-list没有正确的转换会虚拟列表，所以watch([itemHeight, visibleCount, scrollTop], 一直不会被触发，导致页面一直不刷新


总之：在上面截图步骤操作后，updateRangeState一直不会触发，页面一直不会刷新，导致显示空白页

接着懒得跟了，看代码发现a-list 和 virtual-list.vue 代码很混乱，很割裂，懒得折腾了，换antdv了

**Comment by liupan1890** [comment]
好吧，我是没想到，问题这么简单就能修正

在@arco-design\web-vue\es\list\list.js
``````
const renderVirtualList = () => {
      const {
        currentPageItems,
        currentPageItemRenderFunc
      } = getListItemRenderMsg(props.data || []);
      return currentPageItems.length ? createVNode(VirtualList, mergeProps({
        "ref": virtualListRef
      }, props.virtualListProps, {
        "class": contentCls.value,
        "data": currentPageItems,
        "onScroll": handleScroll
      }), {
        item: ({
          item,
          index
        }) => currentPageItemRenderFunc(item, index)
      }) : renderEmpty();
    };
``````
这里判断列表为空时，显示"暂无数据"renderEmpty()

此时，会导致createVNode(VirtualList 被删除
进而导致@arco-design\web-vue\es\_components\virtual-list\virtual-list.vue_vue&type=script&lang.js
里面的viewportRef.value变成null

进而导致scrollTop.value = getValidScrollTop(rawScrollTop, scrollHeight - clientHeight);无法访达

进而导致watch([itemHeight, visibleCount, scrollTop], () => 无法触发

最终也就是白屏不刷新

----

修复方案：把list.js里 currentPageItems.length ? createVNode(VirtualList : renderEmpty(); 换成v-show 就好了，不删除之隐藏切换显示

**Comment by kirazxyun** [comment]
你好，十分感谢您的反馈，您的追踪过程为我们排查问题减少了许多弯路，十分感谢。通过您提供的例子和分析过程，我们复现了场景并追踪到了问题代码。此处的问题主要出现在两处：
1. getScrollPercentage 获取滚动比例的时候，容器的 scrollHeight 和 cliendHeight 可能是一样的(没有出现滚动条)，此时因为没有判断出现了除数为 0 的情况，导致了计算出来 startIndex 为 NaN，从而导致了在是否出现滚动条的边界情况下更新失败。
2. 更新 rangeState 所监听的变量缺失，也就是 `watch([itemHeight, visibleCount, scrollTop], () => {})` 没有被触发的问题，此处应该加上对数据源的监听，因为容器基础条件没有变化的情况下，数据更新没有触发 endIndex 的更新而导致更新失败。

这个 bug 将会在最近的版本安排上线修复～

**Comment by Kadima-M** [comment]
这个是已经修复了吗?

**Comment by Kadima-M** [comment]
这个bug是已经修复发布了吗?

**Comment by sq800** [comment]
出现了同样的BUG
"@arco-design/web-vue": "^2.56.1",
"vue": "^3.4.38",

**Comment by AprilTong** [comment]
vue-virtual-scroll-list 版本2.3.5，也遇到了一样的问题👀

**Comment by alvin0804** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GrapevineLin** [comment]
仍然存在 bug@arco-design/web-vue@2.56.3'
