### ISSUE TITLE
是否可以让Modal在点击开始以及结束时都在遮罩层再关闭，现在很容易出现误操作

### ISSUE THREAD

**Issue by jyp0912** [arco-design/arco-design-vue#707]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
在modal中有进度条组件，拖拽后鼠标移到了遮罩层上直接关闭了Modal

## What problem does this feature solve?
改善用户体验

**Comment by Flsion** [comment]
@jyp0912 好的，这里会优化一下
