### ISSUE TITLE
input组件字数统计值不一定正确

### ISSUE THREAD

**Issue by lainbo** [arco-design/arco-design-vue#71]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue: 2.0.3
- **System:** win10
- **Browser:** Chrome 95
- **Reproduction Link:** https://codesandbox.io/s/arcoshu-ru-kuang-wen-zi-tong-ji-zhi-bu-zheng-que-ii8g8?file=/src/App.vue

## Extra info
对文本内容应该做一次判断，使用以下代码得到真正的length
const spRegexp = /[\\uD800-\\uDBFF][\\uDC00-\\uDFFF]/g;

if (str) {
  val = value.replace(spRegexp, '_').length;
}

## What is expected?
罕见字长度也应该是1

## Steps to reproduce
往输入框中输入一些罕见字，如“𠮷”、“💩”，单个文字长度会被识别成2

**Comment by Flsion** [comment]
@lainbo Hi，你好，这是个很好的问题。关于这个问题，我想开放出来一个length的自定义方法更好些，这种字符的判断在不同地区可能会不一样，我不是很确定Unicode正则是否能匹配到全部这样的内容
