### ISSUE TITLE
表格table缺少表格树形边框配置

### ISSUE THREAD

**Issue by zhangzhenfei** [arco-design/arco-design-vue#716]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
表格table缺少表格树形边框配置

## 预期解决问题
表格table缺少表格树形边框配置

**Comment by Flsion** [comment]
@zhangzhenfei 你好，我没有太理解这个配置的意思，目前树形表格也是属于父级的一部分，公用border配置的，这个可以提供一个类似的示例吗

**Comment by zhangzhenfei** [comment]
写了错别字，是表格内部的单元格竖边框，目前就只有横向边框

**Comment by hehehai** [comment]
@zhangzhenfei 

可以设置的
```
<a-table
     :bordered="{ cell: true }"
/>
```
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12692552/158142669-3fb91fdc-af9a-42f8-a023-1eff7255c7dc.png">

**Comment by hehehai** [comment]
@Flsion 是否有必要像 react table 组件一样，设置一个 borderCell 属性？

<img width="993" alt="image" src="https://user-images.githubusercontent.com/12692552/158143190-67f4c368-bc12-4ba7-b0d1-21a9906135c5.png">

**Comment by Flsion** [comment]
> 是表格内部的单元格竖边框，目前就只有横向边框

react 版本是从之前继承的属性，保留了这个。因为功能相同，vue 这里开发时给去掉了
