### ISSUE TITLE
文档功能缺失

### ISSUE THREAD

**Issue by daly-dai** [arco-design/arco-design-vue#718]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
react文档的同样功能就行

## What problem does this feature solve?
react文档还有自己的搜索框  vue没有  每次想找组件都要滚动很久

**Comment by Flsion** [comment]
@daly-dai vue文档的搜索已经在开发中，完成后会开放出来
