### ISSUE TITLE
@arco-design/web-vue/es/icon 的图标库体积挺大的，如何自动按需导入？

### ISSUE THREAD

**Issue by jiengsad** [arco-design/arco-design-vue#721]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
unplugin-icons

## 预期解决问题
希望官网能给做一个图标按需导入的vite插件。

**Comment by Flsion** [comment]
@jiengsad 组件库的 unplugin-vue-components 也可以支持icon的按需加载

![image](https://user-images.githubusercontent.com/29793175/155530103-1279763b-d456-4914-8ed2-6effbec197a0.png)

可以在选项中开启 resolveIcons

**Comment by zhuxiwen** [comment]
左侧菜单的icon有好的按需加载方式吗？
<img width="544" alt="image" src="https://user-images.githubusercontent.com/19161200/165790076-eeb56344-a086-4f3a-8579-f1a7a79a1b33.png">

**Comment by Booshaw** [comment]
> 左侧菜单的icon有好的按需加载方式吗？ <img alt="image" width="544" src="https://user-images.githubusercontent.com/19161200/165790076-eeb56344-a086-4f3a-8579-f1a7a79a1b33.png">

我使用webpack重新搭建, 这里的icon无内容显示

**Comment by xiaopengRUNNING** [comment]
> > 左侧菜单的icon有好的按需加载方式吗？ <img alt="image" width="544" src="https://user-images.githubusercontent.com/19161200/165790076-eeb56344-a086-4f3a-8579-f1a7a79a1b33.png">
> 
> 我使用webpack重新搭建, 这里的icon无内容显示

这个问题解决了吗
