### ISSUE TITLE
源码本地启动问题

### ISSUE THREAD

**Issue by BigFrontEnd-China** [arco-design/arco-design-vue#722]
文档源码跑不起来
![image](https://user-images.githubusercontent.com/19523223/155500007-23c4d991-e04b-4039-bc99-3d2746445981.png)
@arco-design/arco-vue-docs-navbar  这个包一直提示安装失败
![image](https://user-images.githubusercontent.com/19523223/155499471-8b8c83b2-c832-40e3-a22d-b9ef50fc0662.png)

**Comment by Flsion** [comment]
@BigFrontEnd-China 这里需要用yarn安装下，可以查看下 https://github.com/arco-design/arco-design-vue/blob/main/CONTRIBUTING.zh-CN.md
