### ISSUE TITLE
vite 2.18.0-beta.1 打包失败

### ISSUE THREAD

**Issue by liuhauyao** [arco-design/arco-design-vue#725]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.18.0-beta.1
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** www.baidu.com

## What is expected?
> vue-tsc --noEmit && vite build

node_modules/@arco-design/web-vue/es/index.d.ts:1:25 - error TS7016: Could not find a declaration file for module './arco-vue'. 'D:/project/matrees-ts/node_modules/@arco-design/web-vue/es/arco-vue.js' implicitly has an 'any' type.

1 export { default } from './arco-vue';
                          ~~~~~~~~~~~~

node_modules/@arco-design/web-vue/es/index.d.ts:49:53 - error TS7016: Could not find a declaration file for module './select'. 'D:/project/matrees-ts/node_modules/@arco-design/web-vue/es/select/index.js' implicitly has an 'any' type.

49 export { default as Select, Option, Optgroup } from './select';
                                                       ~~~~~~~~~~


Found 2 errors.


<!-- generated by arco-issue. DO NOT REMOVE -->

**Comment by Flsion** [comment]
@liuhauyao 升级新版本试下，处理了下这个问题

**Comment by liuhauyao** [comment]
新版本问题已解决
