### ISSUE TITLE
偶发 滑动输入条 Slider 鼠标拖动 bug

### ISSUE THREAD

**Issue by LuckyHookin** [arco-design/arco-design-vue#73]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** docs website
- **System:** windows 10
- **Browser:** 版本 95.0.4638.54（正式版本） （64 位）
- **Reproduction Link:** https://arco.design/vue/component/slider

## What is expected?
不会出现 禁止 手势；鼠标左键放开后滑块不会跟随。

## Steps to reproduce
请看 gif 图：
![动画1](https://user-images.githubusercontent.com/45350455/140254873-972d18ce-321f-48e1-9589-af2b7b2ec1b8.gif)

快速拖动滑块，特别是在两边界或向上拖动时。

**Comment by kirazxyun** [comment]
收到，我们这边仔细过一下鼠标滑出的问题。
