### ISSUE TITLE
Arco-VUE如何在函数调用modal对话框时content中渲染自定义组件？

### ISSUE THREAD

**Issue by kustone** [arco-design/arco-design-vue#747]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
官方示例是arco.$modal.info(title:str,content:str)的例子，没有展示如和渲染自定义组件
`this.$modal.info({ title: 'Info Title', content: 'This is an info message' });`

我尝试使用以下方法弹出组件，但显示异常（html基础标签正常显示，组件标签无法显示并且报错）
```
import newEle from '@/views/layout/component/new.vue'；
this.$modal.open({ title: "测试标题", content:()=>{ return newEle.render() } })
```

## What problem does this feature solve?
请教一下，Arco-VUE组件库的Modal 对话框，如何在函数调用的情况下传递自定义组件？Modal的content参数类型为renderfunction，我尝试了以下方法去展示自定义组件，但无法正常渲染自定义组件中使用的arco组件，希望能提供一下方法示例，十分感谢！！

**Comment by Flsion** [comment]
@kustone 可以通过 h 函数或者 JSX 方式自定义内容。https://vuejs.org/guide/extras/render-function.html 这里是 vue 的相关文档，类似 content: ()=> h('div','test') 或者 content: ()=> <div>test</div>
