### ISSUE TITLE
希望 Select 等有使用 Trigger 的都可以完整继承 TriggerProps 而不是组件优先

### ISSUE THREAD

**Issue by VicBilibily** [arco-design/arco-design-vue#750]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
通过 Tab 键切换焦点触发 Select 选项弹出

## 预期解决问题
期望通过 TriggerProps 更改 Select 的 Trigger 方式。现在 Select 固定 Trigger 方式为 click ，希望可以通过 TriggerProps 传入参数修改 Trigger 方式为 focus 。

**Comment by Flsion** [comment]
@VicBilibily 好的，trigger-props 属性会修改下覆盖优先级。另外现在的 select 在 focus 时可以通过 Enter 打开下拉菜单
