### ISSUE TITLE
树 Tree能否暴露一些方法

### ISSUE THREAD

**Issue by Likunone** [arco-design/arco-design-vue#755]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
例如 element-plus的tree组件 https://element-plus.gitee.io/zh-CN/component/tree.html#%E6%96%B9%E6%B3%95

## What problem does this feature solve?
设置节点是否被选中
返回当前被选中节点的数据

**Comment by kirazxyun** [comment]
你好，可以的，我们会规划一些实用的方法暴露出来。
