### ISSUE TITLE
table rowSelection selectedRowKeys 数据绑定错误

### ISSUE THREAD

**Issue by thales-jiang** [arco-design/arco-design-vue#757]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **System:** mac
- **Browser:** chrome98.0.4758.109
- **Reproduction Link:** https://arco.design/vue/component/table

## What is expected?
selectedRowKeys = ref<string[]>([])

## Steps to reproduce
const rowSelection = {
  type: 'checkbox',
  showCheckedAll: true,
  selectedRowKeys: ref<string[]>([])
}

数据出错

如果用
 selectedRowKeys: []

则数据没法改变，并且文档中没有使用表格多选的实例

**Comment by Flsion** [comment]
@thales-jiang selectedRowKeys 属性是受控的，table会一直显示为这个状态，需要用 selection-change 事件来改变 selectedRowKeys 的值。如果只是赋初始值，不关心后续状态，可以使用 defaultSelectedRowKeys。
![image](https://user-images.githubusercontent.com/29793175/156139322-10d36fd9-706a-4ca6-b501-433eef158955.png)

**Comment by thales-jiang** [comment]
谢谢回复，我看过这个才按照那样做的，selectedRowKeys既然是受控，应该是给一个ref可以动态的输入输出string[]
可是这块并不能。

我现在要做的是，用户对复选的内容操作之后，让selectedRowKeys清空，但是现在无法完成

**Comment by thales-jiang** [comment]
我解决了，但是文档不太清楚，我这么做的

首先在表格设置row-selection和侦听事件selection-change
<a-table  :data="list"  row-key="id" :row-selection="rowSelection" @selection-change="onSelectionChange" >

然后在rowSelection设置selectedRowKeys为空数组
const rowSelection = reactive({
  type: 'checkbox',
  selectedRowKeys: []
});

在onSelectionChange事件里改变selectedRowKeys
const onSelectionChange = (arr:any) => {
  rowSelection.selectedRowKeys = arr;
};

这样就等于是自己控制了selectedRowKeys
可是官方文档没有给出怎么获得复选框选择的内容的方式，我只能猜是事件

**Comment by ad666666** [comment]
要是有小伙伴按照这个方法没成功的话，注意下
const rowSelection = reactive({
		type: 'checkbox',
		showCheckedAll: true,
		selectedRowKeys: [],
	});
这段代码，官方文档里没带 reactive(），加上就能实现了
