### ISSUE TITLE
Button组件的样式会与tailwindcss的preflight冲突

### ISSUE THREAD

**Issue by Xy2002** [arco-design/arco-design-vue#759]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.17.0
- **系统版本:** macOS
- **浏览器版本:** chrome98.0.4758.109
- **复现地址:** https://codepen.io/Marshall_W/pen/gOXQyQZ

## 预期结果
希望能解决与tailwindcss的样式冲突

## 复现步骤
当Button组件的type为primary且没有设置status时，tailwindcss的preflight会将组件type=primary预设的样式覆盖为background-color:transparent，但设置status时，显示正常

**Comment by xuxucode** [comment]
`<a-form-item  required>` 有类似情况，* 号会显示在 label 上方:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/8274162/156478754-0c3387ee-bf3b-4f1f-8d0f-e88beed5389a.png">

**Comment by xuxucode** [comment]
[tailwindcss preflight](https://tailwindcss.com/docs/preflight) 基于 [modern-normalize](https://github.com/tailwindlabs/tailwindcss/pull/2572) 添加了 button、svg 等样式，arco 基于 normalize.css，两者冲突和多余，禁用 preflight 后就好了:
```diff
// tailwind.config.js
module.exports = {
+  corePlugins: {
+    preflight: false,
+  },
```

**Comment by IsLand-x** [comment]
![image](https://user-images.githubusercontent.com/50228788/156885966-e985e01f-7b5b-4ed5-bfd9-b80336e4e290.png)
可以这样改一下源码，提高权重。

**Comment by Xy2002** [comment]
> [tailwindcss preflight](https://tailwindcss.com/docs/preflight) 基于 [modern-normalize](https://github.com/tailwindlabs/tailwindcss/pull/2572) 添加了 button、svg 等样式，arco 基于 normalize.css，两者冲突和多余，禁用 preflight 后就好了:
> 
> ```diff
> // tailwind.config.js
> module.exports = {
> +  corePlugins: {
> +    preflight: false,
> +  },
> ```
> 
> 然而 preflight 中的有些样式还是必要的，比如 [border-style](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L11)，需要手动添加。

后续发现调换import顺序就好了。如果直接禁用tailwindcss preflight会导致我的项目需要大量修改样式
```TypeScript
// src/main.ts
import './index.css' //tailwindcss directives
import '@arco-design/web-vue/dist/arco.css'
```

**Comment by IsLand-x** [comment]
> > [tailwindcss preflight](https://tailwindcss.com/docs/preflight) 基于 [modern-normalize](https://github.com/tailwindlabs/tailwindcss/pull/2572) 添加了 button、svg 等样式，arco 基于 normalize.css，两者冲突和多余，禁用 preflight 后就好了:
> > ```diff
> > // tailwind.config.js
> > module.exports = {
> > +  corePlugins: {
> > +    preflight: false,
> > +  },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然而 preflight 中的有些样式还是必要的，比如 [border-style](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L11)，需要手动添加。
> 
> 后续发现调换import顺序就好了。如果直接禁用tailwindcss preflight会导致我的项目需要大量修改样式
> 
> ```ts
> // src/main.ts
> import './index.css' //tailwindcss directives
> import '@arco-design/web-vue/dist/arco.css'
> ```

这样做是引入全量样式，项目体积会变大吧？

**Comment by Xy2002** [comment]
> > > [tailwindcss preflight](https://tailwindcss.com/docs/preflight) 基于 [modern-normalize](https://github.com/tailwindlabs/tailwindcss/pull/2572) 添加了 button、svg 等样式，arco 基于 normalize.css，两者冲突和多余，禁用 preflight 后就好了:
> > > ```diff
> > > // tailwind.config.js
> > > module.exports = {
> > > +  corePlugins: {
> > > +    preflight: false,
> > > +  },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然而 preflight 中的有些样式还是必要的，比如 [border-style](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css#L11)，需要手动添加。
> > 
> > 
> > 后续发现调换import顺序就好了。如果直接禁用tailwindcss preflight会导致我的项目需要大量修改样式
> > ```ts
> > // src/main.ts
> > import './index.css' //tailwindcss directives
> > import '@arco-design/web-vue/dist/arco.css'
> > ```
> 
> 这样做是引入全量样式，项目体积会变大吧？

是的，但是因为是不那么重要的项目，所以怎么方便怎么来🤣，不是特别需要考虑项目体积

**Comment by hyp530** [comment]
> 

请问，使用unplugin-vue-components按需引用arco，normlize.css污染了整体样式，怎么降低normlize.css的优先级呢？

**Comment by xuxucode** [comment]
在 tailwindcss 越来越流行的情况下，建议 arco-design 替换掉 `normlize.css` 而使用 `modern-normalize`，两者保持更好的兼容性。

**Comment by flsion** [comment]
> @flsion 在 tailwindcss 越来越流行的情况下，建议 arco-design 替换掉 `normlize.css` 而使用 `modern-normalize`，两者保持更好的兼容性。

好的，我来调研一下看看
