### ISSUE TITLE
upload组件照片墙模式 当上传的文件类型为视频时照片墙内封面图片展示错误

### ISSUE THREAD

**Issue by xiyanbox** [arco-design/arco-design-vue#762]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **Browser:** chrome98.0.4758.109
- **Reproduction Link:** https://codepen.io/m5637379/pen/ExbGLpN?editors=001
![image](https://user-images.githubusercontent.com/18209483/156509837-78c11803-09d8-41d3-b23a-8f1f133c4289.png)

## What is expected?
展示默认图片或者视频第一帧

**Comment by Flsion** [comment]
@xiyanbox 视频的处理已经超出了upload组件的范畴，这里可以增加一个image插槽，可以让用户自定义下图片的展示
