### ISSUE TITLE
表格(table)在使用树形数据展示时，如果绑定的数据源中有字段'id'，则会显示出扩展行expand

### ISSUE THREAD

**Issue by tinyniu** [arco-design/arco-design-vue#764]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://arco.design/vue/component/table#subtree

## What is expected?
树形表格，不再因为有字段'id'而出现空白的扩展行expand

**Comment by Flsion** [comment]
@tinyniu 是否设置了 :rowKey="id"

**Comment by tinyniu** [comment]
@Flsion 好使，谢谢啊；

**大佬文档需要更新下，Arco Design Vue 文档中没有 table props 并没有明确说明有rowKey属性。**
