### ISSUE TITLE
tree组件能否增加半选节点相关功能和方法

### ISSUE THREAD

**Issue by abnereel** [arco-design/arco-design-vue#785]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
可以参考iview 或者 element plus

## What problem does this feature solve?
tree组件用在菜单权限这块的不少，菜单这块，上级菜单没有下级菜单是不会出来，所以需要保存半选对象的key

**Comment by kirazxyun** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)
> 
> ## Basic Info
> ## What are the similar cases of this feature
> 可以参考iview 或者 element plus
> 
> ## What problem does this feature solve?
> tree组件用在菜单权限这块的不少，菜单这块，上级菜单没有下级菜单是不会出来，所以需要保存半选对象的key

计划增加一下 getHalfCheckedNodes 用来获取半选节点

**Comment by abnereel** [comment]
赋值的时候考虑一下包含半选节点的key，但是并没有全选

**Comment by abnereel** [comment]
目前半选赋值给tree，会导致全选
