### ISSUE TITLE
open nuxt

### ISSUE THREAD

**Issue by skyblued** [arco-design/arco-design-vue#789]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
看到更新日志,说支持ssr, 可以支持nuxt吗

## What problem does this feature solve?
可以在nuxt中使用吗

**Comment by Flsion** [comment]
@skyblued 可以在nuxt3中使用，目前ssr功能还处于beta版，部分组件存在提示警告的问题，如遇到问题可以创建个issue

**Comment by skyblued** [comment]
plugins 文件里面
import { defineNuxtPlugin } from "#app";

import ArcoVue from '@arco-design/web-vue';
import '@arco-design/web-vue/dist/arco.css';


export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.use(ArcoVue)
})

下面是运行时报错信息

Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by skyblued** [comment]
如果可以的话, 您这边有运行完整的例子模板吗?
