### ISSUE TITLE
表格组件头部显示问题

### ISSUE THREAD

**Issue by nuaajiangteng** [arco-design/arco-design-vue#790]
表格组件头部过长，当表格没数据的时候，头部高度撑得过高
![7821CACE92AD36E88D0C8FCB587C3986](https://user-images.githubusercontent.com/29668874/157177078-1d765fb2-56ef-4dd9-b6af-f243dae1829c.jpg)
![8D72112E96FCD883F9042A7A4CB4A29E](https://user-images.githubusercontent.com/29668874/157177089-80a3df90-f6a4-470c-9e2d-2a792c19471d.jpg)

**Comment by Flsion** [comment]
@nuaajiangteng 你好，这个是不是某列的标题产生了换行，可以提供一个复现地址吗

**Comment by hehehai** [comment]
@Flsion 有个问题想请教下，th 的宽度是如何被影响的，😅看了代码没找到

**Comment by hehehai** [comment]
@Flsion

**Comment by Flsion** [comment]
@hehehai 这个应该是无宽度的th被挤压后换行导致整体的高度变高了，需要在空数据的时候把表头的滚动放开，我来处理下
