### ISSUE TITLE
dayjs error found in nuxt3

### ISSUE THREAD

**Issue by waset** [arco-design/arco-design-vue#792]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.18.1
- **Browser:** chrome98.0.4758.109
- **Reproduction Link:** https://codesandbox.io/s/musing-yonath-3r70zr?file=/package.json

## What is expected?
建议修复dayjs引入方法

## Steps to reproduce
dev下报dayjs模块错误

**Comment by flsion** [comment]
This problem will be solved after the official version of nuxt3

**Comment by Baiyuetribe** [comment]
same erros
![image](https://user-images.githubusercontent.com/43716063/180970553-4f26adb4-6e85-427f-9586-0260191d789a.png)
![image](https://user-images.githubusercontent.com/43716063/180970603-5fb1027c-1564-4269-9d90-b5de1c7a32b4.png)

**Comment by ylater** [comment]
这个问题会再近期更新中解决吗?
![image](https://user-images.githubusercontent.com/5534187/197444394-25bc8fb7-6b57-4218-831b-10fa7cb2159d.png)

**Comment by loca-spirit** [comment]
这个问题能修复一下吗？希望引入dayjs2.0
