### ISSUE TITLE
Drawer组件可配置是否隐藏取消按钮

### ISSUE THREAD

**Issue by wehuss** [arco-design/arco-design-vue#793]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
就像Modal组件一样
![image](https://user-images.githubusercontent.com/48681136/157356572-d5bbb83a-44f3-4e2d-891b-72e7a3053442.png)

## What problem does this feature solve?
可配置是否隐藏取消按钮

**Comment by Flsion** [comment]
@wehuss 好的，新版本会增加一下这个属性

**Comment by hongtu1993** [comment]
> @wehuss 好的，新版本会增加一下这个属性

那么，如何隐藏footer呢？

**Comment by hongtu1993** [comment]
> > @wehuss 好的，新版本会增加一下这个属性
> 
> 那么，如何隐藏footer呢？

抱歉，原有有 footer 属性，可以控制是否显示。
