### ISSUE TITLE
动态表单无法验证

### ISSUE THREAD

**Issue by venlee1993** [arco-design/arco-design-vue#799]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.18.1
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://codepen.io/VenleeO8/pen/abVeJvV

## What is expected?
期望能够验证动态的表单

**Comment by Flsion** [comment]
@venlee1993 18版本有修改获取field的方法，导致了这个问题。目前可以使用之前的版本，这个问题会在新版本修复

**Comment by kanyxmo** [comment]
这个问题还没解决啊
