### ISSUE TITLE
a-table是否支持固定表头滚动？

### ISSUE THREAD

**Issue by jerryhu88** [arco-design/arco-design-vue#80]

**Comment by LuckyHookin** [comment]
![image](https://user-images.githubusercontent.com/45350455/140454984-7e623b01-edad-4386-af1b-b25941976e92.png)
当设置了 scroll，列表滚动时表头是固定在上面的：
![image](https://user-images.githubusercontent.com/45350455/140455318-45662193-5101-443d-8c25-9d090e3ad24b.png)

https://codepen.io/luckyhookin/pen/XWaZZzY?editors=1010

**Comment by Flsion** [comment]
@jerryhu88 Hi，table的功能更新已经在进行啦，这个功能会在后续的版本中推出
