### ISSUE TITLE
table 动态表头场景下，排序图标显隐异常

### ISSUE THREAD

**Issue by hehehai** [arco-design/arco-design-vue#801]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.18.1
- **浏览器版本:** chrome98.0.4758.109
- **复现地址:** https://stackblitz.com/edit/vue-5thw2j?file=src/App.vue

## 额外补充
是否和 key 有关？看到代码中key使用的index

## 预期结果
排序图标和当前所在单元格均不可见，且兄弟单元格正常显示

**Comment by hehehai** [comment]
th 的 key 是否可以使用 dataIndex + index ?

**Comment by hehehai** [comment]
@Flsion

**Comment by Flsion** [comment]
@hehehai 你好，我检查了下，这个是 th 内部对column的用法导致的问题，没有监听到column的更新。我在th组件上修复下这个问题，用key的方法也可以重新加载这个组件解决问题
