### ISSUE TITLE
级联选择器change回调事件参数是否有暴露选中项option

### ISSUE THREAD

**Issue by yilujun100** [arco-design/arco-design-vue#805]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
当选中某项值的时候会根据选中项做一些额外的操作

## What problem does this feature solve?
目前change事件只有value选中值

**Comment by flsion** [comment]
可以使用 `object` 形式的 value 用来扩展选中值的信息
