### ISSUE TITLE
input-number的精度无效

### ISSUE THREAD

**Issue by seepine** [arco-design/arco-design-vue#81]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 2.0.0
- **System:** Macos
- **Browser:** GoogleChrome
- **Reproduction Link:** https://arco.design/vue/component/input-number#precision

## What is expected?
能够有精度限制

## Steps to reproduce
功能无效
![image](https://user-images.githubusercontent.com/93666053/140447330-6ccc662c-827a-445c-b5ef-cd397f39b24e.png)

**Comment by kirazxyun** [comment]
收到～
