### ISSUE TITLE
暗黑模式下，左侧banner的title不明显

### ISSUE THREAD

**Issue by Hazel-Lin** [arco-design/arco-design-vue#811]
在暗黑模式下的登录页面左侧banner中的title不明显
![image](https://user-images.githubusercontent.com/52577448/157845699-db166f2e-ac35-4324-8ac6-8ae2887beb0b.png)

**Comment by flsion** [comment]
pro 相关 issue 可以提交到 https://github.com/arco-design/arco-design-pro-vue/issues 上
