### ISSUE TITLE
表格组件 当配置expandable 中 defaultExpandAllRows = true 时 data中有默认数据才有效果， 异步获取data赋值 没有展开效果

### ISSUE THREAD

**Issue by venlee1993** [arco-design/arco-design-vue#814]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.17.0
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://codepen.io/VenleeO8/pen/zYpYOqj?editors=1010

## What is expected?
期望当 异步获取数据的时候 table 树状 也能展开

**Comment by Flsion** [comment]
@venlee1993 这个是符合预期的，defaultExpandAllRows 属性只会在表格首次加载后生效一次。针对异步的情况，目前可以控制expandedRowKeys 传入所有行的key。这里会考虑增加一个展开的方法，方便使用

**Comment by qingtiantongxie** [comment]
expand 方法只有 rowKey 一个参数  有点狭窄   是否可以把record 带进来 我用es查询  需要_id and _index 两个值  但是expand 只能拿一个  另外一个还要find 一下  十分繁琐  table 组件很多地方的参数都只有限定死的 使用很不方便  希望可以优化下
