### ISSUE TITLE
Tree 组件展开受控时能否禁止收缩动画

### ISSUE THREAD

**Issue by liupan1890** [arco-design/arco-design-vue#815]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
``````
 <a-tree
            :expanded-keys="CopyTreeExpandedKeys"   //注：已明确指定受控展开
            :data="CopyTreeData"
            :virtualListProps="{
              height: TreeHeight
            }"
          >
          </a-tree>
``````

## What problem does this feature solve?
一个文件树，文件夹--文件列表
  
要求文件夹默认展开，且不可收缩
  
当前设置  :expanded-keys="allkeyslist" 时，虽然能够做到默认展开，且不可收缩。但点击收缩图标时，会触发收缩动画，导致文件树闪烁且滚动位置错位

![shousuo](https://user-images.githubusercontent.com/67817756/158009022-4fc592f2-4d4d-4419-90cf-1ec86faec529.gif)
  
如上图，应该在 @expand 事件里，根据返回值，决定，可以取消收缩/展开 动画，最终实现不可收缩时不触发动画

--

注：请留意，截图中，收缩后又自动展开（因为没有修改expanded-keys），此时导致

1.Tree 闪烁，很难看(尤其是截图最后，出现了半个屏幕的白屏闪烁)
2.Tree 收缩动画结束后，滚动位置没有恢复正确的滚动位置，导致显示错位

注2：在设置  :expanded-keys="allkeyslist" 时，点击收缩图标也无法收缩，因为不是设置  v-model:expanded-keys="allkeyslist"

**Comment by kirazxyun** [comment]
收到问题，我们优化一下
