### ISSUE TITLE
表格组件内表头如何居中？

### ISSUE THREAD

**Issue by Web-Kevin** [arco-design/arco-design-vue#816]
默认表头内容是左对齐 使用align属性也只能改变内容的对齐方式，表头该如何更改对齐方式？

**Comment by hehehai** [comment]
@Web-Kevin align 可以控制表头的对齐方式的

**Comment by Web-Kevin** [comment]
![image](https://user-images.githubusercontent.com/5680712/158063446-fc572872-7724-46bc-bf99-084d44c38e52.png)
![image](https://user-images.githubusercontent.com/5680712/158063472-16f1598b-a730-4ead-aed4-2e9d3fd65445.png)
@hehehai 我这么配置的 是不配置错误啊

**Comment by hehehai** [comment]
@Web-Kevin 配置对了，目前基础使用下可以（表头没有设置排序，筛选的）


有排序或筛选的情况下，可以先这样解决
```js
{
	title: "日期",
	dataIndex: "rq",
	sortable: {
      sortDirections: ['ascend', 'descend'],
    },
	align: "center",
	cellStyle: { 'justify-content': 'center' },
}
```

**Comment by hehehai** [comment]
@Flsion 🤔这里 align 的行为应该一致的，你觉得呢

**Comment by Flsion** [comment]
嗯，这里需要处理一下，应该是要都居中的

**Comment by Web-Kevin** [comment]
@hehehai @Flsion
