### ISSUE TITLE
InputTag 标签输入框 清空bug

### ISSUE THREAD

**Issue by xxxlrlovegd** [arco-design/arco-design-vue#82]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** 最新版本的design-vue
- **System:** arco-design-vue
- **Browser:** google
- **Reproduction Link:** https://arco.design/vue/component/input-tag

## What is expected?
清空数据之后 清空按钮应该还显示的

## Steps to reproduce
InputTag 标签输入框 点击输入框清空按钮之后数据清空后，再次输入数据清空按钮不在显示了

**Comment by kirazxyun** [comment]
@xxxlrlovegd 你好，请问复现步骤是什么呢，目前有 tag 的情况下是会有清空按钮的哦，如果只是在输入状态是不会有清空按钮的，试试输入完整后按一下回车看看～

**Comment by xxxlrlovegd** [comment]
感谢您的回复，解答了我的这个问题。



At 2021-11-05 10:48:28, "kira" ***@***.***> wrote:

@xxxlrlovegd 你好，请问复现步骤是什么呢，目前有 tag 的情况下是会有清空按钮的哦，如果只是在输入状态是不会有清空按钮的，试试输入完整后按一下回车看看～

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
