### ISSUE TITLE
model 脚本实例，状态方法的文档可以补充下默认配置

### ISSUE THREAD

**Issue by hehehai** [arco-design/arco-design-vue#824]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
状态方法的默认配置和open方法的区别

```
simple: true,
hideCancel: true,
```

这个在文档中可以说明一下

## 预期解决问题
open防范默认 config 和 状态方法默认配置不一致，但文档中未说明

**Comment by Flsion** [comment]
@hehehai 好的，这里会添加下相应的说明

**Comment by Flsion** [comment]
示例处增加了相关提示 https://arco.design/vue/component/modal#notice
