### ISSUE TITLE
希望【自动补全】【选择器】组件能支持键盘操作

### ISSUE THREAD

**Issue by zengjinwork** [arco-design/arco-design-vue#834]
目前【自动补全】【选择器】不支持键盘选择。

尤其【自动补全】如果键盘输入完毕时，能紧接着使用方向键选择下拉项，将会明显提升操作流畅度。

React版实现的很好。

**Comment by Flsion** [comment]
@zengjinwork 目前都是支持的

![Kapture 2022-03-18 at 12 09 02](https://user-images.githubusercontent.com/29793175/158936080-89c3ae81-854f-42d8-9cc1-5828679416ff.gif)

**Comment by zengjinwork** [comment]
@Flsion 你好, 我确认了下是在86内核上不起作用, 国产浏览器好多还停在86内核, react版本是可以的.
无伤大雅了, 当然能解决的话更好🌹🌹

**Comment by Flsion** [comment]
> 

好的，知道了，我去测试一下，应该是使用的Event不兼容的问题

**Comment by flsion** [comment]
新版本以修改触发方式，如果仍然存在问题，可以再新建个 issue
