### ISSUE TITLE
Modal模块中，使用this.$modal.info(config)打开的对话框不能通过返回的ModalReturn的close方法关闭

### ISSUE THREAD

**Issue by erlangera** [arco-design/arco-design-vue#836]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.19.0
- **System:** Windows 8.1
- **Browser:** chrome99.0.4844.74
- **Reproduction Link:** https://codepen.io/erlangera/pen/yLpexBP

## Extra info
目测是@arco-design\web-vue\es\modal\index.js中open方法返回值有问题
原为return { close };
应改为return { close: handleClose };

## What is expected?
对话框能够关闭

**Comment by Flsion** [comment]
@erlangera 好的，感谢反馈，这次的版本会修复下
