### ISSUE TITLE
table-column 组件支持 render 函数

### ISSUE THREAD

**Issue by hehehai** [arco-design/arco-design-vue#850]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
18版本可以使用 render prop 渲染，新版本只能使用 cell slot, 某些 jsx 组件使用起来不方便

## 预期解决问题
可以使用 render prop, 参数和 cell slot 相同

**Comment by hehehai** [comment]
@Flsion 组件的 render

**Comment by Flsion** [comment]
@hehehai 能提供个复现的地址或者代码吗，看下是怎样的方式
