### ISSUE TITLE
tree 无法触发expand 方法 绑定expanded-keys 展开功能无法使用

### ISSUE THREAD

**Issue by venlee1993** [arco-design/arco-design-vue#851]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.20.0
- **Browser:** chrome99.0.4844.82
- **Reproduction Link:** https://codepen.io/VenleeO8/pen/ZEvOjzz?editors=1011

## What is expected?
期望能触发expand时间 绑定expanded-keys后可以正常使用

**Comment by Flsion** [comment]
@venlee1993 这个问题已经修复了，可以升级一下
