### ISSUE TITLE
2.18.0版本select 多选模式下“单个内容没有删除按钮”

### ISSUE THREAD

**Issue by ZQFTF** [arco-design/arco-design-vue#855]
![image](https://user-images.githubusercontent.com/48020274/159453086-6e5b198e-e8da-4d8d-8b2b-6f50699169c0.png)

**Comment by Flsion** [comment]
@ZQFTF 你好，可以提供个复现的地址吗

**Comment by ZQFTF** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design-vue] 2.18.0版本select 多选模式下“单个内容没有删除按钮” (Issue #855)





 
@ZQFTF 你好，可以提供个复现的地址吗

**Comment by Flsion** [comment]
新版本已经修复这个问题
