### ISSUE TITLE
Tag component: no mini style

### ISSUE THREAD

**Issue by JonZhang3** [arco-design/arco-design-vue#857]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.20.1
- **浏览器版本:** chrome99.0.4844.74
- **复现地址:** https://arco.design/vue/component/tag

## 预期结果
Display Mini style tag normally

## 复现步骤
No mini style

**Comment by Flsion** [comment]
@JonZhang3 你好，这个问题有和设计讨论过，由与浏览器上最小字体为 12px ，不适合再缩小尺寸了，tag组件会删除多余的 mini 大小
