### ISSUE TITLE
建议添加邮政编码，地图锚点之类的图标

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#859]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What problem does this feature solve?
最近在练手一个房产项目，发现内置的图标库里面没有与地理相关的图标，每次需要用到时就需要自己制作或外部引入。如果内置图标库里加入了相关图标那就帮了大忙了。

## What are the similar cases of this feature
特别是邮政编码图标（两横一竖）在国外的很多表单项里出现的是非常频繁的，所以有空的话恳请各位大佬添加一下。

![mapLocal](https://user-images.githubusercontent.com/77368194/159600392-96a58452-ae19-4fc4-a50d-582823bff02c.png)
![postalCode](https://user-images.githubusercontent.com/77368194/159600396-623f80e5-cf23-426b-8f35-e05d6103dcd2.png)

**Comment by Flsion** [comment]
@yymjku18 好的，我和设计同学反馈一下

**Comment by flsion** [comment]
组件库内的图标库暂不会增加，可以使用 https://arco.design/iconbox/libs 创建一个图标库
