### ISSUE TITLE
希望可以开放一些表格的方法

### ISSUE THREAD

**Issue by chowchihang** [arco-design/arco-design-vue#875]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
像element-ui一样增加一些表格的方法
https://element.eleme.cn/#/zh-CN/component/table

<img width="925" alt="image" src="https://user-images.githubusercontent.com/31722591/160085936-1f0a05d4-cbcf-4113-9ee2-1234b19c3b59.png">

## What problem does this feature solve?
可以使用方法，如被动修改表格功能属性等

**Comment by Flsion** [comment]
@chowchihang 好的，下个版本中 table 会添加一些操作函数

**Comment by flsion** [comment]
新版表格已增加相关操作函数

**Comment by niceMoonMaker** [comment]
为什么不增加获取所有选中row的数据方法呢？
