### ISSUE TITLE
TreeSelect v-model 绑定值不存在会选中不存在的数据

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#880]
https://codepen.io/svipchao/pen/poperZv

selected的类型不管是Nubmer还是String，如果数据里不存在，则会默认选中该值

个人觉得应该实现的效果是，select不是input，它不应该选中一个不存在的数据

**Comment by kirazxyun** [comment]
你好，对于找不到选项的值，我们遵循的兜底方案是显示 value 值，目前来看是有缺陷的，为了适配更多的需求，我们将增加 fallback 选项，让用户决定如何显示找不到选项的值。这个功能已安排，请关注后续更新。
