### ISSUE TITLE
tree绑定checked-keys后复选框无法勾选

### ISSUE THREAD

**Issue by Tony2021** [arco-design/arco-design-vue#881]
当tree开启复选框功能，绑定checked-keys后无法操作复选框。直接拷贝了官网“带复选框的树”的示例代码运行后也是同样的情况

**Comment by Flsion** [comment]
@Tony2021 你好，请问下组件库是什么版本，2.20.1 版本有修复下 tree 的问题

**Comment by Tony2021** [comment]
原来是2.20.0,后来升级到最新版本解决问题了
在2022年3月26日 ***@***.***> 写道：

@Tony2021 你好，请问下组件库是什么版本，2.20.1 版本有修复下 tree 的问题

**Comment by Tony2021** [comment]
原来版本是2.20.0,升级到2.21.1，问题解决了

**Comment by 1zilc** [comment]
2.45.1 问题依旧存在

**Comment by HongtianBryant** [comment]
@arco-design/web-vue的2.45.2版本依然有这个问题 确定修复了吗

**Comment by java668** [comment]
2.50.2 还有这个问题啊
