### ISSUE TITLE
table组件 开启虚拟滚动后，列宽度失效问题以及横向滚动失效问题

### ISSUE THREAD

**Issue by abang951** [arco-design/arco-design-vue#882]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.21.1
- **浏览器版本:** chrome99.0.4844.83
- **复现地址:** https://codesandbox.io/s/infallible-thunder-vlzjnp?file=/src/App.vue

## 预期结果
1.数据列与表头位置匹配  2.多列时可以横向滚动

**Comment by Flsion** [comment]
@abang951 新版本中处理了这个问题。由于虚拟列表的实现方法不能处理自动横向滚动的问题，如果横向长度超出的话可以开启scroll 配合使用 https://codesandbox.io/s/objective-tree-90d7v2?file=/src/App.vue
