### ISSUE TITLE
可编辑表格和展开行如何结合

### ISSUE THREAD

**Issue by llocry** [arco-design/arco-design-vue#883]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
暂无

## What problem does this feature solve?
希望可实现展开行的可编辑表格

## Extra info
根据官方文档，可编辑表格通过slot实现，但是能获取到的rowIndex只是当前点击行的index，无法确定上级

**Comment by llocry** [comment]
准确说应该是树形数据展示结合可编辑表格

**Comment by Flsion** [comment]
@llocry 这里想要加个类似 indexPath 的参数，如果是树形数据的话，会把每一层的index都包括近来，这样的话可以方便定位一下

**Comment by flsion** [comment]
新版本上可以支持修改 slot 传出的值了~
