### ISSUE TITLE
Timeline组件加上最大高度

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-vue#884]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
无

## 预期解决问题
当前父元素设置style:max-height后，Timeline组件仍然撑开高度。希望Timeline组件能增加设置最大高度，多出高度内容增加滚动条。

**Comment by Flsion** [comment]
@cxiniao 好的，我们研究看一下

**Comment by chenxch** [comment]
我认为应该是父元素在添加个`overflow-y: auto;` 组件不需要做变动。

**Comment by cxiniao** [comment]
@chenxch 有道理，感谢。
