### ISSUE TITLE
menu 动态切换菜单后不会自动展开已选择的菜单，auto-open-selected只在初始化的时候有效

### ISSUE THREAD

**Issue by yanbowe** [arco-design/arco-design-vue#888]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.21.1
- **浏览器版本:** chrome99.0.4844.82
- **复现地址:** https://codesandbox.io/s/lucid-brahmagupta-wc0zle?file=/src/App.vue

## 预期结果
切换至另外一个菜单层级时，自动展开已切换菜单的层级

## 复现步骤
打开链接，点击下方切换菜单按钮，发现不会自动展开已切换的菜单层级。

**Comment by kirazxyun** [comment]
auto-open-selected 只在初始化的时候生效，如果是动态的数据，建议自行控制 open-keys

**Comment by yanbowe** [comment]
> auto-open-selected 只在初始化的时候生效，如果是动态的数据，建议自行控制 open-keys

不考虑做选中菜单后自动展开当前层级吗

**Comment by kirazxyun** [comment]
> > auto-open-selected 只在初始化的时候生效，如果是动态的数据，建议自行控制 open-keys
> 
> 当我设置open-keys的时候，菜单变得不正常，open-keys不能和selected-keys为一个数组？也就是说我需要额外维护一个open-keys数组吗？不考虑增加选中菜单时自动展开当前层级吗？

不能是一个的，open-keys 存储的是 sub-menu 的 key，而 selected-keys 是已选菜单的 key，一般是 menu-item。open-keys 和 selected-keys 都支持了 v-model，存储和修改都很方便，可以试试看。

**Comment by jiankafei** [comment]
@kirazxyun auto-open-selected 这个属性真的很鸡肋，完全没有发挥它的名字表示的功能该有的作用。

**Comment by NieBarBar** [comment]
有一个解决办法：给Menu组件加上一个key，值为当前激活的菜单项的key，这样每次菜单项切换会引起Menu组件重新渲染，auto-open-selected 也就有用了。
缺点：会引起Menu组件不必要的重渲染，有效率问题，自行取舍。

**Comment by wtz** [comment]
最新版本的加key后，直接报错：
![image](https://github.com/user-attachments/assets/64821751-d119-4b6b-803a-cbf46bf5c4b6)
