### ISSUE TITLE
cascader级联选择是否可以加个label的className

### ISSUE THREAD

**Issue by 95743** [arco-design/arco-design-vue#890]
我只想保留级联选择最后一项的选择框该如何实现？

**Comment by Flsion** [comment]
@95743 这个可以通过定制样式把 选择器 隐藏起来，非末尾的 arco-cascader-panel-column 下的 arco-cascader-option 中的 arco-checkbox 全部 display:none 。 arco-cascader-panel-column 的选择可以根据你的实际情况用 css 选择器筛选下
