### ISSUE TITLE
Select 多选是否可增加全局的Tag关闭设置

### ISSUE THREAD

**Issue by JonZhang3** [arco-design/arco-design-vue#891]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 现有案例
可参考Antd https://ant.design/components/select-cn/#components-select-demo-multiple
![image](https://user-images.githubusercontent.com/53330083/160382895-2e9a5572-0934-44b9-8da4-1779c2acb475.png)

## 预期解决问题
有时，并不期望打开下来列表，取消选中项，每项都增加 tagProps 又很麻烦。所以期望增加一个全局的tagClosable属性，来实现这个效果

**Comment by Flsion** [comment]
@JonZhang3 这个 关闭icon 默认是应该显示，这里是个 select 的问题，在 2.21.2 版本中已经修复了
