### ISSUE TITLE
在二级菜单添加icon不生效

### ISSUE THREAD

**Issue by wapscccs** [arco-design/arco-design-vue#895]
只有一级菜单才只有icon吗？在二级菜单添加icon不生效

**Comment by Flsion** [comment]
@wapscccs 这个是指哪里？

**Comment by kirazxyun** [comment]
@wapscccs submenu  和 menu-item 都支持设置 icon 的

**Comment by kirazxyun** [comment]
@wapscccs 你好，该 issue 没有活跃度这边关闭了，有问题的话可以再开启。
