### ISSUE TITLE
tabs 的v-model 设置无效

### ISSUE THREAD

**Issue by followyourhreat** [arco-design/arco-design-vue#896]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.18.0
- **Browser:** chrome98.0.4758.82
- **Reproduction Link:** https://www.baidu.com/

## What is expected?
v-model的值能够正确聚焦

**Comment by Flsion** [comment]
@followyourhreat tabs的v-model需要绑定属性名 https://codesandbox.io/s/happy-visvesvaraya-hy5m57?file=/src/App.vue
