### ISSUE TITLE
mention 双向绑定时，选择@列表项目时，选项值会覆盖 mention 当前值

### ISSUE THREAD

**Issue by netpole** [arco-design/arco-design-vue#899]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.21.2
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** https://codesandbox.io/s/admiring-ardinghelli-d4jg18?file=/src/App.vue

## What is expected?
选择 @选项 后应当将选项值插入到 mention 当前值内，而非覆盖。

/packages/web-vue/components/mention/mention.tsx：

237:
      ...
      emit('select', value);
      emit('update:modelValue', value); // 错误
      emit('change', nextValue);
      ...

**Comment by Flsion** [comment]
@netpole 是这里的问题，这里应该也是 nextValue
