### ISSUE TITLE
当form-item的label用slot来渲染下拉选时，点击下拉有闪烁一下自动关闭的问题

### ISSUE THREAD

**Issue by JobinJia** [arco-design/arco-design-vue#900]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.21.2
- **System:** mac Os
- **Browser:** chrome99.0.4844.83
- **Reproduction Link:** https://codesandbox.io/s/frosty-grass-51zp1o

## What is expected?
当form-item的label用slot来渲染下拉选时, 能正常的使用

**Comment by Flsion** [comment]
@JobinJia 好的，初步看是 label 元素又一次触发 focus 导致的，我看看处理一下

**Comment by Flsion** [comment]
@JobinJia 新版本增加了一个 label-component 属性，可以修改下渲染的元素，如果这里有放置输入组件的话，可以设置为 'span' 就不会有问题了

**Comment by JobinJia** [comment]
> @JobinJia 新版本增加了一个 label-component 属性，可以修改下渲染的元素，如果这里有放置输入组件的话，可以设置为 'span' 就不会有问题了

okay,  let me try . 
另外期望可以提供一个基于Grid Row Col 布局的FormItem. 这样使布局更简单且更方便 ：） 

thx agin
