### ISSUE TITLE
a-upload 多选图片时自定义上传时，无法请求一次接口批量上传，upload-button.js文件  handleInputChange函数中为什么value值设置为空？ target.value = ""

### ISSUE THREAD

**Issue by smallQQx** [arco-design/arco-design-vue#901]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.21.2
- **Browser:** chrome96.0.4664.110
- **Reproduction Link:** https://codesandbox.io/s/zen-wilson-s6jr5u

## What is expected?
upload-button.js文件  handleInputChange函数中 target.value不要设置为空

**Comment by smallQQx** [comment]
目前在 change中没有一个时机去触发自定义上传函数，因为多选时，change会执行多次，无法做到请求一次接口批量上传图片，这个问题目前您有方法吗

**Comment by smallQQx** [comment]
> > 
> 
> 1.你的auto-upload为false，当然不会触发上传。 2.change执行多次，上传接口目前来看也就触发一次

有可能是我描述的不太清楚。是这样的，打开文件选择弹框多选图片后，调用自定义上传的函数upload（只需执行一次，传给后台的参数是 选择的图片file集合）。就是这个upload 没有一个可执行的时机。如果放在change中，多选图片时change会执行多次，就达不到一次调用action接口批量上传的效果。

**Comment by smallQQx** [comment]
> > 
> 
> 1.你的auto-upload为false，当然不会触发上传。 2.change执行多次，上传接口目前来看也就触发一次

有可能是我描述的不太清楚。是这样的，打开文件选择弹框多选图片后，调用自定义上传的函数upload（只需执行一次，调用action上传接口，传给后台的参数是 选择的图片file集合）。就是这个upload 没有一个可执行的时机。如果放在change中，多选图片时change会执行多次，就达不到一次调用action接口批量上传的效果。

**Comment by chenxch** [comment]
既然关闭了自动上传，当然需要你手动去触发这个上传的动作，可以参考下`手动上传`的demo。

**Comment by Gzbox** [comment]
> > > 
> > 
> > 
> > 1.你的auto-upload为false，当然不会触发上传。 2.change执行多次，上传接口目前来看也就触发一次
> 
> 有可能是我描述的不太清楚。是这样的，打开文件选择弹框多选图片后，调用自定义上传的函数upload（只需执行一次，传给后台的参数是 选择的图片file集合）。就是这个upload 没有一个可执行的时机。如果放在change中，多选图片时change会执行多次，就达不到一次调用action接口批量上传的效果。

一次接口请求  批量上传  你最后用arco 做到了没？
