### ISSUE TITLE
上传组件 - 选择的图片比较大的时候，展示的很慢

### ISSUE THREAD

**Issue by abnereel** [arco-design/arco-design-vue#904]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.21.2
- **系统版本:** MacOS
- **浏览器版本:** chrome99.0.4844.74
- **复现地址:** https://codesandbox.io/s/zimt6t?file=/src/App.vue

## 预期结果
上传大图时也希望能快速展示

## 复现步骤
官方文档中可以复现该问题，我上传的是一张5.9M的图片，选择后会需要几秒钟才会展示出来

**Comment by chenxch** [comment]
可以检查一下network，看看上传的网速如何哈

**Comment by abnereel** [comment]
还没有到上传的步骤，只是选择图片，这个地方和网络没有关系

**Comment by abnereel** [comment]
> 可以检查一下network，看看上传的网速如何哈

你可以在官方文档中的案例中上传一张5M以上的图片试试

**Comment by chenxch** [comment]
> > 可以检查一下network，看看上传的网速如何哈
> 
> 你可以在官方文档中的案例中上传一张5M以上的图片试试

你可以想下或者去源码中看看这个图片既然没有上传，那是怎么渲染出来的，如果你能想到的话，图片大小和渲染速度是成正比的。
