### ISSUE TITLE
带时间的日期选择时间不正确

### ISSUE THREAD

**Issue by Vurtne-hz** [arco-design/arco-design-vue#905]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.21.2
- **系统版本:** Windows
- **浏览器版本:** Microsoft Edge 99.0.1150.55
- **复现地址:** https://arco.design/vue/component/date-picker#showtime

## 预期结果
开始的时间和结束的时间不互换

## 复现步骤
开始的时间和结束的时间如果先选择开始日期再选择结束日期，时间有几率会互换，先选结束日期则不会互换

**Comment by kirazxyun** [comment]
@Vurtne-hz 你好，希望给个稳定复现的路径。

**Comment by Vurtne-hz** [comment]
@kirazxyun  就用官网的https://arco.design/vue/component/date-picker#showtime 在**带时间的日期选择**的最后一个时间区间里选择的开始日期和结束日期，时间用默认，4-1至4-8，4-1至4-15，4-1至4-22，4-1至4-29，来回试几次就可以复现

**Comment by Vurtne-hz** [comment]
@kirazxyun 又测试了下，我明白原因了，如果我是点击的结束日期打开的选择框，焦点会在结束日期那里，那么我选择的第一个是日期是结束日期，此时焦点会到开始时间那，选择第二个日期就是开始日期，假如开始日期比结束日期大时，按正常逻辑是应该互换日期的，但是现在时间也跟着互换了。能只互换日期不互换时间吗？

**Comment by kirazxyun** [comment]
不能只换日期的，顺序算的是最终的值，包含时间在内，比如在同一个日期的时候，时间就决定了顺序。如果是为了固化时间的话，可以监听一下 select 事件，记录开始时间和结束时间，在 change 事件里面自行对值进行合并，可以参考 demo：https://codesandbox.io/s/thirsty-shockley-yft29u
