### ISSUE TITLE
用了表格的summary属性的疑问

### ISSUE THREAD

**Issue by 511701863** [arco-design/arco-design-vue#906]
summary 合计栏打开后 如果我的columns中的值 return了一个值 则合计就会固定出现这个值 并且不会计算  或者 如果我用传统写法

**Comment by 511701863** [comment]
<a-table
                :pagination="false"
                :data="contractBItem.contractCList"
                class="table-form"
                :scroll="{ y: 400 }"
              >
                <template #columns>
                  <a-table-column title="序号" data-index="startDate" align="left" width="80">
                    <template #cell="{ rowIndex }">
                      <div>{{ rowIndex + 1 }}</div>
                    </template>
                  </a-table-column>

**Comment by 511701863** [comment]
<a-table
                :pagination="false"
                :data="contractBItem.contractCList"
                class="table-form"
                :scroll="{ y: 400 }"
                :summary="true"
              >
                <template #columns>
                  <a-table-column title="序号" data-index="startDate" align="left" width="80">
                    <template #cell="{ rowIndex }">
                      <div>{{ rowIndex + 1 }}</div>
                    </template>
                  </a-table-column>
                  <a-table-column title="阶段起止日期" data-index="startDate" align="left">
                    <template #cell="{ rowIndex }">
                      <a-form-item
                        hide-label
                        :field="`contractCList.${rowIndex}.startDate`"
                        :rules="[
                          {
                            required: true,
                            message: '请输入adjustMonth',
                            trigger: 'blur',
                          },
                        ]"
                      >
                        <div class="date-box">
                          <a-date-picker
                            size="mini"
                            v-model="contractBItem.contractCList[rowIndex].startDate"
                            type="date"
                          ></a-date-picker>
                          <span>到</span>
                          <a-date-picker
                            size="small"
                            v-model="contractBItem.contractCList[rowIndex].endDate"
                            type="date"
                            :allow-clear="false"
                            :disabled-time="
                              pickerOptions4EndDate(
                                contractBItem.contractCList[rowIndex].endDate,
                                contractBItem.contractCList[rowIndex].startDate,
                                contractBItem,
                              )
                            "
                          >
                            
                          </a-date-picker>
                        </div>
                      </a-form-item>
                    </template>
                  </a-table-column>
                  <a-table-column title="操作" align="left" v-if="!data.disabled">
                    <template #cell="{ rowIndex }">
                      <a-button type="primary" @click="addTableListRes(rowIndex)">增加</a-button>
                      <a-button type="danger" @click="handleDeleteRes(rowIndex)">删除</a-button>
                    </template>
                  </a-table-column>
                </template>
              </a-table>

**Comment by Flsion** [comment]
@511701863 如果 summary 这里使用的是函数方式，data 参数中会给出当前页的全部数据，由用户自己计算想要的值。函数的返回结果会作为要显示的内用直接展示出来

**Comment by 511701863** [comment]
> @511701863这里使用函数的方式，数据参数中会提供当前页面的数据，用户自己计算想要的数据。函数的返回结果会作为要显示的内用如果直接展示出来
试过了函数返回的显示方式也不行，因为定义的column 里的列有return一个值或组件 就会导致合计栏也会显示该 return的值 ，但是暂时用插槽的方式可以解决这个问题

**Comment by flsion** [comment]
@511701863 是的，如果有指定返回值，会优先使用用户返回的，table 不会再自己计算了

**Comment by flsion** [comment]
如果还有问题可以再谈论，这个 issue 先关闭了
