### ISSUE TITLE
使用对话框 Modal时出现的问题

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#914]
在使用Modal时我遇到了以下一些问题:
1.  :align-center="false" 时，若设置width="auto" 则宽度变为了100%。
2.  :align-center="false" 时，若设置draggable 进行拖动，鼠标闪现出框，拖动效果异常。
3.  能否设置对话框的弹出位置，现在能在关闭居中的情况下设置top值，但不知道是否有办法设置left值。

**Comment by sperains** [comment]
2.21.2 确实有以上问题
