### ISSUE TITLE
icon-link 图标不像一个链接，和 React 的不一样

### ISSUE THREAD

**Issue by xuxucode** [arco-design/arco-design-vue#921]
## Vue
<img width="152" alt="Screen Shot 2022-04-01 at 8 45 25 PM" src="https://user-images.githubusercontent.com/8274162/161266251-6d9324c5-2359-4e62-bda5-79b1bcf33593.png">
此图标实际上对应 React 里的 IconAttachment，且 Vue 缺少 icon-attachment

## React:
<img width="169" alt="Screen Shot 2022-04-01 at 8 44 34 PM" src="https://user-images.githubusercontent.com/8274162/161266162-0930469e-76ec-4caa-b7ea-4e2bd82570df.png"><img width="164" alt="Screen Shot 2022-04-06 at 9 29 14 AM" src="https://user-images.githubusercontent.com/8274162/161877486-09812f61-89d7-45a3-96fc-21e9ea52ac63.png">

**Comment by Flsion** [comment]
@xuxucode 好的，这里应该和react版本一致，下个版本会处理下
