### ISSUE TITLE
2.22 Tree组件展开时节点位置乱跳，无法正常使用

### ISSUE THREAD

**Issue by liupan1890** [arco-design/arco-design-vue#923]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.22.0
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** https://codesandbox.io/s/admiring-violet-2qnjti?file=/src/App.vue

## What is expected?

https://codesandbox.io/s/admiring-violet-2qnjti?file=/src/App.vue
https://vue-ekn4wd.stackblitz.io
展开节点时，节点位置不动，子节点显示在正确的位置

#### 1.展开靠上的节点时，节点位置移动了一点（预期是不移动）
![weizhi](https://user-images.githubusercontent.com/67817756/161366696-37eaf535-10d2-4fb1-8da5-44988d11cc60.gif)

#### 3.收缩靠下的节点时，节点位置下移300px,（预期是下面的其他节点自动上移填充，而不是节点本身下移）
![w1](https://user-images.githubusercontent.com/67817756/161367238-e17b73c3-117b-4ed7-bb99-b023822e9cd9.png)

#### 4.展开或收缩靠下的节点时后，滚动鼠标滚轮，节点先跳到原始位置，然后再正常滚动（预期是正常滚动，不乱跳）
![weizhi2](https://user-images.githubusercontent.com/67817756/161366840-6b2b473a-5441-48c5-ae75-f65c58281abf.gif)

**Comment by liupan1890** [comment]
另外说一下，在tree里已经提供了`toggleCheck`方法，切换选中状态，但是文档里没提这个方法，我也不敢用

那么，`toggleSelect`,`toggleExpanded` 是否也安排一下？

另外再说一下，` <a-tree :data="treeData" :load-more="loadMore" />`,使用动态加载时，如果通过`treeref.expandNode()`方法展开一个节点，并不会触发loadMore。只有手动点击 选择框(口)时，才能触发loadMore，感觉也是个BUG吧

**Comment by liupan1890** [comment]
好奇试了一下react版，据然是正常的没有这个BUG

https://arco.design/react/components/tree

> 人不能...至少不应该...   畜生啊，这就是亲娘和后娘的区别吗？

![weizhi3](https://user-images.githubusercontent.com/67817756/161371299-dea00c94-7144-4f5e-a19c-862d3a46655f.gif)

**Comment by kirazxyun** [comment]
收到问题，我们优化一下

**Comment by flsion** [comment]
新版虚拟列表已经修复此问题
