### ISSUE TITLE
2.22 select 不支持value==enmpty

### ISSUE THREAD

**Issue by liupan1890** [arco-design/arco-design-vue#924]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.22.0
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** https://arco.design/issue-helper?repo=arco-design-vue

## Extra info
```javascript
      <a-select :style="{ width: '252px' }" :model-value="uiFileOrderDuli" @update:model-value="cb({ uiFileOrderDuli: $event })">
        <a-option value="">
          不开启
          <template #suffix>推荐</template>
        </a-option>
        <a-option value="name asc">开启&默认文件名 升序</a-option>
        <a-option value="name desc">开启&默认文件名 降序</a-option>
        <a-option value="updated_at asc">开启&默认时间 升序</a-option>
        <a-option value="updated_at desc">开启&默认时间 降序</a-option>
        <a-option value="size asc">开启&默认大小 升序</a-option>
        <a-option value="size desc">开启&默认大小 降序</a-option>
      </a-select>
```

## What is expected?
支持空的value选项

忘了之前是哪个版本了，是支持如上`<a-option value="">不开启</a-option>`这种选项的，最新的版本里不再支持了，会显示空白框

![en1](https://user-images.githubusercontent.com/67817756/161367505-6684200b-d215-457a-8f1d-c779c791a951.png)

**Comment by mumup** [comment]
+1

**Comment by flsion** [comment]
select 会把 ''、null、undefined 当做没有选择的状态，并且 default-value = ''，目前可以使用其他的值替代一下
