### ISSUE TITLE
求助:如何添加一个路由，让它不在侧边栏显示

### ISSUE THREAD

**Issue by yymjku18** [arco-design/arco-design-vue#930]
如题，如何添加一个路由，让它不在侧边栏显示。或者说如何隐藏一个路由在侧边栏的显示。
但还要保证该路由依然可以通过链接正常进入，进入后侧边栏也能正常出现。
比如:【用户中心】我不需要在侧边栏出现，只可以从右上角进入。有没有简单的办法实现啊。本人基础薄弱，恳请看到的大佬指导一下。
如今尝试了直接在router/index.ts里注册不想在侧边栏显示的路由，可是这样做进入页面后侧边栏就没有了。

**Comment by hehehai** [comment]
@yymjku18 最新的 [arco-design-vue](https://github.com/arco-design/arco-design-pro-vue) 是支持这个的

https://github.com/arco-design/arco-design-pro-vue/blob/ebf5e18aedd284c5e411bde850646e355d56b23e/arco-design-pro-vite/src/router/typings.d.ts#L3-L12

```ts
hideInMenu?: boolean; // 若设置为 true，则不会在侧边菜单总显示
```

```ts
{
   path: 'workplace',
   name: 'Workplace',
   component: () => import('@/views/dashboard/workplace/index.vue'),
   meta: {
     locale: 'menu.dashboard.workplace',
	 hideInMenu: true,
     requiresAuth: true,
     roles: ['*'],
},
```

https://github.com/arco-design/arco-design-pro-vue/blob/ebf5e18aedd284c5e411bde850646e355d56b23e/arco-design-pro-vite/src/components/menu/index.vue#L50-L53

``` ts
// 仅展示未隐藏的路由
element.children = element.children.filter(
    (x) => x.meta?.hideInMenu !== true
);
```

workplace 路由依然存在，仅是在menu中不显示了

**Comment by yymjku18** [comment]
@hehehai 非常感谢，有空把文档也更新一下吧

**Comment by yymjku18** [comment]
@hehehai 你好，请问三级路由菜单现在可以实现么

**Comment by hehehai** [comment]
@yymjku18 arco-design-pro 目前是支持多级嵌套菜单的

https://github.com/arco-design/arco-design-pro-vue/blob/ebf5e18aedd284c5e411bde850646e355d56b23e/arco-design-pro-vite/src/components/menu/index.vue#L98-L129

```tsx
return (
  <a-menu-item key={elem.name} onClick={() => goto(elem)}>
    {t(elem?.meta?.locale || '')}
    {travel(elem.children ?? [])}
  </a-menu-item>
);
```

设置子路由即可
```ts
{
  path: 'dashboard',
  name: 'dashboard',
  // ...
  children: [
    {
      path: 'workplace',
      name: 'workplace',
	 // ...
      children: [
        {
          path: 'demo3',
          name: 'demo3',
		  // ...
        },
      ],
    },
  ],
};
```

@Flsion

🤔 目前多级嵌套菜单还不完善
<img width="207" alt="image" src="https://user-images.githubusercontent.com/12692552/161665346-77e05b7f-9329-4d3a-93fb-13ec7453012f.png">

调整了一下，可以参考下
```tsx
const renderSubMenu = () => {
      function travel(_route: RouteRecordRaw[], nodes = []) {
        if (_route) {
          _route.forEach((element) => {
            // This is demo, modify nodes as needed
            const icon = element?.meta?.icon ? `<${element?.meta?.icon}/>` : ``;
            const r = element?.children ? (
              <a-sub-menu
                key={element?.name}
                v-slots={{
                  icon: () => h(compile(icon)),
                  title: () => h(compile(t(element?.meta?.locale || ''))),
                }}
              >
                {travel(element?.children)}
              </a-sub-menu>
            ) : (
              <a-menu-item key={element.name} onClick={() => goto(element)}>
                {t(element?.meta?.locale || '')}
                {travel(element.children ?? [])}
              </a-menu-item>
            );
            nodes.push(r as never);
          });
        }
        return nodes;
      }
      return travel(menuTree.value);
    };
```
<img width="205" alt="image" src="https://user-images.githubusercontent.com/12692552/161667420-2d281d8f-cb0e-4845-8b57-bc84bd7d415d.png">

**Comment by sHow8e** [comment]
@yymjku18 hihi. 菜单项的配置（隐藏某项等）可以参见项目内的routes/typings.d.ts文件。多级菜单需要自己去做递归的处理。因为每个业务系统的展现都不一样哈。3q

**Comment by xutian111** [comment]
为什么我的图标不显示，我在路由哪里配置了icon: 'icon-dashboard'
![image](https://user-images.githubusercontent.com/89231915/231693840-9a77722a-a3d0-4593-ab6b-2e9d128e6a33.png)
