### ISSUE TITLE
drawer里面滚动的时候select组件的下拉内容不会随自身的组件滚动

### ISSUE THREAD

**Issue by yunshengyu** [arco-design/arco-design-vue#931]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.22.1
- **System:** os
- **Browser:** chrome99.0.4844.84
- **Reproduction Link:** https://codesandbox.io/s/romantic-rgb-rilo8j?file=/src/App.vue

## What is expected?
希望点击下拉的时候 内容会跟随滚动条的滚动而移动

**Comment by Flsion** [comment]
@yunshengyu 可以通过 trigger-props 开启滚动容器处理这个场景 https://arco.design/vue/component/trigger#scroll 
这个属性默认是关闭的，近期询问这个的比较多，我考虑下这个是否要默认开启

**Comment by yunshengyu** [comment]
<a-select
      :trigger-props="{ updateAtScroll: true }"           
      allow-search
      allow-clear
    />

以上写法可以解决此问题

**Comment by yunshengyu** [comment]
<a-select
              :trigger-props="{ updateAtScroll: true }" />

**Comment by yunshengyu** [comment]
<a-select :trigger-props="{ updateAtScroll: true }" /> 这样写可以解决问题
