### ISSUE TITLE
Modal 希望简单模式(simple)下仍然能显示关闭按钮

### ISSUE THREAD

**Issue by xuxucode** [arco-design/arco-design-vue#936]
目前在设置`:simple="true"`之后关闭按钮没有显示。
希望默认显示关闭按钮；或者至少能通过`closable`配置：当用户**明确**设置`:closable="true"` 之后就显示，否者默认不显示。

**Comment by hehehai** [comment]
@xuxucode hi, 目前该功能已支持 [文档](https://arco.design/vue/component/modal#notice)

**Comment by xuxucode** [comment]
v2.36.1 没有解决，右上角仍然没有关闭按钮。

源码显示当 simple 为 false 时才显示关闭按钮：
https://github.com/arco-design/arco-design-vue/blob/main/packages/web-vue/components/modal/modal.vue#L61
```html
<div
  v-if="!simple && closable"
  tabindex="-1"
  role="button"
  aria-label="Close"
  :class="`${prefixCls}-close-btn`"
  @click="handleCancel"
>
```

实测效果：
<img width="887" alt="simple_no_close@2x" src="https://user-images.githubusercontent.com/8274162/189519546-be347d17-3ae0-4ad6-8610-f5f90579b78d.png" width="500px">

**Comment by hehehai** [comment]
@xuxucode 嗯，关闭按钮 simple 是不显示的，建议使用取消按钮，或者在普通模式下，调整 model 样式。

**Comment by xuxucode** [comment]
👌，谢谢
