### ISSUE TITLE
DatePicker组件日历面板异常

### ISSUE THREAD

**Issue by lainbo** [arco-design/arco-design-vue#937]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.22.1
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** https://codesandbox.io/s/funny-brahmagupta-k91yyn?file=/src/App.vue

## What is expected?
1、希望修正组件库文档中,DatePicker案例的写法，替换dayjs的语法，使其正常工作

## Steps to reproduce
1、将dayjs升级至1.11.0
2、使用DatePicker——带时间的日期选择
3、保证DatePicker有 :time-picker-props="{ defaultValue: dayjs('09:09:06', 'HH:mm:ss') }"属性
4、日历面板任意点击日期，面板内的日期会全变成NaN
5、dayjs在1.11.0不支持dayjs('09:09:06', 'HH:mm:ss')这种方式，详见链接

**Comment by kirazxyun** [comment]
解析自定义格式，需要插件 customParseFormat 的支持

**Comment by lainbo** [comment]
> @lainbo 你好， 解析自定义格式，需要插件 customParseFormat 的支持，参考 demo https://codesandbox.io/s/compassionate-glitter-pvr7f3?file=/src/App.vue

我的意思是，dayjs之前是可以在不引入插件做到组件库文档中的那种格式化的，即dayjs('09:09:06', 'HH:mm:ss')，这一段也是从咱们的datePicker的文档中复制的
现在吧dayjs升级到1.11.0之后不可以这样写了，希望把datePicker的文档更新一下

**Comment by kirazxyun** [comment]
好的，会更新demo的，防止使用错误

**Comment by kirazxyun** [comment]
[#950](url)
