### ISSUE TITLE
<table-column> Props 和 TableColumn 有什么区别

### ISSUE THREAD

**Issue by nuaajiangteng** [arco-design/arco-design-vue#942]
如图所示，同一个属性【ellipsis】在<table-column> Props 和 TableColumn的区别是什么，用法上有什么区别？
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/29668874/162194960-7a7642d4-d0ea-484b-a6d2-e55691f787d4.png">
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/29668874/162195020-da88c452-27c8-42c2-9a7b-d19ba324f146.png">

**Comment by hehehai** [comment]
@nuaajiangteng 你好，没区别，<table-column> 是组件，TableColumn 是类型（可以理解为jsx的组件）

**Comment by tazyong** [comment]
#### `<table-column>` 是组件，使用方法如下：
https://arco.design/vue/component/table#custom
![image](https://user-images.githubusercontent.com/24738011/162366380-47fdb224-07e4-4471-a687-6d8f7677aece.png)

#### `TableColumn` 是类型接口，使用方法如下：
https://arco.design/vue/component/table#basic
![image](https://user-images.githubusercontent.com/24738011/162366938-e8604b43-ef6b-41db-8015-43a5893be69b.png)

**Comment by kirazxyun** [comment]
@nuaajiangteng 以上两个回答都能解决这个问题，这两个是列的两种配置方式，作为属性的 ellipsis 的作用是一样的。
