### ISSUE TITLE
Select组件trigger插槽Select宽度问题

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#955]
版本号：2.23.0

https://codesandbox.io/s/selectzu-jian-triggercha-cao-wen-ti-tb1tth

宽度与trigger内元素保持一致，a-select定义宽度无效

![image](https://user-images.githubusercontent.com/30397859/162462514-9f36a9c1-1c50-4e28-a92d-0c508dcb996f.png)

**Comment by Flsion** [comment]
select的trigger组件有默认开启 auto-fit-popup-width 属性，这里可以关闭下 https://arco.design/vue/component/select#basic。下个版本可以做下处理，如果用了trigger插槽的话不再开启了
