### ISSUE TITLE
Table使用scroll数据为空时滚动条位置不对

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#956]
版本号：2.23.0

https://codesandbox.io/s/keen-hawking-1rg9co

![image](https://user-images.githubusercontent.com/30397859/162461832-1f5113c7-9596-4232-9373-7c171ce03143.png)

**Comment by Flsion** [comment]
是这样的，数据为空时，滚动条会显示在表头处

**Comment by svipchao** [comment]
你好，这个问题没有被修复，使用 :scroll="{ x: number }" 没有数据的情况下上方依然会出现滚动条
https://codesandbox.io/s/keen-hawking-1rg9co
