### ISSUE TITLE
建议增加标签组，效果类似于InputTag

### ISSUE THREAD

**Issue by svipchao** [arco-design/arco-design-vue#957]
可以设置最多展示标签数量

![image](https://user-images.githubusercontent.com/30397859/162577149-08e931a1-a128-4ad4-929a-97407de8f19e.png)

**Comment by Flsion** [comment]
@svipchao 可以有，后面安排添加下

**Comment by hehehai** [comment]
溢出缩略组件已在 [beta](https://github.com/arco-design/arco-design-vue/tree/beta) 中，待近期测试稳定后发布，可实现标签组功能。
