### ISSUE TITLE
如何创建一个没有子菜单的顶层菜单，关联一个页面

### ISSUE THREAD

**Issue by CharellKing** [arco-design/arco-design-vue#965]
export default {
  path: 'test',
  name: 'Test',
  component: () => import('@/views/test/index.vue'),
  meta: {
    locale: 'menu.test',
    requiresAuth: true,
    icon: 'icon-book',
    order: 0,
  },
};

即使 test component 组件是有内容的，http://localhost:3000/test 页面显示是空的； 我看了一下 acro-design-pro的所有的菜单必须有子菜单，只有这样才能OK么？

**Comment by hehehai** [comment]
@CharellKing 你好，可以参考这个 https://github.com/arco-design/arco-design-vue/issues/930#issuecomment-1088207082

**Comment by CharellKing** [comment]
我看到过这个帖子，这个帖子是关于隐藏菜单的，我这里并不需要隐藏；我这里只是想将某个menu和view的路由关联起来，而这个menu是没有子菜单的；尝试了一下，都失败了；根本不能点击menu，以及menu相关页面，也是空的。

**Comment by hehehai** [comment]
@CharellKing 嗯，方便贴下route代码和菜单的截图嘛？

**Comment by CharellKing** [comment]
![image](https://user-images.githubusercontent.com/1913489/163101966-eaed24b1-65ec-4b43-bb7d-0ed8010a303d.png)


![image](https://user-images.githubusercontent.com/1913489/163102065-d645dc1b-82bc-4462-a9b4-0b8264b9d55e.png)


![image](https://user-images.githubusercontent.com/1913489/163102263-763a6ad0-c393-403a-872b-70a573555269.png)

**Comment by CharellKing** [comment]
menu.test menu 点击没有反应

**Comment by hehehai** [comment]
@CharellKing 嗯，这是 arco-design-pro 菜单设计的问题

https://github.com/arco-design/arco-design-pro-vue/blob/ebf5e18aedd284c5e411bde850646e355d56b23e/arco-design-pro-vite/src/components/menu/index.vue#L98-L129

可以调整一下menu 的层级渲染

``` tsx
const renderSubMenu = () => {
      function travel(_route: RouteRecordRaw[], nodes = []) {
        if (_route) {
          _route.forEach((element) => {
            // This is demo, modify nodes as needed
            const icon = element?.meta?.icon ? `<${element?.meta?.icon}/>` : ``;
            const r = element?.children ? (
              <a-sub-menu
                key={element?.name}
                v-slots={{
                  icon: () => h(compile(icon)),
                  title: () => h(compile(t(element?.meta?.locale || ''))),
                }}
              >
                {travel(element?.children)}
              </a-sub-menu>
            ) : (
              <a-menu-item key={element.name} onClick={() => goto(element)}>
                {t(element?.meta?.locale || '')}
                {travel(element.children ?? [])}
              </a-menu-item>
            );
            nodes.push(r as never);
          });
        }
        return nodes;
      }
      return travel(menuTree.value);
    };
```

https://github.com/arco-design/arco-design-vue/issues/930#issuecomment-1088207082

**Comment by CharellKing** [comment]
现在test menu 可以点击，并路由到http://localhost:3000/test;但是http://localhost:3000/test显示为空，没有显示helloworld

**Comment by hehehai** [comment]
@CharellKing 嗯，这里是需要 `route-view` 的，可参考其他页面的写法，或查看 [vue router](https://router.vuejs.org/zh/guide/#html)

**Comment by CharellKing** [comment]
![image](https://user-images.githubusercontent.com/1913489/163114882-0cb20c69-09d6-4963-aefa-610588108ce5.png)
顶层没有图标

**Comment by hehehai** [comment]
> ![image](https://user-images.githubusercontent.com/1913489/163114882-0cb20c69-09d6-4963-aefa-610588108ce5.png) 顶层没有图标

@CharellKing 

```tsx
const renderSubMenu = () => {
      function travel(_route: RouteRecordRaw[], nodes = []) {
        if (_route) {
          _route.forEach((element) => {
            // This is demo, modify nodes as needed
            const icon = element?.meta?.icon ? `<${element?.meta?.icon}/>` : ``;
            const r = element?.children ? (
              <a-sub-menu
                key={element?.name}
                v-slots={{
                  icon: () => h(compile(icon)),
                  title: () => h(compile(t(element?.meta?.locale || ''))),
                }}
              >
                {travel(element?.children)}
              </a-sub-menu>
            ) : (
              <a-menu-item 
				key={element.name} 
				v-slots={{
                  icon: () => h(compile(icon))
                }} 
				onClick={() => goto(element)}
			  >
                {t(element?.meta?.locale || '')}
                {travel(element.children ?? [])}
              </a-menu-item>
            );
            nodes.push(r as never);
          });
        }
        return nodes;
      }
      return travel(menuTree.value);
    };
```

**Comment by CharellKing** [comment]
> @CharellKing 嗯，这里是需要 `route-view` 的，可参考其他页面的写法，或查看 [vue router](https://router.vuejs.org/zh/guide/#html)
如果是参考其他的页面的写法，其他的页面的router-view放到顶层menu的index中；我如此加了一下，似乎不生效，
<template>
  <router-view>
  <div class="container">
      <p>helloworld</p>
  </div>
  </router-view>
</template>

<script lang="ts" setup>
</script>

<script lang="ts">
  export default {
    name: 'Test',
  };
</script>

**Comment by sulimi** [comment]
哈喽，我也遇到了这个问题，而且icon不显示

**Comment by hehehai** [comment]
@sulimi 你好，新版本已支持改功能 

https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md

若旧版本要升级支持该功能，可以参考这个pr进行升级  https://github.com/arco-design/arco-design-pro-vue/pull/59/files

**Comment by nightost** [comment]
> https://github.com/arco-design/arco-design-pro-vue/pull/59/files

但是添加的路由component如何继承default-layout

官方的链接
<img width="641" alt="image" src="https://user-images.githubusercontent.com/3621908/197563601-4136e36e-4786-4160-8574-85b69c8c2a6f.png">
给出的link并没有指明如何配置

**Comment by xuhongwei** [comment]
@nightost 
我目前是这么配置的：
1. 外层菜单增加配置`hideChildrenInMenu: true`，隐藏子菜单
2. 外层菜单增加配置`redirect: '/dashboard/workplace'`， 点击后跳转到目标子菜单
3. children 目标子菜单中增加配置 `activeMenu: 'dashboard'`, 更改选中后的一级菜单选中状态

```ts
import { DEFAULT_LAYOUT } from '../base';
import { AppRouteRecordRaw } from '../types';

const DASHBOARD: AppRouteRecordRaw = {
  path: '/dashboard',
  name: 'dashboard',
  component: DEFAULT_LAYOUT,
  redirect: '/dashboard/workplace',
  meta: {
    locale: '工作台',
    requiresAuth: false,
    icon: 'icon-dashboard',
    order: 0,
    hideChildrenInMenu: true,
  },
  children: [
    {
      path: 'workplace',
      name: 'workplace',
      component: () => import('@/views/workplace/index.vue'),
      meta: {
        locale: '工作台',
        activeMenu: 'dashboard',
        requiresAuth: true,
        roles: ['*'],
      },
    },
  ],
};

export default DASHBOARD;
```

**Comment by Jonyon** [comment]
> @nightost 我目前是这么配置的：
> 
> 1. 外层菜单增加配置`hideChildrenInMenu: true`，隐藏子菜单
> 2. 外层菜单增加配置`redirect: '/dashboard/workplace'`， 点击后跳转到目标子菜单
> 3. children 目标子菜单中增加配置 `activeMenu: 'dashboard'`, 更改选中后的一级菜单选中状态
> 
> ```ts
> import { DEFAULT_LAYOUT } from '../base';
> import { AppRouteRecordRaw } from '../types';
> 
> const DASHBOARD: AppRouteRecordRaw = {
>   path: '/dashboard',
>   name: 'dashboard',
>   component: DEFAULT_LAYOUT,
>   redirect: '/dashboard/workplace',
>   meta: {
>     locale: '工作台',
>     requiresAuth: false,
>     icon: 'icon-dashboard',
>     order: 0,
>     hideChildrenInMenu: true,
>   },
>   children: [
>     {
>       path: 'workplace',
>       name: 'workplace',
>       component: () => import('@/views/workplace/index.vue'),
>       meta: {
>         locale: '工作台',
>         activeMenu: 'dashboard',
>         requiresAuth: true,
>         roles: ['*'],
>       },
>     },
>   ],
> };
> 
> export default DASHBOARD;
> ```

2024年了，有简单的解决办法了吗？

**Comment by mingzhou** [comment]
> @nightost 我目前是这么配置的：
> 
> 1. 外层菜单增加配置`hideChildrenInMenu: true`，隐藏子菜单
> 2. 外层菜单增加配置`redirect: '/dashboard/workplace'`， 点击后跳转到目标子菜单
> 3. children 目标子菜单中增加配置 `activeMenu: 'dashboard'`, 更改选中后的一级菜单选中状态
> 
> ```ts
> import { DEFAULT_LAYOUT } from '../base';
> import { AppRouteRecordRaw } from '../types';
> 
> const DASHBOARD: AppRouteRecordRaw = {
>   path: '/dashboard',
>   name: 'dashboard',
>   component: DEFAULT_LAYOUT,
>   redirect: '/dashboard/workplace',
>   meta: {
>     locale: '工作台',
>     requiresAuth: false,
>     icon: 'icon-dashboard',
>     order: 0,
>     hideChildrenInMenu: true,
>   },
>   children: [
>     {
>       path: 'workplace',
>       name: 'workplace',
>       component: () => import('@/views/workplace/index.vue'),
>       meta: {
>         locale: '工作台',
>         activeMenu: 'dashboard',
>         requiresAuth: true,
>         roles: ['*'],
>       },
>     },
>   ],
> };
> 
> export default DASHBOARD;
> ```

这个可以在菜单栏处看起来像是一级菜单了。
但是在页签的地方，还是会显示成二级菜单："/数据可视化/分析页"
最好能直接显示成"/分析页"
