### ISSUE TITLE
从网络下载表头数据, 生成的循序不一致

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#972]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.23.0
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** https://codesandbox.io/s/infallible-solomon-r2ne0i?file=/src/App.vue

## What is expected?
我自定义了表头, 把操作一列放到了for循环后面, 应该生成的循序也按照循序来, 操作一列在最后面

**Comment by hehehai** [comment]
@pylist 你好，动态的column，需要设置下 index

``` vue
<template>
  <a-table :columns="tableInfo.columns" :data="listData">
    <template #columns>
      <a-table-column
        v-for="(item, idx) in tableInfo.columns"
        :key="item.dataIndex"
        :index="idx"
        :title="item.title"
        :data-index="item.dataIndex"
      ></a-table-column>
      <a-table-column title="操作" fixed="left" :index="10">
        <template #cell="{ record }">
          <a-button type="primary" size="mini">小时</a-button>
        </template>
      </a-table-column>
    </template>
  </a-table>
</template>
```

<img width="998" alt="image" src="https://user-images.githubusercontent.com/12692552/163290924-a82e4c4d-f4d7-4632-84b4-26bb1816614b.png">

**Comment by pylist** [comment]
好的, 谢谢
