### ISSUE TITLE
cascader级联选择器 options属性动态调用接口赋值不生效

### ISSUE THREAD

**Issue by TanYuanJie** [arco-design/arco-design-vue#974]
组件的props属性值已经传入，但是页面没有渲染
![62AE1894-F935-498A-AB70-F1663565F300](https://user-images.githubusercontent.com/49168065/163297630-9f2c3bbd-3581-4a02-b159-c566b4cd103d.png)
<img width="564" alt="image" src="https://user-images.githubusercontent.com/49168065/163297802-1a547d1d-9224-488d-9b52-6bc3bcf43e96.png">
![image](https://user-images.githubusercontent.com/49168065/163297825-a3b2deca-66f1-47f1-9f76-d047f0a5278a.png)

请问下是什么原因呢

**Comment by TanYuanJie** [comment]
![image](https://user-images.githubusercontent.com/49168065/163301919-2b091c0b-8b35-4a9c-bcc2-15756c2e33ab.png)
![image](https://user-images.githubusercontent.com/49168065/163301986-baae5808-9a71-41ae-9fdb-5fe3c25a1452.png)
promise后添加元素，不会渲染

**Comment by TanYuanJie** [comment]
怀疑是promise后，计算属性没有执行，点击已有的11选项，添加的元素就能渲染出来了。这应该是个BUG

**Comment by Flsion** [comment]
@TanYuanJie 2.23.0 版本已经处理了这个问题，，可以升级下。之前的版本需要用 ref 重新赋值的方式才能触发更新
