### ISSUE TITLE
版本 2.22.1, 同时开启行选择器与chidren子项, 点击全选后 , 再点击反选会有问题

### ISSUE THREAD

**Issue by zyhzyh1120** [arco-design/arco-design-vue#975]
<a-table row-key="code" :columns="columns" :data="data" :row-selection="{ type: 'checkbox', showCheckedAll: true }" />

const data = ref([
  code: "15215275",
  name: '构建化过程',
  createTime: "2022/04/14 18:29:50",
  children: [
    {
      code: "15215275",
      name: '子构建化过程',
      createTime: "2022/04/14 18:29:50",
      followerName: "test08的用户名"
    }
  ],
  followerName: "test08的用户名"
])

**Comment by zyhzyh1120** [comment]
反选时无反应

**Comment by Flsion** [comment]
@zyhzyh1120 你好，可以提供一个复现的地址吗？
