### ISSUE TITLE
日期范围选择的时候，YYYY-MM-DD HH:mm

### ISSUE THREAD

**Issue by coder-jerryh** [arco-design/arco-design-vue#98]

**Comment by jerryhu88** [comment]
![image](https://user-images.githubusercontent.com/40226377/140524824-32cd5963-6bd2-4474-910d-0a894c931643.png)

**Comment by kirazxyun** [comment]
@jerryhu88 你好，请问是想要右下角的时间时间也根据 format 来吗，这个是根据 UI 设计来的哈，是固定显示为 HH:mm:ss 来显示的哦。

**Comment by jerryhu88** [comment]
我的想法是要表现一致😁

**Comment by kirazxyun** [comment]
> 我的想法是要表现一致😁
明白，不过 UI 问题我们还是遵循设计规范哈，目前和 React 版的组件库有不一致的地方，后期会再统一一波交互，到时候可以再关注一下～

**Comment by flsion** [comment]
目前这里在 UI 上会保持统一
