### ISSUE TITLE
点击表格分页的时候返回数据顶部, 返回顶部组件用在表格好像没起作用

### ISSUE THREAD

**Issue by pylist** [arco-design/arco-design-vue#987]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
https://codesandbox.io/s/practical-tharp-98wwb1?file=/src/App.vue

## What problem does this feature solve?
不然每次都要滑动很久到最上面看第一条数据

**Comment by hehehai** [comment]
@pylist 你好

table的使用滚动有两种情况
1. table本身没有设置滚动（如：`:scroll="{y: 100}"`）
这里可以使用 back-top，但 target需要指向 table 外部的容器，具体和普通 back-top相同（但依然不会点击分页滚动到顶部，这不是 table的问题，仅是滚动容器的滚动）

2. table本身内容可滚动
可以参考这个 https://vue-nuj8hq.stackblitz.io

上面两种其实一样的，就是在page change 时，将滚动容器的状体修改为顶部，这里滚动容器的区别可能就是（table-body或documet.body）
