### ISSUE TITLE
请求优化虚拟表格滚动效果

### ISSUE THREAD

**Issue by OneSeven** [arco-design/arco-design-vue#988]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 

https://user-images.githubusercontent.com/17974392/163684616-9a48e53d-adcf-46c3-a243-4639bbdd6bd7.mp4

## 现有案例
https://ant.design/components/table-cn/#components-table-demo-virtual-list
https://arco.design/react/components/table#%E5%A4%A7%E6%95%B0%E6%8D%AE

## 预期解决问题
滚动和拖动滚动条，列表会出现空白

**Comment by lainbo** [comment]
我感觉虚拟滚动表格卡卡的，我换vxe了，纵享丝滑

**Comment by hehehai** [comment]
@OneSeven @lainbo hi, 虚拟列表已进行优化，建议使用 2.36.1 以上版本体验, [文档](https://arco.design/vue/docs/faq#%E8%99%9A%E6%8B%9F%E5%88%97%E8%A1%A8%E7%9A%84%E4%BD%BF%E7%94%A8)
