### ISSUE TITLE
descriptions组件 非bodered模式下，且在 layout = inline-horizontal   或 layout = inline-vertical 模式下，改变size只是改变标题和描述列表的距离（改变size无效），

### ISSUE THREAD

**Issue by lin-97** [arco-design/arco-design-vue#992]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
无

**Comment by hehehai** [comment]
@lin-97 hi, 这个组件的 size 改变目前除 mini 外是不影响文字大小的，有需要的话，可以自己使用样式控制一下。
