### ISSUE TITLE
请问线上自定义主题色功能有例子吗?

### ISSUE THREAD

**Issue by cx741041875** [arco-design/arco-design-vue#993]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
线上环境支持用户自定义主题色

## What problem does this feature solve?
定制主题

## Extra info
根据官网开发指南中的定制主题实现了自定义主题色，但是每次更改需要修改配置文件再打包发布。

**Comment by cx741041875** [comment]
> @cx741041875 你好，是需要在程序运行时，修改主题色吗？
> 
> 可以修改 css 变量，arco design 的色值变量使用的是 css var <img alt="图像" width="269" src="https://user-images.githubusercontent.com/12692552/164127307-76ee3ad8-b386-4f26-b402-cfd2900aabc9.png">
> 
> 具体实现，可以参考 arco-design-pro 的 明/暗模式
> 
> https://github.com/arco-design/arco-design-pro-vue/blob/2340e3043a30e8a037b93e5a9c7e40ef7dc4a2d5/arco-design-pro-vite/src/store/modules/app/index.ts#L25
> 
> <img alt="图像" width="364" src="https://user-images.githubusercontent.com/12692552/164127781-0d2814ad-e490-4af5-af58-a75de4768c86.png">

谢谢，使用@arco-design/color 通过HEX色值生成了一组(1-10)的主题色然后通过setProperty替换了arcoblur1-10，虽然实现了需求，但是不知道这个思路对不对
![image](https://user-images.githubusercontent.com/48713520/164179020-9922d853-b1c0-498d-8daf-a774a83fd569.png)

**Comment by cx741041875** [comment]
@hehehai 懂了，再次感谢!!!

**Comment by Mowmowj** [comment]
@cx741041875  你好请问具体怎么改颜色阿 是要创建一个less文件吗

**Comment by Mowmowj** [comment]
@hehehai 如何修改变量啊 vite配置文件里 less嘛 我修改了 之前有用 引入了 message 组件就失效了

**Comment by duanshoujian** [comment]
> @cx741041875
> 
> 这里修改
> 
> ```
> const colorName = 'gold'
> 
> Array.from({length: 10}).forEach((_, index) => {
> 	document.body.style.setProperty(`--primary-${index + 1}`, `var(--${colorName}-${index + 1})`)
> })
> ```
> 
> colorName 可以参考 框架内置的颜色关键值 https://arco.design/palette/list
> 
> 如果想要自己生成颜色序列，将 `--primary-1` .... `--primary-10` 分别设置颜色就行 例如： `...('--primary-1', '#333')`

你好，可以通过less配置的方式直接替换css变量吗？比如--primary: red 这种
