### ISSUE TITLE
table组件select事件参数

### ISSUE THREAD

**Issue by toadprince** [arco-design/arco-design-vue#995]
table组件select事件，除了可获取rowkeys，能否返回tabledata（当TableRowSelection的type=radio时）

**Comment by hehehai** [comment]
@toadprince 你好

如果为 radio 的可以参考下这个实现 https://codesandbox.io/s/icy-hooks-vrtcq7?file=/src/App.vue

**Comment by flsion** [comment]
select 事件已经增加行数据
