### ISSUE TITLE
建议table显示省略号属性（ellipsis）开启后，鼠标移到省略处通过Tooltip显示完全信息

### ISSUE THREAD

**Issue by sqlFC** [arco-design/arco-design-vue#998]
![image](https://user-images.githubusercontent.com/29202691/164143962-0e416ac5-c47f-46b8-84fa-1d07e2d18fc2.png)

**Comment by hehehai** [comment]
@sqlFC 你好，这个功能近期会上🥳

**Comment by Flsion** [comment]
`2.26.0` 版本会增加这个功能

**Comment by WestarkMFF** [comment]
+1
